import assert from'node:assert/strict';import{spawn}from'node:child_process';import{randomUUID as uuid}from'node:crypto';import{sql}from'../../../tests/integration/cost/fixtures/postgres-rpc.mjs';
process.env.VP_RESULT_DATA_SQL_CONTAINER='vpj08-events-sql-20261010';const{fixture,claims}=await import('../../../tests/integration/privacy/result-data-sql/ownproof/runtime.mjs');
async function db(q){const r=await sql('vpj08-events-sql-20261010',q);assert.equal(r.code,0,r.stderr);return r.stdout.trim();}
function connection(name){const p=spawn('docker',['exec','-i','vpj08-events-sql-20261010','psql','-h','/tmp/vpj59-socket','-U','postgres','-X','-q','-At','-v','ON_ERROR_STOP=1'],{stdio:['pipe','pipe','pipe']});let stdout='',stderr='';p.stdout.setEncoding('utf8');p.stderr.setEncoding('utf8');p.stdout.on('data',s=>stdout+=s);p.stderr.on('data',s=>stderr+=s);const done=new Promise((resolve,reject)=>{p.on('error',reject);p.on('close',code=>resolve({code,stdout,stderr}));});p.stdin.write(`set statement_timeout='5s';set lock_timeout='5s';set application_name='${name}';\n`);return{p,done,output:()=>stdout};}
async function until(check){const end=Date.now()+4000;while(Date.now()<end){if(await check())return;await new Promise(r=>setTimeout(r,10));}throw Error('owned concurrency checkpoint not reached');}
const a=await fixture();const admit=async()=>{const thread=uuid(),turn=uuid(),task=uuid(),message=uuid();await db(`begin;${claims(a)}select public.submit_service_task_turn('${thread}','${turn}','${uuid()}','${a.policy}','en','Canonical concurrent task','${task}',1,'new_goal',null);select public.submit_assistant_message_v1('${a.conversation}','${message}','${uuid()}','${a.policy}','en','Canonical concurrent followup','follow_up','${a.goal}',1,'${task}','${a.rootMessage}',null);commit;`);return turn;};const turnA=await admit(),turnB=await admit();
const ca=connection('vpj08-proof-a');ca.p.stdin.write(`begin;select turn_private.terminal('${turnA}','cancelled',1);select 'A_ALLOCATED';\n`);await until(()=>ca.output().includes('A_ALLOCATED'));
const cb=connection('vpj08-proof-b');cb.p.stdin.end(`begin;select turn_private.terminal('${turnB}','cancelled',1);select 'B_ALLOCATED';commit;\n`);
await until(async()=>await db("select count(*) from pg_stat_activity where application_name='vpj08-proof-b' and wait_event_type='Lock';")==='1');assert.ok(!cb.output().includes('B_ALLOCATED'),'B cannot allocate/commit beyond uncommitted head');
const before=await db(`select last_sequence from turn_private.assistant_event_heads_v1 where conversation_id='${a.conversation}';`);assert.equal(before,'5','uncommitted A head is invisible');
ca.p.stdin.end('commit;\n');const ra=await ca.done,rb=await cb.done;assert.equal(ra.code,0,ra.stderr);assert.equal(rb.code,0,rb.stderr);
const rows=JSON.parse(await db(`select jsonb_agg(jsonb_build_object('sequence',sequence,'turn',turn_id,'status',status) order by sequence) from turn_private.assistant_events_v1 where conversation_id='${a.conversation}' and sequence>5;`));assert.deepEqual(rows,[{sequence:6,turn:turnA,status:'cancelled'},{sequence:7,turn:turnB,status:'cancelled'}]);
// A committed page may use a captured head while another append is in flight;
// it exposes no uncommitted row or head and never acknowledges its ordinal.
const epoch=JSON.parse(await db(`begin;${claims(a)}set role authenticated;select public.read_assistant_events_v1('${a.policy}','${a.conversation}',7,50);commit;`));assert.deepEqual(epoch.events,[]);assert.equal(epoch.lastSequence,7);
await db(`update identity_private.mobile_accounts set epoch=epoch+1,session_id=null where owner_id='${a.owner}';`);const stale=await sql('vpj08-events-sql-20261010',`begin;${claims(a)}set role authenticated;select public.read_assistant_events_v1('${a.policy}','${a.conversation}',0,50);rollback;`);assert.notEqual(stale.code,0);assert.match(stale.stderr,/SESSION_REPLACED|UNAUTHENTICATED|SESSION_NOT_CURRENT/);
console.log('two genuine canonical terminal transactions: blocking head prevents commit inversion, uncommitted head invisible, contiguous committed ordinals; changed native epoch denies old session SQL-claims scope PASS; no global processes or credentials touched');
