import assert from'node:assert/strict';import{randomUUID as uuid}from'node:crypto';import{sql}from'../../../tests/integration/cost/fixtures/postgres-rpc.mjs';
process.env.VP_RESULT_DATA_SQL_CONTAINER='vpj08-events-sql-20261010';const{fixture,claims}=await import('../../../tests/integration/privacy/result-data-sql/ownproof/runtime.mjs');
async function db(q){const r=await sql('vpj08-events-sql-20261010',q);assert.equal(r.code,0,r.stderr);return r.stdout.trim();}
const a=await fixture();const page=async(after=0)=>JSON.parse(await db(`begin;${claims(a)}set role authenticated;select public.read_assistant_events_v1('${a.policy}','${a.conversation}',${after},50);commit;`));
assert.equal((await page()).events[2].availability,'recheck');const amended=uuid();await db(`begin;${claims(a)}select public.submit_assistant_message_v1('${a.conversation}','${amended}','${uuid()}','${a.policy}','en','Owner accepted goal amendment','amendment','${a.goal}',1,null,'${a.rootMessage}',null);commit;`);
const historical=await page();assert.equal(historical.kind,'assistant_events',JSON.stringify(historical));assert.deepEqual(historical.events.slice(0,2).map(x=>x.status),['accepted','completed']);assert.equal(historical.events[2].availability,'unavailable');
const content=JSON.parse(await db(`begin;${claims(a)}select public.read_result_artifact_v2('${a.artifact}',1);commit;`));assert.equal(content.current,false); // original result content/currentness qualification untouched
const thread=uuid(),turn=uuid(),task=uuid(),message=uuid();await db(`begin;${claims(a)}select public.submit_service_task_turn('${thread}','${turn}','${uuid()}','${a.policy}','en','New current goal task','${task}',1,'new_goal',null);select public.submit_assistant_message_v1('${a.conversation}','${message}','${uuid()}','${a.policy}','en','Current goal followup','follow_up','${a.goal}',2,'${task}','${amended}',null);commit;`);
const all=await page();assert.deepEqual(all.events.map(x=>x.sequence),[1,2,3,4]);assert.equal(all.events[3].taskId,task);assert.equal((await page(3)).events[0].taskId,task);
await db(`update turn_private.text_consents set revoked_at=clock_timestamp() where owner_id='${a.owner}' and policy_id='${a.policy}';`);assert.deepEqual(await page(3),{kind:'unavailable'});
console.log('actual Goal amendment preserves readable old Task hints, old artifact unavailable/current=false, canonical new Task and oldcursor replay, consent revocation deny PASS');
