-- Exact relation registration; complete own witness replaces generic unsupported-copy classification.
CREATE OR REPLACE FUNCTION result_data_private.relations_v1()
 RETURNS TABLE(relation_name text, pk text[])
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO ''
AS $function$ values
 ('community_private.audit',array['id']::text[]),
 ('community_private.disclosures_j1',array['actor_id']::text[]),
 ('community_private.operations_j1',array['owner_id','operation_id']::text[]),
 ('community_private.receipts',array['actor_id','operation_id']::text[]),
 ('community_private.reviewers',array['actor_id']::text[]),
 ('community_private.settings',array['singleton']::text[]),
 ('community_private.submissions',array['id']::text[]),
 ('community_publication_private.audit',array['id']::text[]),
 ('community_publication_private.operations',array['owner_id','operation_id']::text[]),
 ('community_publication_private.publications',array['id']::text[]),
 ('community_publication_private.qualifications',array['actor_id']::text[]),
 ('community_publication_private.references',array['id']::text[]),
 ('community_publication_private.rights_reviews',array['id']::text[]),
 ('community_publication_private.settings',array['singleton']::text[]),
 ('community_safety_private.appeals',array['id']::text[]),
 ('community_safety_private.audit',array['id']::text[]),
 ('community_safety_private.blocks',array['id']::text[]),
 ('community_safety_private.controlled_readers',array['actor_id','submission_id']::text[]),
 ('community_safety_private.decisions',array['id']::text[]),
 ('community_safety_private.moderators',array['actor_id']::text[]),
 ('community_safety_private.operations',array['owner_id','operation_id']::text[]),
 ('community_safety_private.reports',array['id']::text[]),
 ('community_safety_private.settings',array['singleton']::text[]),
 ('community_safety_private.states',array['submission_id']::text[]),
 ('coverage_export_private.request_fences_v1',array['request_id']::text[]),
 ('coverage_export_private.requests_v1',array['request_id']::text[]),
 ('coverage_export_private.sections_v1',array['request_id','section']::text[]),
 ('export_private.core_artifacts_v1',array['request_id']::text[]),
 ('export_private.core_jobs_v1',array['request_id']::text[]),
 ('export_private.core_policies_v1',array['id']::text[]),
 ('export_private.core_tickets_v1',array['operation_id']::text[]),
 ('export_private.entitlement_page_progress_v1',array['request_id','generation']::text[]),
 ('export_private.entitlement_source_revisions_v1',array['owner_id']::text[]),
 ('export_private.memory_section_progress_v1',array['request_id','generation','section']::text[]),
 ('export_private.memory_source_revisions_v1',array['owner_id']::text[]),
 ('guide_private.bindings_v1',array['turn_id']::text[]),
 ('guide_private.progress_v1',array['owner_id','reference_id','locale','interest']::text[]),
 ('guide_private.uses_v1',array['id']::text[]),
 ('knowledge_review_private.audit',array['id']::text[]),
 ('knowledge_review_private.candidate_assertions',array['candidate_id']::text[]),
 ('knowledge_review_private.candidates',array['id']::text[]),
 ('knowledge_review_private.members',array['actor_id']::text[]),
 ('knowledge_review_private.ontology_relations',array['predicate']::text[]),
 ('knowledge_review_private.ontology_types',array['type_id']::text[]),
 ('knowledge_review_private.publication_audit',array['candidate_id','version']::text[]),
 ('knowledge_review_private.publication_settings',array['singleton']::text[]),
 ('knowledge_review_private.publications',array['candidate_id']::text[]),
 ('knowledge_review_private.receipts',array['actor_id','operation_id']::text[]),
 ('knowledge_review_private.settings',array['singleton']::text[]),
 ('knowledge_review_private.source_impact_items',array['id']::text[]),
 ('knowledge_review_private.source_impact_outbox',array['id']::text[]),
 ('knowledge_review_private.source_impact_pages',array['set_id','cursor_key']::text[]),
 ('knowledge_review_private.source_impact_projections',array['id']::text[]),
 ('knowledge_review_private.source_impact_review_requests',array['delivery_id']::text[]),
 ('knowledge_review_private.source_impact_sets',array['id']::text[]),
 ('knowledge_review_private.source_revisions',array['id']::text[]),
 ('knowledge_review_private.statement_sources',array['candidate_id','source_revision_id']::text[]),
 ('knowledge_review_private.statements',array['candidate_id']::text[]),
 ('knowledge_review_private.wiki_generation_jobs',array['id']::text[]),
 ('knowledge_review_private.wiki_page_revisions',array['id']::text[]),
 ('knowledge_review_private.wiki_pages',array['id']::text[]),
 ('knowledge_review_private.wiki_statement_candidates',array['candidate_id']::text[]),
 ('lodging_classification_private.mapping_audit',array['mapping_id','version']::text[]),
 ('lodging_classification_private.mappings',array['id']::text[]),
 ('lodging_classification_private.operations',array['actor_id','operation_id']::text[]),
 ('lodging_classification_private.statements',array['candidate_id']::text[]),
 ('material_exit_private.progress_v1',array['request_id']::text[]),
 ('material_exit_private.requests_v1',array['request_id']::text[]),
 ('material_exit_private.reservation_fences_v1',array['owner_id','kind','object_id']::text[]),
 ('memory_private.native_command_heads_v1',array['memory_id']::text[]),
 ('memory_private.native_command_receipts_v1',array['owner_id','operation_id']::text[]),
 ('memory_private.native_update_preimages_v1',array['operation_id']::text[]),
 ('notification_exit_private.fences',array['owner_id','kind','object_id']::text[]),
 ('notification_exit_private.pages',array['request_id','page_number']::text[]),
 ('notification_exit_private.requests',array['request_id']::text[]),
 ('notification_exit_private.settings',array['singleton']::text[]),
 ('notification_private.attempts',array['notification_id']::text[]),
 ('notification_private.devices',array['id']::text[]),
 ('notification_private.dismissals',array['owner_id','trip_id','source_kind','source_id','semantic_digest']::text[]),
 ('notification_private.operations',array['owner_id','operation_id']::text[]),
 ('notification_private.outbox',array['id']::text[]),
 ('notification_private.reminders',array['id']::text[]),
 ('notification_private.settings',array['singleton']::text[]),
 ('notification_private.watches',array['id']::text[]),
 ('offline_private.text_commands_v1',array['operation_id']::text[]),
 ('offline_private.text_sources_v1',array['id']::text[]),
 ('offline_private.text_version_bindings_v1',array['trip_id','version','field_key']::text[]),
 ('offline_private.trip_text_state_v1',array['trip_id']::text[]),
 ('pdf_intake_private.confirm_proofs_v1',array['proposal_id']::text[]),
 ('pdf_intake_private.export_progress_v1',array['request_id','generation']::text[]),
 ('pdf_intake_private.export_version_v1',array['version']::text[]),
 ('pdf_intake_private.operations_v1',array['owner_id','operation_id']::text[]),
 ('pdf_intake_private.source_revisions_v1',array['owner_id']::text[]),
 ('place_actions_private.operations',array['owner_id','operation_id']::text[]),
 ('place_actions_private.saved_places',array['owner_id','trip_id','canonical_poi_id']::text[]),
 ('place_quota_private.usage',array['actor_id','bucket','window_seconds']::text[]),
 ('privacy_private.linked_delete_fences_v1',array['entity_kind','entity_id']::text[]),
 ('privacy_private.linked_delete_jobs_v1',array['request_id']::text[]),
 ('privacy_private.linked_delete_plans_v1',array['id']::text[]),
 ('privacy_private.linked_delete_worker_settings_v1',array['singleton']::text[]),
 ('privacy_private.memory_delete_jobs_v1',array['request_id']::text[]),
 ('privacy_private.memory_delete_plans_v1',array['id']::text[]),
 ('privacy_private.memory_delete_worker_settings_v1',array['singleton']::text[]),
 ('privacy_private.trip_deletions',array['request_id']::text[]),
 ('private.audit_events',array['id']::text[]),
 ('public.canonical_pois',array['id']::text[]),
 ('public.chat_threads',array['id']::text[]),
 ('public.chat_turn_events',array['id']::text[]),
 ('public.chat_turn_idempotency',array['owner_id','thread_id','idempotency_key']::text[]),
 ('public.connection_probe_resources',array['id']::text[]),
 ('public.fact_records',array['id']::text[]),
 ('public.memory_consents',array['id']::text[]),
 ('public.memory_consumer_receipts',array['id']::text[]),
 ('public.memory_profiles',array['id']::text[]),
 ('public.memory_receipts',array['id']::text[]),
 ('public.model_budget_attempts',array['scope_id','attempt_id']::text[]),
 ('public.model_budget_provider_limits',array['scope_id','provider']::text[]),
 ('public.model_budget_scopes',array['id']::text[]),
 ('public.privacy_receipts',array['id']::text[]),
 ('public.privacy_requests',array['id']::text[]),
 ('public.provider_poi_mappings',array['id']::text[]),
 ('public.review_probe_changes',array['id']::text[]),
 ('public.storekit_grants',array['environment','transaction_id']::text[]),
 ('public.travel_reminders',array['id']::text[]),
 ('public.trip_action_references',array['id']::text[]),
 ('public.trip_archives',array['trip_id']::text[]),
 ('public.trip_audit_events',array['id']::text[]),
 ('public.trip_days',array['trip_id','day_id']::text[]),
 ('public.trip_events',array['id']::text[]),
 ('public.trip_idempotency',array['owner_id','idempotency_key']::text[]),
 ('public.trip_items',array['trip_id','item_id']::text[]),
 ('public.trip_place_references',array['id']::text[]),
 ('public.trip_proposals',array['id']::text[]),
 ('public.trip_version_snapshots',array['trip_id','version']::text[]),
 ('public.trips',array['id']::text[]),
 ('public.turn_feedback',array['id']::text[]),
 ('public.turns',array['id']::text[]),
 ('public.user_profiles',array['owner_id']::text[]),
 ('public.v4_migration_baseline',array['id']::text[]),
 ('readiness_private.operations_v1',array['operation_id']::text[]),
 ('readiness_private.scopes_v1',array['task_id']::text[]),
 ('recovery_private.contexts_v1',array['id']::text[]),
 ('recovery_private.lineage_v1',array['proposal_id']::text[]),
 ('recovery_private.operations_v1',array['owner_id','operation_id']::text[]),
 ('recovery_private.transport_proofs_v1',array['transaction_id','proposal_id']::text[]),
 ('research_intake_private.applications',array['id']::text[]),
 ('research_intake_private.events',array['id']::text[]),
 ('research_intake_private.receipts',array['token_hash']::text[]),
 ('research_intake_private.settings',array['singleton']::text[]),
 ('reservation_private.current_v1',array['owner_id','reference_id']::text[]),
 ('reservation_private.events_v1',array['owner_id','reference_id','revision']::text[]),
 ('reservation_private.operations_v1',array['owner_id','operation_id']::text[]),
 ('scoped_edit_private.contexts_v1',array['id']::text[]),
 ('scoped_edit_private.lineage_v1',array['proposal_id']::text[]),
 ('scoped_edit_private.lock_epochs_v1',array['trip_id']::text[]),
 ('scoped_edit_private.locks_v1',array['trip_id','item_id']::text[]),
 ('scoped_edit_private.operations_v1',array['owner_id','operation_id']::text[]),
 ('scoped_edit_private.proofs_v1',array['transaction_id','proposal_id']::text[]),
 ('scoped_edit_private.requests_v1',array['turn_id']::text[]),
 ('scoped_edit_private.work_v1',array['turn_id']::text[]),
 ('scoped_edit_private.worker_settings_v1',array['policy_id']::text[]),
 ('service_brief_private.audit',array['event_id']::text[]),
 ('service_brief_private.briefs',array['case_id']::text[]),
 ('service_brief_private.export_leases',array['owner_id','session_id','request_id']::text[]),
 ('service_brief_private.operations',array['actor_id','session_id','surface','operation_id']::text[]),
 ('service_brief_private.previews',array['id']::text[]),
 ('service_brief_private.settings',array['singleton']::text[]),
 ('service_cases_private.audit',array['case_id','revision']::text[]),
 ('service_cases_private.cases',array['id']::text[]),
 ('service_cases_private.staff',array['actor_id']::text[]),
 ('service_operations_private.audit',array['case_id','revision']::text[]),
 ('service_operations_private.data_operations',array['actor_id','session_id','operation_id']::text[]),
 ('service_operations_private.export_progress',array['request_id','generation']::text[]),
 ('service_operations_private.minutes',array['case_id','operation_id']::text[]),
 ('service_operations_private.operations',array['actor_id','session_id','surface','operation_id']::text[]),
 ('service_operations_private.operators',array['actor_id']::text[]),
 ('service_operations_private.services',array['case_id']::text[]),
 ('service_operations_private.settings',array['singleton']::text[]),
 ('service_operations_private.shifts',array['id']::text[]),
 ('service_operations_private.slots',array['shift_id','slot']::text[]),
 ('traffic_private.dispatches_v1',array['id']::text[]),
 ('traffic_private.policies_v1',array['id']::text[]),
 ('traffic_private.producers_v1',array['role_oid']::text[]),
 ('traffic_private.receipts_v1',array['id']::text[]),
 ('traffic_private.scopes_v1',array['id']::text[]),
 ('trip_lifecycle_private.export_progress_v2',array['request_id','generation','section']::text[]),
 ('trip_lifecycle_private.memory_edges_v1',array['owner_id','operation_id','memory_id']::text[]),
 ('trip_lifecycle_private.operations_v1',array['owner_id','operation_id']::text[]),
 ('trip_lifecycle_private.owner_heads_v1',array['owner_id']::text[]),
 ('trip_lifecycle_private.states_v1',array['trip_id']::text[]),
 ('trip_support_private.confirm_proofs',array['transaction_id','proposal_id']::text[]),
 ('trip_support_private.confirmation_receipts',array['owner_id','idempotency_key']::text[]),
 ('trip_support_private.entity_mappings',array['id']::text[]),
 ('trip_support_private.impact_claims',array['delivery_id','attempt']::text[]),
 ('trip_support_private.item_supports',array['id']::text[]),
 ('trip_support_private.preparations',array['id']::text[]),
 ('trip_support_private.support_receipts',array['id']::text[]),
 ('turn_private.assistant_conversations',array['id']::text[]),
 ('turn_private.assistant_goal_trip_links',array['goal_id']::text[]),
 ('turn_private.assistant_goal_trip_receipts',array['operation_id']::text[]),
 ('turn_private.assistant_goals',array['id']::text[]),
 ('turn_private.assistant_message_source_receipts',array['message_id']::text[]),
 ('turn_private.assistant_messages',array['id']::text[]),
 ('turn_private.assistant_travel_intakes',array['message_id']::text[]),
 ('turn_private.grounded_ai_assist_jobs',array['id']::text[]),
 ('turn_private.grounded_turns',array['turn_id']::text[]),
 ('turn_private.hosted_worker_control',array['singleton']::text[]),
 ('turn_private.hosted_worker_heartbeats',array['worker_id']::text[]),
 ('turn_private.planning_action_receipts',array['turn_id','action_key']::text[]),
 ('turn_private.planning_comparisons',array['turn_id']::text[]),
 ('turn_private.planning_consents',array['owner_id','policy_id']::text[]),
 ('turn_private.planning_intake_bindings',array['turn_id']::text[]),
 ('turn_private.planning_model_dispatches',array['lease_token']::text[]),
 ('turn_private.planning_observations',array['turn_id','action_key']::text[]),
 ('turn_private.planning_policies',array['id']::text[]),
 ('turn_private.planning_v2_collector_origins',array['execution_id']::text[]),
 ('turn_private.planning_v2_collector_outputs',array['execution_id']::text[]),
 ('turn_private.planning_v2_collector_principals',array['id']::text[]),
 ('turn_private.planning_v2_completed_receipts',array['execution_id']::text[]),
 ('turn_private.planning_v2_completion_proofs',array['execution_id']::text[]),
 ('turn_private.planning_v2_execution_profiles',array['id']::text[]),
 ('turn_private.planning_v2_execution_runs',array['id']::text[]),
 ('turn_private.planning_v2_external_call_windows',array['execution_id']::text[]),
 ('turn_private.planning_v2_model_attempt_bindings',array['turn_id']::text[]),
 ('turn_private.planning_v2_model_local_journal',array['request_id']::text[]),
 ('turn_private.planning_v2_place_checkpoints',array['turn_id']::text[]),
 ('turn_private.planning_v2_registered_tariffs',array['id']::text[]),
 ('turn_private.planning_v2_result_claims',array['execution_id']::text[]),
 ('turn_private.result_artifacts',array['id']::text[]),
 ('turn_private.result_events',array['id']::text[]),
 ('turn_private.result_revisions',array['artifact_id','revision']::text[]),
 ('turn_private.service_task_capacity',array['task_id']::text[]),
 ('turn_private.service_task_capacity_settings',array['singleton']::text[]),
 ('turn_private.service_task_turns',array['turn_id']::text[]),
 ('turn_private.service_tasks',array['id']::text[]),
 ('turn_private.text_consents',array['owner_id','policy_id']::text[]),
 ('turn_private.text_content',array['turn_id']::text[]),
 ('turn_private.text_dispatches',array['lease_token']::text[]),
 ('turn_private.text_policies',array['id']::text[]),
 ('turn_private.work',array['turn_id']::text[]),
 ('turn_private.assistant_event_heads_v1',array['conversation_id']::text[]),
 ('turn_private.assistant_events_v1',array['conversation_id','sequence']::text[])
$function$
;

CREATE OR REPLACE FUNCTION result_data_private.related_v1(relation_n text, v jsonb, g jsonb)
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare r record;parent_n jsonb;
begin
 -- Exact managed delivery copies are qualified/retired by assistantDelivery witness.
 if relation_n in ('turn_private.assistant_event_heads_v1','turn_private.assistant_events_v1') then return false;end if;
 if relation_n like 'privacy_private.%' then return false;end if;
 for r in select * from result_data_private.json_references_v1(result_data_private.documents_v1(relation_n,v)) loop
  if g->r.kind ? r.entity_id::text then return true;end if;
 end loop;
 for parent_n in select * from result_data_private.notification_parents_v1(relation_n,v) loop
  for r in select * from result_data_private.json_references_v1(parent_n) loop
   if g->r.kind ? r.entity_id::text then return true;end if;
  end loop;
 end loop;
 return relation_n='turn_private.planning_v2_collector_origins' and g->'journalIds' ? (v->>'request_id')
  or relation_n='turn_private.result_artifacts' and g->'artifactIds' ? (v->>'id')
  or relation_n='turn_private.planning_v2_execution_runs' and g->'executionIds' ? (v->>'id')
  or relation_n='turn_private.planning_v2_model_local_journal' and g->'journalIds' ? (v->>'request_id');
end$function$
;
