import assert from'node:assert/strict';import{randomUUID as uuid}from'node:crypto';import{sql}from'../../../tests/integration/cost/fixtures/postgres-rpc.mjs';
process.env.VP_RESULT_DATA_SQL_CONTAINER='vpj08-events-sql-20261010';const{fixture,claims}=await import('../../../tests/integration/privacy/result-data-sql/ownproof/runtime.mjs');
async function db(q){const r=await sql('vpj08-events-sql-20261010',q);assert.equal(r.code,0,r.stderr);return r.stdout.trim();}
const a=await fixture();const selection={scope:'turn-sensitive-data/1',requestId:uuid(),turnId:a.turn,objectIds:[]};
const call=async(c)=>JSON.parse(await db(`begin;${claims(a)}select public.privacy_turn_data_v1('${c.action}','${JSON.stringify(c)}',1);commit;`));
const p=await call({action:'preview',...selection});assert.equal(p.eligible,true,JSON.stringify(p));
const source=JSON.parse(await db(`select turn_data_private.source_v1('${a.owner}','${a.turn}');`));assert.equal(source.assistantDelivery.rows.length,3);
const r=await call({action:'erase',...selection,sourceDigest:p.sourceDigest,previewDigest:p.previewDigest,confirmed:true});assert.equal(r.state,'erased',JSON.stringify(r));
const page=async(after=0)=>JSON.parse(await db(`begin;${claims(a)}set role authenticated;select public.read_assistant_events_v1('${a.policy}','${a.conversation}',${after},50);commit;`));
const after=await page();assert.equal(after.kind,'assistant_events',JSON.stringify(after));assert.deepEqual(after.events.map(x=>x.type),Array(6).fill('source_retired'));assert.equal(after.lastSequence,6);assert.equal((await page(1)).lastSequence,6);assert.equal((await page(3)).events.length,3);
for(const table of['turn_private.assistant_conversations','turn_private.assistant_goals','turn_private.service_tasks','public.chat_threads','public.turns'])assert.equal(await db(`select count(*) from ${table} where ${table.endsWith('assistant_conversations')?'id':table.endsWith('assistant_goals')?'id':table.endsWith('service_tasks')?'id':table.endsWith('chat_threads')?'id':'id'}='${table.endsWith('assistant_conversations')?a.conversation:table.endsWith('assistant_goals')?a.goal:table.endsWith('service_tasks')?a.task:table.endsWith('chat_threads')?a.thread:a.turn}';`),'1');
const thread=uuid(),turn=uuid(),task=uuid(),message=uuid();await db(`begin;${claims(a)}select public.submit_service_task_turn('${thread}','${turn}','${uuid()}','${a.policy}','en','New lawful task','${task}',1,'new_goal',null);select public.submit_assistant_message_v1('${a.conversation}','${message}','${uuid()}','${a.policy}','en','New lawful followup','follow_up','${a.goal}',1,'${task}','${a.rootMessage}',null);commit;`);
const fresh=await page(6);assert.equal(fresh.kind,'assistant_events',JSON.stringify(fresh));assert.equal(fresh.events.length,1);assert.equal(fresh.events[0].taskId,task);assert.equal(fresh.events[0].status,'accepted');assert.equal(fresh.lastSequence,7);
console.log('actual original selected Turn preview/CAS/retirement/parent preservation/deleted-anchor/zero/reconnect/new canonical Task same-conversation replay PASS; SQL-claims admin invocation, not signedAuth');
