import fs from 'node:fs';import assert from 'node:assert/strict';import {query}from './transport.mjs';const read=p=>JSON.parse(fs.readFileSync(p));const tasks=[],locales=[];
for(const locale of ['en','zh']){
 const admission=read(locale+'-admitted.json'),before=read(locale+'-before-kill.json'),checkpoint=read(locale+'-crash-checkpoint.json'),result=read(locale+'-recovery-final.json'),samples=read(locale+'-recovery-samples.json');
 assert.equal(checkpoint.status,'PASS');assert.equal(result.status,'PASS');assert.equal(result.turnId,admission.turn_id);assert.equal(result.taskId,admission.task_id);assert.equal(result.workAttempt,2);assert.equal(result.attempts,1);assert.equal(result.terminalEvents,1);assert.equal(result.unresolved,0);
 const expiry=Date.parse(before.work.expiresAt);assert.ok(samples.some(x=>x.workAttempt===1&&Date.parse(x.databaseNow)<expiry&&x.attempts===0));assert.ok(Date.parse(result.databaseNow)>=expiry);
 const crash=read('service-'+locale+'-crash-result.json'),recovery=read('service-'+locale+'-recovery-result.json');assert.equal(crash.signal,'SIGKILL');assert.equal(recovery.exitCode,0);assert.equal(recovery.result.reason,'stopped');
 const journals=['crash','recovery'].map(p=>fs.readFileSync('service-'+locale+'-'+p+'.jsonl','utf8').trim().split('\n').map(JSON.parse));assert.equal(journals[0][0].configurationDigest,journals[1][0].configurationDigest);
 assert.equal(journals[0].filter(x=>x.schemaVersion==='provider-destination/1'&&x.phase==='attempted').length,0);assert.equal(journals[1].filter(x=>x.schemaVersion==='provider-destination/1'&&x.phase==='attempted').length,1);assert.equal(journals[1].filter(x=>x.phase==='poll-returned'&&x.result==='finished').length,1);assert.ok(journals[1].some(x=>x.phase==='poll-returned'&&x.result==='empty'));
 for(const phase of ['before-relaunch','after-relaunch'])assert.ok(read('native-'+locale+'-'+phase+'.json').rows.some(x=>x.AXUniqueId==='grounded.status'));
 assert.ok(read('native-'+locale+'-recovered-answer.json').rows.some(x=>x.AXUniqueId==='knowledge.answer.answered'));assert.equal(read('native-'+locale+'-logout.json').loginFormObserved,true);tasks.push(admission.task_id);locales.push({locale,taskId:admission.task_id,turnId:admission.turn_id,workLeases:2,modelCalls:1,nativeProcessRestart:true});
}
const ids=tasks.map(x=>"'"+x+"'").join(',');const r=JSON.parse(query(`begin read only;set local role postgres;select json_build_object('attempts',(select count(*)from public.model_budget_attempts where task_id in(${ids})),'settled',(select count(*)from public.model_budget_attempts where task_id in(${ids})and status='settled'),'unresolved',(select count(*)from public.model_budget_attempts where task_id in(${ids})and status not in('settled','released')),'actualMicros',(select sum(actual_micros)from public.model_budget_attempts where task_id in(${ids})),'terminalEvents',(select json_agg(json_build_object('turnId',e.turn_id,'eventId',e.event_id,'state',e.state))from public.chat_turn_events e join turn_private.service_task_turns l on l.turn_id=e.turn_id where l.task_id in(${ids})and e.event_type='terminal'));rollback;`));assert.equal(r.attempts,2);assert.equal(r.settled,2);assert.equal(r.unresolved,0);assert.equal(r.terminalEvents.length,2);assert.ok(r.terminalEvents.every(x=>x.eventId==='worker-terminal-2'&&x.state==='completed'));fs.writeFileSync('audit.json',JSON.stringify({at:new Date().toISOString(),status:'PASS',scope:'real unmodified worker CLI killed after lease claim while budget reservation blocked; native restart and natural lease recovery, not post-dispatch crash',locales,budget:r,currency:'CNY',costBasis:'conservative tariff, not invoice'},null,2)+'\n');console.log(r);
