import fs from 'node:fs';import assert from 'node:assert/strict';import {query} from './transport.mjs';
const locale=process.argv[2];assert.ok(['en','zh'].includes(locale));const t=JSON.parse(fs.readFileSync(locale+'-admitted.json'));const samples=[];const deadline=Date.now()+200000;let final;
while(Date.now()<deadline){
 const r=JSON.parse(query(`begin read only;set local role postgres;select json_build_object('databaseNow',clock_timestamp(),'turnId',t.id,'turnState',t.status,'taskId',l.task_id,'relationship',l.relationship,'workState',w.state,'workAttempt',w.attempt,'leaseExpiresAt',w.expires_at,'originalOutcome',g.original_outcome,'completedAt',g.completed_at,'attempts',(select count(*)from public.model_budget_attempts where task_id=l.task_id),'settled',(select count(*)from public.model_budget_attempts where task_id=l.task_id and status='settled'),'unresolved',(select count(*)from public.model_budget_attempts where task_id=l.task_id and status not in('settled','released')),'terminalEvents',(select count(*)from public.chat_turn_events where turn_id=t.id and event_type='terminal'))from public.turns t join turn_private.work w on w.turn_id=t.id join turn_private.service_task_turns l on l.turn_id=t.id join turn_private.grounded_turns g on g.turn_id=t.id where t.id='${t.turn_id}';rollback;`));
 assert.equal(r.taskId,t.task_id);samples.push(r);fs.writeFileSync(locale+'-recovery-samples.json',JSON.stringify(samples,null,2)+'\n');
 if(['completed','failed','cancelled','unavailable'].includes(r.turnState)){final=r;break;}
 await new Promise(r=>setTimeout(r,8000));
}
assert.ok(final,'Recovery not observed within observation window; inspect existing service, do not restart blindly');assert.equal(final.turnState,'completed');assert.equal(final.originalOutcome,'answered');assert.equal(final.workAttempt,2);assert.equal(final.attempts,1);assert.equal(final.settled,1);assert.equal(final.unresolved,0);assert.equal(final.terminalEvents,1);
fs.writeFileSync(locale+'-recovery-final.json',JSON.stringify({at:new Date().toISOString(),status:'PASS',...final},null,2)+'\n',{flag:'wx'});console.log({status:'PASS',locale,turnId:final.turnId,taskId:final.taskId,workAttempt:final.workAttempt,attempts:final.attempts,terminalEvents:final.terminalEvents});
