export const copy = {
  zh: {
    title: '真人协助工作台', language: '语言', intro: '使用当前登录会话读取已获授权的服务任务。接单前不承诺负责人或完成时间。', login: '登录或切换账号', refresh: '重新读取', loading: '正在核对会话、资格与任务…', capacity: '当前容量', available: '可接单', full: '容量已满', unknown: '未知', checked: '核对时间', empty: '当前没有可读取的服务任务。',
    unavailable: '暂时无法读取。请核对登录、当前工作时段、员工资格与任务授权。', disabled: '服务运营暂未启用。', pending: '原操作回执尚未确认，已暂停新操作。查不到回执不代表操作未执行。', confirmed: '已核对原操作回执；下方状态来自重新读取。', identity: '原操作属于另一账号或会话；请回到原会话核对。', storage: '无法可靠保存或清理恢复记录。新操作已暂停，请勿重复接单。', invalid: '请核对结果证据和人工时段。', readAck: '核对原操作回执', abandon: '申请停止原操作并核对回执', bytesLost: '原请求正文已清除，只能核对原回执。', operation: '未确认操作', actor: '当前员工', case: '任务', status: '状态', grant: '任务授权', expires: '授权有效至', urgency: '紧急程度', normal: '普通', urgent: '紧急', urgentHint: '紧急情况请使用当地官方紧急服务渠道；本工作台不承诺即时响应。', problem: '已授权问题', staff: '负责人', noStaff: '尚未接单，无负责人或完成时间承诺。', acceptedAt: '接单时间', shift: '实际工作时段截至', noEta: '工作时段不是预计完成时间。', context: 'Traveler Brief、来源与 Trip：未知', minutes: '已记录人工分钟', minutesHint: '只汇总已登记时段；实际总投入与成本未知。0 表示尚无记录。', evidence: '结果证据', noEvidence: '尚无结果证据。', tutorial: '教程交付', contacted_provider: '已联系服务方', external_resolution: '外部实际解决', tutorialHint: '教程交付解决不代表外部实际解决。联系记录不代表问题已解决。', reference: '证据引用', note: '证据说明', observed: '证据观察时间', start: '人工开始时间（可选）', end: '人工结束时间（可选）', record: '登记结果', accept: '接单', assign: '开始处理 / 分派给当前员工', update: '回传结果', evidenceKind: '证据种类', none: '不新增证据', queued: '排队中', accepted: '已接单', assigned: '处理中', waiting_external: '等待外部反馈', resolved: '已解决', unresolved: '未解决', cancelled: '已取消', active: '有效', expired: '已过期', revoked: '已撤销', outcome: '回传状态', doneHint: '只登记已发生的结果和证据。此操作不会联系服务方，也不会写入 Trip。',
  },
  en: {
    title: 'Human assistance workspace', language: 'Language', intro: 'Read granted service cases using the current signed-in session. No assignee or completion time is promised before acceptance.', login: 'Sign in or switch account', refresh: 'Refresh', loading: 'Checking session, qualification and cases…', capacity: 'Current capacity', available: 'Available', full: 'Full', unknown: 'Unknown', checked: 'Checked at', empty: 'No readable service cases.',
    unavailable: 'Unable to read. Check sign-in, current shift, staff qualification and case access.', disabled: 'Service operations are not enabled.', pending: 'The original operation is unconfirmed. New operations are paused. An absent receipt does not mean it was never applied.', confirmed: 'Original receipt verified; the state below was read again.', identity: 'The original operation belongs to another account or session. Return to that session to check it.', storage: 'Recovery metadata could not be saved or cleared reliably. New operations are paused. Do not accept twice.', invalid: 'Check result evidence and recorded time intervals.', readAck: 'Check original receipt', abandon: 'Request abandonment and check receipt', bytesLost: 'Original request content was cleared. Only the original receipt can be checked.', operation: 'Unconfirmed operation', actor: 'Current staff member', case: 'Case', status: 'Status', grant: 'Case grant', expires: 'Grant expires', urgency: 'Urgency', normal: 'Normal', urgent: 'Urgent', urgentHint: 'For emergencies use official local emergency services. This workspace does not promise an immediate response.', problem: 'Granted problem', staff: 'Assignee', noStaff: 'Not accepted. No assignee or completion time is promised.', acceptedAt: 'Accepted at', shift: 'Current shift ends', noEta: 'The shift end is not an estimated completion time.', context: 'Traveler Brief, sources and Trip: unknown', minutes: 'Recorded manual minutes', minutesHint: 'Recorded intervals only. Actual total effort and cost are unknown. Zero means no time has been recorded.', evidence: 'Result evidence', noEvidence: 'No result evidence yet.', tutorial: 'Tutorial delivered', contacted_provider: 'Provider contacted', external_resolution: 'External resolution', tutorialHint: 'Resolution through a tutorial does not establish external resolution. Contact alone does not establish resolution.', reference: 'Evidence reference', note: 'Evidence note', observed: 'Observed at', start: 'Work started (optional)', end: 'Work ended (optional)', record: 'Record result', accept: 'Accept case', assign: 'Assign to current staff member', update: 'Return result', evidenceKind: 'Evidence kind', none: 'No additional evidence', queued: 'Queued', accepted: 'Accepted', assigned: 'Assigned', waiting_external: 'Waiting for external feedback', resolved: 'Resolved', unresolved: 'Unresolved', cancelled: 'Cancelled', active: 'Active', expired: 'Expired', revoked: 'Revoked', outcome: 'Result status', doneHint: 'Record only observed results and evidence. This operation does not contact a provider or write to a Trip.',
  },
} as const;
export type Locale = keyof typeof copy;
