// Disposable network-none PostgreSQL. Original actor/Trip authority, synthetic
// admin-created auth/session rows and claims. This is not signed target Auth.
import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID as uuid} from 'node:crypto';
import {readFileSync,readdirSync} from 'node:fs';
import {command,sql} from '../cost/fixtures/postgres-rpc.mjs';
const enabled=process.env.VP_TURN_DB_TEST==='1',container='vpj10-scoped-'+uuid().slice(0,8);let created=false,legacyV2=null;
const db=async q=>{const r=await sql(container,q);assert.equal(r.code,0,r.stderr);return r.stdout.trim();};
const lit=v=>"'"+JSON.stringify(v).replaceAll("'","''")+"'::jsonb";
const claims=a=>`set request.jwt.claim.role='authenticated';set request.jwt.claim.sub='${a.owner}';set request.jwt.claims='${JSON.stringify({role:'authenticated',is_anonymous:false,session_id:a.session})}';`;
const fields=(overrides={})=>({kind:'lodging',supplier:'booking',externalReference:'Opaque-123',title:'Synthetic hotel',startsAt:'2026-10-08T16:00:00+08:00',endsAt:'2026-10-10T11:00:00+08:00',timeZone:'Asia/Shanghai',address:'Synthetic address',terms:'Synthetic corrected terms',status:'reserved',...overrides});
const source=()=>({kind:'user_reported',localMaterialId:null,localContentHash:null,locator:null});
const input=(overrides={})=>({operationId:uuid(),referenceId:uuid(),expectedTripVersion:0,expectedRevision:0,fields:fields(),source:source(),explicitlyConfirmed:true,...overrides});
const confirmSQL=(a,v)=>claims(a)+`select public.confirm_reservation_reference_v1('${a.trip}',${lit(v)});`;
const confirm=async(a,v)=>JSON.parse(await db(confirmSQL(a,v)));
const read=async(a,ref=null,head=0,after=null,limit=20)=>JSON.parse(await db(claims(a)+`select public.read_reservation_references_v1('${a.trip}',${head},${ref?"'"+ref+"'":'null'},${after?"'"+after+"'":'null'},${limit});`));
const op=async(a,id)=>JSON.parse(await db(claims(a)+`select public.read_reservation_operation_v1('${a.trip}','${id}');`));
async function fixture(){const a={owner:uuid(),session:uuid(),trip:uuid()};await db(`insert into auth.users(id) values('${a.owner}');insert into auth.sessions(id,user_id) values('${a.session}','${a.owner}');insert into identity_private.mobile_accounts(owner_id,epoch,session_id) values('${a.owner}',1,'${a.session}');insert into identity_private.mobile_attempts values('${a.owner}','${uuid()}','${a.session}',1);${claims(a)}insert into public.trips(id,owner_id,title) values('${a.trip}','${a.owner}','Synthetic reservation Trip');`);return a;}
const denial=async(q,message)=>{const r=await sql(container,q);assert.notEqual(r.code,0);assert.match(r.stderr,message);};
before(async()=>{if(!enabled)return;
 const r=await command('docker',['run','--pull=never','--rm','-d','--network','none','--name',container,'--user','postgres','--entrypoint','/bin/sh','public.ecr.aws/supabase/postgres:17.6.1.159','-c','umask 077;mkdir /tmp/vpj59-socket;initdb -D /tmp/vpj59-db -A trust --no-locale -E UTF8 >/tmp/init.log 2>&1 && exec postgres -D /tmp/vpj59-db -c listen_addresses= -c unix_socket_directories=/tmp/vpj59-socket -c unix_socket_permissions=0700']);assert.equal(r.code,0,r.stderr);created=true;
 for(let i=0;i<100;i++){if((await command('docker',['exec',container,'pg_isready','-h','/tmp/vpj59-socket','-U','postgres'])).code===0)break;await new Promise(r=>setTimeout(r,100));}
 await db(readFileSync('tests/integration/turn/fixtures/durable-work-schema.sql','utf8'));
 await db("create function auth.role() returns text language sql as $$select nullif(current_setting('request.jwt.claim.role',true),'')$$;create schema extensions;create extension pgcrypto with schema extensions;");
 for(const f of readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')).sort()){if(f==='20261005020000_scoped_edit.sql'){const a=await fixture(),thread=uuid(),turn=uuid();legacyV2=turn;await db(`insert into public.chat_threads(id,owner_id,status) values('${thread}','${a.owner}','active');insert into public.turns(id,owner_id,thread_id,status) values('${turn}','${a.owner}','${thread}','accepted');insert into turn_private.work(turn_id,owner_id,session_id,max_attempts,lease_ms,execution_mode) values('${turn}','${a.owner}','${a.session}',3,30000,'planning_intake_comparison_v2');`);}await db('begin;'+readFileSync('supabase/migrations/'+f,'utf8')+'commit;');}
});
after(async()=>{if(created)assert.equal((await command('docker',['rm','-f',container])).code,0);});
const run=(name,fn)=>test(name,{skip:!enabled,timeout:120000},fn);
run('append-only migration replay compiles under original schema', async()=>{ assert.equal(await db("select to_regprocedure('public.prepare_scoped_trip_edit_v1(uuid,jsonb)') is not null;"),'t'); });
const contextInput=(scope={dayIds:['d1'],itemIds:[]},bindings=[])=>({expectedHeadVersion:0,scope,locale:'en',reservationBindings:bindings});
const prepare=async(a,v=contextInput())=>JSON.parse(await db(claims(a)+`select public.prepare_scoped_trip_edit_v1('${a.trip}',${lit(v)});`));
const basis=c=>({contextId:c.contextId,contextDigest:c.contextDigest,baseVersion:c.baseVersion});
const mutation=(c,edit={kind:'set_time',itemId:'b',startsAt:'2026-10-08T12:00:00+00:00',endsAt:'2026-10-08T13:00:00+00:00'})=>({action:'manual',operationId:uuid(),basis:basis(c),edit});
const submitSQL=(a,m)=>claims(a)+`select public.submit_scoped_trip_edit_v1('${a.trip}',${lit(m)});`;
const submit=async(a,m)=>JSON.parse(await db(submitSQL(a,m)));
const readOp=async(a,id)=>JSON.parse(await db(claims(a)+`select public.read_scoped_trip_edit_operation_v1('${a.trip}','${id}');`));
const abandon=async(a,m)=>JSON.parse(await db(claims(a)+`select public.abandon_scoped_trip_edit_operation_v1('${a.trip}',${lit({action:'abandon',operationId:m.operationId,mutation:m})});`));
const confirmProposalSQL=(a,r)=>claims(a)+`select outcome from public.confirm_and_apply_trip_proposal('${r.proposalId}','${uuid()}','${r.proposalDigest}');`;
async function tripFixture(){const a=await fixture();await db(`insert into public.trip_days(trip_id,owner_id,day_id,trip_date,time_zone) values('${a.trip}','${a.owner}','d1','2026-10-08','Etc/UTC'),('${a.trip}','${a.owner}','d2','2026-10-09','Etc/UTC');insert into public.trip_items(trip_id,owner_id,day_id,item_id,title) values('${a.trip}','${a.owner}','d1','a','A'),('${a.trip}','${a.owner}','d1','b','B'),('${a.trip}','${a.owner}','d1','c','C'),('${a.trip}','${a.owner}','d2','z','Z');update public.trip_version_snapshots set content=public.trip_content_snapshot('${a.trip}','Synthetic scoped Trip') where trip_id='${a.trip}' and version=0;update public.trips set title='Synthetic scoped Trip' where id='${a.trip}';`);return a;}
const snap=async a=>JSON.parse(await db(claims(a)+`select public.trip_content_snapshot('${a.trip}',title) from public.trips where id='${a.trip}';`));
run('manual candidate is unconfirmed until original exact writer; current scope snapshot and receipt are closed',async()=>{
 const a=await tripFixture(),c=await prepare(a);assert.equal(c.kind,'scoped_edit_context/1');assert.deepEqual(c.orderedItemIdsByDay,[{dayId:'d1',itemIds:['a','b','c']},{dayId:'d2',itemIds:['z']}]);const m=mutation(c),r=await submit(a,m);assert.equal(r.kind,'scoped_edit_proposal/1');assert.equal((await snap(a)).days[0].items[1].startsAt,undefined);assert.equal((await readOp(a,m.operationId)).state,'pending');assert.equal((await submit(a,m)).proposalId,r.proposalId);assert.equal(await db(confirmProposalSQL(a,r)),'applied');assert.equal((await readOp(a,m.operationId)).resultingVersion,1);assert.equal((await snap(a)).days[0].items[1].startsAt,'2026-10-08T12:00:00+00:00');
});
run('sparse real reorder preserves unselected fields and slot; legacy edits preserve persisted order; rollback reloads order',async()=>{
 const a=await tripFixture(),c=await prepare(a,contextInput({dayIds:[],itemIds:['a','c']})),m=mutation(c,{kind:'reorder_items',dayId:'d1',itemIds:['c','a']}),r=await submit(a,m);assert.equal(await db(confirmProposalSQL(a,r)),'applied');const ordered=await snap(a);assert.deepEqual(ordered.days[0].items.map(i=>i.id),['c','b','a']);assert.deepEqual(ordered.days[0].items[1],c.snapshot.days[0].items[1]);
 const p=JSON.parse(await db(claims(a)+`select row_to_json(r) from public.create_trip_proposal_patch('${a.trip}',${lit({expectedVersion:1,operations:[{kind:'set_title',title:'Old client'}]})})r;`));const dig=await db(claims(a)+`select digest from public.read_trip_proposal_v2('${p.proposal_id}');`);assert.equal(await db(claims(a)+`select outcome from public.confirm_and_apply_trip_proposal('${p.proposal_id}','${uuid()}','${dig}');`),'applied');assert.deepEqual((await snap(a)).days[0].items,ordered.days[0].items);
 const rollback=JSON.parse(await db(claims(a)+`select row_to_json(r) from public.create_trip_rollback_proposal('${a.trip}',1)r;`));const rd=await db(claims(a)+`select digest from public.read_trip_proposal_v2('${rollback.proposal_id}');`);assert.equal(await db(claims(a)+`select outcome from public.confirm_and_apply_trip_proposal('${rollback.proposal_id}','${uuid()}','${rd}');`),'applied');assert.deepEqual((await snap(a)).days[0].items,ordered.days[0].items);
});
run('selected move permits natural slot shift and retains all unselected fields and relative order',async()=>{
 const a=await tripFixture(),c=await prepare(a,contextInput({dayIds:[],itemIds:['a']})),r=await submit(a,mutation(c,{kind:'move_item',itemId:'a',toDayId:'d2'}));assert.equal(await db(confirmProposalSQL(a,r)),'applied');const n=await snap(a);assert.deepEqual(n.days[0].items,c.snapshot.days[0].items.slice(1));assert.equal(n.days[1].items[0].id,'a');
});
run('explicit lock CAS is distinct from manual edits and invalidates all older contexts',async()=>{
 const a=await tripFixture(),c=await prepare(a),m={action:'lock',operationId:uuid(),basis:basis(c),itemId:'b',locked:true},r=await submit(a,m);assert.equal(r.lockRevision,1);assert.equal(await db(`select head_version from public.trips where id='${a.trip}';`),'0');assert.equal((await submit(a,mutation(c))).reason,'stale_basis');const fresh=await prepare(a);assert.deepEqual(fresh.lockedItemIds,['b']);await denial(submitSQL(a,mutation(fresh)),/PROTECTED_ITEM/);const unlocked=await submit(a,{...m,operationId:uuid(),basis:basis(fresh),locked:false});assert.equal(unlocked.lockRevision,2);assert.deepEqual((await prepare(a)).lockedItemIds,[]);
});
run('abandon before submit creates durable tombstone; committed proposal remains pending, never undo or reject',async()=>{
 const a=await tripFixture(),c=await prepare(a),m=mutation(c);assert.equal((await readOp(a,m.operationId)).state,'unknown');assert.equal((await abandon(a,m)).state,'cancelled');assert.equal((await submit(a,m)).reason,'cancelled');assert.equal((await readOp(a,m.operationId)).state,'cancelled');assert.equal(await db(`select count(*) from public.trip_proposals where trip_id='${a.trip}';`),'0');
 const m2=mutation(c),r=await submit(a,m2);assert.equal((await abandon(a,m2)).state,'committed');assert.equal(await db(`select status from public.trip_proposals where id='${r.proposalId}';`),'pending');await denial(submitSQL(a,{...m2,edit:{...m2.edit,itemId:'a'}}),/IDEMPOTENCY_KEY_REUSE/);
});
run('direct RPC refuses invalid scope/source/client fields, cross actor and context swap',async()=>{
 const a=await tripFixture(),b=await tripFixture(),c=await prepare(a);assert.equal((await submit(b,mutation(c))).reason,'stale_basis');const bad={...mutation(c),patch:{expectedVersion:0,operations:[]}};await denial(submitSQL(a,bad),/INVALID_INPUT/);assert.equal((await prepare(a,contextInput({dayIds:['missing'],itemIds:[]}))).reason,'invalid_scope');assert.equal((await submit(a,{...mutation(c),basis:{...basis(c),contextDigest:'a'.repeat(64)}})).reason,'stale_basis');
});
run('profile/Memory/session/source changes reject before original Trip write',async()=>{
 for(const kind of ['profile','memory','session']){
 const a=await tripFixture(),c=await prepare(a),r=await submit(a,mutation(c));
 if(kind==='profile')await db(`insert into public.user_profiles(owner_id,travel_pace) values('${a.owner}','balanced');`);
 if(kind==='memory')await db(`insert into public.memory_consents(id,owner_id,status) values('${uuid()}','${a.owner}','granted');`);
 if(kind==='session')await db(`update identity_private.mobile_accounts set epoch=epoch+1 where owner_id='${a.owner}';`);
 await denial(confirmProposalSQL(a,r),/SCOPED_CONFIRM_GUARD|SESSION/);assert.equal(await db(`select head_version from public.trips where id='${a.trip}';`),'0');
 }
});
run('same-transaction source changes after writer force deferred rollback',async()=>{
 const a=await tripFixture(),c=await prepare(a),r=await submit(a,mutation(c));await denial('begin;'+confirmProposalSQL(a,r)+`insert into public.memory_consents(id,owner_id,status) values('${uuid()}','${a.owner}','granted');commit;`,/SCOPED_CONFIRM_GUARD/);assert.equal(await db(`select head_version from public.trips where id='${a.trip}';`),'0');assert.equal(await db(`select status from public.trip_proposals where id='${r.proposalId}';`),'pending');
});
run('marked revision and successor cannot escape immutable lineage; expired context cleanup still blocks confirmation',async()=>{
 const a=await tripFixture(),c=await prepare(a),r=await submit(a,mutation(c));await denial(claims(a)+`select public.revise_trip_proposal_patch('${r.proposalId}',${lit({expectedVersion:0,operations:[{kind:'set_title',title:'Escaped'}]})});`,/SCOPED/);await db(`delete from scoped_edit_private.contexts_v1 where id='${c.contextId}';`);assert.equal(await db(`select count(*) from scoped_edit_private.lineage_v1 where proposal_id='${r.proposalId}';`),'1');await denial(confirmProposalSQL(a,r),/SCOPED_CONFIRM_GUARD/);
});
async function sleeping(name){for(let i=0;i<100;i++){if(await db(`select exists(select 1 from pg_stat_activity where application_name='${name}' and wait_event='PgSleep');`)==='t')return;await new Promise(r=>setTimeout(r,10));}assert.fail('holder not observed');}
run('real two-transaction submit/abandon races create one outcome with exact-body receipt recovery',async()=>{
 const a=await tripFixture(),c=await prepare(a),m=mutation(c);const held=sql(container,`set application_name='scoped-submit-holder';begin;${submitSQL(a,m)}select pg_sleep(0.8);commit;`);await sleeping('scoped-submit-holder');const other=abandon(a,m);assert.equal((await held).code,0);assert.equal((await other).state,'committed');assert.equal(await db(`select count(*) from scoped_edit_private.operations_v1 where owner_id='${a.owner}';`),'1');assert.equal(await db(`select count(*) from public.trip_proposals where trip_id='${a.trip}';`),'1');
 const b=await tripFixture(),bc=await prepare(b),bm=mutation(bc);const cancel=sql(container,`set application_name='scoped-cancel-holder';begin;${claims(b)}select public.abandon_scoped_trip_edit_operation_v1('${b.trip}',${lit({action:'abandon',operationId:bm.operationId,mutation:bm})});select pg_sleep(0.8);commit;`);await sleeping('scoped-cancel-holder');const late=submit(b,bm);assert.equal((await cancel).code,0);assert.equal((await late).reason,'cancelled');assert.equal(await db(`select count(*) from public.trip_proposals where trip_id='${b.trip}';`),'0');
});
run('new capabilities default deny all roles and original archive/deletion/account cascades erase scope metadata',async()=>{
 for(const role of ['anon','authenticated','service_role'])assert.equal(await db(`select exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where (n.nspname='scoped_edit_private' or n.nspname='public' and p.proname like '%scoped_trip_edit%') and has_function_privilege('${role}',p.oid,'EXECUTE'));`),'f');
 for(const mode of ['archive','delete','account']){
 const a=await tripFixture(),c=await prepare(a);await submit(a,mutation(c));if(mode==='archive'){const r=(await readOp(a,(await db(`select operation_id from scoped_edit_private.operations_v1 where owner_id='${a.owner}';`)))).receipt;await db(confirmProposalSQL(a,r));await db(claims(a)+`select public.archive_trip_v1('${a.trip}',1,'${uuid()}',true);`);};if(mode==='delete')await db(claims(a)+`select public.request_trip_deletion_v1('${uuid()}','${a.trip}',0,true);`);if(mode==='account')await db(`delete from auth.users where id='${a.owner}';`);
 for(const table of ['contexts_v1','operations_v1','lineage_v1','locks_v1','lock_epochs_v1','proofs_v1','work_v1','requests_v1'])assert.equal(await db(`select count(*) from scoped_edit_private.${table} where trip_id='${a.trip}';`),'0',table);
 }
});
const serviceClaims="set request.jwt.claim.role='service_role';set request.jwt.claim.sub='';set request.jwt.claims='{\"role\":\"service_role\"}';";
async function workerFixture(){const a=await tripFixture(),policy=uuid(),planning=uuid(),scope=uuid(),configuration=uuid();await db(`insert into turn_private.text_policies(id,provider,recipient,endpoint,source_region,processing_region,storage_region,terms_version,notice_version,notice_hash,notice_zh,notice_en,retention,effective_at,expires_at,terms_recheck_at) values('${policy}','qwen','Synthetic recipient','https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions','Synthetic','Synthetic','Synthetic','synthetic-v1','synthetic-v1','${'a'.repeat(64)}','Synthetic scoped notice','Synthetic scoped notice','retain_after_hide_v1',clock_timestamp()-interval '1 hour',clock_timestamp()+interval '1 day',clock_timestamp()+interval '1 day');insert into turn_private.text_consents(owner_id,policy_id) values('${a.owner}','${policy}');insert into turn_private.planning_policies(id,text_policy_id,environment,notice_version,notice_hash,notice_zh,notice_en,effective_at,expires_at) values('${planning}','${policy}','local_synthetic','synthetic-v1','${'b'.repeat(64)}','Synthetic scoped source notice','Synthetic scoped source notice',clock_timestamp()-interval '1 hour',clock_timestamp()+interval '1 day');insert into turn_private.planning_consents(owner_id,policy_id) values('${a.owner}','${planning}');insert into public.model_budget_scopes(id,owner_id,currency,limit_micros,task_limit_micros,task_attempt_limit,concurrency_limit,enabled,expires_at) values('${scope}','${a.owner}','CNY',10000,1000,3,3,true,clock_timestamp()+interval '1 day');insert into public.model_budget_provider_limits(scope_id,provider,model,price_version,limit_micros,attempt_limit_micros,enabled) values('${scope}','qwen','qwen3.7-plus-2026-05-26','synthetic-v1',10000,1000,true);insert into scoped_edit_private.worker_settings_v1(policy_id,planning_policy_id,enabled,notice_hash,scope_id,model,price_version,reserved_micros,timeout_ms,max_output_tokens,configuration_id,configuration_version,source_use,expires_at) values('${policy}','${planning}',true,'${'b'.repeat(64)}','${scope}','qwen3.7-plus-2026-05-26','synthetic-v1',100,10000,1000,'${configuration}',1,'scoped_trip_edit_v1',clock_timestamp()+interval '1 day');update turn_private.hosted_worker_control set enabled=true where singleton;`);return {...a,policy,planning,scope,configuration};}
const workerRPC=async(name,p)=>JSON.parse(await db(serviceClaims+`select public.${name}(${Object.entries(p).map(([k,v])=>`${k} => ${v===null?'null':typeof v==='object'?lit(v):typeof v==='number'?v:"'"+String(v).replaceAll("'","''")+"'"}`).join(',')});`));
async function leaseAsk(a,edits=[{kind:'set_time',itemId:'b',startsAt:'2026-10-08T12:00:00+00:00',endsAt:'2026-10-08T13:00:00+00:00'}]){const c=await prepare(a),m={action:'ask',operationId:uuid(),basis:basis(c),text:'Synthetic selected edit'},r=await submit(a,m);assert.equal(r.reason,'queued');const l=await workerRPC('claim_scoped_trip_edit_work_v1',{p_owner_id:a.owner,p_policy_id:a.policy,p_scope_id:a.scope});assert.equal(l.kind,'leased');const input=await workerRPC('read_scoped_trip_edit_work_v1',{p_turn_id:l.turnId,p_lease_token:l.leaseToken});assert.equal(input.kind,'scoped_edit_input/1');return {c,m,l,b:input.binding,input,edits};}
const usage={inputTokens:10,outputTokens:5,totalTokens:15,cachedInputTokens:null,uncachedInputTokens:null,reasoningTokens:null,cost:'unknown'};
async function saveCandidate(a,w,actual=20,complete=true){const p={p_binding:w.b};assert.equal((await workerRPC('scoped_trip_edit_budget_v1',{...p,p_effect:'reserve',p_reserved_micros:100,p_actual_micros:null,p_outcome:null})).kind,'reserved');assert.equal((await workerRPC('scoped_trip_edit_budget_v1',{...p,p_effect:'dispatch',p_reserved_micros:null,p_actual_micros:null,p_outcome:null})).kind,'dispatched');const output={kind:'candidate',edits:w.edits};const saved=await workerRPC('record_scoped_trip_edit_output_v1',{...p,p_output:output,p_usage:usage,p_actual_micros:actual});assert.equal(saved.kind,'saved_output');assert.equal(saved.accounting,'pending');assert.equal((await workerRPC('scoped_trip_edit_budget_v1',{...p,p_effect:'finish',p_reserved_micros:null,p_actual_micros:actual,p_outcome:'settle'})).kind,'settled');const patch=JSON.parse(await db(`select scoped_edit_private.candidate_patch_v1(c,'${w.m.operationId}','${w.b.attemptId}',${lit(w.edits)}) from scoped_edit_private.contexts_v1 c where id='${w.c.contextId}';`));if(!complete)return {patch};const completion=await workerRPC('complete_scoped_trip_edit_work_v1',{...p,p_patch:patch});assert.equal(completion.kind,'candidate_saved');return {completion,patch};}
run('worker stays default pending without qualification; original queue and synthetic budget produce settled candidate with no Proposal',async()=>{
 const ordinary=await tripFixture(),oc=await prepare(ordinary),om={action:'ask',operationId:uuid(),basis:basis(oc),text:'Synthetic Ask'};assert.equal((await submit(ordinary,om)).reason,'provider_unavailable');assert.equal(await db(`select count(*) from turn_private.work where owner_id='${ordinary.owner}';`),'0');
 const a=await workerFixture(),w=await leaseAsk(a),{completion}=await saveCandidate(a,w,0);assert.equal(completion.receipt.candidates[0].candidateId,w.b.attemptId);assert.equal(await db(`select count(*) from public.trip_proposals where trip_id='${a.trip}';`),'0');assert.equal((await readOp(a,w.m.operationId)).receipt.kind,'scoped_edit_candidates/1');assert.equal((await workerRPC('read_scoped_trip_edit_completion_v1',{p_binding:w.b})).kind,'candidate_saved');
 const select={action:'select_candidate',operationId:uuid(),basis:basis(w.c),askOperationId:w.m.operationId,candidateId:w.b.attemptId},r=await submit(a,select);assert.equal(r.kind,'scoped_edit_proposal/1');assert.equal(await db(confirmProposalSQL(a,r)),'applied');assert.equal((await readOp(a,select.operationId)).state,'applied');
});
run('current consent/global stop/source gates prevent effects; lease reclaim reuses output and original budget attempt',async()=>{
 const a=await workerFixture(),w=await leaseAsk(a);await db(`update turn_private.hosted_worker_control set enabled=false where singleton;`);assert.equal((await workerRPC('authorize_scoped_trip_edit_effect_v1',{p_binding:w.b,p_effect:'reserve'})).kind,'pending');await db(`update turn_private.hosted_worker_control set enabled=true where singleton;`);const saved=await saveCandidate(a,w,20,false);await db(`update turn_private.work set expires_at=clock_timestamp()-interval '1 second' where turn_id='${w.l.turnId}';`);const l2=await workerRPC('claim_scoped_trip_edit_work_v1',{p_owner_id:a.owner,p_policy_id:a.policy,p_scope_id:a.scope});assert.equal(l2.kind,'leased');assert.notEqual(l2.leaseToken,w.b.leaseToken);const in2=await workerRPC('read_scoped_trip_edit_work_v1',{p_turn_id:l2.turnId,p_lease_token:l2.leaseToken});assert.equal(in2.binding.attemptId,w.b.attemptId);assert.equal((await workerRPC('read_scoped_trip_edit_output_v1',{p_binding:in2.binding})).accounting,'settled');assert.equal((await workerRPC('complete_scoped_trip_edit_work_v1',{p_binding:in2.binding,p_patch:saved.patch})).kind,'candidate_saved');assert.equal((await workerRPC('read_scoped_trip_edit_completion_v1',{p_binding:in2.binding})).kind,'candidate_saved');assert.equal(await db(`select count(*) from public.model_budget_attempts where task_id='${w.b.taskId}';`),'1');
 await db(`update turn_private.planning_consents set revoked_at=clock_timestamp() where owner_id='${a.owner}' and policy_id='${a.planning}';`);assert.equal((await workerRPC('authorize_scoped_trip_edit_effect_v1',{p_binding:in2.binding,p_effect:'publish'})).kind,'pending');
});
run('typed add replace remove are constrained to current context sources and deterministic IDs',async()=>{
 const a=await workerFixture(),edits=[{kind:'replace_item',itemId:'b',sourceItemId:'z'},{kind:'remove_item',itemId:'a'},{kind:'add_item',sourceItemId:'c',toDayId:'d1'}],w=await leaseAsk(a,edits),{completion}=await saveCandidate(a,w);assert.deepEqual(completion.receipt.candidates[0].diff.changes.map(c=>c.kind),['removed','replaced','added']);const selection={action:'select_candidate',operationId:uuid(),basis:basis(w.c),askOperationId:w.m.operationId,candidateId:w.b.attemptId};const r=await submit(a,selection);assert.equal(await db(confirmProposalSQL(a,r)),'applied');const after=await snap(a);assert.equal(after.days[0].items.find(i=>i.id==='b').title,'Z');assert.equal(after.days[0].items.some(i=>i.id==='a'),false);assert.equal(after.days[0].items.some(i=>i.id.startsWith('edit-')&&i.title==='C'),true);
 const b=await workerFixture(),c=await prepare(b,contextInput({dayIds:[],itemIds:['b']}));await denial(`select scoped_edit_private.candidate_patch_v1(c,'${uuid()}','${uuid()}',${lit([{kind:'add_item',sourceItemId:'c',toDayId:'d1'}])}) from scoped_edit_private.contexts_v1 c where id='${c.contextId}';`,/ADD_OUTSIDE_SCOPE/);
});
run('reservation preservation is explicit exact revision binding, unknown stays unavailable and changes invalidate confirmation',async()=>{
 const a=await tripFixture(),v=input({fields:fields({kind:'activity',startsAt:null,endsAt:null,timeZone:null})});await confirm(a,v);const required=await prepare(a);assert.equal(required.kind,'scoped_edit_binding_required/1');assert.equal(required.reservations[0].referenceId,v.referenceId);const c=await prepare(a,contextInput({dayIds:['d1'],itemIds:[]},[{itemId:'b',referenceId:v.referenceId,referenceRevision:1}]));assert.equal(c.kind,'scoped_edit_context/1');assert.deepEqual(c.fixedItemIds,['b']);await denial(submitSQL(a,mutation(c)),/PROTECTED_ITEM/);
 const r=await submit(a,mutation(c,{kind:'set_time',itemId:'a',startsAt:'2026-10-08T12:00:00+00:00',endsAt:null}));await confirm(a,{...v,operationId:uuid(),expectedRevision:1,fields:fields({kind:'activity',startsAt:null,endsAt:null,timeZone:null,status:'amended'})});await denial(confirmProposalSQL(a,r),/SCOPED_CONFIRM_GUARD/);
 const unknown=await tripFixture();await confirm(unknown,input({fields:fields({status:'unknown'})}));assert.equal((await prepare(unknown)).reason,'provider_unavailable');
 await db('alter function public.read_reservation_references_v1(uuid,integer,uuid,uuid,integer) rename to fixture_missing_reservation_reader;');assert.equal((await prepare(await tripFixture())).reason,'provider_unavailable');await db('alter function public.fixture_missing_reservation_reader(uuid,integer,uuid,uuid,integer) rename to read_reservation_references_v1;');
});
run('live TTL and bounded cleanup preserve lineage and never permit old candidate confirmation',async()=>{
 const a=await tripFixture();await db(`create function scoped_edit_private.fixture_short_ttl() returns trigger language plpgsql as $$begin if new.owner_id='${a.owner}' then new.expires_at=clock_timestamp()+interval '250 milliseconds';end if;return new;end $$;create trigger fixture_short_ttl before insert on scoped_edit_private.contexts_v1 for each row execute function scoped_edit_private.fixture_short_ttl();`);const c=await prepare(a),r=await submit(a,mutation(c));await db('select pg_sleep(0.3);');assert.equal((await submit(a,mutation(c))).reason,'stale_basis');assert.equal(await db(confirmProposalSQL(a,r)),'proposal_expired');assert.equal(await db(serviceClaims+'select scoped_edit_private.cleanup_expired_v1(1);'),'1');assert.equal(await db(`select count(*) from scoped_edit_private.lineage_v1 where proposal_id='${r.proposalId}';`),'1');assert.equal(await db(`select head_version from public.trips where id='${a.trip}';`),'0');await db('drop trigger fixture_short_ttl on scoped_edit_private.contexts_v1;drop function scoped_edit_private.fixture_short_ttl();');
});
run('exact export lease pages all scoped metadata sections; old inventory remains unenrolled partial',async()=>{
 const a=await tripFixture(),c=await prepare(a);await submit(a,{action:'lock',operationId:uuid(),basis:basis(c),itemId:'b',locked:true});const fresh=await prepare(a);await submit(a,mutation(fresh,{kind:'set_time',itemId:'a',startsAt:'2026-10-08T12:00:00+00:00',endsAt:null}));const request=uuid(),policy=uuid();await db(`insert into export_private.core_policies_v1(id,revision,enabled,environment,key_id,max_run_ms,artifact_ttl_ms,ticket_ttl_ms,max_pages,page_size,max_bytes,valid_until) values('${policy}',1,true,'local','synthetic-scoped',90000,600000,300000,100,100,8388608,clock_timestamp()+interval '1 day');`);await db(claims(a)+`select public.privacy_core_export_v1('request',${lit({requestId:request,confirmed:true})});`);const lease=JSON.parse(await db(serviceClaims+`select public.privacy_core_export_v1('claim',${lit({requestId:request,operationId:uuid(),maxRunMs:90000,expectedEnvironment:'local',expectedKeyId:'synthetic-scoped'})});`));const exportSQL=(id=lease.leaseId,gen=lease.generation,after=null)=>serviceClaims+`select scoped_edit_private.export_metadata_v1('${request}','${id}',${gen},${after?"'"+after+"'":'null'},2);`;let page,after=null,records=[];do{page=JSON.parse(await db(exportSQL(lease.leaseId,lease.generation,after)));assert.equal(page.enrolled,false);assert.equal(page.inventoryStatus,'partial');records.push(...page.items);after=page.nextCursor;}while(page.hasMore);assert.deepEqual([...new Set(records.map(r=>r.section))].sort(),['contexts','lineage','locks','operations']);assert.equal(page.sectionComplete,true);assert.equal(JSON.stringify(records).includes('Synthetic selected edit'),false);assert.deepEqual(JSON.parse(await db(exportSQL(uuid()))),{kind:'unavailable'});assert.deepEqual(JSON.parse(await db(exportSQL(lease.leaseId,lease.generation+1))),{kind:'unavailable'});await denial(exportSQL(lease.leaseId,lease.generation,'operation:'+uuid()),/INVALID_EXPORT_CURSOR/);await db(`update export_private.core_jobs_v1 set lease_expires_at=clock_timestamp()-interval '1 second' where request_id='${request}';`);assert.deepEqual(JSON.parse(await db(exportSQL())),{kind:'unavailable'});
});
const sourceRoot=process.env.VP_SCOPED_TS_SOURCE_ROOT??process.cwd();
async function tsModule(path){return import('file://'+sourceRoot+'/'+path);}
run('real TypeScript service consumes SQL context, immutable candidates, explicit selection and original exact proposal',async()=>{
 const {runScopedEdit,assertOriginalScopedProposal}=await tsModule('lib/server/trip/scoped-edit/service.ts'),{candidateScopedEditsPatch}=await tsModule('lib/server/trip/scoped-edit/candidate-guard.ts'),{applyPatch}=await tsModule('lib/server/trip/patch/contract.ts');const a=await workerFixture(),before={...await snap(a),version:0};const rpc=async(name,p)=>({data:JSON.parse(await db(claims(a)+`select public.${name}(${Object.entries(p).map(([k,v])=>`${k} => ${typeof v==='object'?lit(v):"'"+String(v).replaceAll("'","''")+"'"}`).join(',')});`)),error:null});
 const c=await runScopedEdit(a.trip,{action:'context',expectedHeadVersion:0,scope:{dayIds:['d1'],itemIds:[]},locale:'en'},rpc,before,Date.now());assert.equal(c.kind,'scoped_edit_context/1');const ask={action:'ask',operationId:uuid(),basis:basis(c),text:'Synthetic selected edit'};const pending=await runScopedEdit(a.trip,ask,rpc,before,Date.now());assert.equal(pending.reason,'queued');const l=await workerRPC('claim_scoped_trip_edit_work_v1',{p_owner_id:a.owner,p_policy_id:a.policy,p_scope_id:a.scope}),input=await workerRPC('read_scoped_trip_edit_work_v1',{p_turn_id:l.turnId,p_lease_token:l.leaseToken});const edits=[{kind:'replace_item',itemId:'b',sourceItemId:'z'},{kind:'add_item',sourceItemId:'c',toDayId:'d1'}],w={c,m:ask,l,b:input.binding,input,edits};const {completion,patch}=await saveCandidate(a,w);const tsPatch=candidateScopedEditsPatch(c.snapshot,edits,{scope:c.scope,lockedItemIds:c.lockedItemIds,fixedItemIds:c.fixedItemIds},{contextId:c.contextId,askOperationId:ask.operationId,candidateId:input.binding.attemptId});assert.deepEqual(patch,tsPatch);
 const ready=await runScopedEdit(a.trip,{action:'read_operation',operationId:ask.operationId},rpc,before,Date.now());assert.equal(ready.receipt.kind,'scoped_edit_candidates/1');assert.deepEqual(ready.receipt.candidates,completion.receipt.candidates);const select={action:'select_candidate',operationId:uuid(),basis:basis(c),askOperationId:ask.operationId,candidateId:input.binding.attemptId};const r=await runScopedEdit(a.trip,select,rpc,before,Date.now());assert.equal(r.kind,'scoped_edit_proposal/1');const after=applyPatch(before,tsPatch);assertOriginalScopedProposal(r,{id:r.proposalId,revision:r.proposalRevision,baseTripVersion:r.baseVersion,digest:r.proposalDigest,expiresAt:r.expiresAt,before,after,patch:tsPatch},Date.now());assert.equal(await db(confirmProposalSQL(a,r)),'applied');assert.deepEqual({...await snap(a),version:1},after);
});
run('provider destination uses exact current prompt/tuple/digest/configuration and phase order without network',async()=>{
 const {createHash}=await import('node:crypto');const workerRoot=process.env.VP_SCOPED_WORKER_SOURCE_ROOT??process.cwd();const {SCOPED_TRIP_EDIT_PROMPT}=await import('file://'+workerRoot+'/lib/server/turn/scoped-edit/model-output.ts');const a=await workerFixture(),w=await leaseAsk(a);await workerRPC('scoped_trip_edit_budget_v1',{p_binding:w.b,p_effect:'reserve',p_reserved_micros:100,p_actual_micros:null,p_outcome:null});await workerRPC('scoped_trip_edit_budget_v1',{p_binding:w.b,p_effect:'dispatch',p_reserved_micros:null,p_actual_micros:null,p_outcome:null});
 const i=w.input,body=JSON.stringify({model:w.b.model,messages:[{role:'system',content:SCOPED_TRIP_EDIT_PROMPT},{role:'user',content:JSON.stringify({ask:i.text,locale:i.locale,trip:i.context.snapshot,scope:i.context.scope,lockedItemIds:i.context.lockedItemIds,fixedItemIds:i.context.fixedItemIds,profile:i.profile,memory:i.memory})}],stream:false,max_tokens:1000,enable_thinking:false,response_format:{type:'json_object'}});const payloadDigest=createHash('sha256').update(body).digest('hex');const keys=['ownerId','taskId','turnId','operationId','contextId','contextDigest','sourceDigest','tripId','baseVersion','policyId','scopeId','attemptId','provider','model','priceVersion'];const requestDigest=createHash('sha256').update(JSON.stringify(['scoped-trip-edit-request/1',keys.map(k=>w.b[k]),payloadDigest])).digest('hex');const destination={schemaVersion:'provider-destination/1',invocationId:uuid(),provider:'qwen',model:w.b.model,endpoint:i.endpoint,configurationId:a.configuration,configurationVersion:1,phase:'configured',observedAt:new Date().toISOString()};const params={p_binding:w.b,p_destination:destination,p_request_id:w.b.attemptId,p_request_digest:requestDigest,p_payload_digest:payloadDigest,p_payload_text:body};const first=await workerRPC('record_scoped_trip_edit_destination_v1',params);assert.deepEqual(first,{kind:'destination_recorded',attemptId:w.b.attemptId,invocationId:destination.invocationId,phase:'configured'});
 const bad=await sql(container,serviceClaims+`select public.record_scoped_trip_edit_destination_v1(${lit(w.b)},${lit({...destination,phase:'response_buffered'})},'${w.b.attemptId}','${requestDigest}','${payloadDigest}','${body.replaceAll("'","''")}');`);assert.notEqual(bad.code,0);assert.match(bad.stderr,/IDEMPOTENCY_KEY_REUSE/);assert.equal((await workerRPC('record_scoped_trip_edit_destination_v1',{...params,p_destination:{...destination,phase:'attempted'}})).phase,'attempted');assert.equal((await workerRPC('record_scoped_trip_edit_destination_v1',{...params,p_destination:{...destination,phase:'response_buffered'}})).phase,'response_buffered');assert.equal(await db(`select count(*) from scoped_edit_private.requests_v1 where turn_id='${w.l.turnId}';`),'1');assert.equal(await db(`select exists(select 1 from information_schema.columns where table_schema='scoped_edit_private' and table_name='requests_v1' and column_name='payload_text');`),'f');
});
run('actual executor uses real SQL budget/source/usage/candidate RPCs with a synthetic provider, recovers lost ACKs and creates no Proposal',async()=>{
 const workerRoot=process.env.VP_SCOPED_WORKER_SOURCE_ROOT??process.cwd();const {executeScopedTripEdit}=await import('file://'+workerRoot+'/lib/server/turn/scoped-edit/executor.ts');const {createTextJobPrice}=await tsModule('lib/server/jobs/staging-text-job.ts');const price=createTextJobPrice({mode:'flat',inputMicrosPerMillion:1000000,outputMicrosPerMillion:1000000,cachedInputMicrosPerMillion:null});const a=await workerFixture(),w=await leaseAsk(a,[{kind:'move_item',itemId:'b',toDayId:'d2'}]);let calls=0,outputLost=false,completionLost=false;const logged=[],rpcErrors=[];
 const ports={now:Date.now,price,recordUsage:async receipt=>{assert.equal(receipt.actualMicros,15);assert.equal(receipt.attemptId??receipt.attempt?.attemptId,w.b.attemptId);logged.push('validated_usage');},rpc:async(name,p)=>{logged.push(name);let r;try{r=await workerRPC(name,p);}catch(e){rpcErrors.push({name,error:String(e.message).slice(0,500)});throw e;}if(name==='record_scoped_trip_edit_output_v1'&&!outputLost){outputLost=true;throw Error('Synthetic lost output ACK');}if(name==='complete_scoped_trip_edit_work_v1'&&!completionLost){completionLost=true;throw Error('Synthetic lost completion ACK');}return r;},transport:async req=>{calls++;assert.equal(req.endpoint,w.input.endpoint);const body=JSON.parse(req.body);assert.equal(body.model,w.b.model);assert.equal(body.messages.length,2);return Response.json({model:w.b.model,usage:{prompt_tokens:10,completion_tokens:5,total_tokens:15},choices:[{index:0,finish_reason:'stop',message:{role:'assistant',content:JSON.stringify({kind:'candidate',edits:w.edits})}}]});}};
 assert.equal(await executeScopedTripEdit(w.l,ports,new AbortController().signal),'persisted',JSON.stringify({logged,rpcErrors,calls}));assert.equal(calls,1);assert.ok(logged.includes('read_scoped_trip_edit_completion_v1'));assert.equal(await db(`select count(*) from public.trip_proposals where trip_id='${a.trip}';`),'0');assert.equal(await db(`select status from public.model_budget_attempts where attempt_id='${w.b.attemptId}';`),'settled');assert.equal(await db(`select actual_micros from public.model_budget_attempts where attempt_id='${w.b.attemptId}';`),'15');assert.equal(await db(`select state from turn_private.work where turn_id='${w.l.turnId}';`),'completed');assert.equal((await readOp(a,w.m.operationId)).receipt.kind,'scoped_edit_candidates/1');
 // A validated safety-blocked response is billable metadata without a candidate.
 const blocked=await workerFixture(),bw=await leaseAsk(blocked);const safetyPorts={...ports,recordUsage:async()=>{},rpc:workerRPC,transport:async()=>Response.json({model:bw.b.model,usage:{prompt_tokens:10,completion_tokens:5,total_tokens:15},choices:[{index:0,finish_reason:'content_filter',message:{role:'assistant',content:''}}]})};assert.equal(await executeScopedTripEdit(bw.l,safetyPorts,new AbortController().signal),'declined');const known=await workerRPC('read_scoped_trip_edit_usage_v1',{p_binding:bw.b});assert.equal(known.kind,'saved_usage');assert.equal(known.actualMicros,15);assert.equal(await db(`select status from public.model_budget_attempts where attempt_id='${bw.b.attemptId}';`),'settled');assert.equal(await db(`select count(*) from public.trip_proposals where trip_id='${blocked.trip}';`),'0');
});
run('marked proposal reader and operation become stale on source change before original confirmation',async()=>{
 const a=await tripFixture(),c=await prepare(a),m=mutation(c),r=await submit(a,m);const readCurrent=async()=>JSON.parse(await db(claims(a)+`select public.read_scoped_trip_edit_proposal_current_v1('${r.proposalId}');`));assert.deepEqual(await readCurrent(),{kind:'scoped_edit_current/1',proposalId:r.proposalId,current:true});await db(`insert into public.memory_consents(id,owner_id,status) values('${uuid()}','${a.owner}','granted');`);assert.equal((await readCurrent()).current,false);assert.equal((await readOp(a,m.operationId)).state,'stale');await denial(confirmProposalSQL(a,r),/SCOPED_CONFIRM_GUARD/);
});
run('legacy intake-v2 remains a legal work mode with an existing row during scoped migration',async()=>{
 assert.equal(await db(`select execution_mode from turn_private.work where turn_id='${legacyV2}';`),'planning_intake_comparison_v2');const a=await workerFixture(),w=await leaseAsk(a);await db(`update turn_private.work set execution_mode='planning_intake_comparison_v2' where turn_id='${w.l.turnId}';`);assert.equal(await db(`select execution_mode from turn_private.work where turn_id='${w.l.turnId}';`),'planning_intake_comparison_v2');assert.equal((await workerRPC('read_scoped_trip_edit_work_v1',{p_turn_id:w.l.turnId,p_lease_token:w.l.leaseToken})).kind,'pending');
});
run('known settled cannot-edit ends original task as declined; unknown usage cannot fake a refusal',async()=>{
 const a=await workerFixture(),w=await leaseAsk(a),p={p_binding:w.b};await workerRPC('scoped_trip_edit_budget_v1',{...p,p_effect:'reserve',p_reserved_micros:100,p_actual_micros:null,p_outcome:null});await workerRPC('scoped_trip_edit_budget_v1',{...p,p_effect:'dispatch',p_reserved_micros:null,p_actual_micros:null,p_outcome:null});assert.equal((await workerRPC('pause_scoped_trip_edit_work_v1',{...p,p_reason:'safety_refused'})).kind,'pending');await workerRPC('record_scoped_trip_edit_output_v1',{...p,p_output:{kind:'cannot_edit',reason:'no_change'},p_usage:usage,p_actual_micros:15});await workerRPC('scoped_trip_edit_budget_v1',{...p,p_effect:'finish',p_reserved_micros:null,p_actual_micros:15,p_outcome:'settle'});assert.equal((await workerRPC('pause_scoped_trip_edit_work_v1',{...p,p_reason:'safety_refused'})).kind,'pending');const declined=await workerRPC('pause_scoped_trip_edit_work_v1',{...p,p_reason:'no_change'});assert.equal(declined.kind,'declined');assert.equal(declined.receipt.reason,'no_change');assert.equal((await readOp(a,w.m.operationId)).state,'declined');assert.equal((await workerRPC('pause_scoped_trip_edit_work_v1',{...p,p_reason:'no_change'})).receipt.reused,true);assert.equal(await db(`select state from turn_private.work where turn_id='${w.l.turnId}';`),'completed');assert.equal(await db(`select status from public.turns where id='${w.l.turnId}';`),'completed');assert.equal(await db(`select count(*) from public.trip_proposals where trip_id='${a.trip}';`),'0');
});
run('composed candidate applies reorder before removal in the original operation order',async()=>{
 const {candidateScopedEditsPatch}=await tsModule('lib/server/trip/scoped-edit/candidate-guard.ts'),{applyPatch}=await tsModule('lib/server/trip/patch/contract.ts');const a=await workerFixture(),edits=[{kind:'reorder_items',dayId:'d1',itemIds:['c','b','a']},{kind:'remove_item',itemId:'a'}],w=await leaseAsk(a,edits),{completion,patch}=await saveCandidate(a,w);const expected=candidateScopedEditsPatch(w.c.snapshot,edits,{scope:w.c.scope,lockedItemIds:[],fixedItemIds:[]},{contextId:w.c.contextId,askOperationId:w.m.operationId,candidateId:w.b.attemptId});assert.deepEqual(patch,expected);const r=await submit(a,{action:'select_candidate',operationId:uuid(),basis:basis(w.c),askOperationId:w.m.operationId,candidateId:completion.receipt.candidates[0].candidateId});assert.equal(await db(confirmProposalSQL(a,r)),'applied');assert.deepEqual({...await snap(a),version:1},applyPatch(w.c.snapshot,expected));
});
