import { readFileSync,writeFileSync,mkdirSync } from 'node:fs';import{createHash}from'node:crypto';import{sql}from'../../cost/fixtures/postgres-rpc.mjs';
const c=readFileSync('/tmp/vpj58-turn-sql-container','utf8').trim(),dir='tests/integration/privacy/turn-data-sql/candidates';mkdirSync(dir,{recursive:true});
const lit=v=>"'"+v.replaceAll("'","''")+"'";const db=async q=>{const r=await sql(c,"set search_path='';"+q);if(r.code)throw Error(r.stderr);return r.stdout.trim();};const hash=v=>createHash('sha256').update(v).digest('hex'),md5=v=>createHash('md5').update(v).digest('hex');
const ids=['export_private.lock_job_v1(uuid,boolean)','public.privacy_core_export_v1(text,jsonb)','profile_data_private.sources_v1()','profile_data_private.schema_v1()','result_data_private.schema_supported_v1()','export_private.profile_hooks_valid_v1()'];
const defs=JSON.parse(await db(`select jsonb_object_agg(id,pg_get_functiondef(id::regprocedure)) from unnest(array[${ids.map(lit).join(',')}]::text[]) id`));
const out={...defs};
out[ids[0]]=defs[ids[0]].replace(' if export_private.profile_source_current_v1(j) is distinct from true then return null;end if;',' if export_private.profile_source_current_v1(j) is distinct from true then return null;end if;\n if export_private.turn_source_current_v1(j) is distinct from true then return null;end if;');
out[ids[1]]=defs[ids[1]].replace('profile_lease_deadline timestamptz;','profile_lease_deadline timestamptz;turn_lease_deadline timestamptz;').replace(" if p_action='profile_page' then return export_private.core_profile_page_v1(p_input);end if;"," if p_action='profile_page' then return export_private.core_profile_page_v1(p_input);end if;\n if p_action='turn_page' then return export_private.core_turn_page_v1(p_input);end if;")
.replace("if j.state='running' and export_private.profile_commit_qualifies_v1(j,p_input->'modules',lease,gen) is distinct from true then raise exception 'INVALID_OUTPUT';end if;", "if j.state='running' and export_private.profile_commit_qualifies_v1(j,p_input->'modules',lease,gen) is distinct from true then raise exception 'INVALID_OUTPUT';end if;\n  if j.state='running' and export_private.turn_commit_qualifies_v1(j,p_input->'modules',lease,gen) is distinct from true then raise exception 'INVALID_OUTPUT';end if;")
.replace('profile_lease_deadline:=j.lease_expires_at;', 'profile_lease_deadline:=j.lease_expires_at;turn_lease_deadline:=j.lease_expires_at;')
.replace("if export_private.profile_source_current_v1(j) is distinct from true then raise exception 'INVALID_OUTPUT';end if;", "if export_private.profile_source_current_v1(j) is distinct from true then raise exception 'INVALID_OUTPUT';end if;\n    if export_private.turn_source_current_v1(j) is distinct from true then raise exception 'INVALID_OUTPUT';end if;")
.replace('perform export_private.record_profile_provenance_v1(j,profile_lease_deadline);','perform export_private.record_profile_provenance_v1(j,profile_lease_deadline);\n  perform export_private.record_turn_provenance_v1(j,turn_lease_deadline);');
// Closed original source inventory gains finite owned rows, never a new namespace exception.
out[ids[2]]=defs[ids[2]].replace(" ('public.privacy_requests','owner_id=$1','id')", " ('turn_data_private.operations_v1','owner_id=$1','request_id'),\n ('turn_data_private.export_provenance_v1','owner_id=$1','\"request_id\",\"generation\"'),\n ('public.privacy_requests','owner_id=$1','id')");
const metadata=JSON.parse(await db(`select jsonb_agg(jsonb_build_object('relation',n.nspname||'.'||c.relname,'columns',(select jsonb_agg(jsonb_build_array(a.attname,format_type(a.atttypid,a.atttypmod),a.attnotnull)order by a.attnum)from pg_attribute a where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped),'constraints',(select jsonb_agg(pg_get_constraintdef(k.oid)order by k.conname)from pg_constraint k where k.conrelid=c.oid))order by n.nspname,c.relname)from pg_class c join pg_namespace n on n.oid=c.relnamespace where c.relkind='r' and n.nspname not in('pg_catalog','information_schema','extensions','auth','result_data_private','storage','realtime','_realtime','vault','supabase_functions','supabase_migrations')`));
const pgJSON=await db(`select (select coalesce(jsonb_agg(jsonb_build_object('relation',n.nspname||'.'||c.relname,'columns',(select jsonb_agg(jsonb_build_array(a.attname,format_type(a.atttypid,a.atttypmod),a.attnotnull) order by a.attnum) from pg_attribute a where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped),'constraints',(select jsonb_agg(pg_get_constraintdef(k.oid) order by k.conname) from pg_constraint k where k.conrelid=c.oid)) order by n.nspname,c.relname),'[]'::jsonb) from pg_class c join pg_namespace n on n.oid=c.relnamespace where c.relkind='r' and n.nspname not in('pg_catalog','information_schema','extensions','auth','result_data_private','storage','realtime','_realtime','vault','supabase_functions','supabase_migrations'))::text`);
const catalogHash=hash(pgJSON);const names=JSON.parse(await db("select jsonb_agg(relation_name) from profile_data_private.sources_v1()"));names.push('public.user_profiles','turn_data_private.operations_v1','turn_data_private.export_provenance_v1');const arr='array['+names.map(lit).join(',')+']::regclass[]';
const columns=JSON.parse(await db(`select jsonb_object_agg(c.oid::regclass::text,jsonb_build_object('columns',(select jsonb_agg(jsonb_build_array(a.attname,format_type(a.atttypid,a.atttypmod),a.attnotnull)order by a.attnum)from pg_attribute a where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped),'constraints',(select jsonb_agg(pg_get_constraintdef(k.oid)order by k.conname)from pg_constraint k where k.conrelid=c.oid)))from pg_class c where c.oid=any(${arr})`));
const fks=JSON.parse(await db(`select coalesce(jsonb_agg(jsonb_build_array(conrelid::regclass::text,confrelid::regclass::text,conname,pg_get_constraintdef(oid)) order by conrelid::regclass::text,conname),'[]')from pg_constraint where contype='f'and(conrelid=any(${arr})or confrelid=any(${arr}))`));
const triggers=JSON.parse(await db(`select coalesce(jsonb_agg(jsonb_build_array(tgrelid::regclass::text,tgname,pg_get_triggerdef(oid),tgfoid::regprocedure::text)order by tgrelid::regclass::text,tgname),'[]')from pg_trigger where not tgisinternal and tgrelid=any(${arr})`));
const schema=JSON.parse(readFileSync('lib/server/privacy/turn-data/source-schema.json','utf8'));const guardTables=schema.map(s=>s.relation).concat(['turn_private.assistant_goal_trip_links','turn_private.assistant_goal_trip_receipts','knowledge_review_private.source_impact_sets','knowledge_review_private.source_impact_items','knowledge_review_private.source_impact_pages','knowledge_review_private.source_impact_outbox','knowledge_review_private.source_impact_projections','knowledge_review_private.source_impact_review_requests','readiness_private.scopes_v1','readiness_private.operations_v1','guide_private.bindings_v1','scoped_edit_private.work_v1','scoped_edit_private.requests_v1','scoped_edit_private.contexts_v1','scoped_edit_private.operations_v1','notification_private.reminders','notification_private.watches','notification_private.dismissals','service_brief_private.briefs','service_brief_private.previews','service_brief_private.operations']);
for(const rel of names.filter(x=>guardTables.includes(x)))triggers.push([rel,'turn_data_parent_fence_v1',`CREATE TRIGGER turn_data_parent_fence_v1 BEFORE INSERT OR DELETE OR UPDATE ON ${rel} FOR EACH ROW EXECUTE FUNCTION turn_data_private.guard_source_v1()`,'turn_data_private.guard_source_v1()']);triggers.sort((a,b)=>a[0]<b[0]?-1:a[0]>b[0]?1:a[1]<b[1]?-1:a[1]>b[1]?1:0);
const body=def=>def.match(/AS \$function\$([\s\S]*?)\$function\$/)[1];
let hooks=out[ids[5]];for(const id of [ids[0],ids[1],ids[2]]){const old=md5(defs[id]),next=md5(out[id]);if(!hooks.includes(old))throw Error('Missing original hook pin '+id);hooks=hooks.replaceAll(old,next);}out[ids[5]]=hooks;
let ps=out[ids[3]];ps=ps.replace(/(expected:=)'(?:''|[^'])*'::jsonb/,(_,a)=>a+lit(JSON.stringify(columns))+'::jsonb').replace(/(if fk is distinct from )'[^']*'::jsonb/,(_,a)=>a+lit(JSON.stringify(fks))+'::jsonb').replace(/(if actual is distinct from )'\[\[[^']*'::jsonb/,(_,a)=>a+lit(JSON.stringify(triggers))+'::jsonb');
for(const id of ids){ps=ps.replaceAll(md5(defs[id]),md5(out[id]));}
ps=ps.replace(/='[a-f0-9]{64}'/g,"='"+catalogHash+"'");ps=ps.replace(/<> '[a-f0-9]{64}'/g,"<> '"+catalogHash+"'");ps=ps.replace(/<>\s*'[a-f0-9]{64}'/g,"<> '"+catalogHash+"'");out[ids[3]]=ps;
out[ids[4]]=out[ids[4]].replace(/='[a-f0-9]{64}'/,"='"+catalogHash+"'");
for(const id of ids){if(out[id]===defs[id])throw Error('No candidate delta '+id);const slug=id.split('(')[0].replaceAll('.','-');writeFileSync(dir+'/'+slug+'.before.sql',defs[id]);writeFileSync(dir+'/'+slug+'.after.sql',out[id]);}
writeFileSync(dir+'/catalog.json',JSON.stringify({catalogHash,ownTables:metadata.filter(x=>x.relation.startsWith('turn_data_private.')),profileSources:names,profileShape:columns,foreignKeys:fks,triggers,guardTables,functions:ids.map(id=>({identity:id,oldDefinitionMd5:md5(defs[id]),newDefinitionMd5:md5(out[id]),oldDefinitionSha:hash(defs[id]),newDefinitionSha:hash(out[id])}))},null,2));
writeFileSync(dir+'/review.sql',ids.map(id=>`-- Precise candidate: ${id}\ndo $baseline$begin if pg_get_functiondef(${lit(id)}::regprocedure) is distinct from $reviewed$${defs[id]}$reviewed$ then raise exception 'TURN_DEPENDENCY_DRIFT';end if;end$baseline$;\n${out[id]}`).join('\n'));
for(const id of ids){const slug=id.split('(')[0].replaceAll('.','-');const {spawnSync}=await import('node:child_process');const r=spawnSync('diff',['-u',dir+'/'+slug+'.before.sql',dir+'/'+slug+'.after.sql'],{encoding:'utf8'});writeFileSync(dir+'/'+slug+'.patch',r.stdout);}
console.log('CANDIDATES',ids.length,'guardTables',guardTables.length,'catalogHash',catalogHash);
