import { fixturePath } from './fixture-path.mjs';
import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{randomUUID as uuid}from'node:crypto';import{sql}from'../../cost/fixtures/postgres-rpc.mjs';const cn=readFileSync(fixturePath('vpj58-turn-sql-container'),'utf8').trim();const{a}=JSON.parse(readFileSync(fixturePath('vpj58-turn-actual-preview.json'),'utf8'));const check=async(q,re)=>{const r=await sql(cn,q);assert.notEqual(r.code,0);assert.match(r.stderr,re);};
await check(`begin;with ids as(insert into public.turns(id,owner_id,thread_id,status)select gen_random_uuid(),'${a.owner}','${a.thread}','completed'from generate_series(1,100)returning id)insert into turn_private.text_content(turn_id,owner_id,thread_id,policy_id,consent_id,locale,input_text)select id,'${a.owner}','${a.thread}','${a.policy}','${a.consent}','en',repeat('界',4000)from ids;select turn_data_private.export_source_v1('${a.owner}');commit;`,/TURN_CAPACITY/);
// Source admission itself rejects >10000 roots before per-identity locks. Seed the
// real rows in bounded transactions so fixture setup does not exhaust PG's
// unchanged lock table before reaching that existing snapshot gate.
const ids=Array.from({length:10001},()=>uuid());
for(let offset=0;offset<ids.length;offset+=250){const values=ids.slice(offset,offset+250).map(id=>`('${id}','${a.owner}','completed')`).join(',');const r=await sql(cn,`insert into public.turns(id,owner_id,status)values${values}`);assert.equal(r.code,0,r.stderr);}
try{await check(`select turn_data_private.export_source_v1('${a.owner}')`,/TURN_CAPACITY/);}finally{for(let offset=0;offset<ids.length;offset+=250){const r=await sql(cn,`delete from public.turns where id in(${ids.slice(offset,offset+250).map(id=>`'${id}'`).join(',')})`);assert.equal(r.code,0,r.stderr);}}
const r=await sql(cn,`select input_text from turn_private.text_content where turn_id='${a.turn}'`);assert.equal(r.code,0);assert.equal(r.stdout.trim(),'Selected sensitive input');console.log('ACTUAL_UTF8_1MB_AND_10001_ROOT_SNAPSHOT_FULL_FAILURE_ROLLBACK_PASS');
