import { fixturePath } from './fixture-path.mjs';
import{readFileSync,writeFileSync}from'node:fs';import{sql}from'../../cost/fixtures/postgres-rpc.mjs';const c=readFileSync(fixturePath('vpj58-turn-sql-container'),'utf8').trim(),db=async q=>{const r=await sql(c,"set search_path='';"+q);if(r.code)throw Error(r.stderr);return r.stdout.trim();};
const deps=['public.privacy_turn_data_v1(text,text,bigint)','export_private.core_turn_page_v1(jsonb)','export_private.turn_commit_qualifies_v1(export_private.core_jobs_v1,jsonb,uuid,integer)','export_private.turn_managed_copy_v1(uuid,uuid)','export_private.turn_source_current_v1(export_private.core_jobs_v1)','export_private.record_turn_provenance_v1(export_private.core_jobs_v1,timestamp with time zone)','export_private.lock_job_v1(uuid,boolean)','public.privacy_core_export_v1(text,jsonb)','profile_data_private.sources_v1()','profile_data_private.schema_v1()','result_data_private.schema_supported_v1()','export_private.profile_hooks_valid_v1()','identity_private.guard_mobile_rpc_v2()','identity_private.mobile_access_v2()','auth.uid()','auth.jwt()','auth.role()','notification_private.exact(jsonb,text[])','notification_private.uuid(jsonb)','notification_private.hash(jsonb)','notification_private.canonical(jsonb)','privacy_private.linked_delete_array_v1(jsonb)','turn_private.text_policy_current(uuid)','turn_private.planning_policy_current(uuid)'];
const lit=v=>"'"+v.replaceAll("'","''")+"'";const hashes=JSON.parse(await db(`select jsonb_object_agg(p.oid::regprocedure::text,md5(pg_get_functiondef(p.oid)))from pg_proc p join pg_namespace n on n.oid=p.pronamespace where (n.nspname='turn_data_private' and p.proname<>'runtime_supported_v1') or n.nspname='conversation_data_private' or p.oid=any(array[${deps.map(x=>lit(x)+'::regprocedure').join(',')}])`));
const pinPath='tests/integration/privacy/turn-data-sql/runtime-pins.json';const existing=JSON.parse(readFileSync(pinPath,'utf8'));for(const id of Object.keys(existing.managed_auth||{}))delete hashes[id];if(JSON.stringify(Object.entries(hashes).sort())!==JSON.stringify(Object.entries(existing.hashes).sort()))throw Error('Runtime pin source changed: explicit reviewed delta required');
const ownCount=Object.keys(hashes).filter(k=>k.startsWith('turn_data_private.')).length+1;
const fn=`create function turn_data_private.runtime_supported_v1() returns boolean language plpgsql stable security definer set search_path='' as $$
declare r record;p pg_proc;begin
 if(select count(*)from pg_proc f join pg_namespace n on n.oid=f.pronamespace where n.nspname='turn_data_private')<>${ownCount} then return false;end if;
 for r in select key,value#>>'{}' digest from jsonb_each(${lit(JSON.stringify(hashes))}::jsonb) loop
  if to_regprocedure(r.key) is null then return false;end if;
  select * into p from pg_proc where oid=r.key::regprocedure;
  if md5(pg_get_functiondef(p.oid)) is distinct from r.digest then return false;end if;
 end loop;
 for r in select key,value allowed from jsonb_each(${lit(JSON.stringify(existing.managed_auth||{}))}::jsonb) loop
  if to_regprocedure(r.key) is null then return false;end if;select * into p from pg_proc where oid=r.key::regprocedure;
  if not(r.allowed ? md5(pg_get_functiondef(p.oid))) then return false;end if;
 end loop;return true;
end$$;`;
const file='supabase/migrations/20261007050000_turn_data.sql';let s=readFileSync(file,'utf8');s=s.replace(/create function turn_data_private.runtime_supported_v1\([\s\S]*?\$\$[\s\S]*?\$\$;/,()=>fn);writeFileSync(file,s);writeFileSync('tests/integration/privacy/turn-data-sql/runtime-pins.json',JSON.stringify({kind:'fixed_reviewed_function_definitions',ownCount,hashes,managed_auth:existing.managed_auth},null,2));const applied=await db(fn.replace('create function','create or replace function'));console.log('FIXED_RUNTIME_DEFINITION_PIN',Object.keys(hashes).length,'identities',ownCount,'own functions',await db('select turn_data_private.runtime_supported_v1(),turn_data_private.hooks_valid_v1(),profile_data_private.schema_v1(),result_data_private.schema_supported_v1()'));
