import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{randomUUID as uuid}from'node:crypto';import{sql}from'../../cost/fixtures/postgres-rpc.mjs';
const cn=readFileSync('/tmp/vpj58-turn-sql-container','utf8').trim();const {a,claims}=JSON.parse(readFileSync('/tmp/vpj58-turn-actual-preview.json','utf8'));const lit=v=>"'"+String(v).replaceAll("'","''")+"'";const db=async q=>{const r=await sql(cn,q);assert.equal(r.code,0,r.stderr);return r.stdout.trim();};const fail=async(q,why)=>{const r=await sql(cn,q);assert.notEqual(r.code,0);assert.match(r.stderr,why);};
await db(`update auth.sessions set created_at=clock_timestamp()where id='${a.session}';`);
const query=c=>`begin;${claims}set role authenticated;select public.privacy_turn_data_v1(${lit(c.action)},${lit(JSON.stringify(c))},1);commit;`;
const pick=()=>({scope:'turn-sensitive-data/1',requestId:uuid(),turnId:a.turn,objectIds:[]});const s=pick(),p=JSON.parse(await db(query({action:'preview',...s})));assert.equal(p.eligible,true);
await fail(`begin;update turn_private.text_content set output_text='changed source'where turn_id='${a.turn}';${claims}set role authenticated;select public.privacy_turn_data_v1('erase',${lit(JSON.stringify({action:'erase',...s,sourceDigest:p.sourceDigest,previewDigest:p.previewDigest,confirmed:true}))},1);commit;`,/TURN_SOURCE_CHANGED/);
assert.equal(await db(`select output_text from turn_private.text_content where turn_id='${a.turn}'`),'Selected sensitive output');
for(const ddl of ['alter table public.turns add column unreviewed_source uuid','create table public.unreviewed_turn_reference(turn_id uuid)','alter table public.turn_feedback add constraint unexpected_turn_fk foreign key(turn_id)references public.turns(id)']){const r=JSON.parse(await db(`begin;${ddl};select turn_data_private.source_v1('${a.owner}','${a.turn}')->'conflicts';rollback;`));assert.ok(r.includes('SOURCE_UNSUPPORTED'));}
await fail(`begin;update turn_private.text_consents set revoked_at=clock_timestamp()where owner_id='${a.owner}'and policy_id='${a.policy}';select turn_data_private.source_v1('${a.owner}','${a.turn}');commit;`,/DATA_POLICY_BLOCKED/);
await fail(`begin;update identity_private.mobile_accounts set epoch=2 where owner_id='${a.owner}';${claims}set role authenticated;select public.privacy_turn_data_v1('preview',${lit(JSON.stringify({action:'preview',...pick()}))},1);commit;`,/SESSION_REPLACED/);
const unknown=pick();const mutation={action:'erase',...unknown,sourceDigest:'a'.repeat(64),previewDigest:'b'.repeat(64),confirmed:true};assert.equal(JSON.parse(await db(query({action:'recover',...unknown,mutationBytes:JSON.stringify(mutation)}))).kind,'unknown');
if(await db('select turn_data_private.write_hooks_valid_v1()')==='f')await fail(query({action:'erase',...s,sourceDigest:p.sourceDigest,previewDigest:p.previewDigest,confirmed:true}),/TURN_SOURCE_UNAVAILABLE/);
assert.equal(await db(`select input_text from turn_private.text_content where turn_id='${a.turn}'`),'Selected sensitive input');
console.log('CAS_ROLLBACK_POLICY_EPOCH_UNKNOWN_SCHEMA_DEFAULT_GUARD_NEGATIVES_PASS');
