// Actual network-none SQL under administrator synthetic claims; no signed Auth/role activation.
import test,{before,after} from 'node:test';import assert from 'node:assert/strict';
import {randomUUID as uuid,randomBytes,createHash,createCipheriv,createDecipheriv} from 'node:crypto';import {readFileSync,readdirSync} from 'node:fs';
import {command,sql} from '../cost/fixtures/postgres-rpc.mjs';
const enabled=process.env.VP_TURN_DB_TEST==='1',container='vpj36-export-'+uuid().slice(0,8);let created=false;
const db=async q=>{const r=await sql(container,q);assert.equal(r.code,0,r.stderr);return r.stdout.trim();};
const lit=v=>"'"+JSON.stringify(v).replaceAll("'","''")+"'::jsonb";
const claims=a=>`set request.jwt.claim.role='authenticated';set request.jwt.claim.sub='${a.owner}';set request.jwt.claims='${JSON.stringify({role:'authenticated',is_anonymous:false,session_id:a.session})}';`;
const query=(a,action,input)=> (a?claims(a):"set request.jwt.claim.role='service_role';set request.jwt.claims='{\"role\":\"service_role\"}';")+`select public.privacy_core_export_v1('${action}',${lit(input)});`;
const call=async(a,action,input)=>JSON.parse(await db(query(a,action,input)));
const deny=async(a,action,input,code)=>{const r=await sql(container,query(a,action,input));assert.notEqual(r.code,0);assert.match(r.stderr,new RegExp(code));};
const sha=b=>createHash('sha256').update(b).digest('hex');
const canonical=v=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v!==null&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
const names=['trip','conversations','results','profile','memory','turn','user_artifact','brief','entitlements'];
const modules=()=>names.map(module=>({module,status:'unavailable',reason:'HANDLER_MISSING',pages:0,rows:0,digest:null}));
async function owner(){const a={owner:uuid(),session:uuid(),request:uuid(),epoch:1};await db(`insert into auth.users(id) values('${a.owner}');insert into auth.sessions(id,user_id) values('${a.session}','${a.owner}');insert into identity_private.mobile_accounts(owner_id,epoch,session_id) values('${a.owner}',1,'${a.session}');insert into identity_private.mobile_attempts(owner_id,attempt_id,session_id,epoch) values('${a.owner}','${uuid()}','${a.session}',1);${claims(a)}insert into public.trips(id,owner_id,title) values('${uuid()}','${a.owner}','Own Trip plaintext');`);return a;}
async function fixture(){const a=await owner();const r=await call(a,'request',{requestId:a.request,confirmed:true});assert.equal(r.state,'queued');const input={requestId:a.request,operationId:uuid(),maxRunMs:90000,expectedEnvironment:'local',expectedKeyId:'synthetic-key'};const lease=await call(null,'claim',input);assert.equal(lease.kind,'privacy_export_lease/1');return {a,lease,input};}
function artifact(f,receipts=modules(),data={}){const key=randomBytes(32),nonce=randomBytes(12),plain=Buffer.from(canonical({schemaVersion:'privacy-core-export/1',requestId:f.a.request,coverage:'partial',allUserDataCompleted:false,data,modules:receipts}));const aad=Buffer.from(canonical(['privacy-core-export/1',f.a.request,f.a.owner,f.lease.generation]));const cipher=createCipheriv('aes-256-gcm',key,nonce);cipher.setAAD(aad);const ciphertext=Buffer.concat([cipher.update(plain),cipher.final()]);return {key,plain,wire:{schemaVersion:'privacy-export-artifact/1',keyId:'synthetic-key',nonce:nonce.toString('base64url'),tag:cipher.getAuthTag().toString('base64url'),ciphertext:ciphertext.toString('base64url'),plaintextDigest:sha(plain),plaintextBytes:plain.length,expiresAt:new Date(Date.now()+300000).toISOString()}};}
const binding=f=>({requestId:f.a.request,leaseId:f.lease.leaseId,generation:f.lease.generation});
async function ready(){const f=await fixture(),art=artifact(f);const p={...binding(f),artifact:art.wire,modules:modules(),coverage:'partial'};const r=await call(null,'commit',p);assert.equal(r.state,'ready_partial');return {...f,art,commit:p,receipt:r};}
before(async()=>{if(!enabled)return;const r=await command('docker',['run','--pull=never','--rm','-d','--network','none','--name',container,'--user','postgres','--entrypoint','/bin/sh','public.ecr.aws/supabase/postgres:17.6.1.159','-c','umask 077;mkdir /tmp/vpj59-socket;initdb -D /tmp/vpj59-db -A trust --no-locale -E UTF8 >/tmp/init.log 2>&1 && exec postgres -D /tmp/vpj59-db -c listen_addresses= -c unix_socket_directories=/tmp/vpj59-socket -c unix_socket_permissions=0700']);assert.equal(r.code,0,r.stderr);created=true;for(let n=0;n<100;n++){if((await command('docker',['exec',container,'pg_isready','-h','/tmp/vpj59-socket','-U','postgres'])).code===0)break;await new Promise(r=>setTimeout(r,100));}
 await db(readFileSync('tests/integration/turn/fixtures/durable-work-schema.sql','utf8'));await db("create function auth.role() returns text language sql as $$select nullif(current_setting('request.jwt.claim.role',true),'')$$;create schema extensions;create extension pgcrypto with schema extensions;");for(const f of readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')).sort())await db('begin;'+readFileSync('supabase/migrations/'+f,'utf8')+'commit;');
 await db(`insert into export_private.core_policies_v1(id,revision,enabled,environment,key_id,max_run_ms,artifact_ttl_ms,ticket_ttl_ms,max_pages,page_size,max_bytes,valid_until) values('${uuid()}',1,true,'local','synthetic-key',90000,600000,300000,1000,100,8388608,clock_timestamp()+interval '1 day');`);
});
after(async()=>{if(created)assert.equal((await command('docker',['rm','-f',container])).code,0);});
const run=(name,fn)=>test(name,{skip:!enabled,timeout:120000},fn);
run('real native-bound request/lease/current Trip page, closed role guards and unchanged intent',async()=>{
 const f=await fixture();assert.equal((await call(f.a,'request',{requestId:f.a.request,confirmed:true})).state,'running');assert.equal((await call(null,'claim',f.input)).reused,true);assert.deepEqual(await call(null,'validate',binding(f)),{kind:'privacy_export_lease_state/1',current:true});const page=await call(null,'trip_page',{...binding(f),afterTripId:null,limit:100});assert.equal(page.items.length,1);assert.equal(page.items[0].title,'Own Trip plaintext');assert.equal(page.sectionComplete,true);assert.deepEqual(Object.keys(page.items[0]).sort(),['tripId','title','headVersion','confirmationState','content'].sort());const clean=JSON.parse(await db(`select export_private.trip_content_v1('{"days":[{"id":"DAY_A","date":"2026-10-03","privateFuture":"excluded","items":[{"id":"ITEM_A","title":"Own text","photoFuture":"excluded"}]}]}'::jsonb);`));assert.deepEqual(Object.keys(clean.days[0]).sort(),['id','date','items'].sort());assert.deepEqual(Object.keys(clean.days[0].items[0]).sort(),['id','dayId','title'].sort());
 await deny(f.a,'claim',f.input,'FORBIDDEN');await deny(null,'read',{requestId:f.a.request},'FORBIDDEN');await deny(null,'claim',{...f.input,expectedKeyId:'wrong'},'INVALID_INPUT');assert.equal(await db(`select status||':'||execution_state from public.privacy_requests where id='${f.a.request}';`),'requested:not_started');
});
run('atomic protected artifact ready_partial, exact lost ACK recovery and decrypt before one-use consume',async()=>{
 const f=await ready();assert.equal((await call(null,'commit',f.commit)).state,'ready_partial');const rec=await call(null,'execution_receipt',{...binding(f),expectedArtifactDigest:f.art.wire.plaintextDigest});assert.equal(rec.outcome,'terminal');assert.equal((await call(null,'execution_receipt',{...binding(f),expectedArtifactDigest:'0'.repeat(64)})).outcome,'unknown');
 const hash=sha(randomBytes(32)),op=uuid(),ticket=await call(f.a,'ticket',{requestId:f.a.request,operationId:op,tokenHash:hash,ticketTtlMs:300000});assert.equal(ticket.kind,'privacy_export_ticket/1');const download=await call(f.a,'download_prepare',{requestId:f.a.request,operationId:op,tokenHash:hash});const dec=createDecipheriv('aes-256-gcm',f.art.key,Buffer.from(download.artifact.nonce,'base64url'));dec.setAAD(Buffer.from(canonical(['privacy-core-export/1',f.a.request,f.a.owner,download.generation])));dec.setAuthTag(Buffer.from(download.artifact.tag,'base64url'));const plain=Buffer.concat([dec.update(Buffer.from(download.artifact.ciphertext,'base64url')),dec.final()]);assert.equal(sha(plain),download.artifactDigest);assert.equal(plain.length,f.art.plain.length);
 const consume={requestId:f.a.request,operationId:op,tokenHash:hash,artifactDigest:download.artifactDigest,generation:download.generation};assert.equal((await call(f.a,'download_consume',consume)).kind,'privacy_export_download_consumed/1');assert.equal((await call(f.a,'download_consume',consume)).kind,'unavailable');assert.equal((await call(f.a,'download_prepare',{requestId:f.a.request,operationId:op,tokenHash:hash})).kind,'unavailable');
});
run('expired lease CAS reclaims one generation, blocks old execution and late artifact faults roll back all writes',async()=>{
 const f=await fixture(),old=binding(f);await db(`update export_private.core_jobs_v1 set lease_expires_at=clock_timestamp()-interval '1 second' where request_id='${f.a.request}';`);assert.equal((await call(null,'validate',old)).current,false);const newLease=await call(null,'claim',{...f.input,operationId:uuid()});assert.equal(newLease.generation,2);f.lease=newLease;const art=artifact(f),commit={...binding(f),artifact:art.wire,modules:modules(),coverage:'partial'};
 assert.equal((await call(null,'commit',{...commit,...old})).kind,'unavailable');
 await db(`create function export_private.fixture_job_fault() returns trigger language plpgsql as $$begin if new.request_id='${f.a.request}' and new.state in ('ready_partial','ready_complete') then raise exception 'FIXTURE_ARTIFACT_RECEIPT_FAILURE';end if;return new;end $$;create trigger fixture_job_fault before update on export_private.core_jobs_v1 for each row execute function export_private.fixture_job_fault();`);
 await deny(null,'commit',commit,'FIXTURE_ARTIFACT_RECEIPT_FAILURE');assert.equal(await db(`select count(*) from export_private.core_artifacts_v1 where request_id='${f.a.request}';`),'0');assert.equal((await call(null,'validate',binding(f))).current,true);await db('drop trigger fixture_job_fault on export_private.core_jobs_v1;drop function export_private.fixture_job_fault();');assert.equal((await call(null,'commit',commit)).state,'ready_partial');assert.equal((await call(null,'execution_receipt',{...old,expectedArtifactDigest:art.wire.plaintextDigest})).outcome,'unknown');
});
run('tickets are request/session/epoch/digest bound; new issue invalidates ACK-lost predecessor without extending artifact TTL',async()=>{
 const f=await ready(),b=await owner(),op=uuid(),hash=sha(randomBytes(32));const input={requestId:f.a.request,operationId:op,tokenHash:hash,ticketTtlMs:300000};await call(f.a,'ticket',input);await deny(b,'read',{requestId:f.a.request},'FORBIDDEN');await deny(b,'ticket',input,'FORBIDDEN');await deny(f.a,'ticket',{...input,tokenHash:'0'.repeat(64)},'EXPORT_CONFLICT');const before=f.receipt.artifactExpiresAt;
 const two={...input,operationId:uuid(),tokenHash:sha(randomBytes(32))};await call(f.a,'ticket',two);assert.equal((await call(f.a,'download_prepare',{requestId:f.a.request,operationId:op,tokenHash:hash})).kind,'unavailable');assert.equal((await call(f.a,'read',{requestId:f.a.request})).artifactExpiresAt,before);
 const session=uuid();await db(`insert into auth.sessions(id,user_id) values('${session}','${f.a.owner}');update identity_private.mobile_accounts set session_id='${session}',epoch=2 where owner_id='${f.a.owner}';delete from auth.sessions where id='${f.a.session}';`);f.a.session=session;f.a.epoch=2;
 assert.equal((await call(null,'execution_receipt',{...binding(f),expectedArtifactDigest:f.art.wire.plaintextDigest})).outcome,'unknown');assert.equal((await call(f.a,'download_prepare',{requestId:f.a.request,operationId:two.operationId,tokenHash:two.tokenHash})).kind,'unavailable');const fresh={...input,operationId:uuid(),tokenHash:sha(randomBytes(32))};assert.equal((await call(f.a,'ticket',fresh)).kind,'privacy_export_ticket/1');
 await db(`update auth.sessions set created_at=clock_timestamp()-interval '6 minutes' where id='${session}';`);await deny(f.a,'ticket',{...fresh,operationId:uuid()},'REAUTHENTICATION_REQUIRED');
});
run('size/module/expiry caps reject mismatches; TTL purge and account cascade erase only generated data; ACL remains closed',async()=>{
 const f=await fixture(),art=artifact(f);await deny(null,'commit',{...binding(f),artifact:{...art.wire,plaintextBytes:8388609},modules:modules(),coverage:'partial'},'INVALID_OUTPUT');await deny(null,'commit',{...binding(f),artifact:art.wire,modules:[],coverage:'complete'},'INVALID_OUTPUT');await deny(null,'claim',{...f.input,operationId:uuid(),maxRunMs:90001},'INVALID_INPUT');
 assert.equal((await call(null,'fail',{...binding(f),reason:'INVALID_OUTPUT'})).state,'failed');assert.equal((await call(null,'execution_receipt',{...binding(f),expectedArtifactDigest:'0'.repeat(64)})).outcome,'terminal');
 const r=await ready();await call(r.a,'ticket',{requestId:r.a.request,operationId:uuid(),tokenHash:sha(randomBytes(32)),ticketTtlMs:300000});await db(`update export_private.core_jobs_v1 set expires_at=clock_timestamp()-interval '1 second' where request_id='${r.a.request}';`);assert.equal((await call(r.a,'read',{requestId:r.a.request})).state,'expired');const purged=await call(null,'purge',{operationId:uuid(),limit:100});assert.equal(purged.removedArtifacts,1);assert.equal(await db(`select count(*) from export_private.core_tickets_v1 where request_id='${r.a.request}';`),'0');assert.equal(await db(`select count(*) from public.trips where owner_id='${r.a.owner}';`),'1');
 const gone=await ready();await db(`delete from auth.users where id='${gone.a.owner}';`);assert.equal(await db(`select count(*) from export_private.core_jobs_v1 where request_id='${gone.a.request}';`),'0');assert.equal(await db(`select count(*) from export_private.core_artifacts_v1 where request_id='${gone.a.request}';`),'0');
 assert.equal(await db("select has_function_privilege('authenticated','public.privacy_core_export_v1(text,jsonb)','EXECUTE') or has_function_privilege('service_role','public.privacy_core_export_v1(text,jsonb)','EXECUTE') or has_table_privilege('authenticated','export_private.core_artifacts_v1','SELECT');"),'f');
});

run('partial SOURCE_UNAVAILABLE after collected pages commits retained data; zero-page partial and nonempty failed refuse',async()=>{
 const f=await fixture(),data={conversations:{conversations:[{conversationId:uuid()}]}},receipts=modules();receipts[1]={module:'conversations',status:'partial',reason:'SOURCE_UNAVAILABLE',pages:1,rows:1,digest:sha(canonical(data.conversations))};const art=artifact(f,receipts,data),input={...binding(f),artifact:art.wire,modules:receipts,coverage:'partial'};
 const zero=structuredClone(receipts);zero[1].pages=0;zero[1].rows=0;await deny(null,'commit',{...input,modules:zero},'INVALID_OUTPUT');
 const failed=structuredClone(receipts);failed[1].status='failed';await deny(null,'commit',{...input,modules:failed},'INVALID_OUTPUT');
 const committed=await call(null,'commit',input);assert.equal(committed.state,'ready_partial');assert.deepEqual(committed.modules[1],receipts[1]);assert.equal(committed.allUserDataCompleted,false);assert.equal((await call(null,'execution_receipt',{...binding(f),expectedArtifactDigest:art.wire.plaintextDigest})).outcome,'terminal');
 assert.equal(await db(`select count(*) from export_private.core_artifacts_v1 where request_id='${f.a.request}';`),'1');
});
