import {runCoreExportJob} from '../../../lib/server/privacy/export-worker.ts';
import {entitlementExportHandler} from '../../../lib/server/privacy/export-entitlements.ts';
// Actual network-none SQL under administrator synthetic claims; no signed Auth/role activation.
import test,{before,after} from 'node:test';import assert from 'node:assert/strict';
import {randomUUID as uuid,randomBytes,createHash,createCipheriv,createDecipheriv} from 'node:crypto';import {readFileSync,readdirSync} from 'node:fs';
import {command,sql} from '../cost/fixtures/postgres-rpc.mjs';
const enabled=process.env.VP_TURN_DB_TEST==='1',container='vpj36-entitlements-'+uuid().slice(0,8);let created=false;
const db=async q=>{const r=await sql(container,q);assert.equal(r.code,0,r.stderr);return r.stdout.trim();};
const lit=v=>"'"+JSON.stringify(v).replaceAll("'","''")+"'::jsonb";
const claims=a=>`set request.jwt.claim.role='authenticated';set request.jwt.claim.sub='${a.owner}';set request.jwt.claims='${JSON.stringify({role:'authenticated',is_anonymous:false,session_id:a.session})}';`;
const query=(a,action,input)=> (a?claims(a):"set request.jwt.claim.role='service_role';set request.jwt.claims='{\"role\":\"service_role\"}';")+`select public.privacy_core_export_v1('${action}',${lit(input)});`;
const call=async(a,action,input)=>JSON.parse(await db(query(a,action,input)));
const deny=async(a,action,input,code)=>{const r=await sql(container,query(a,action,input));assert.notEqual(r.code,0);assert.match(r.stderr,new RegExp(code));};
const sha=b=>createHash('sha256').update(b).digest('hex');
const canonical=v=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v!==null&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
const names=['trip','conversations','results','profile','memory','turn','user_artifact','brief','entitlements'];
const modules=()=>names.map(module=>({module,status:'unavailable',reason:'HANDLER_MISSING',pages:0,rows:0,digest:null}));
async function owner(){const a={owner:uuid(),session:uuid(),request:uuid(),epoch:1};await db(`insert into auth.users(id) values('${a.owner}');insert into auth.sessions(id,user_id) values('${a.session}','${a.owner}');insert into identity_private.mobile_accounts(owner_id,epoch,session_id) values('${a.owner}',1,'${a.session}');insert into identity_private.mobile_attempts(owner_id,attempt_id,session_id,epoch) values('${a.owner}','${uuid()}','${a.session}',1);${claims(a)}insert into public.trips(id,owner_id,title) values('${uuid()}','${a.owner}','Own Trip plaintext');`);return a;}
async function fixture(){const a=await owner();const r=await call(a,'request',{requestId:a.request,confirmed:true});assert.equal(r.state,'queued');const input={requestId:a.request,operationId:uuid(),maxRunMs:90000,expectedEnvironment:'local',expectedKeyId:'synthetic-key'};const lease=await call(null,'claim',input);assert.equal(lease.kind,'privacy_export_lease/1');return {a,lease,input};}
function artifact(f,receipts=modules(),data={}){const key=randomBytes(32),nonce=randomBytes(12),plain=Buffer.from(canonical({schemaVersion:'privacy-core-export/1',requestId:f.a.request,coverage:'partial',allUserDataCompleted:false,data,modules:receipts}));const aad=Buffer.from(canonical(['privacy-core-export/1',f.a.request,f.a.owner,f.lease.generation]));const cipher=createCipheriv('aes-256-gcm',key,nonce);cipher.setAAD(aad);const ciphertext=Buffer.concat([cipher.update(plain),cipher.final()]);return {key,plain,wire:{schemaVersion:'privacy-export-artifact/1',keyId:'synthetic-key',nonce:nonce.toString('base64url'),tag:cipher.getAuthTag().toString('base64url'),ciphertext:ciphertext.toString('base64url'),plaintextDigest:sha(plain),plaintextBytes:plain.length,expiresAt:new Date(Date.now()+300000).toISOString()}};}
const binding=f=>({requestId:f.a.request,leaseId:f.lease.leaseId,generation:f.lease.generation});
async function ready(){const f=await fixture(),art=artifact(f);const p={...binding(f),artifact:art.wire,modules:modules(),coverage:'partial'};const r=await call(null,'commit',p);assert.equal(r.state,'ready_partial');return {...f,art,commit:p,receipt:r};}
before(async()=>{if(!enabled)return;const r=await command('docker',['run','--pull=never','--rm','-d','--network','none','--name',container,'--user','postgres','--entrypoint','/bin/sh','public.ecr.aws/supabase/postgres:17.6.1.159','-c','umask 077;mkdir /tmp/vpj59-socket;initdb -D /tmp/vpj59-db -A trust --no-locale -E UTF8 >/tmp/init.log 2>&1 && exec postgres -D /tmp/vpj59-db -c listen_addresses= -c unix_socket_directories=/tmp/vpj59-socket -c unix_socket_permissions=0700']);assert.equal(r.code,0,r.stderr);created=true;for(let n=0;n<100;n++){if((await command('docker',['exec',container,'pg_isready','-h','/tmp/vpj59-socket','-U','postgres'])).code===0)break;await new Promise(r=>setTimeout(r,100));}
 await db(readFileSync('tests/integration/turn/fixtures/durable-work-schema.sql','utf8'));await db("create function auth.role() returns text language sql as $$select nullif(current_setting('request.jwt.claim.role',true),'')$$;create schema extensions;create extension pgcrypto with schema extensions;");for(const f of readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')).sort())await db('begin;'+readFileSync('supabase/migrations/'+f,'utf8')+'commit;');
 await db(`insert into export_private.core_policies_v1(id,revision,enabled,environment,key_id,max_run_ms,artifact_ttl_ms,ticket_ttl_ms,max_pages,page_size,max_bytes,valid_until) values('${uuid()}',1,true,'local','synthetic-key',90000,600000,300000,1000,100,8388608,clock_timestamp()+interval '1 day');`);
});
after(async()=>{if(created)assert.equal((await command('docker',['rm','-f',container])).code,0);});
const run=(name,fn)=>test(name,{skip:!enabled,timeout:120000},fn);

async function grants(a){for(const tx of ['tx_A','tx_B']){const value={ownerId:a.owner,appAccountToken:a.owner,environment:'Sandbox',transactionId:tx+'_'+a.owner,productId:'synthetic.journey.pass',purchaseAt:new Date().toISOString(),catalogVersion:1,policyVersion:'synthetic-v1',capacitySnapshot:{source:'synthetic only',taskLimit:3}};await db(`set request.jwt.claim.role='service_role';select public.storekit_apply_verified_v1('${JSON.stringify(value)}'::jsonb);`);}}
const page=(f,cursor=null,limit=1)=>call(null,'entitlement_page',{...binding(f),cursor,limit});
run('real StoreKit producer→bounded entitlement handler→protected artifact, no owner service leak or extra columns',async()=>{
 const f=await fixture();await grants(f.a);const handler=entitlementExportHandler(f.lease,async(action,input)=>call(null,action,input)),data={grants:[]};let cursor=null;do{const p=await handler.page('grants',cursor,1,AbortSignal.timeout(30000));data.grants.push(...p.items);cursor=p.nextCursor;}while(cursor);assert.equal(data.grants.length,2);assert.equal(Object.keys(data.grants[0]).length,11);assert.equal(JSON.stringify(data).includes('appAccountToken'),false);const counts=handler.progress();assert.deepEqual(counts,{pages:2,rows:2,terminal:true});
 const receipts=modules();receipts[8]={module:'entitlements',status:'partial',reason:'LIVE_TRAVERSAL',pages:counts.pages,rows:counts.rows,digest:sha(canonical(data))};const art=artifact(f,receipts,{entitlements:data});const committed=await call(null,'commit',{...binding(f),artifact:art.wire,modules:receipts,coverage:'partial'});assert.equal(committed.state,'ready_partial');assert.deepEqual(committed.modules[8],receipts[8]);assert.equal(committed.modules[7].status,'unavailable');assert.equal(committed.allUserDataCompleted,false);
});
run('page chain/source revocation fences late commit and ready tickets; financial records retained and old ready not retrofitted',async()=>{
 const f=await fixture();await grants(f.a);const p=await page(f);assert.equal(p.hasMore,true);assert.deepEqual(await page(f),p);await deny(null,'entitlement_page',{...binding(f),cursor:null,limit:2},'EXPORT_SOURCE_CURSOR_CONFLICT');
 await db(`update public.storekit_grants set state='revoked',revoked_at=now() where owner_id='${f.a.owner}';`);assert.equal((await call(null,'validate',binding(f))).current,false);assert.equal((await page(f,p.nextCursor)).kind,'unavailable');assert.equal(await db(`select count(*) from public.storekit_grants where owner_id='${f.a.owner}';`),'2');
 const old=await ready();assert.equal(await db(`select entitlement_source_revision is null from export_private.core_jobs_v1 where request_id='${old.a.request}';`),'t');assert.equal((await page(old)).kind,'unavailable');assert.equal(await db(`select entitlement_source_revision is null from export_private.core_jobs_v1 where request_id='${old.a.request}';`),'t');
 const live=await fixture();await grants(live.a);const first=await page(live),last=await page(live,first.nextCursor);const data={grants:[...first.items,...last.items]},receipts=modules();receipts[8]={module:'entitlements',status:'partial',reason:'LIVE_TRAVERSAL',pages:2,rows:2,digest:sha(canonical(data))};const art=artifact(live,receipts,{entitlements:data});await call(null,'commit',{...binding(live),artifact:art.wire,modules:receipts,coverage:'partial'});const input={requestId:live.a.request,operationId:uuid(),tokenHash:sha(randomBytes(32)),ticketTtlMs:300000};await call(live.a,'ticket',input);await db(`update public.storekit_grants set state='revoked',revoked_at=now() where owner_id='${live.a.owner}';`);assert.equal((await call(live.a,'download_prepare',{requestId:live.a.request,operationId:input.operationId,tokenHash:input.tokenHash})).kind,'unavailable');assert.equal((await call(live.a,'download_consume',{requestId:live.a.request,operationId:input.operationId,tokenHash:input.tokenHash,artifactDigest:art.wire.plaintextDigest,generation:live.lease.generation})).kind,'unavailable');
 assert.equal(await db("select has_function_privilege('service_role','export_private.entitlement_page_v1(jsonb)','EXECUTE') or has_function_privilege('authenticated','public.privacy_core_export_v1(text,jsonb)','EXECUTE');"),'f');
});

run('real production export worker registers entitlements through leased SQL, keeps Brief unavailable and commits actual coverage',async()=>{
 const a=await owner();await grants(a);await call(a,'request',{requestId:a.request,confirmed:true});const policy={enabled:true,environment:'local',maxRunMs:60000,artifactTtlMs:300000,downloadTicketTtlMs:300000,maxPages:1000,pageSize:100,maxBytes:8388608},key={keyId:'synthetic-key',key:randomBytes(32)};
 const domain=async(action,input)=>call(null,action,input);const rpc=async(name,input)=>JSON.parse(await db("set request.jwt.claim.role='service_role';set request.jwt.claims='{\"role\":\"service_role\"}';select public."+name+'('+Object.entries(input).map(([k,v])=>k+'=>'+(v===null?'null':typeof v==='number'?String(v):"'"+String(v).replaceAll("'","''")+"'")).join(',')+');'));
 const receipt=await runCoreExportJob(a.request,uuid(),policy,key,domain,rpc,AbortSignal.timeout(90000));assert.equal(receipt.state,'ready_partial',JSON.stringify(receipt));const ent=receipt.modules.find(m=>m.module==='entitlements');assert.equal(ent.status,'partial');assert.equal(ent.reason,'LIVE_TRAVERSAL');assert.equal(ent.pages,1);assert.equal(ent.rows,2);assert.equal(receipt.modules.find(m=>m.module==='brief').reason,'HANDLER_MISSING');assert.equal(receipt.allUserDataCompleted,false);
});
