import {createServer} from 'node:http';import {createLinkedTripDeletionWorker} from '../../../lib/server/privacy/linked-trip/server-worker.ts';
import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import {randomUUID as uuid} from 'node:crypto';import {readFileSync,readdirSync} from 'node:fs';import {command,sql} from '../cost/fixtures/postgres-rpc.mjs';
const enabled=process.env.VP_TURN_DB_TEST==='1',container='vpj36-linked-'+uuid().slice(0,8);let created=false;
const db=async q=>{const r=await sql(container,q);assert.equal(r.code,0,r.stderr);return r.stdout.trim();};
const lit=v=>"'"+JSON.stringify(v).replaceAll("'","''")+"'::jsonb";
const claims=a=>`set request.jwt.claim.role='authenticated';set request.jwt.claim.sub='${a.owner}';set request.jwt.claims='${JSON.stringify({role:'authenticated',is_anonymous:false,session_id:a.session})}';`;
const query=(a,action,input)=>(a?claims(a):"set request.jwt.claim.role='service_role';set request.jwt.claims='{\"role\":\"service_role\"}';")+`select public.privacy_linked_trip_delete_v1('${action}',${lit(input)});`;
const call=async(a,action,input)=>JSON.parse(await db(query(a,action,input)));
const deny=async(a,action,input,code)=>{const r=await sql(container,query(a,action,input));assert.notEqual(r.code,0);assert.match(r.stderr,new RegExp(code));};
async function fixture(){const a={owner:uuid(),session:uuid(),trip:uuid(),otherTrip:uuid(),thread:uuid(),turn:uuid(),otherThread:uuid()};await db(`insert into auth.users(id) values('${a.owner}');insert into auth.sessions(id,user_id) values('${a.session}','${a.owner}');insert into identity_private.mobile_accounts(owner_id,epoch,session_id) values('${a.owner}',1,'${a.session}');insert into identity_private.mobile_attempts values('${a.owner}','${uuid()}','${a.session}',1);${claims(a)}insert into public.trips(id,owner_id,title) values('${a.trip}','${a.owner}','Chosen Trip'),('${a.otherTrip}','${a.owner}','Outside Trip');insert into public.chat_threads(id,owner_id,trip_id,status) values('${a.thread}','${a.owner}','${a.trip}','active'),('${a.otherThread}','${a.owner}','${a.otherTrip}','active');insert into public.turns(id,owner_id,thread_id,trip_id,status) values('${a.turn}','${a.owner}','${a.thread}','${a.trip}','completed');`);return a;}
const preview=a=>call(a,'preview',{tripId:a.trip,expectedVersion:0});
const confirm=(a,p,request=uuid())=>call(a,'confirm',{requestId:request,planId:p.planId,scopeDigest:p.scopeDigest,expectedVersion:p.expectedVersion,confirmed:true,selection:p.selection});
before(async()=>{if(!enabled)return;const r=await command('docker',['run','--pull=never','--rm','-d','--network','none','--name',container,'--user','postgres','--entrypoint','/bin/sh','public.ecr.aws/supabase/postgres:17.6.1.159','-c','umask 077;mkdir /tmp/vpj59-socket;initdb -D /tmp/vpj59-db -A trust --no-locale -E UTF8 >/tmp/init.log 2>&1 && exec postgres -D /tmp/vpj59-db -c listen_addresses= -c unix_socket_directories=/tmp/vpj59-socket -c unix_socket_permissions=0700']);assert.equal(r.code,0,r.stderr);created=true;for(let n=0;n<100;n++){if((await command('docker',['exec',container,'pg_isready','-h','/tmp/vpj59-socket','-U','postgres'])).code===0)break;await new Promise(r=>setTimeout(r,100));}
 await db(readFileSync('tests/integration/turn/fixtures/durable-work-schema.sql','utf8'));await db("create function auth.role() returns text language sql as $$select nullif(current_setting('request.jwt.claim.role',true),'')$$;create schema extensions;create extension pgcrypto with schema extensions;");for(const f of readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')).sort())await db('begin;'+readFileSync('supabase/migrations/'+f,'utf8')+'commit;');await db('insert into privacy_private.linked_delete_worker_settings_v1(singleton,enabled,max_lease_ms) values(true,true,30000);');});
after(async()=>{if(created)assert.equal((await command('docker',['rm','-f',container])).code,0);});const run=(name,fn)=>test(name,{skip:!enabled,timeout:120000},fn);
run('exact server plan and explicit scoped confirm queue then erase linked Trip with same receipt',async()=>{const a=await fixture(),p=await preview(a);assert.deepEqual(p.conflicts,[]);assert.deepEqual(p.selection.threadIds,[a.thread]);assert.deepEqual(p.selection.turnIds,[a.turn]);const queued=await confirm(a,p);assert.equal(queued.state,'queued');assert.equal(await db(`set request.jwt.claim.role='service_role';select public.next_trip_deletion_v1() is null;`),'t');const lease=await call(null,'claim',{requestId:queued.requestId,operationId:uuid()});assert.equal(lease.kind,'leased');const complete=await call(null,'execute',{requestId:queued.requestId,leaseId:lease.leaseId});assert.equal(complete.state,'completed');assert.deepEqual(await call(null,'execute',{requestId:queued.requestId,leaseId:lease.leaseId}),complete);assert.equal(await db(`select count(*) from public.trips where id='${a.otherTrip}';`),'1');assert.equal(await db(`select count(*) from public.chat_threads where id='${a.otherThread}';`),'1');assert.equal(await db(`select count(*) from public.turns where id='${a.turn}';`),'0');assert.equal(complete.allUserDataCompleted,false);});
run('selected retained Task/capacity identities keep quota but private input/output are truly erased and old readers unavailable',async()=>{
 const a=await fixture(),task=uuid(),policy=uuid(),consent=uuid(),scope=uuid(),attempt=uuid();await db(`update public.chat_threads set trip_id=null where id='${a.thread}';insert into turn_private.text_policies(id,provider,recipient,endpoint,source_region,processing_region,storage_region,terms_version,notice_version,notice_hash,notice_zh,notice_en,retention,effective_at,expires_at,terms_recheck_at) values('${policy}','qwen','fixture','https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions','local','local','local','test','test','${'a'.repeat(64)}','合成','Synthetic','retain_after_hide_v1',now()-interval '1 hour',now()+interval '1 day',now()+interval '1 day');
 begin;insert into turn_private.service_tasks(id,owner_id,thread_id,goal_turn_id,last_turn_id,policy_id,consent_id,scope_version,goal_digest) values('${task}','${a.owner}','${a.thread}','${a.turn}','${a.turn}','${policy}','${consent}',1,'${'b'.repeat(64)}');insert into turn_private.service_task_turns(turn_id,task_id,owner_id,relationship,idempotency_key,request_digest) values('${a.turn}','${task}','${a.owner}','new_goal','${uuid()}','${'c'.repeat(64)}');insert into turn_private.text_content(turn_id,owner_id,thread_id,policy_id,consent_id,locale,input_text,output_kind,output_text) values('${a.turn}','${a.owner}','${a.thread}','${policy}','${consent}','en','Original private chosen input','answered','Original private chosen output');commit;
 insert into turn_private.service_task_capacity(task_id,owner_id,policy_version,tier,admitted_at,state,settled_turn_id,settled_at) values('${task}','${a.owner}','service-task-development/1','free',now(),'settled','${a.turn}',now());
 insert into public.model_budget_scopes(id,owner_id,currency,limit_micros,task_limit_micros,task_attempt_limit,concurrency_limit,enabled,expires_at) values('${scope}','${a.owner}','CNY',10000,1000,3,3,true,now()+interval '1 day');insert into public.model_budget_provider_limits(scope_id,provider,model,price_version,limit_micros,attempt_limit_micros,enabled) values('${scope}','qwen','synthetic-model','synthetic-v1',10000,1000,true);insert into public.model_budget_attempts(scope_id,attempt_id,task_id,provider,model,price_version,reserved_micros,actual_micros,status) values('${scope}','${attempt}','${task}','qwen','synthetic-model','synthetic-v1',10,5,'settled');`);
 const p=await preview(a);assert.deepEqual(p.conflicts,[]);assert.deepEqual(p.selection.taskIds,[task]);const q=await confirm(a,p),l=await call(null,'claim',{requestId:q.requestId,operationId:uuid()});const r=await call(null,'execute',{requestId:q.requestId,leaseId:l.leaseId});assert.equal(r.state,'completed');assert.equal(r.erasedCounts.textBodies,1);
 assert.equal(await db(`select input_text='[deleted by scoped Trip request]' and output_text is null and output_kind is null and hidden_at is not null from turn_private.text_content where turn_id='${a.turn}';`),'t');assert.equal(await db(`select state from turn_private.service_task_capacity where task_id='${task}';`),'settled');assert.equal(await db(`select actual_micros from public.model_budget_attempts where attempt_id='${attempt}';`),'5');assert.equal(JSON.parse(await db(claims(a)+`select public.read_text_turn('${a.turn}');`)).kind,'unavailable');
});
run('shared and active scopes conflict, selection/date changes require preview, queue blocks new related writes',async()=>{
 const a=await fixture();await db(`insert into public.turns(id,owner_id,thread_id,trip_id,status) values('${uuid()}','${a.owner}','${a.thread}','${a.otherTrip}','completed');`);const shared=await preview(a);assert.ok(shared.conflicts.includes('SHARED_OR_FOREIGN_CHAT'));await deny(a,'confirm',{requestId:uuid(),planId:shared.planId,scopeDigest:shared.scopeDigest,expectedVersion:0,confirmed:true,selection:shared.selection},'SCOPE_CONFLICT');
 const b=await fixture(),p=await preview(b);await db(`insert into public.turns(id,owner_id,thread_id,trip_id,status) values('${uuid()}','${b.owner}','${b.thread}','${b.trip}','completed');`);await deny(b,'confirm',{requestId:uuid(),planId:p.planId,scopeDigest:p.scopeDigest,expectedVersion:0,confirmed:true,selection:p.selection},'SCOPE_CHANGED');
 const fresh=await preview(b);await deny(b,'confirm',{requestId:uuid(),planId:fresh.planId,scopeDigest:fresh.scopeDigest,expectedVersion:0,confirmed:true,selection:{...fresh.selection,turnIds:[]}},'SCOPE_NOT_COMPLETE');const queued=await confirm(b,fresh);
 const rejected=await sql(container,claims(b)+`insert into public.turns(id,owner_id,thread_id,trip_id,status) values('${uuid()}','${b.owner}','${b.thread}',null,'accepted');`);assert.notEqual(rejected.code,0);assert.match(rejected.stderr,/LINKED_TRIP_DELETION_PENDING/);
 const active=await fixture();await db(`update public.turns set status='accepted' where id='${active.turn}';`);assert.ok((await preview(active)).conflicts.includes('ACTIVE_WORK'));
 assert.equal(queued.state,'queued');
});
run('explicit export request selection invalidates whole owner-generated copies and blocks old/new collector until erase',async()=>{
 const a=await fixture(),request=uuid(),policy=uuid();await db(`${claims(a)}select public.request_privacy_action('${request}','export');insert into export_private.core_policies_v1(id,revision,enabled,environment,key_id,max_run_ms,artifact_ttl_ms,ticket_ttl_ms,max_pages,page_size,max_bytes,valid_until) values('${policy}',1,false,'local','fixture',90000,600000,300000,1000,100,8388608,now()+interval '1 day');insert into export_private.core_jobs_v1(request_id,owner_id,session_id,session_epoch,policy_id,policy_snapshot,state,generation,expires_at,artifact_digest,artifact_bytes,artifact_expires_at) values('${request}','${a.owner}','${a.session}',1,'${policy}','{}','ready_partial',1,now()+interval '1 hour','${'d'.repeat(64)}',1,now()+interval '1 hour');insert into export_private.core_artifacts_v1(request_id,owner_id,generation,lease_id,key_id,nonce,tag,ciphertext,plaintext_digest,plaintext_bytes,ciphertext_digest,aad,expires_at) values('${request}','${a.owner}',1,'${uuid()}','fixture',decode('${'01'.repeat(12)}','hex'),decode('${'02'.repeat(16)}','hex'),decode('03','hex'),'${'d'.repeat(64)}',1,'${'e'.repeat(64)}','fixture',now()+interval '1 hour');insert into export_private.core_tickets_v1(operation_id,request_id,owner_id,session_id,session_epoch,generation,artifact_digest,token_hash,expires_at) values('${uuid()}','${request}','${a.owner}','${a.session}',1,1,'${'d'.repeat(64)}','${'f'.repeat(64)}',now()+interval '5 minutes');`);
 const p=await preview(a);assert.deepEqual(p.selection.exportRequestIds,[request]);await deny(a,'confirm',{requestId:uuid(),planId:p.planId,scopeDigest:p.scopeDigest,expectedVersion:0,confirmed:true,selection:{...p.selection,exportRequestIds:[]}},'SCOPE_NOT_COMPLETE');const q=await confirm(a,p);assert.equal(await db(`select state from export_private.core_jobs_v1 where request_id='${request}';`),'expired');assert.equal(await db(`select count(*) from export_private.core_artifacts_v1 where request_id='${request}';`),'0');assert.equal(await db(`select count(*) from export_private.core_tickets_v1 where request_id='${request}';`),'0');
 const denied=await sql(container,`update export_private.core_jobs_v1 set state='running' where request_id='${request}';`);assert.notEqual(denied.code,0);assert.match(denied.stderr,/LINKED_TRIP_DELETION_PENDING/);const l=await call(null,'claim',{requestId:q.requestId,operationId:uuid()});const r=await call(null,'execute',{requestId:q.requestId,leaseId:l.leaseId});assert.equal(r.state,'completed');assert.equal(r.erasedCounts.exports,1);assert.equal(r.erasedCounts.tickets,1);assert.equal(await db(`select status||':'||execution_state from public.privacy_requests where id='${request}';`),'requested:not_started');
});

run('completed snapshots minimise deleted Trip text; bounded expiry purge preserves queued plans and account cascades new copies only',async()=>{
 const a=await fixture(),p=await preview(a),q=await confirm(a,p),l=await call(null,'claim',{requestId:q.requestId,operationId:uuid()});await call(null,'execute',{requestId:q.requestId,leaseId:l.leaseId});assert.equal(await db(`select graph='{}'::jsonb from privacy_private.linked_delete_plans_v1 where id='${p.planId}';`),'t');assert.equal(await db(`select expected_graph='{}'::jsonb and execution_xid is null and execution_digest is null from privacy_private.linked_delete_jobs_v1 where request_id='${q.requestId}';`),'t');
 const b=await fixture(),expired=await preview(b);await db(`update privacy_private.linked_delete_plans_v1 set expires_at=now()-interval '1 second' where id='${expired.planId}';`);assert.equal((await call(null,'purge',{operationId:uuid(),limit:100})).removedPlans,1);assert.equal(await db(`select count(*) from privacy_private.linked_delete_plans_v1 where id='${expired.planId}';`),'0');
 const waiting=await preview(b),queued=await confirm(b,waiting);await db(`update privacy_private.linked_delete_plans_v1 set expires_at=now()-interval '1 second' where id='${waiting.planId}';`);assert.equal((await call(null,'purge',{operationId:uuid(),limit:100})).removedPlans,0);assert.equal(await db(`select count(*) from privacy_private.linked_delete_jobs_v1 where request_id='${queued.requestId}';`),'1');
 await db(`delete from auth.users where id='${b.owner}';`);assert.equal(await db(`select count(*) from privacy_private.linked_delete_plans_v1 where owner_id='${b.owner}';`),'0');assert.equal(await db(`select count(*) from privacy_private.linked_delete_jobs_v1 where owner_id='${b.owner}';`),'0');assert.equal(await db(`select count(*) from privacy_private.linked_delete_fences_v1 where owner_id='${b.owner}';`),'0');assert.equal(await db(`select count(*) from privacy_private.trip_deletions where request_id='${queued.requestId}';`),'1');
});

run('actual server consumer loopback SQL executes one scoped erase after lost ACK; default disabled zero RPC and actual ACL denied',async()=>{
 const a=await fixture(),p=await preview(a),q=await confirm(a,p);let calls=0,executes=0,firstAckLost=true;const inputs=[];
 const server=createServer(async(req,res)=>{try{assert.equal(req.url,'/rest/v1/rpc/privacy_linked_trip_delete_v1');assert.equal(req.method,'POST');let raw='';for await(const c of req)raw+=c;const body=JSON.parse(raw);inputs.push(body);calls++;const result=await call(null,body.p_action,body.p_input);if(body.p_action==='execute'){executes++;if(firstAckLost){firstAckLost=false;res.writeHead(503,{'Content-Type':'application/json'});res.end('{"error":"synthetic_ack_loss"}');return;}}res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify(result));}catch{res.writeHead(503,{'Content-Type':'application/json'});res.end('{"error":"fixture_failure"}');}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;try{
 const credential=()=> 'local-fixture-credential';const disabled=createLinkedTripDeletionWorker({environment:'local',databaseUrl:'http://127.0.0.1:'+port},{credential:()=>{assert.fail('disabled credential read');}});assert.equal(await disabled(q.requestId,AbortSignal.timeout(30000)),'disabled');assert.equal(calls,0);
 const worker=createLinkedTripDeletionWorker({enabled:true,environment:'local',databaseUrl:'http://127.0.0.1:'+port},{credential});assert.equal(await worker(q.requestId,AbortSignal.timeout(30000)),'completed');assert.equal(calls,3);assert.equal(executes,2);assert.deepEqual(inputs[1],inputs[2]);const receipt=await call(a,'read',{requestId:q.requestId});assert.equal(receipt.erasedCounts.turns,1);assert.equal(receipt.erasedCounts.threads,1);assert.equal(await db(`select count(*) from public.trips where id='${a.otherTrip}';`),'1');
 assert.equal(await db("select has_function_privilege('authenticated','public.privacy_linked_trip_delete_v1(text,jsonb)','EXECUTE') or has_function_privilege('service_role','public.privacy_linked_trip_delete_v1(text,jsonb)','EXECUTE');"),'f');
 }finally{server.closeAllConnections();await new Promise(r=>server.close(r));}
});
