// Actual network-none SQL under administrator synthetic claims; no signed Auth/role activation.
import test,{before,after} from 'node:test';import assert from 'node:assert/strict';
import {randomUUID as uuid,randomBytes,createHash,createCipheriv,createDecipheriv} from 'node:crypto';import {readFileSync,readdirSync} from 'node:fs';
import {command,sql} from '../cost/fixtures/postgres-rpc.mjs';
const enabled=process.env.VP_TURN_DB_TEST==='1',container='vpj36-memory-'+uuid().slice(0,8);let created=false;
const db=async q=>{const r=await sql(container,q);assert.equal(r.code,0,r.stderr);return r.stdout.trim();};
const lit=v=>"'"+JSON.stringify(v).replaceAll("'","''")+"'::jsonb";
const claims=a=>`set request.jwt.claim.role='authenticated';set request.jwt.claim.sub='${a.owner}';set request.jwt.claims='${JSON.stringify({role:'authenticated',is_anonymous:false,session_id:a.session})}';`;
const query=(a,action,input)=> (a?claims(a):"set request.jwt.claim.role='service_role';set request.jwt.claims='{\"role\":\"service_role\"}';")+`select public.privacy_core_export_v1('${action}',${lit(input)});`;
const call=async(a,action,input)=>JSON.parse(await db(query(a,action,input)));
const deny=async(a,action,input,code)=>{const r=await sql(container,query(a,action,input));assert.notEqual(r.code,0);assert.match(r.stderr,new RegExp(code));};
const sha=b=>createHash('sha256').update(b).digest('hex');
const canonical=v=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v!==null&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
const names=['trip','conversations','results','profile','memory','turn','user_artifact','brief','entitlements'];
const modules=()=>names.map(module=>({module,status:'unavailable',reason:'HANDLER_MISSING',pages:0,rows:0,digest:null}));
async function owner(){const a={owner:uuid(),session:uuid(),request:uuid(),epoch:1};await db(`insert into auth.users(id) values('${a.owner}');insert into auth.sessions(id,user_id) values('${a.session}','${a.owner}');insert into identity_private.mobile_accounts(owner_id,epoch,session_id) values('${a.owner}',1,'${a.session}');insert into identity_private.mobile_attempts(owner_id,attempt_id,session_id,epoch) values('${a.owner}','${uuid()}','${a.session}',1);${claims(a)}insert into public.trips(id,owner_id,title) values('${uuid()}','${a.owner}','Own Trip plaintext');`);return a;}
async function fixture(){const a=await owner();const r=await call(a,'request',{requestId:a.request,confirmed:true});assert.equal(r.state,'queued');const input={requestId:a.request,operationId:uuid(),maxRunMs:90000,expectedEnvironment:'local',expectedKeyId:'synthetic-key'};const lease=await call(null,'claim',input);assert.equal(lease.kind,'privacy_export_lease/1');return {a,lease,input};}
function artifact(f,receipts=modules(),data={}){const key=randomBytes(32),nonce=randomBytes(12),plain=Buffer.from(canonical({schemaVersion:'privacy-core-export/1',requestId:f.a.request,coverage:'partial',allUserDataCompleted:false,data,modules:receipts}));const aad=Buffer.from(canonical(['privacy-core-export/1',f.a.request,f.a.owner,f.lease.generation]));const cipher=createCipheriv('aes-256-gcm',key,nonce);cipher.setAAD(aad);const ciphertext=Buffer.concat([cipher.update(plain),cipher.final()]);return {key,plain,wire:{schemaVersion:'privacy-export-artifact/1',keyId:'synthetic-key',nonce:nonce.toString('base64url'),tag:cipher.getAuthTag().toString('base64url'),ciphertext:ciphertext.toString('base64url'),plaintextDigest:sha(plain),plaintextBytes:plain.length,expiresAt:new Date(Date.now()+300000).toISOString()}};}
const binding=f=>({requestId:f.a.request,leaseId:f.lease.leaseId,generation:f.lease.generation});
async function ready(){const f=await fixture(),art=artifact(f);const p={...binding(f),artifact:art.wire,modules:modules(),coverage:'partial'};const r=await call(null,'commit',p);assert.equal(r.state,'ready_partial');return {...f,art,commit:p,receipt:r};}
before(async()=>{if(!enabled)return;const r=await command('docker',['run','--pull=never','--rm','-d','--network','none','--name',container,'--user','postgres','--entrypoint','/bin/sh','public.ecr.aws/supabase/postgres:17.6.1.159','-c','umask 077;mkdir /tmp/vpj59-socket;initdb -D /tmp/vpj59-db -A trust --no-locale -E UTF8 >/tmp/init.log 2>&1 && exec postgres -D /tmp/vpj59-db -c listen_addresses= -c unix_socket_directories=/tmp/vpj59-socket -c unix_socket_permissions=0700']);assert.equal(r.code,0,r.stderr);created=true;for(let n=0;n<100;n++){if((await command('docker',['exec',container,'pg_isready','-h','/tmp/vpj59-socket','-U','postgres'])).code===0)break;await new Promise(r=>setTimeout(r,100));}
 await db(readFileSync('tests/integration/turn/fixtures/durable-work-schema.sql','utf8'));await db("create function auth.role() returns text language sql as $$select nullif(current_setting('request.jwt.claim.role',true),'')$$;create schema extensions;create extension pgcrypto with schema extensions;");for(const f of readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')).sort())await db('begin;'+readFileSync('supabase/migrations/'+f,'utf8')+'commit;');
 await db(`insert into export_private.core_policies_v1(id,revision,enabled,environment,key_id,max_run_ms,artifact_ttl_ms,ticket_ttl_ms,max_pages,page_size,max_bytes,valid_until) values('${uuid()}',1,true,'local','synthetic-key',90000,600000,300000,1000,100,8388608,clock_timestamp()+interval '1 day');`);
});
after(async()=>{if(created)assert.equal((await command('docker',['rm','-f',container])).code,0);});
const run=(name,fn)=>test(name,{skip:!enabled,timeout:120000},fn);

const native=async(a,input)=>JSON.parse(await db(claims(a)+`select public.native_memory_command_v1(${lit(input)});`));
async function memory(a){const c=await native(a,{action:'consentCreate',operationId:uuid()}),create={action:'create',operationId:uuid(),memoryId:uuid(),receiptId:uuid(),consentId:c.consentId,constraintKind:'preference',summary:'Current canonical Memory',saveLongTerm:true};await native(a,create);const update={action:'update',operationId:uuid(),memoryId:create.memoryId,sourceReceiptId:create.receiptId,expectedRevision:1,summary:'Updated canonical Memory',saveLongTerm:true};await native(a,update);return {create,update};}
const page=(f,section,cursor=null,limit=100)=>call(null,'memory_page',{...binding(f),section,cursor,limit});
const sections=['profiles','consents','receipts','consumerReferences','commands','undoMetadata'];
async function collect(f){let pages=0,rows=0,revision=null;const data={};for(const section of sections){data[section]=[];let cursor=null;do{const p=await page(f,section,cursor);assert.equal(p.schemaVersion,'memory-core-export/1');assert.equal(p.section,section);if(revision===null)revision=p.sourceRevision;assert.equal(p.sourceRevision,revision);data[section].push(...p.items);pages++;rows+=p.items.length;cursor=p.nextCursor;}while(cursor);}return {data,pages,rows,revision};}
run('all actual Memory sources export only current summary/minimal closed metadata and true reader counters',async()=>{
 const f=await fixture(),m=await memory(f.a),thread=uuid(),turn=uuid();await db(`${claims(f.a)}insert into public.chat_threads(id,owner_id,status) values('${thread}','${f.a.owner}','active');insert into public.turns(id,owner_id,thread_id,status) values('${turn}','${f.a.owner}','${thread}','completed');insert into public.memory_consumer_receipts(id,owner_id,memory_id,source_receipt_id,consumer_kind,turn_id,constraint_kind) values('${uuid()}','${f.a.owner}','${m.create.memoryId}','${m.create.receiptId}','turn','${turn}','preference');`);const c=await collect(f);assert.equal(c.data.profiles[0].summary,'Updated canonical Memory');assert.equal(c.data.commands.length,3);assert.equal(c.data.undoMetadata.length,1);const raw=JSON.stringify(c.data);for(const secret of ['prior_summary','input_digest','undoAvailable','Current canonical Memory'])assert.equal(raw.includes(secret),false);
 assert.equal(c.pages,6);assert.equal(c.data.consumerReferences.length,1);const before=await db(`select sum(pages) from export_private.memory_section_progress_v1 where request_id='${f.a.request}';`);assert.equal((await page(f,'consumerReferences')).sectionComplete,true);assert.equal(await db(`select sum(pages) from export_private.memory_section_progress_v1 where request_id='${f.a.request}';`),before);
 const receipts=modules();receipts[4]={module:'memory',status:'partial',reason:'LIVE_TRAVERSAL',pages:c.pages,rows:c.rows,digest:sha(canonical(c.data))};const art=artifact(f,receipts,{memory:c.data}),commit={...binding(f),artifact:art.wire,modules:receipts,coverage:'partial'};assert.equal((await call(null,'commit',commit)).state,'ready_partial');assert.equal((await page(f,'profiles')).kind,'unavailable');
 const bad=structuredClone(receipts);bad[4].pages++;await deny(null,'commit',{...commit,modules:bad},'INVALID_OUTPUT');
});
run('mutation between pages or after ready revokes every controlled disclosure path without rebasing old jobs',async()=>{
 const f=await fixture(),m=await memory(f.a);await page(f,'profiles');await native(f.a,{action:'revoke',operationId:uuid(),memoryId:m.create.memoryId,sourceReceiptId:m.create.receiptId,expectedRevision:2});assert.equal((await call(null,'validate',binding(f))).current,false);assert.equal((await page(f,'consents')).kind,'unavailable');
 const other=await fixture(),n=await memory(other.a),c=await collect(other),receipts=modules();receipts[4]={module:'memory',status:'partial',reason:'LIVE_TRAVERSAL',pages:c.pages,rows:c.rows,digest:sha(canonical(c.data))};const art=artifact(other,receipts,{memory:c.data});await call(null,'commit',{...binding(other),artifact:art.wire,modules:receipts,coverage:'partial'});
 const ticket={requestId:other.a.request,operationId:uuid(),tokenHash:sha(randomBytes(32)),ticketTtlMs:300000};await call(other.a,'ticket',ticket);await native(other.a,{action:'state',operationId:uuid(),memoryId:n.create.memoryId,sourceReceiptId:n.create.receiptId,expectedRevision:2,state:'deleted'});assert.equal((await call(other.a,'download_prepare',{requestId:other.a.request,operationId:ticket.operationId,tokenHash:ticket.tokenHash})).kind,'unavailable');assert.equal((await call(other.a,'download_consume',{requestId:other.a.request,operationId:ticket.operationId,tokenHash:ticket.tokenHash,artifactDigest:art.wire.plaintextDigest,generation:other.lease.generation})).kind,'unavailable');assert.equal((await call(other.a,'ticket',{...ticket,operationId:uuid()})).kind,'unavailable');
});
run('true ordered keyset progress forbids cursor skipping, limit drift or invented complete receipts; old jobs stay unfenced',async()=>{
 const f=await fixture();await memory(f.a);const first=await page(f,'commands',null,1);assert.equal(first.hasMore,true);assert.deepEqual(await page(f,'commands',null,1),first);await deny(null,'memory_page',{...binding(f),section:'commands',cursor:null,limit:2},'EXPORT_SOURCE_CURSOR_CONFLICT');await deny(null,'memory_page',{...binding(f),section:'commands',cursor:uuid(),limit:1},'INVALID_EXPORT_CURSOR');
 const receipts=modules();receipts[4]={module:'memory',status:'partial',reason:'LIVE_TRAVERSAL',pages:1,rows:1,digest:sha('fixture-only')};const art=artifact(f,receipts,{memory:{}});await deny(null,'commit',{...binding(f),artifact:art.wire,modules:receipts,coverage:'partial'},'INVALID_OUTPUT');
 const old=await ready();assert.equal(await db(`select memory_source_revision is null from export_private.core_jobs_v1 where request_id='${old.a.request}';`),'t');assert.equal((await page(old,'profiles')).kind,'unavailable');assert.equal(await db(`select memory_source_revision is null from export_private.core_jobs_v1 where request_id='${old.a.request}';`),'t');
});
run('two actual SQL sessions: raw service write NOWAIT fails without partial source change; native writer and account GC retain old boundaries',async()=>{
 const f=await fixture(),m=await memory(f.a);const before=await db(`select revision from export_private.memory_source_revisions_v1 where owner_id='${f.a.owner}';`);
 const holder=sql(container,`set application_name='memory_export_holder';begin;${query(null,'memory_page',{...binding(f),section:'profiles',cursor:null,limit:100})}select pg_sleep(1.0);commit;`);
 for(let n=0;n<80;n++){if(await db("select exists(select 1 from pg_stat_activity where application_name='memory_export_holder' and wait_event_type='Timeout');")==='t')break;if(n===79)assert.fail('bounded export holder not observed');await new Promise(r=>setTimeout(r,10));}
 const raw=await sql(container,`set role service_role;set request.jwt.claim.role='service_role';update public.memory_profiles set summary='UNCOMMITTED raw mutation' where id='${m.create.memoryId}';`);assert.notEqual(raw.code,0);assert.match(raw.stderr,/could not obtain lock/);const ended=await holder;assert.equal(ended.code,0,ended.stderr);assert.equal(await db(`select summary from public.memory_profiles where id='${m.create.memoryId}';`),'Updated canonical Memory');assert.equal(await db(`select revision from export_private.memory_source_revisions_v1 where owner_id='${f.a.owner}';`),before);
 await native(f.a,{action:'update',operationId:uuid(),memoryId:m.create.memoryId,sourceReceiptId:m.create.receiptId,expectedRevision:2,summary:'Valid new canonical Memory',saveLongTerm:true});assert.equal((await call(null,'validate',binding(f))).current,false);
 await db(`delete from auth.users where id='${f.a.owner}';`);assert.equal(await db(`select count(*) from export_private.memory_source_revisions_v1 where owner_id='${f.a.owner}';`),'0');assert.equal(await db(`select count(*) from export_private.memory_section_progress_v1 where request_id='${f.a.request}';`),'0');assert.equal(await db(`select count(*) from export_private.core_jobs_v1 where request_id='${f.a.request}';`),'0');
 assert.equal(await db("select has_function_privilege('service_role','export_private.core_memory_page_v1(jsonb)','EXECUTE') or has_function_privilege('authenticated','public.privacy_core_export_v1(text,jsonb)','EXECUTE');"),'f');
});
