import {createServer} from 'node:http';
import {createMemoryDeletionWorker} from '../../../lib/server/privacy/memory-delete/server-worker.ts';
import {memoryDeletionHTTP} from '../../../lib/server/privacy/memory-delete/http.ts';
import {memoryDeletePlan,memoryDeleteReceipt} from '../../../lib/server/privacy/memory-delete/contract.ts';
import {nativeFixture,subject,sessionId} from '../../contract/identity/native-fixture.ts';
// Actual network-none SQL under administrator synthetic claims; no signed Auth/role activation.
import test,{before,after} from 'node:test';import assert from 'node:assert/strict';
import {randomUUID as uuid,randomBytes,createHash,createCipheriv,createDecipheriv} from 'node:crypto';import {readFileSync,readdirSync} from 'node:fs';
import {command,sql} from '../cost/fixtures/postgres-rpc.mjs';
const enabled=process.env.VP_TURN_DB_TEST==='1',container='vpj36-memory-delete-'+uuid().slice(0,8);let created=false;
const db=async q=>{const r=await sql(container,q);assert.equal(r.code,0,r.stderr);return r.stdout.trim();};
const lit=v=>"'"+JSON.stringify(v).replaceAll("'","''")+"'::jsonb";
const claims=a=>`set request.jwt.claim.role='authenticated';set request.jwt.claim.sub='${a.owner}';set request.jwt.claims='${JSON.stringify({role:'authenticated',is_anonymous:false,session_id:a.session})}';`;
const query=(a,action,input)=> (a?claims(a):"set request.jwt.claim.role='service_role';set request.jwt.claims='{\"role\":\"service_role\"}';")+`select public.privacy_core_export_v1('${action}',${lit(input)});`;
const call=async(a,action,input)=>JSON.parse(await db(query(a,action,input)));
const deletion=async(a,action,input)=>JSON.parse(await db(query(a,action,input).replaceAll('privacy_core_export_v1','privacy_memory_delete_v1')));
const rejects=async(a,action,input,code)=>{const r=await sql(container,query(a,action,input).replaceAll('privacy_core_export_v1','privacy_memory_delete_v1'));assert.notEqual(r.code,0);assert.match(r.stderr,new RegExp(code));};
const deny=async(a,action,input,code)=>{const r=await sql(container,query(a,action,input));assert.notEqual(r.code,0);assert.match(r.stderr,new RegExp(code));};
const sha=b=>createHash('sha256').update(b).digest('hex');
const canonical=v=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v!==null&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
const names=['trip','conversations','results','profile','memory','turn','user_artifact','brief','entitlements'];
const modules=()=>names.map(module=>({module,status:'unavailable',reason:'HANDLER_MISSING',pages:0,rows:0,digest:null}));
async function owner(ids={}){const a={owner:uuid(),session:uuid(),request:uuid(),epoch:1,...ids};await db(`insert into auth.users(id) values('${a.owner}');insert into auth.sessions(id,user_id) values('${a.session}','${a.owner}');insert into identity_private.mobile_accounts(owner_id,epoch,session_id) values('${a.owner}',1,'${a.session}');insert into identity_private.mobile_attempts(owner_id,attempt_id,session_id,epoch) values('${a.owner}','${uuid()}','${a.session}',1);${claims(a)}insert into public.trips(id,owner_id,title) values('${uuid()}','${a.owner}','Own Trip plaintext');`);return a;}
async function fixture(){const a=await owner();const r=await call(a,'request',{requestId:a.request,confirmed:true});assert.equal(r.state,'queued');const input={requestId:a.request,operationId:uuid(),maxRunMs:90000,expectedEnvironment:'local',expectedKeyId:'synthetic-key'};const lease=await call(null,'claim',input);assert.equal(lease.kind,'privacy_export_lease/1');return {a,lease,input};}
function artifact(f,receipts=modules(),data={}){const key=randomBytes(32),nonce=randomBytes(12),plain=Buffer.from(canonical({schemaVersion:'privacy-core-export/1',requestId:f.a.request,coverage:'partial',allUserDataCompleted:false,data,modules:receipts}));const aad=Buffer.from(canonical(['privacy-core-export/1',f.a.request,f.a.owner,f.lease.generation]));const cipher=createCipheriv('aes-256-gcm',key,nonce);cipher.setAAD(aad);const ciphertext=Buffer.concat([cipher.update(plain),cipher.final()]);return {key,plain,wire:{schemaVersion:'privacy-export-artifact/1',keyId:'synthetic-key',nonce:nonce.toString('base64url'),tag:cipher.getAuthTag().toString('base64url'),ciphertext:ciphertext.toString('base64url'),plaintextDigest:sha(plain),plaintextBytes:plain.length,expiresAt:new Date(Date.now()+300000).toISOString()}};}
const binding=f=>({requestId:f.a.request,leaseId:f.lease.leaseId,generation:f.lease.generation});
async function ready(){const f=await fixture(),art=artifact(f);const p={...binding(f),artifact:art.wire,modules:modules(),coverage:'partial'};const r=await call(null,'commit',p);assert.equal(r.state,'ready_partial');return {...f,art,commit:p,receipt:r};}
before(async()=>{if(!enabled)return;const r=await command('docker',['run','--pull=never','--rm','-d','--network','none','--name',container,'--user','postgres','--entrypoint','/bin/sh','public.ecr.aws/supabase/postgres:17.6.1.159','-c','umask 077;mkdir /tmp/vpj59-socket;initdb -D /tmp/vpj59-db -A trust --no-locale -E UTF8 >/tmp/init.log 2>&1 && exec postgres -D /tmp/vpj59-db -c listen_addresses= -c unix_socket_directories=/tmp/vpj59-socket -c unix_socket_permissions=0700']);assert.equal(r.code,0,r.stderr);created=true;for(let n=0;n<100;n++){if((await command('docker',['exec',container,'pg_isready','-h','/tmp/vpj59-socket','-U','postgres'])).code===0)break;await new Promise(r=>setTimeout(r,100));}
 await db(readFileSync('tests/integration/turn/fixtures/durable-work-schema.sql','utf8'));await db("create function auth.role() returns text language sql as $$select nullif(current_setting('request.jwt.claim.role',true),'')$$;create schema extensions;create extension pgcrypto with schema extensions;");for(const f of readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')).sort())await db('begin;'+readFileSync('supabase/migrations/'+f,'utf8')+'commit;');
 await db(`insert into export_private.core_policies_v1(id,revision,enabled,environment,key_id,max_run_ms,artifact_ttl_ms,ticket_ttl_ms,max_pages,page_size,max_bytes,valid_until) values('${uuid()}',1,true,'local','synthetic-key',90000,600000,300000,1000,100,8388608,clock_timestamp()+interval '1 day');`);
});
after(async()=>{if(created)assert.equal((await command('docker',['rm','-f',container])).code,0);});
const run=(name,fn)=>test(name,{skip:!enabled,timeout:120000},fn);
const native=async(a,input)=>JSON.parse(await db(claims(a)+`select public.native_memory_command_v1(${lit(input)});`));
async function memory(a){const c=await native(a,{action:'consentCreate',operationId:uuid()}),create={action:'create',operationId:uuid(),memoryId:uuid(),receiptId:uuid(),consentId:c.consentId,constraintKind:'preference',summary:'Canonical private summary',saveLongTerm:true};await native(a,create);await native(a,{action:'update',operationId:uuid(),memoryId:create.memoryId,sourceReceiptId:create.receiptId,expectedRevision:1,summary:'Updated private summary',saveLongTerm:true});return create;}
const confirmation=(p,requestId=uuid())=>({requestId,planId:p.planId,scopeDigest:p.scopeDigest,confirmed:true,selection:p.selection});
async function enable(){await db("insert into privacy_private.memory_delete_worker_settings_v1 values(true,true,30000) on conflict(singleton) do update set enabled=true;");}
run('actual original command group tombstones and scrubs, default-disabled cleanup, exact lease completion and replay',async()=>{
 const a=await owner(),m1=await memory(a),m2=await memory(a),p=await deletion(a,'preview',{memoryIds:[m2.memoryId,m1.memoryId]}),input=confirmation(p);
 assert.deepEqual(p.conflicts,[]);assert.equal(p.counts.memories,2);assert.equal(JSON.stringify(p).includes('private summary'),false);
 await rejects(a,'confirm',{...input,selection:{...p.selection,memories:p.selection.memories.slice(0,1)}},'SCOPE_CHANGED');
 const q=await deletion(a,'confirm',input);assert.equal(q.state,'queued');assert.equal(q.sourceTombstoned,true);assert.equal(q.cleanupPending,true);
 assert.equal(await db(`select count(*) from public.memory_profiles where id in ('${m1.memoryId}','${m2.memoryId}') and state='deleted' and summary is null and revision=3;`),'2');
 assert.equal(await db(`select count(*) from memory_private.native_update_preimages_v1 where owner_id='${a.owner}';`),'0');
 assert.deepEqual(await deletion(a,'confirm',input),q);
 assert.deepEqual(await deletion(null,'claim',{requestId:input.requestId,operationId:uuid()}),{kind:'blocked'});
 await enable();const op=uuid(),l=await deletion(null,'claim',{requestId:input.requestId,operationId:op});assert.equal(l.kind,'leased');assert.equal((await deletion(null,'claim',{requestId:input.requestId,operationId:op})).leaseId,l.leaseId);
 const c=await deletion(null,'execute',{requestId:input.requestId,leaseId:l.leaseId});assert.equal(c.state,'completed');assert.equal(c.cleanupPending,false);assert.equal(c.allUserDataCompleted,false);assert.deepEqual(await deletion(null,'execute',{requestId:input.requestId,leaseId:l.leaseId}),c);assert.deepEqual(await deletion(a,'read',{requestId:input.requestId}),c);
 assert.equal(await db(`select expected_graph='{}' and execution_xid is null and execution_digest is null from privacy_private.memory_delete_jobs_v1 where request_id='${input.requestId}';`),'t');
});
run('late original-command failure rolls back every tombstone, private receipt, counter and request',async()=>{
 const a=await owner(),m=[await memory(a),await memory(a)].sort((x,y)=>x.memoryId.localeCompare(y.memoryId)),p=await deletion(a,'preview',{memoryIds:m.map(x=>x.memoryId)}),input=confirmation(p),before=await db(`select revision from export_private.memory_source_revisions_v1 where owner_id='${a.owner}';`);
 await db(`create function public.synthetic_memory_late_failure() returns trigger language plpgsql as $$begin if new.memory_id='${m[1].memoryId}' and new.receipt->>'state'='deleted' then raise exception 'SYNTHETIC_LATE_FAILURE';end if;return new;end $$;create trigger synthetic_late before insert on memory_private.native_command_receipts_v1 for each row execute function public.synthetic_memory_late_failure();`);
 await rejects(a,'confirm',input,'SYNTHETIC_LATE_FAILURE');
 assert.equal(await db(`select count(*) from public.memory_profiles where owner_id='${a.owner}' and state='explicit' and summary='Updated private summary' and revision=2;`),'2');assert.equal(await db(`select revision from export_private.memory_source_revisions_v1 where owner_id='${a.owner}';`),before);assert.equal(await db(`select count(*) from privacy_private.memory_delete_jobs_v1 where request_id='${input.requestId}';`),'0');assert.equal(await db(`select count(*) from memory_private.native_update_preimages_v1 where owner_id='${a.owner}';`),'2');
 await db('drop trigger synthetic_late on memory_private.native_command_receipts_v1;drop function public.synthetic_memory_late_failure();');
 assert.equal((await deletion(a,'confirm',input)).state,'queued');
});
async function generated(a,m,basis=m){
 const policy=uuid(),conversation=uuid(),goal=uuid(),message=uuid(),followup=uuid(),thread=uuid(),turn=uuid(),task=uuid(),artifactId=uuid(),ref=uuid();
 await db(`insert into turn_private.text_policies(id,provider,recipient,endpoint,source_region,processing_region,storage_region,terms_version,notice_version,notice_hash,notice_zh,notice_en,retention,effective_at,expires_at,terms_recheck_at) values('${policy}','qwen','synthetic','https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions','local','local','local','test','test','${'a'.repeat(64)}','合成','Synthetic','retain_after_hide_v1',now()-interval '1 hour',now()+interval '1 day',now()+interval '1 day');insert into turn_private.text_consents(owner_id,policy_id) values('${a.owner}','${policy}');`);
 await db(claims(a)+`select public.submit_assistant_message_v1('${conversation}','${message}','${uuid()}','${policy}','en','Original goal input','goal_start','${goal}',null,null,null,null);select public.submit_service_task_turn('${thread}','${turn}','${uuid()}','${policy}','en','Original chosen input','${task}',1,'new_goal',null);select public.submit_assistant_message_v1('${conversation}','${followup}','${uuid()}','${policy}','en','Original followup','follow_up','${goal}',1,'${task}','${message}',null);`);
 await db(`update public.turns set status='completed' where id='${turn}';update turn_private.work set state='completed',lease_token=null,expires_at=null where turn_id='${turn}';update turn_private.text_content set output_kind='answered',output_text='Generated selected output' where turn_id='${turn}';insert into public.memory_consumer_receipts(id,owner_id,memory_id,source_receipt_id,consumer_kind,turn_id,constraint_kind) values('${ref}','${a.owner}','${m.memoryId}','${m.receiptId}','turn','${turn}','preference');
 insert into turn_private.result_artifacts(id,owner_id,task_id,goal_id,input_message_id,current_revision) values('${artifactId}','${a.owner}','${task}','${goal}','${followup}',1);
 insert into turn_private.result_revisions(artifact_id,revision,owner_id,idempotency_key,request_digest,input_sequence,task_turn_id,goal_version,memory_basis,content) values('${artifactId}',1,'${a.owner}','${uuid()}','${'a'.repeat(64)}',2,'${turn}',1,'${JSON.stringify(basis?[{id:basis.memoryId,revision:2}]:[])}','{"schemaVersion":"comparison/1","summary":"Generated selected body"}');`);
 return {policy,thread,turn,task,artifactId,ref};
}
run('exact generated output and whole controlled export cleanup retains original input, Trip and other owner data; queued writer fences',async()=>{
 const f=await ready(),a=f.a,m=await memory(a),x=await generated(a,m),other=await owner(),otherMemory=await memory(other),outside=await generated(other,otherMemory);
 const ticket={requestId:a.request,operationId:uuid(),tokenHash:sha(randomBytes(32)),ticketTtlMs:300000};assert.equal((await call(a,'ticket',ticket)).kind,'privacy_export_ticket/1');
 const p=await deletion(a,'preview',{memoryIds:[m.memoryId]});assert.deepEqual(p.conflicts,[]);assert.deepEqual(p.selection.consumerReferenceIds,[x.ref]);assert.deepEqual(p.selection.generatedTurnIds,[x.turn]);assert.deepEqual(p.selection.artifactIds,[x.artifactId]);assert.deepEqual(p.selection.exportRequestIds,[a.request]);
 const input=confirmation(p),q=await deletion(a,'confirm',input);assert.equal(q.state,'queued');assert.equal(await db(`select state from export_private.core_jobs_v1 where request_id='${a.request}';`),'expired');
 assert.equal((await call(a,'download_prepare',{requestId:a.request,operationId:ticket.operationId,tokenHash:ticket.tokenHash})).kind,'unavailable');
 for(const statement of [
 `update turn_private.text_content set output_text='Pending revival' where turn_id='${x.turn}';`,
 `update turn_private.result_artifacts set lifecycle='withdrawn' where id='${x.artifactId}';`,
 `insert into turn_private.result_revisions(artifact_id,revision,owner_id,idempotency_key,request_digest,input_sequence,task_turn_id,goal_version,memory_basis,content) values('${uuid()}',1,'${a.owner}','${uuid()}','${'a'.repeat(64)}',2,'${x.turn}',1,'[{"id":"${m.memoryId}","revision":2}]','{}');`,
 `insert into public.memory_consumer_receipts(owner_id,memory_id,source_receipt_id,consumer_kind,proposal_id,constraint_kind) values('${a.owner}','${m.memoryId}','${m.receiptId}','proposal','${uuid()}','preference');`,
 `update export_private.core_jobs_v1 set state='running' where request_id='${a.request}';`,
 `select public.privacy_core_export_v1('request',${lit({requestId:uuid(),confirmed:true})});`
 ]){const r=await sql(container,claims(a)+statement);assert.notEqual(r.code,0);assert.match(r.stderr,/MEMORY_DELETION_PENDING/);}
 await enable();const l=await deletion(null,'claim',{requestId:input.requestId,operationId:uuid()}),c=await deletion(null,'execute',{requestId:input.requestId,leaseId:l.leaseId});assert.equal(c.state,'completed');assert.deepEqual(c.erasedCounts,{consumerReferences:1,artifacts:1,generatedOutputs:1,exports:1,tickets:1});
 assert.equal(await db(`select input_text='Original chosen input' and output_text is null and output_kind is null and hidden_at is null from turn_private.text_content where turn_id='${x.turn}';`),'t');
 assert.equal(await db(`select count(*) from turn_private.result_revisions where artifact_id='${x.artifactId}';`),'0');assert.equal(await db(`select count(*) from export_private.core_artifacts_v1 where request_id='${a.request}';`),'0');assert.equal(await db(`select count(*) from export_private.core_tickets_v1 where request_id='${a.request}';`),'0');
 assert.equal(await db(`select output_text from turn_private.text_content where turn_id='${outside.turn}';`),'Generated selected output');assert.equal(await db(`select count(*) from public.trips where owner_id='${a.owner}';`),'1');assert.equal(await db(`select count(*) from turn_private.assistant_messages where task_id='${x.task}';`),'1');
});
run('source CAS, foreign owner, terminal/active scope, full sentinel and purge do not permit truncated confirmation',async()=>{
 const a=await owner(),m=await memory(a),p=await deletion(a,'preview',{memoryIds:[m.memoryId]});await native(a,{action:'update',operationId:uuid(),memoryId:m.memoryId,sourceReceiptId:m.receiptId,expectedRevision:2,summary:'Concurrent current source',saveLongTerm:true});await rejects(a,'confirm',confirmation(p),'SCOPE_CHANGED');
 const foreign=await owner();await rejects(foreign,'preview',{memoryIds:[m.memoryId]},'FORBIDDEN');
 const x=await generated(a,m);await db(`update public.turns set status='accepted' where id='${x.turn}';`);const active=await deletion(a,'preview',{memoryIds:[m.memoryId]});assert.ok(active.conflicts.includes('ACTIVE_WORK'));await rejects(a,'confirm',confirmation(active),'SCOPE_CONFLICT');await db(`update public.turns set status='completed' where id='${x.turn}';`);
 const many=await owner(),consent=(await native(many,{action:'consentCreate',operationId:uuid()})).consentId;
 await db(`begin;${claims(many)}insert into public.memory_profiles(id,owner_id,source_receipt_id,consent_id,state,constraint_kind,summary) select gen_random_uuid(),'${many.owner}',gen_random_uuid(),'${consent}','explicit','preference','Bounded synthetic' from generate_series(1,101);insert into public.memory_receipts(id,owner_id,memory_id,event_state,source_kind) select source_receipt_id,owner_id,id,'explicit','user_confirmed' from public.memory_profiles where owner_id='${many.owner}';commit;`);
 const ids=JSON.parse(await db(`select jsonb_agg(id order by id) from public.memory_profiles where owner_id='${many.owner}';`)),cap=await deletion(many,'preview',{memoryIds:ids});assert.deepEqual(cap.conflicts,['SCOPE_TOO_LARGE']);assert.equal(cap.selection.memories.length,0);await rejects(many,'confirm',confirmation(cap),'SCOPE_CONFLICT');
 const fresh=await deletion(a,'preview',{memoryIds:[m.memoryId]}),q=await deletion(a,'confirm',confirmation(fresh));assert.ok((await deletion(a,'preview',{memoryIds:[m.memoryId]})).conflicts.includes('TERMINAL_MEMORY'));
 await db(`update privacy_private.memory_delete_plans_v1 set expires_at=clock_timestamp()-interval '1 second' where owner_id='${a.owner}';`);assert.ok((await deletion(null,'purge',{operationId:uuid(),limit:100})).removedPlans>=2);assert.equal(await db(`select count(*) from privacy_private.memory_delete_jobs_v1 where request_id='${q.requestId}';`),'1');
 await db(`delete from auth.users where id='${a.owner}';`);assert.equal(await db(`select count(*) from privacy_private.memory_delete_jobs_v1 where owner_id='${a.owner}';`),'0');
 assert.equal(await db("select has_function_privilege('authenticated','public.privacy_memory_delete_v1(text,jsonb)','EXECUTE') or has_function_privilege('service_role','public.privacy_memory_delete_v1(text,jsonb)','EXECUTE');"),'f');
});
run('unselected Memory revision increments do not strand cleanup; selected tombstone tampering fails closed',async()=>{
 const a=await owner(),chosen=await memory(a),unselected=await memory(a),p=await deletion(a,'preview',{memoryIds:[chosen.memoryId]}),q=await deletion(a,'confirm',confirmation(p));
 await native(a,{action:'update',operationId:uuid(),memoryId:unselected.memoryId,sourceReceiptId:unselected.receiptId,expectedRevision:2,summary:'Unselected changed and retained',saveLongTerm:true});
 await enable();const l=await deletion(null,'claim',{requestId:q.requestId,operationId:uuid()});assert.equal((await deletion(null,'execute',{requestId:q.requestId,leaseId:l.leaseId})).state,'completed');assert.equal(await db(`select summary from public.memory_profiles where id='${unselected.memoryId}';`),'Unselected changed and retained');
 const b=await owner(),m=await memory(b),scope=await deletion(b,'preview',{memoryIds:[m.memoryId]}),queued=await deletion(b,'confirm',confirmation(scope)),lease=await deletion(null,'claim',{requestId:queued.requestId,operationId:uuid()});
 await db(`update public.memory_profiles set updated_at=clock_timestamp() where id='${m.memoryId}';`);await rejects(null,'execute',{requestId:queued.requestId,leaseId:lease.leaseId},'SCOPE_CHANGED');assert.equal((await deletion(b,'read',{requestId:queued.requestId})).state,'queued');
});
run('actual owner HTTP to SQL and one-shot worker transport survive lost ACK with one exact cleanup; real new ACL denies',async t=>{
 const actualFetch=globalThis.fetch;const a=await owner({owner:subject,session:sessionId}),m=await memory(a),x=await generated(a,m),database='https://dzqdzetcctkhbrhlxxgn.supabase.co',host='vp-v4-memorydelete-jtcao515s-projects.vercel.app',f=await nativeFixture(t,database);
 const env={VERCEL_ENV:'preview',VERCEL_URL:host,VISEPANDA_NATIVE_STAGING:'true',VISEPANDA_TRIP_PROTOCOL_V2:'true',NEXT_PUBLIC_SUPABASE_URL:database,NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:f.config.publishableKey},old=Object.fromEntries(Object.keys(env).map(k=>[k,process.env[k]]));Object.assign(process.env,env);t.after(()=>{for(const[k,v]of Object.entries(old))v===undefined?delete process.env[k]:process.env[k]=v;});
 const prior=globalThis.fetch;t.mock.method(globalThis,'fetch',async(input,init)=>{
 const r=new Request(input,init),url=new URL(r.url);if(url.hostname==='127.0.0.1')return actualFetch(r);
 if(url.pathname.endsWith('/privacy_memory_delete_v1')){const body=await r.json();return Response.json(await deletion(a,body.p_action,body.p_input));}
 if(url.pathname.endsWith('/native_session_v2'))return Response.json(JSON.parse(await db(claims(a)+"select public.native_session_v2('session');")));
 return prior(input,init);
 });
 const base=`https://${host}/api/privacy/native/v1/memories/delete`,post=v=>new Request(base,{method:'POST',headers:{authorization:'Bearer '+f.token,'content-type':'application/json'},body:JSON.stringify(v)});
 const previewResponse=await memoryDeletionHTTP(post({action:'preview',memoryIds:[m.memoryId]}));assert.equal(previewResponse.status,200);const p=await previewResponse.json();assert.equal(memoryDeletePlan(p),true);
 const input=confirmation(p),response=await memoryDeletionHTTP(post({action:'confirm',...input}));assert.equal(response.status,202);const q=await response.json();assert.equal(memoryDeleteReceipt(q),true);assert.equal(q.state,'queued');
 let calls=0,executes=0,lost=true;const inputs=[];const server=createServer(async(req,res)=>{try{assert.equal(req.url,'/rest/v1/rpc/privacy_memory_delete_v1');let raw='';for await(const part of req)raw+=part;const body=JSON.parse(raw);inputs.push(body);calls++;const result=await deletion(null,body.p_action,body.p_input);if(body.p_action==='execute'){executes++;if(lost){lost=false;res.writeHead(503,{'Content-Type':'application/json'});res.end('{"error":"synthetic_ack_loss"}');return;}}res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify(result));}catch{res.writeHead(503,{'Content-Type':'application/json'});res.end('{"error":"fixture_failure"}');}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
 try{
 const disabled=createMemoryDeletionWorker({environment:'local',databaseUrl:url},{credential:()=>assert.fail('disabled credential read')});assert.equal(await disabled(q.requestId,AbortSignal.timeout(30000)),'disabled');assert.equal(calls,0);
 await enable();const worker=createMemoryDeletionWorker({enabled:true,environment:'local',databaseUrl:url},{credential:()=> 'synthetic-local-credential'});assert.equal(await worker(q.requestId,AbortSignal.timeout(30000)),'completed');assert.equal(calls,3);assert.equal(executes,2);assert.deepEqual(inputs[1],inputs[2]);
 const read=await memoryDeletionHTTP(new Request(base+'?requestId='+q.requestId,{headers:{authorization:'Bearer '+f.token}}));assert.equal(read.status,200);const c=await read.json();assert.equal(memoryDeleteReceipt(c),true);assert.equal(c.erasedCounts.generatedOutputs,1);assert.equal(await db(`select input_text from turn_private.text_content where turn_id='${x.turn}';`),'Original chosen input');
 for(const role of ['authenticated','service_role']){const r=await sql(container,`set role ${role};`+query(role==='authenticated'?a:null,role==='authenticated'?'read':'claim',role==='authenticated'?{requestId:q.requestId}:{requestId:q.requestId,operationId:uuid()}).replaceAll('privacy_core_export_v1','privacy_memory_delete_v1'));assert.notEqual(r.code,0);assert.match(r.stderr,/permission denied for function privacy_memory_delete_v1/);}
 }finally{server.closeAllConnections();await new Promise(r=>server.close(r));}
});
run('foreign generated basis reveals no foreign IDs; reference overflow returns no executable subset; two sessions preserve lock ordering',async()=>{
 const a=await owner(),m=await memory(a),b=await owner(),other=await memory(b),foreign=await generated(b,other,m);
 const p=await deletion(a,'preview',{memoryIds:[m.memoryId]});assert.ok(p.conflicts.includes('FOREIGN_REFERENCE'));assert.equal(JSON.stringify(p).includes(foreign.artifactId),false);await rejects(a,'confirm',confirmation(p),'SCOPE_CONFLICT');
 const c=await owner(),n=await memory(c),thread=uuid();await db(`begin;insert into public.chat_threads(id,owner_id,status) values('${thread}','${c.owner}','active');insert into public.turns(id,owner_id,thread_id,status) select gen_random_uuid(),'${c.owner}','${thread}','completed' from generate_series(1,1001);insert into public.memory_consumer_receipts(owner_id,memory_id,source_receipt_id,consumer_kind,turn_id,constraint_kind) select '${c.owner}','${n.memoryId}','${n.receiptId}','turn',id,'preference' from public.turns where owner_id='${c.owner}' and thread_id='${thread}';commit;`);
 const cap=await deletion(c,'preview',{memoryIds:[n.memoryId]});assert.deepEqual(cap.conflicts,['SCOPE_TOO_LARGE']);assert.deepEqual(cap.selection.consumerReferenceIds,[]);assert.deepEqual(cap.selection.memories,[]);await rejects(c,'confirm',confirmation(cap),'SCOPE_CONFLICT');
 const d=await owner(),chosen=await memory(d),outside=await memory(d),derived=await generated(d,chosen),freeParent=await generated(d,outside,null),historical=await generated(d,outside);await db(`insert into turn_private.result_revisions(artifact_id,revision,owner_id,idempotency_key,request_digest,input_sequence,task_turn_id,goal_version,memory_basis,content) values('${historical.artifactId}',2,'${d.owner}','${uuid()}','${'a'.repeat(64)}',2,'${historical.turn}',1,'[]','{}');update turn_private.result_artifacts set current_revision=2 where id='${historical.artifactId}';`);const plan=await deletion(d,'preview',{memoryIds:[chosen.memoryId]}),input=confirmation(plan);const holder=sql(container,`set application_name='memory_delete_holder';begin;${query(d,'confirm',input).replaceAll('privacy_core_export_v1','privacy_memory_delete_v1')}select pg_sleep(3);commit;`);
 for(let i=0;i<100;i++){if(await db("select exists(select 1 from pg_stat_activity where application_name='memory_delete_holder' and wait_event_type='Timeout');")==='t')break;if(i===99)assert.fail('bounded holder not observed');await new Promise(r=>setTimeout(r,10));}
 const raw=await sql(container,`set role service_role;set request.jwt.claim.role='service_role';update public.memory_profiles set updated_at=clock_timestamp() where id='${outside.memoryId}';`);assert.notEqual(raw.code,0);assert.match(raw.stderr,/could not obtain lock/);// The confirm job is still invisible to this transaction. A Memory-bearing
 // revision must nevertheless take the account fence before its FK/CAS writes.
 const memoryWrite=await sql(container,`insert into turn_private.result_revisions(artifact_id,revision,owner_id,idempotency_key,request_digest,input_sequence,task_turn_id,goal_version,memory_basis,content) values('${freeParent.artifactId}',2,'${d.owner}','${uuid()}','${'a'.repeat(64)}',2,'${freeParent.turn}',1,'[{"id":"${chosen.memoryId}","revision":2}]','{}');`);assert.notEqual(memoryWrite.code,0);assert.match(memoryWrite.stderr,/could not obtain lock on row in relation "mobile_accounts"/);
 const historicalWrite=await sql(container,`insert into turn_private.result_revisions(artifact_id,revision,owner_id,idempotency_key,request_digest,input_sequence,task_turn_id,goal_version,memory_basis,content) values('${historical.artifactId}',3,'${d.owner}','${uuid()}','${'a'.repeat(64)}',2,'${historical.turn}',1,'[]','{}');`);assert.notEqual(historicalWrite.code,0);assert.match(historicalWrite.stderr,/could not obtain lock on row in relation "mobile_accounts"/);
 const ended=await holder;assert.equal(ended.code,0,ended.stderr);assert.equal(await db(`select state||':'||revision from public.memory_profiles where id='${chosen.memoryId}';`),'deleted:3');assert.equal(await db(`select count(*) from turn_private.result_revisions where artifact_id='${derived.artifactId}';`),'1');
});
