import type { Locale } from "@/lib/i18n";

type CanvasCopy = Readonly<{
  eyebrow: string; title: string; subtitle: string; language: string; loading: string; signIn: string;
  unavailable: string; forbidden: string; noProposal: string; reload: string; currentTrip: string;
  version: string; pending: string; revision: string; oldValue: string; newValue: string; evidence: string;
  assumptions: string; notRecorded: string; include: string; edit: string; saveRevision: string;
  saving: string; reject: string; rejecting: string; confirm: string; confirming: string; conflict: string;
  applied: string; rejected: string; audit: string; noAudit: string; boundary: string;
}>;

export const canvasCopy: Readonly<Record<Locale, CanvasCopy>> = {
  zh: { eyebrow:"已认证行程",title:"Trip Canvas",subtitle:"确认前先检查真实差异。",language:"界面语言",loading:"正在读取行程…",signIn:"请先登录",unavailable:"Trip Canvas 暂时不可用。",forbidden:"你无权访问此行程。",noProposal:"当前没有可确认的 Proposal。",reload:"重新读取",currentTrip:"当前 Trip",version:"版本",pending:"待确认变化",revision:"Revision",oldValue:"旧值",newValue:"新值",evidence:"证据",assumptions:"假设",notRecorded:"R1 尚未记录；不得推断",include:"包含这项变化",edit:"编辑新标题",saveRevision:"保存为新 revision",saving:"正在保存…",reject:"拒绝 Proposal",rejecting:"正在拒绝…",confirm:"确认并应用",confirming:"正在确认…",conflict:"版本或 Proposal 状态已变化；没有覆盖任何数据。",applied:"已应用并从数据库重新读取。",rejected:"已拒绝并持久化。",audit:"审计记录",noAudit:"暂无审计记录。",boundary:"模型不能直接修改 Trip；只有可见 Proposal 经用户确认后才能写入。"},
  en: { eyebrow:"Authenticated trip",title:"Trip Canvas",subtitle:"Inspect the real diff before confirming.",language:"Interface language",loading:"Loading the Trip…",signIn:"Sign in first",unavailable:"Trip Canvas is temporarily unavailable.",forbidden:"You cannot access this Trip.",noProposal:"There is no confirmable Proposal.",reload:"Reload",currentTrip:"Current Trip",version:"Version",pending:"Pending change",revision:"Revision",oldValue:"Old value",newValue:"New value",evidence:"Evidence",assumptions:"Assumptions",notRecorded:"Not recorded in R1; do not infer",include:"Include this change",edit:"Edit the new title",saveRevision:"Save as a new revision",saving:"Saving…",reject:"Reject Proposal",rejecting:"Rejecting…",confirm:"Confirm and apply",confirming:"Confirming…",conflict:"The Trip or Proposal changed; nothing was overwritten.",applied:"Applied and reloaded from the database.",rejected:"Rejected and persisted.",audit:"Audit events",noAudit:"No audit events yet.",boundary:"The model cannot write the Trip. Only a visible, user-confirmed Proposal can be applied."},
  es: { eyebrow:"Viaje autenticado",title:"Trip Canvas",subtitle:"Revisa la diferencia real antes de confirmar.",language:"Idioma de la interfaz",loading:"Cargando el viaje…",signIn:"Inicia sesión primero",unavailable:"Trip Canvas no está disponible temporalmente.",forbidden:"No puedes acceder a este viaje.",noProposal:"No hay ninguna propuesta confirmable.",reload:"Volver a cargar",currentTrip:"Viaje actual",version:"Versión",pending:"Cambio pendiente",revision:"Revisión",oldValue:"Valor anterior",newValue:"Valor nuevo",evidence:"Evidencia",assumptions:"Supuestos",notRecorded:"No registrado en R1; no inferir",include:"Incluir este cambio",edit:"Editar el nuevo título",saveRevision:"Guardar como nueva revisión",saving:"Guardando…",reject:"Rechazar propuesta",rejecting:"Rechazando…",confirm:"Confirmar y aplicar",confirming:"Confirmando…",conflict:"El viaje o la propuesta cambió; no se sobrescribió nada.",applied:"Aplicado y recargado desde la base de datos.",rejected:"Rechazado y guardado.",audit:"Eventos de auditoría",noAudit:"Aún no hay eventos de auditoría.",boundary:"El modelo no puede escribir el viaje. Solo se aplica una propuesta visible y confirmada por el usuario."},
  ru: { eyebrow:"Авторизованная поездка",title:"Trip Canvas",subtitle:"Проверьте реальное изменение перед подтверждением.",language:"Язык интерфейса",loading:"Загрузка поездки…",signIn:"Сначала войдите",unavailable:"Trip Canvas временно недоступен.",forbidden:"У вас нет доступа к этой поездке.",noProposal:"Нет предложения для подтверждения.",reload:"Обновить",currentTrip:"Текущая поездка",version:"Версия",pending:"Ожидающее изменение",revision:"Ревизия",oldValue:"Старое значение",newValue:"Новое значение",evidence:"Доказательства",assumptions:"Предположения",notRecorded:"Не записано в R1; не делать выводов",include:"Включить изменение",edit:"Изменить новый заголовок",saveRevision:"Сохранить новую ревизию",saving:"Сохранение…",reject:"Отклонить предложение",rejecting:"Отклонение…",confirm:"Подтвердить и применить",confirming:"Подтверждение…",conflict:"Поездка или предложение изменились; данные не перезаписаны.",applied:"Применено и перечитано из базы данных.",rejected:"Отклонено и сохранено.",audit:"Аудит",noAudit:"Записей аудита пока нет.",boundary:"Модель не может изменять поездку. Применяется только видимое подтверждённое пользователем предложение."},
  ar: { eyebrow:"رحلة موثقة",title:"Trip Canvas",subtitle:"راجع الفرق الحقيقي قبل التأكيد.",language:"لغة الواجهة",loading:"جارٍ تحميل الرحلة…",signIn:"سجّل الدخول أولاً",unavailable:"Trip Canvas غير متاح مؤقتاً.",forbidden:"لا يمكنك الوصول إلى هذه الرحلة.",noProposal:"لا يوجد اقتراح قابل للتأكيد.",reload:"إعادة التحميل",currentTrip:"الرحلة الحالية",version:"الإصدار",pending:"تغيير معلق",revision:"مراجعة",oldValue:"القيمة السابقة",newValue:"القيمة الجديدة",evidence:"الدليل",assumptions:"الافتراضات",notRecorded:"غير مسجل في R1؛ لا تستنتج",include:"تضمين هذا التغيير",edit:"تعديل العنوان الجديد",saveRevision:"حفظ كمراجعة جديدة",saving:"جارٍ الحفظ…",reject:"رفض الاقتراح",rejecting:"جارٍ الرفض…",confirm:"تأكيد وتطبيق",confirming:"جارٍ التأكيد…",conflict:"تغيرت الرحلة أو حالة الاقتراح؛ لم تتم الكتابة فوق أي بيانات.",applied:"تم التطبيق وإعادة القراءة من قاعدة البيانات.",rejected:"تم الرفض والحفظ.",audit:"سجل التدقيق",noAudit:"لا توجد أحداث تدقيق بعد.",boundary:"لا يستطيع النموذج تعديل الرحلة. لا يُطبّق إلا اقتراح ظاهر يؤكده المستخدم."},
};
