// Disposable network-none PostgreSQL. Original actor/Trip authority, synthetic
// admin-created auth/session rows and claims. This is not signed target Auth.
import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID as uuid} from 'node:crypto';
import {readFileSync,readdirSync} from 'node:fs';
import {command,sql} from '../cost/fixtures/postgres-rpc.mjs';
const enabled=process.env.VP_TURN_DB_TEST==='1',container='vpj24-reservations-'+uuid().slice(0,8);let created=false;
const db=async q=>{const r=await sql(container,q);assert.equal(r.code,0,r.stderr);return r.stdout.trim();};
const lit=v=>"'"+JSON.stringify(v).replaceAll("'","''")+"'::jsonb";
const claims=a=>`set request.jwt.claim.role='authenticated';set request.jwt.claim.sub='${a.owner}';set request.jwt.claims='${JSON.stringify({role:'authenticated',is_anonymous:false,session_id:a.session})}';`;
const fields=(overrides={})=>({kind:'lodging',supplier:'booking',externalReference:'Opaque-123',title:'Synthetic hotel',startsAt:'2026-10-08T16:00:00+08:00',endsAt:'2026-10-10T11:00:00+08:00',timeZone:'Asia/Shanghai',address:'Synthetic address',terms:'Synthetic corrected terms',status:'reserved',...overrides});
const source=()=>({kind:'user_reported',localMaterialId:null,localContentHash:null,locator:null});
const input=(overrides={})=>({operationId:uuid(),referenceId:uuid(),expectedTripVersion:0,expectedRevision:0,fields:fields(),source:source(),explicitlyConfirmed:true,...overrides});
const confirmSQL=(a,v)=>claims(a)+`select public.confirm_reservation_reference_v1('${a.trip}',${lit(v)});`;
const confirm=async(a,v)=>JSON.parse(await db(confirmSQL(a,v)));
const read=async(a,ref=null,head=0,after=null,limit=20)=>JSON.parse(await db(claims(a)+`select public.read_reservation_references_v1('${a.trip}',${head},${ref?"'"+ref+"'":'null'},${after?"'"+after+"'":'null'},${limit});`));
const op=async(a,id)=>JSON.parse(await db(claims(a)+`select public.read_reservation_operation_v1('${a.trip}','${id}');`));
async function fixture(){const a={owner:uuid(),session:uuid(),trip:uuid()};await db(`insert into auth.users(id) values('${a.owner}');insert into auth.sessions(id,user_id) values('${a.session}','${a.owner}');insert into identity_private.mobile_accounts(owner_id,epoch,session_id) values('${a.owner}',1,'${a.session}');insert into identity_private.mobile_attempts values('${a.owner}','${uuid()}','${a.session}',1);${claims(a)}insert into public.trips(id,owner_id,title) values('${a.trip}','${a.owner}','Synthetic reservation Trip');`);return a;}
const denial=async(q,message)=>{const r=await sql(container,q);assert.notEqual(r.code,0);assert.match(r.stderr,message);};
before(async()=>{if(!enabled)return;
 const r=await command('docker',['run','--pull=never','--rm','-d','--network','none','--name',container,'--user','postgres','--entrypoint','/bin/sh','public.ecr.aws/supabase/postgres:17.6.1.159','-c','umask 077;mkdir /tmp/vpj59-socket;initdb -D /tmp/vpj59-db -A trust --no-locale -E UTF8 >/tmp/init.log 2>&1 && exec postgres -D /tmp/vpj59-db -c listen_addresses= -c unix_socket_directories=/tmp/vpj59-socket -c unix_socket_permissions=0700']);assert.equal(r.code,0,r.stderr);created=true;
 for(let i=0;i<100;i++){if((await command('docker',['exec',container,'pg_isready','-h','/tmp/vpj59-socket','-U','postgres'])).code===0)break;await new Promise(r=>setTimeout(r,100));}
 await db(readFileSync('tests/integration/turn/fixtures/durable-work-schema.sql','utf8'));
 await db("create function auth.role() returns text language sql as $$select nullif(current_setting('request.jwt.claim.role',true),'')$$;create schema extensions;create extension pgcrypto with schema extensions;");
 for(const f of readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')).sort())await db('begin;'+readFileSync('supabase/migrations/'+f,'utf8')+'commit;');
});
after(async()=>{if(created)assert.equal((await command('docker',['rm','-f',container])).code,0);});
const run=(name,fn)=>test(name,{skip:!enabled,timeout:120000},fn);
run('original actor/current Trip confirms exact original operation ACK; CAS/amend/cancel never writes Trip',async()=>{
 const a=await fixture(),v=input(),ack=await confirm(a,v);assert.equal(ack.kind,'reservation_confirmation/1');assert.equal(ack.operationId,v.operationId);assert.equal(ack.resultRevision,1);assert.deepEqual(ack.command,v);assert.equal(ack.receipt.evidenceTier,'user_reported');assert.equal(ack.receipt.sourceQualification,'untrusted');assert.equal(ack.receipt.sourceVersion,null);assert.equal(ack.receipt.tripMutation,'none');assert.match(ack.commandDigest,/^[a-f0-9]{64}$/);
 assert.deepEqual(await confirm(a,Object.fromEntries(Object.entries(v).reverse())),ack);assert.deepEqual(await read(a,v.referenceId),ack.receipt);const recovered=await op(a,v.operationId);assert.deepEqual(recovered.command,v);assert.deepEqual(recovered.receipt,ack.receipt);assert.equal(recovered.commandDigest,ack.commandDigest);
 assert.deepEqual(await confirm(a,{...v,operationId:uuid()}),{kind:'conflict'});assert.deepEqual(await confirm(a,{...v,fields:fields({title:'changed'})}),{kind:'conflict'});
 const changed={...v,operationId:uuid(),expectedRevision:1,fields:fields({title:'Corrected',status:'amended',terms:'Only current terms'})};const second=await confirm(a,changed);assert.equal(second.resultRevision,2);assert.equal((await op(a,v.operationId)).result,'superseded');assert.equal((await op(a,v.operationId)).receipt,null);assert.equal((await op(a,v.operationId)).command,null);assert.deepEqual(await confirm(a,v),{kind:'conflict'});
 const cancel=await confirm(a,{...changed,operationId:uuid(),expectedRevision:2,fields:fields({status:'cancelled'})});assert.equal(cancel.resultRevision,3);assert.equal(cancel.receipt.fields.status,'cancelled');assert.equal(await db(`select head_version from public.trips where id='${a.trip}';`),'0');assert.equal(await db(`select count(*) from public.trip_events where trip_id='${a.trip}';`),'0');assert.equal(await db(`select count(*) from reservation_private.events_v1 where owner_id='${a.owner}';`),'3');
 const historical=await db(`select coalesce(jsonb_agg(to_jsonb(e)),'[]')::text from reservation_private.events_v1 e where owner_id='${a.owner}';`);assert.equal(historical.includes('Synthetic address'),false);assert.equal(historical.includes('Only current terms'),false);assert.equal(historical.includes('Corrected'),false);
});
async function patch(a){const value={expectedVersion:0,operations:[{kind:'set_title',title:'Confirmed synthetic Trip'}]};const proposal=JSON.parse(await db(claims(a)+`select row_to_json(r) from public.create_trip_proposal_patch('${a.trip}',${lit(value)}) r;`));const digest=await db(claims(a)+`select digest from public.read_trip_proposal_v2('${proposal.proposal_id}');`);assert.equal(await db(claims(a)+`select outcome from public.confirm_and_apply_trip_proposal('${proposal.proposal_id}','${uuid()}','${digest}');`),'applied');}
run('closed validation refuses unavailable artifact, controls, invented tiers, impossible clocks and revision overflow',async()=>{
 const a=await fixture(),v=input();const artifact={kind:'artifact_reference',artifactId:uuid(),artifactRevision:1,sourceReceiptId:uuid(),sourceDigest:'a'.repeat(64),locator:'Synthetic source'};
 await denial(confirmSQL(a,{...v,source:artifact}),/RESERVATION_SOURCE_UNAVAILABLE/);
 for(const bad of [{...v,verified:true},{...v,explicitlyConfirmed:false},{...v,source:{...source(),tier:'provider_verified'}},{...v,fields:fields({title:'\u0007'})},{...v,fields:fields({title:'😀'.repeat(81)})},{...v,fields:fields({title:'\u00a0'})},{...v,fields:fields({startsAt:'2026-02-30T00:00:00Z'})},{...v,fields:fields({endsAt:'2026-10-08T08:00:00Z'})},{...v,fields:fields({startsAt:'2026-10-08T08:00:00'})},{...v,fields:fields({timeZone:'Invented/Zone'})},{...v,expectedRevision:0.5}])await denial(confirmSQL(a,bad),/INVALID_INPUT/);
 assert.equal(await db(`select count(*) from reservation_private.current_v1 where owner_id='${a.owner}';`),'0');
 const numeric=input({fields:fields({externalReference:'Typed-numeric'})});const numericSQL=confirmSQL(a,numeric).replace('\"expectedTripVersion\":0','\"expectedTripVersion\":0.0').replace('\"expectedRevision\":0','\"expectedRevision\":0.0');const typed=JSON.parse(await db(numericSQL));assert.deepEqual(typed.command,numeric);assert.deepEqual(JSON.parse(await db(numericSQL)),typed);assert.deepEqual(await confirm(a,numeric),typed);const typedOp=await op(a,numeric.operationId);assert.equal(typedOp.result,'applied');assert.deepEqual(typedOp.command,numeric);assert.equal(typedOp.commandDigest,typed.commandDigest);
 const upper={...v,operationId:v.operationId.toUpperCase(),referenceId:v.referenceId.toUpperCase()};const ack=await confirm(a,upper);assert.deepEqual(ack.command,upper);assert.deepEqual((await op(a,v.operationId)).command,upper);assert.deepEqual(await confirm(a,upper),ack);
 await db(`update reservation_private.current_v1 set revision=9007199254740990 where owner_id='${a.owner}' and reference_id='${v.referenceId}';`);await denial(confirmSQL(a,{...v,operationId:uuid(),expectedRevision:9007199254740990}),/INVALID_INPUT/);assert.equal(await db(`select revision from reservation_private.current_v1 where owner_id='${a.owner}' and reference_id='${v.referenceId}';`),'9007199254740990');
});
run('owner/current-head list and single reads have exact cursor fences and original ACK head after confirmed Trip patch',async()=>{
 const a=await fixture(),b=await fixture(),one=input(),two=input({fields:fields({externalReference:'Different-code'})});const ack=await confirm(a,one);await confirm(a,two);assert.deepEqual(await read({...b,trip:a.trip}),{kind:'unavailable'});assert.deepEqual(await op({...b,trip:a.trip},one.operationId),{kind:'unavailable'});assert.deepEqual(await read(b,one.referenceId),{kind:'unavailable'});
 const page=await read(a,null,0,null,1);assert.equal(page.kind,'reservation_references/1');assert.equal(page.items.length,1);assert.equal(page.hasMore,true);assert.equal(page.nextCursor,page.items[0].referenceId);const end=await read(a,null,0,page.nextCursor,1);assert.equal(end.items.length,1);assert.equal(end.hasMore,false);assert.equal(end.nextCursor,null);assert.ok(page.items[0].referenceId<end.items[0].referenceId);
 await denial(claims(a)+`select public.read_reservation_references_v1('${a.trip}',0,null,'${uuid()}',1);`,/INVALID_RESERVATION_CURSOR/);await denial(claims(a)+`select public.read_reservation_references_v1('${a.trip}',0,'${one.referenceId}',null,1);`,/INVALID_INPUT/);
 await patch(a);assert.deepEqual(await read(a,one.referenceId,0),{kind:'conflict'});assert.equal((await read(a,one.referenceId,1)).tripVersion,1);assert.deepEqual(await confirm(a,one),ack);const r=await op(a,one.operationId);assert.equal(r.receipt.tripVersion,0);assert.equal(r.current.tripVersion,1);assert.deepEqual(r.command,one);
 const anotherTrip=uuid();await db(claims(a)+`insert into public.trips(id,owner_id,title) values('${anotherTrip}','${a.owner}','Other owned Trip');`);assert.deepEqual(await confirm({...a,trip:anotherTrip},one),{kind:'conflict'});assert.deepEqual(await op({...a,trip:anotherTrip},one.operationId),{kind:'unavailable'});
});
run('server identity separates supplier/owner/Trip; official code alone never merges vendors; UTC equivalent complete fields dedupe',async()=>{
 const a=await fixture(),first=input();await confirm(a,first);assert.deepEqual(await confirm(a,input({fields:fields({externalReference:'  Opaque-123  ',title:'Different corrected title'})})),{kind:'conflict'});assert.equal((await confirm(a,input({fields:fields({supplier:'trip'})}))).kind,'reservation_confirmation/1');
 const b=await fixture();assert.equal((await confirm(b,input())).kind,'reservation_confirmation/1');
 const official=fields({supplier:'official',externalReference:'Same-local-code',title:'Vendor A'});assert.equal((await confirm(a,input({fields:official}))).kind,'reservation_confirmation/1');assert.equal((await confirm(a,input({fields:{...official,title:'Vendor B'}}))).kind,'reservation_confirmation/1');assert.deepEqual(await confirm(a,input({fields:official,source:{...source(),locator:'Different untrusted material'}})),{kind:'conflict'});
 const fallback=fields({supplier:'other',externalReference:null,title:'  Complete    fields  ',startsAt:'2026-10-08T16:00:00+08:00'});const v=input({fields:fallback});await confirm(a,v);assert.deepEqual(await confirm(a,input({fields:{...fallback,title:'Complete fields',startsAt:'2026-10-08T08:00:00Z'}})),{kind:'conflict'});
 const utc=await db(`set timezone='Pacific/Honolulu';select reservation_private.identity_v1(${lit(fallback)});`),other=await db(`set timezone='Asia/Tokyo';select reservation_private.identity_v1(${lit({...fallback,startsAt:'2026-10-08T08:00:00Z'})});`);assert.equal(utc,other);
 const ack=await confirm(a,input({fields:fields({externalReference:'UTC-new',timeZone:null,startsAt:'2026-10-08T08:00:00.123456Z'})}));assert.equal(ack.receipt.fields.timeZone,null);assert.equal(ack.receipt.fields.startsAt,'2026-10-08T08:00:00.123456Z');assert.match(ack.receipt.confirmedAt,/\.\d{3}Z$/);assert.deepEqual(JSON.parse(await db("set timezone='Pacific/Honolulu';"+confirmSQL(a,ack.command))),ack);
});
async function sleeping(name){for(let i=0;i<100;i++){if(await db(`select exists(select 1 from pg_stat_activity where application_name='${name}' and wait_event='PgSleep');`)==='t')return;await new Promise(r=>setTimeout(r,10));}assert.fail('holder transaction not observed');}
run('two live PostgreSQL transactions serialize duplicate create/CAS and retain only one winning event',async()=>{
 const a=await fixture(),v=input();const holder=sql(container,`set application_name='reservation-create-holder';begin;${confirmSQL(a,v)}select pg_sleep(1);commit;`);await sleeping('reservation-create-holder');const other=input();assert.deepEqual(await confirm(a,other),{kind:'unavailable'});assert.equal((await holder).code,0);assert.deepEqual(await confirm(a,other),{kind:'conflict'});assert.deepEqual((await confirm(a,v)).command,v);assert.equal(await db(`select count(*) from reservation_private.current_v1 where owner_id='${a.owner}';`),'1');
 const amended={...v,operationId:uuid(),expectedRevision:1,fields:fields({status:'amended'})},stale={...amended,operationId:uuid(),fields:fields({status:'cancelled'})};const held=sql(container,`set application_name='reservation-cas-holder';begin;${confirmSQL(a,amended)}select pg_sleep(1);commit;`);await sleeping('reservation-cas-holder');assert.deepEqual(await confirm(a,stale),{kind:'unavailable'});assert.equal((await held).code,0);assert.deepEqual(await confirm(a,stale),{kind:'conflict'});assert.equal((await read(a,v.referenceId)).revision,2);assert.equal(await db(`select count(*) from reservation_private.events_v1 where owner_id='${a.owner}';`),'2');
 const race=await fixture(),a1=input(),a2=input();const responses=await Promise.all([confirm(race,a1),confirm(race,a2)]);assert.equal(responses.filter(r=>r.kind==='reservation_confirmation/1').length,1);assert.ok(responses.some(r=>['unavailable','conflict'].includes(r.kind)));assert.equal(await db(`select count(*) from reservation_private.current_v1 where owner_id='${race.owner}';`),'1');
});
run('late acknowledgement insert failure rolls back new/current/history; immutable metadata never exposes prior payload',async()=>{
 const a=await fixture(),v=input();await confirm(a,v);const before=await read(a,v.referenceId);await db(`create function reservation_private.fixture_ack_fault() returns trigger language plpgsql as $$begin if new.owner_id='${a.owner}' then raise exception 'FIXTURE_ACK_FAILURE';end if;return new;end $$;create trigger fixture_ack_fault before insert on reservation_private.operations_v1 for each row execute function reservation_private.fixture_ack_fault();`);
 await denial(confirmSQL(a,{...v,operationId:uuid(),expectedRevision:1,fields:fields({title:'Failed correction'})}),/FIXTURE_ACK_FAILURE/);assert.deepEqual(await read(a,v.referenceId),before);await denial(confirmSQL(a,input({fields:fields({externalReference:'New-failure'})})),/FIXTURE_ACK_FAILURE/);assert.equal(await db(`select count(*) from reservation_private.current_v1 where owner_id='${a.owner}';`),'1');assert.equal(await db(`select count(*) from reservation_private.events_v1 where owner_id='${a.owner}';`),'1');assert.equal(await db(`select count(*) from reservation_private.operations_v1 where owner_id='${a.owner}';`),'1');
 await db('drop trigger fixture_ack_fault on reservation_private.operations_v1;drop function reservation_private.fixture_ack_fault();');await denial(`update reservation_private.operations_v1 set command_digest='${'a'.repeat(64)}' where owner_id='${a.owner}';`,/RESERVATION_ACK_IMMUTABLE/);await denial(`update reservation_private.events_v1 set status='unknown' where owner_id='${a.owner}';`,/RESERVATION_ACK_IMMUTABLE/);
});
run('original archive/D1/D3/account lifecycle erases all reservation state and prevents replay; financial minimum survives D3',async()=>{
 const gone=async a=>{for(const t of ['current_v1','events_v1','operations_v1'])assert.equal(await db(`select count(*) from reservation_private.${t} where owner_id='${a.owner}' and trip_id='${a.trip}';`),'0',t);};
 const archived=await fixture();await patch(archived);const va=input({expectedTripVersion:1});await confirm(archived,va);await db(claims(archived)+`select public.archive_trip_v1('${archived.trip}',1,'${uuid()}',true);`);await gone(archived);assert.deepEqual(await confirm(archived,va),{kind:'unavailable'});assert.deepEqual(await op(archived,va.operationId),{kind:'unavailable'});assert.deepEqual(await read(archived,null,1),{kind:'unavailable'});
 const d1=await fixture(),v1=input(),request=uuid();await confirm(d1,v1);const queued=JSON.parse(await db(claims(d1)+`select public.request_trip_deletion_v1('${request}','${d1.trip}',0,true);`));assert.equal(queued.state,'queued');await gone(d1);assert.deepEqual(await confirm(d1,v1),{kind:'unavailable'});assert.equal(JSON.parse(await db(`set request.jwt.claim.role='service_role';select public.execute_trip_deletion_v1('${request}');`)).state,'completed');assert.equal(await db(`select count(*) from public.trips where id='${d1.trip}';`),'0');
 const d3=await fixture(),v3=input(),thread=uuid(),turn=uuid(),scope=uuid(),attempt=uuid();await confirm(d3,v3);await db(claims(d3)+`insert into public.chat_threads(id,owner_id,trip_id,status) values('${thread}','${d3.owner}','${d3.trip}','active');insert into public.turns(id,owner_id,thread_id,trip_id,status) values('${turn}','${d3.owner}','${thread}','${d3.trip}','completed');insert into public.model_budget_scopes(id,owner_id,currency,limit_micros,task_limit_micros,task_attempt_limit,concurrency_limit,enabled,expires_at) values('${scope}','${d3.owner}','CNY',10000,1000,3,3,true,now()+interval '1 day');insert into public.model_budget_provider_limits(scope_id,provider,model,price_version,limit_micros,attempt_limit_micros,enabled) values('${scope}','qwen','synthetic-model','synthetic-v1',10000,1000,true);insert into public.model_budget_attempts(scope_id,attempt_id,task_id,provider,model,price_version,reserved_micros,actual_micros,status) values('${scope}','${attempt}','${uuid()}','qwen','synthetic-model','synthetic-v1',10,5,'settled');insert into privacy_private.linked_delete_worker_settings_v1(singleton,enabled,max_lease_ms) values(true,true,30000) on conflict(singleton) do nothing;`);
 const privacy=async(actor,action,body)=>JSON.parse(await db((actor?claims(actor):"set request.jwt.claim.role='service_role';set request.jwt.claims='{\"role\":\"service_role\"}';")+`select public.privacy_linked_trip_delete_v1('${action}',${lit(body)});`));const plan=await privacy(d3,'preview',{tripId:d3.trip,expectedVersion:0});assert.deepEqual(plan.conflicts,[]);const q=await privacy(d3,'confirm',{requestId:uuid(),planId:plan.planId,scopeDigest:plan.scopeDigest,expectedVersion:0,confirmed:true,selection:plan.selection});await gone(d3);const lease=await privacy(null,'claim',{requestId:q.requestId,operationId:uuid()});assert.equal((await privacy(null,'execute',{requestId:q.requestId,leaseId:lease.leaseId})).state,'completed');assert.equal(await db(`select actual_micros from public.model_budget_attempts where attempt_id='${attempt}';`),'5');assert.equal(await db(`select count(*) from public.trips where id='${d3.trip}';`),'0');assert.deepEqual(await op(d3,v3.operationId),{kind:'unavailable'});
 const account=await fixture();await confirm(account,input());await db(`delete from auth.users where id='${account.owner}';`);await gone(account);
});
run('private exact D2 lease export shows corrected current only; existing inventory stays partial and every default ACL is closed',async()=>{
 const a=await fixture(),v=input(),b=await fixture();await confirm(a,v);await confirm(a,{...v,operationId:uuid(),expectedRevision:1,fields:fields({title:'Export corrected only',address:'Corrected export address',terms:'Current export terms'})});await confirm(b,input());
 for(const role of ['anon','authenticated','service_role']){
  assert.equal(await db(`select exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where (n.nspname='reservation_private' or n.nspname='public' and p.proname in ('confirm_reservation_reference_v1','read_reservation_references_v1','read_reservation_operation_v1')) and has_function_privilege('${role}',p.oid,'EXECUTE'));`),'f');
  for(const t of ['current_v1','events_v1','operations_v1']){assert.equal(await db(`select has_table_privilege('${role}','reservation_private.${t}','SELECT,INSERT,UPDATE,DELETE');`),'f');await denial(`set role ${role};select * from reservation_private.${t};`,/permission denied/);}
  await denial(`set role ${role};select public.confirm_reservation_reference_v1('${a.trip}',${lit(v)});`,/permission denied/);
 }
 assert.equal(await db("select count(*) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='reservation_private' and c.relkind='r' and c.relrowsecurity;"),'3');
 const request=uuid(),policy=uuid();await db(`insert into export_private.core_policies_v1(id,revision,enabled,environment,key_id,max_run_ms,artifact_ttl_ms,ticket_ttl_ms,max_pages,page_size,max_bytes,valid_until) values('${policy}',1,true,'local','synthetic-reservation',90000,600000,300000,100,100,8388608,clock_timestamp()+interval '1 day');`);await db(claims(a)+`select public.privacy_core_export_v1('request',${lit({requestId:request,confirmed:true})});`);const lease=JSON.parse(await db(`set request.jwt.claim.role='service_role';set request.jwt.claims='{\"role\":\"service_role\"}';select public.privacy_core_export_v1('claim',${lit({requestId:request,operationId:uuid(),maxRunMs:90000,expectedEnvironment:'local',expectedKeyId:'synthetic-reservation'})});`));
 const exportSQL=(id=lease.leaseId,gen=lease.generation,after=null)=>`set request.jwt.claim.role='service_role';select reservation_private.export_metadata_v1('${request}','${id}',${gen},${after?"'"+after+"'":'null'},1);`;
 const page=JSON.parse(await db(exportSQL()));assert.equal(page.enrolled,false);assert.equal(page.inventoryStatus,'partial');assert.equal(page.sectionComplete,true);assert.equal(page.items.length,1);assert.equal(page.items[0].current.fields.title,'Export corrected only');assert.equal(page.items[0].events.length,2);assert.equal(page.items[0].operations.length,2);assert.equal(page.items[0].historical,true);assert.equal(JSON.stringify(page).includes('Synthetic address'),false);assert.equal(JSON.stringify(page).includes('Synthetic corrected terms'),false);assert.equal(JSON.stringify(page).includes('commandDigest'),false);assert.deepEqual(JSON.parse(await db(exportSQL(uuid()))),{kind:'unavailable'});assert.deepEqual(JSON.parse(await db(exportSQL(lease.leaseId,2))),{kind:'unavailable'});await denial(exportSQL(lease.leaseId,lease.generation,uuid()),/INVALID_EXPORT_CURSOR/);
 assert.equal(await db("select position('reservation' in pg_get_functiondef('export_private.valid_modules_v1(jsonb,integer)'::regprocedure))=0;"),'t');assert.equal(await db("select has_function_privilege('service_role','public.assistant_conversation_export_owner_v1(uuid,text,uuid,integer)','EXECUTE');"),'t');
 await db(`update export_private.core_jobs_v1 set lease_expires_at=clock_timestamp()-interval '1 second' where request_id='${request}';`);assert.deepEqual(JSON.parse(await db(exportSQL())),{kind:'unavailable'});
});
