import fs from 'node:fs';import assert from 'node:assert/strict';import {query} from './transport.mjs';
const phase=process.argv[2];assert.ok(['admitted','held','cancelled','settled'].includes(phase));const intent=JSON.parse(fs.readFileSync('native-en-root-intent.json')),job=JSON.parse(fs.readFileSync('worker-en.json'));const lit=x=>"'"+x.replaceAll("'","''")+"'";
const rows=JSON.parse(query(`begin read only;set local role postgres;select coalesce(json_agg(json_build_object('turnId',c.turn_id,'taskId',g.task_id,'status',t.status,'outcome',g.original_outcome,'attempts',(select coalesce(json_agg(json_build_object('attemptId',a.attempt_id,'status',a.status,'reservedMicros',a.reserved_micros,'actualMicros',a.actual_micros)),'[]') from public.model_budget_attempts a where a.task_id=g.task_id),'events',(select coalesce(json_agg(json_build_object('eventId',e.event_id,'sequence',e.sequence,'type',e.event_type,'state',e.state) order by e.sequence),'[]') from public.chat_turn_events e where e.turn_id=c.turn_id))),'[]') from turn_private.text_content c join turn_private.grounded_turns g on g.turn_id=c.turn_id join public.turns t on t.id=c.turn_id where c.owner_id=${lit(job.ownerId)} and c.policy_id=${lit(job.policyId)} and c.input_text=${lit(intent.text)} and c.created_at>=to_timestamp(${Number(intent.at)})-interval '2 seconds';rollback;`));assert.equal(rows.length,1);const r=rows[0];
if(phase==='admitted'){assert.equal(r.status,'accepted');assert.equal(r.attempts.length,0);}
else{
 const first=JSON.parse(fs.readFileSync('admitted.json'));assert.equal(r.turnId,first.turnId);assert.equal(r.taskId,first.taskId);assert.equal(r.attempts.length,1);
 const journal=fs.readFileSync('fault-service.jsonl','utf8').trim().split('\n').map(JSON.parse);const usages=journal.filter(x=>x.schemaVersion==='vpj07-usage-journal/1');assert.equal(usages.length,1);const u=usages[0].receipt;assert.equal(u.turnId,r.turnId);assert.equal(u.attempt.attemptId,r.attempts[0].attemptId);assert.equal(u.attempt.ownerId,job.ownerId);assert.equal(u.attempt.scopeId,job.budget.scopeId);assert.equal(journal.filter(x=>x.schemaVersion==='provider-destination/1'&&x.phase==='attempted').length,1);r.validatedMicros=u.actualMicros;
 if(phase==='held'){assert.equal(r.attempts[0].status,'dispatched');assert.equal(r.attempts[0].actualMicros,null);assert.equal(r.status,'accepted');assert.equal(r.events.filter(x=>x.type==='terminal').length,0);}
 if(phase==='cancelled'||phase==='settled'){assert.equal(r.status,'cancelled');assert.equal(r.events.filter(x=>x.type==='terminal').length,1);assert.equal(r.events.find(x=>x.type==='terminal').state,'cancelled');}
 if(phase==='cancelled'){assert.ok(['dispatched','pending'].includes(r.attempts[0].status));assert.equal(r.attempts[0].actualMicros,null);}
 if(phase==='settled'){assert.equal(r.attempts[0].status,'settled');assert.equal(r.attempts[0].actualMicros,u.actualMicros);}
}
fs.writeFileSync(phase+'.json',JSON.stringify({at:new Date().toISOString(),phase,...r},null,2)+'\n',{mode:0o600,flag:'wx'});console.log({phase,turnId:r.turnId,taskId:r.taskId,status:r.status,attempts:r.attempts.length});
