import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createNativeTextEnvironment} from './native-text-environment.mjs';
import {waitUntil} from '../identity/database-barrier.mjs';
import {identityLocalEnv} from '../identity/local-supabase.mjs';

test('real local Auth, native HTTP, consent, durable worker and recovery enforce owner/session boundaries',{skip:process.env.VP_NATIVE_TEXT_INTEGRATION!=='true',timeout:180000},async t=>{
 const continuous=process.env.VP_NATIVE_TEXT_SERVICE_INTEGRATION==='true';
 const e=await createNativeTextEnvironment({continuous});t.after(()=>e.cleanup());
 const call=async(path,token,method='GET',body,headers={})=>{
  const r=await fetch(e.api+path,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body===undefined?{}:{'Content-Type':'application/json'}),...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,body:await r.json()};
 };
 const login=async(user)=>{const attemptId=randomUUID();const c=await call('/api/auth/native/v2/credentials',null,'POST',{email:user.email,password:user.password,attemptId});assert.equal(c.status,200);assert.equal((await call('/api/auth/native/v2/login',c.body.accessToken,'POST',{attemptId})).status,200);return c.body.accessToken;};
 const token=await login(e.users[0]),other=await login(e.users[1]),base='/api/chat/native/v1';
 assert.equal((await call(base+'/policy')).status,401);
 assert.equal((await call(base+'/policy',token,'GET',undefined,{Origin:e.api})).status,400);
 assert.equal((await call(base+'/policy',token,'GET',undefined,{Cookie:'synthetic=only'})).status,400);
 const policy=(await call(base+'/policy',token)).body.policy;assert.equal(policy.id,e.policyId);assert.equal(policy.consentState,'not_accepted');assert.ok(policy.noticeEn.includes('Local synthetic'));
 const input={threadId:randomUUID(),turnId:randomUUID(),idempotencyKey:randomUUID(),policyId:e.policyId,locale:'en',text:'Synthetic local request'};
 assert.equal((await call(base+'/turns',token,'POST',input)).status,403);
 assert.equal(e.sql(`select count(*) from public.chat_threads where id='${input.threadId}';`),'0','denied submission leaves no orphan thread');
 assert.equal((await call(base+'/consent',token,'POST',{policyId:e.policyId,noticeHash:'b'.repeat(64)})).status,403);
 assert.equal((await call(base+'/consent',token,'POST',{policyId:e.policyId,noticeHash:e.noticeHash})).status,200);
 const accepted=await Promise.all([call(base+'/turns',token,'POST',input),call(base+'/turns',token,'POST',input)]);assert.deepEqual(accepted.map(r=>r.status).sort(),[200,201]);
 await waitUntil(async()=>{const r=await call(base+'/turns',token);return r.body.turns?.some(t=>t.turnId===input.turnId&&t.outcome==='answered');},30000,'actual worker final answer');
 const final=(await call(base+'/turns',token)).body.turns[0];assert.equal(final.output,'Local synthetic answer: request completed.');assert.equal(e.counts.http,1);
 const receiptCount=continuous?e.serviceEvidence().runs.flat().filter(r=>r.schemaVersion==='provider-destination/1').length:e.counts.destinationReceipts;
 assert.equal(receiptCount,3,'configured/attempted/buffered metadata hooks ran');
 assert.equal(e.sql(`select status||':'||actual_micros from public.model_budget_attempts where task_id='${input.turnId}';`),'settled:1','synthetic reviewed tariff rounds up once after model/usage validation');
 assert.equal((await call(base+'/turns',other)).body.turns.length,0);
 assert.equal((await call(base+'/turns',token,'POST',{...input,text:'Changed'})).status,409);
 assert.equal((await call(base+'/turns',token,'POST',{...input,reasoning:'forbidden extra field'})).status,400);
 if(continuous){
  await e.restartServiceWorkers();
  assert.equal(e.sql(`select status||':'||actual_micros from public.model_budget_attempts where task_id='${input.turnId}';`),'settled:1','process restart retains the settled ledger');
  assert.equal((await call(base+'/turns',token,'POST',input)).status,200);
 }
 const taskBase='/api/chat/native/v2',taskId=randomUUID();
 const goal={...input,threadId:randomUUID(),turnId:randomUUID(),idempotencyKey:randomUUID(),text:'Synthetic kind=clarification',serviceTask:{id:taskId,scopeVersion:1,relationship:'new_goal',parentTurnId:null}};
 const submit=body=>call(taskBase+'/turns',token,'POST',body);
 const waitOutcome=async(turnId,outcome)=>waitUntil(async()=>{const r=await call(taskBase+'/turns',token);return r.body.version===2&&r.body.turns?.some(t=>t.turnId===turnId&&t.outcome===outcome&&t.serviceTaskId===taskId);},30000,'actual ServiceTask outcome');
 assert.equal((await submit({...goal,serviceTask:{...goal.serviceTask,extra:true}})).status,400);
 assert.equal((await submit(goal)).status,201);await waitOutcome(goal.turnId,'clarification');
 const clarification={...goal,turnId:randomUUID(),idempotencyKey:randomUUID(),text:'Synthetic kind=technical_failure',serviceTask:{...goal.serviceTask,relationship:'clarification',parentTurnId:goal.turnId}};
 assert.deepEqual((await Promise.all([submit(clarification),submit(clarification)])).map(r=>r.status).sort(),[200,201]);await waitOutcome(clarification.turnId,'technical_failure');
 assert.equal((await submit(goal)).status,200);
 const repair={...goal,turnId:randomUUID(),idempotencyKey:randomUUID(),text:'Synthetic repaired answer',serviceTask:{...goal.serviceTask,relationship:'repair',parentTurnId:clarification.turnId}};
 assert.equal((await submit(repair)).status,201);await waitOutcome(repair.turnId,'answered');
 assert.equal(e.sql(`select count(*)||':'||sum(actual_micros) from public.model_budget_attempts where task_id='${taskId}' and status='settled';`),'3:3');
 assert.equal((await call(taskBase+'/turns',other)).body.turns.length,0);
 assert.equal((await submit({...repair,turnId:randomUUID(),idempotencyKey:randomUUID()})).status,409);
 const {serviceTask:ignored,...legacy}=goal;void ignored;
 assert.equal((await call(base+'/turns',token,'POST',{...legacy,turnId:randomUUID(),idempotencyKey:randomUUID()})).status,409);
 const contextBase='/api/chat/native/v3',contextId=randomUUID();
 const contextGoal={...goal,policyId:e.taskPolicyId,threadId:randomUUID(),turnId:randomUUID(),idempotencyKey:randomUUID(),text:'Synthetic original goal kind=clarification',serviceTask:{id:contextId,scopeVersion:1,relationship:'new_goal',parentTurnId:null}};
 assert.equal((await call(contextBase+'/policy',token)).body.policy.consentState,'not_accepted');
 assert.equal((await call(contextBase+'/turns',token,'POST',contextGoal)).status,403,'old consent does not grant history mode');
 assert.equal((await call(contextBase+'/consent',token,'POST',{policyId:e.taskPolicyId,noticeHash:e.noticeHash})).status,403);
 assert.equal((await call(contextBase+'/consent',token,'POST',{policyId:e.taskPolicyId,noticeHash:e.taskNoticeHash})).status,200);
 const waitContext=async(turnId,outcome)=>waitUntil(async()=>{const r=await call(contextBase+'/turns',token);return r.body.version===3&&r.body.turns?.some(t=>t.turnId===turnId&&t.outcome===outcome);},30000,'actual context-mode outcome');
 assert.equal((await call(contextBase+'/turns',token,'POST',contextGoal)).status,201);await waitContext(contextGoal.turnId,'clarification');
 const contextNext={...contextGoal,turnId:randomUUID(),idempotencyKey:randomUUID(),text:'North.',serviceTask:{...contextGoal.serviceTask,relationship:'clarification',parentTurnId:contextGoal.turnId}};
 assert.equal((await call(contextBase+'/turns',token,'POST',contextNext)).status,201);await waitContext(contextNext.turnId,'answered');
 const sent=e.requests.find(r=>r.messages.at(-1).content==='North.');assert.ok(sent);assert.equal(sent.messages.length,4);
 assert.equal(sent.messages[1].content,contextGoal.text);assert.equal(sent.messages[2].content,'Local synthetic answer: request completed.');
 assert.equal(e.sql(`select count(*)||':'||sum(actual_micros) from public.model_budget_attempts where task_id='${contextId}' and status='settled';`),'2:2');
 assert.equal((await call(contextBase+'/turns',other)).body.turns.length,0);
 assert.equal((await submit(goal)).status,200,'v2 original policy replay still works after v3 use');
 assert.equal((await call(contextBase+'/consent',token,'DELETE',{policyId:e.taskPolicyId})).status,200);
 assert.equal((await call(contextBase+'/turns',token)).body.turns.length,0);
 if(continuous)assert.deepEqual(e.serviceEvidence().failures,[],'normal processing and restart have no failed exits');
 const beforeHeld=e.counts.http;
 const held={...input,threadId:randomUUID(),turnId:randomUUID(),idempotencyKey:randomUUID(),text:'Synthetic HOLD request'};
 assert.equal((await call(base+'/turns',token,'POST',held)).status,201);
 await waitUntil(()=>e.counts.http===beforeHeld+1,10000,'held provider request');
 assert.equal((await call(base+'/turns/'+held.turnId+'/cancel',token,'POST',{})).status,200);e.releaseModels();
 await waitUntil(()=>e.sql(`select status from public.turns where id='${held.turnId}';`)==='cancelled',5000,'cancelled terminal');
 assert.equal(e.sql(`select output_text is null from turn_private.text_content where turn_id='${held.turnId}';`),'t');
 assert.equal((await call(base+'/consent',token,'DELETE',{policyId:e.policyId})).status,200);
 assert.equal((await call(base+'/turns',token)).body.turns.length,0);
 assert.equal((await call(base+'/policy',token)).body.policy.consentState,'withdrawn');
 assert.equal((await call(base+'/consent',token,'POST',{policyId:e.policyId,noticeHash:e.noticeHash})).status,403);
 await login(e.users[0]);assert.equal((await call(base+'/policy',token)).status,401,'replaced mobile token rejected');
 if(continuous){
  await waitUntil(()=>e.serviceEvidence().failures.length===1,5000,'cancelled in-flight poll stops service');
  const evidence=e.serviceEvidence();assert.deepEqual(evidence.failures,['service-exit-1']);assert.equal(evidence.runs.length,4);
  assert.equal(evidence.runs[2].at(-1).reason,'unavailable','cancelled work cannot trigger automatic retries');
  assert.equal(e.counts.http,beforeHeld+1,'cancelled request was sent only once');
  assert.equal(evidence.runs[0][0].expiresAt,evidence.runs[2][0].expiresAt,'restart cannot renew expiry');
  assert.equal(evidence.runs[1][0].expiresAt,evidence.runs[3][0].expiresAt);
  assert.ok(evidence.runs[2].some(r=>r.phase==='poll-returned'&&r.result==='finished'),'new process consumes later requests');
  assert.ok(evidence.runs[3].some(r=>r.phase==='poll-returned'&&r.result==='finished'),'task mode continues after process restart');
 }
});

test('v5 conversation persists independent answer and versioned goal changes without extra task attempts',{skip:process.env.VP_NATIVE_TEXT_INTEGRATION!=='true',timeout:180000},async t=>{
 const e=await createNativeTextEnvironment();t.after(()=>e.cleanup());
 const call=async(path,token,method='GET',body)=>{const response=await fetch(e.api+path,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:response.status,body:await response.json()};};
 const login=async(user)=>{const attemptId=randomUUID();const c=await call('/api/auth/native/v2/credentials',null,'POST',{email:user.email,password:user.password,attemptId});assert.equal(c.status,200);assert.equal((await call('/api/auth/native/v2/login',c.body.accessToken,'POST',{attemptId})).status,200);return c.body.accessToken;};
 const owner=await login(e.users[0]),other=await login(e.users[1]),base='/api/chat/native/v5';
 const policy=(await call(base+'/policy',owner)).body.policy;
 const conversationId=randomUUID();
 const make=(relationship,overrides={})=>({conversationId,messageId:randomUUID(),idempotencyKey:randomUUID(),policyId:policy.id,locale:'en',text:'Synthetic independent question',relationship,goalId:null,expectedGoalVersion:null,taskId:null,parentMessageId:null,turnId:relationship==='independent_question'?randomUUID():null,...overrides});
 const question=make('independent_question');
 assert.equal((await call(base+'/conversation',owner,'POST',question)).status,403,'consent required');
 assert.equal(e.sql(`select count(*) from turn_private.assistant_conversations where id='${conversationId}';`),'0');
 assert.equal((await call(base+'/consent',owner,'POST',{policyId:policy.id,noticeHash:policy.noticeHash})).status,200);
 const responses=await Promise.all([call(base+'/conversation',owner,'POST',question),call(base+'/conversation',owner,'POST',question)]);
 assert.deepEqual(responses.map(x=>x.status).sort(),[200,201]);
 await waitUntil(async()=>{const read=await call(base+'/conversation',owner);return read.body.messages?.[0]?.outcome==='answered';},30000,'v5 independent text answer');
 let read=(await call(base+'/conversation',owner)).body;
 assert.equal(read.version,5);assert.equal(read.conversationId,conversationId);assert.equal(read.messages[0].output,'Local synthetic answer: request completed.');
 assert.equal((await call(base+'/conversation',other)).status,403,'other owner without consent sees nothing');
 assert.equal((await call(base+'/consent',other,'POST',{policyId:policy.id,noticeHash:policy.noticeHash})).status,200);
 assert.deepEqual((await call(base+'/conversation',other)).body.messages,[],'consented other owner sees no conversation');
 assert.equal((await call(base+'/conversation',other,'POST',make('goal_start',{goalId:randomUUID(),turnId:null}))).status,403,'other owner cannot append to conversation');
 assert.equal((await call(base+'/conversation',owner,'POST',{...question,text:'Changed'})).status,409);
 assert.equal((await call(base+'/conversation',owner,'POST',{...question,selectedArtifactId:randomUUID()})).status,400,'unknown artifact field closed');
 const goalId=randomUUID();const start=make('goal_start',{text:'Plan a China trip without dates',goalId,turnId:null});
 assert.equal((await call(base+'/conversation',owner,'POST',start)).status,201);
 read=(await call(base+'/conversation',owner)).body;
 assert.equal(read.goals[0].scopeVersion,1);assert.equal(read.messages.length,2);
 const amend=make('amendment',{text:'Prefer rail and fewer transfers',goalId,expectedGoalVersion:1,parentMessageId:start.messageId,turnId:null});
 const conflict=make('amendment',{text:'Prefer buses',goalId,expectedGoalVersion:1,parentMessageId:start.messageId,turnId:null});
 const raced=await Promise.all([call(base+'/conversation',owner,'POST',amend),call(base+'/conversation',owner,'POST',conflict)]);
 assert.deepEqual(raced.map(x=>x.status).sort(),[201,409]);
 const winner=raced[0].status===201?amend:conflict;
 read=(await call(base+'/conversation',owner)).body;
 assert.equal(read.goals[0].scopeVersion,2);assert.deepEqual(read.messages.map(x=>x.sequence),[1,2,3]);
 const follow=make('follow_up',{text:'Please keep this in mind',goalId,expectedGoalVersion:2,parentMessageId:winner.messageId,turnId:null});
 assert.equal((await call(base+'/conversation',owner,'POST',follow)).status,201);
 assert.equal((await call(base+'/conversation',owner,'POST',{...follow,expectedGoalVersion:1,messageId:randomUUID(),idempotencyKey:randomUUID()})).status,409);
 assert.equal((await call(base+'/conversation',owner,'POST',{...follow,taskId:randomUUID(),messageId:randomUUID(),idempotencyKey:randomUUID()})).status,409,'unowned task rejected');
 assert.equal(e.sql(`select count(*) from public.model_budget_attempts where scope_id='${e.users[0].scopeId}';`),'1','goal edits did not enqueue or settle another attempt');
 const taskIds=[],links=[];
 for(let index=0;index<2;index++){
  const taskId=randomUUID(),taskTurn=randomUUID();taskIds.push(taskId);
  const task={threadId:randomUUID(),turnId:taskTurn,idempotencyKey:randomUUID(),policyId:policy.id,locale:'en',text:'Synthetic related task '+index,serviceTask:{id:taskId,scopeVersion:1,relationship:'new_goal',parentTurnId:null}};
  assert.equal((await call('/api/chat/native/v2/turns',owner,'POST',task)).status,201,'existing task explicitly admitted');
  const link=make('follow_up',{text:'Attach accepted task '+index,goalId,expectedGoalVersion:2,parentMessageId:follow.messageId,taskId,turnId:null});
  assert.equal((await call(base+'/conversation',owner,'POST',link)).status,201,'goal references existing task');
  links.push(link);
 }
 read=(await call(base+'/conversation',owner)).body;
 assert.deepEqual(read.messages.filter(x=>x.taskId).map(x=>x.taskId),taskIds);
 const artifactId=randomUUID(),publicationKey=randomUUID();
 const content={schemaVersion:'comparison/1',title:'Synthetic directions',summary:'Fixture only; no travel recommendation.',options:[
  {id:'one',title:'Synthetic A',tradeoff:'Unknown travel time.'},{id:'two',title:'Synthetic B',tradeoff:'Unknown availability.'}],actions:[]};
 const publish=(expected=0,key=publicationKey,body=content)=>{
  const literal=JSON.stringify(body).replaceAll("'","''");
  return e.sql(`set request.jwt.claim.role='service_role';select public.publish_comparison_result_v1('${e.users[0].id}','${artifactId}',${expected},'${key}','${taskIds[0]}','${goalId}','${links[0].messageId}',null,null,2,'[]'::jsonb,'${literal}'::jsonb);`);
 };
 const published=JSON.parse(publish());assert.deepEqual({kind:published.kind,artifactId:published.artifactId,revision:published.revision,reused:published.reused},
  {kind:'published',artifactId,revision:1,reused:false});
 assert.equal(JSON.parse(publish()).reused,true,'idempotent publication returns the same immutable revision');
 assert.throws(()=>publish(0,randomUUID()),/REVISION_CONFLICT/,'CAS prevents a second revision one');
 assert.throws(()=>publish(1,randomUUID(),{...content,actions:[{kind:'open_url',url:'https://example.test'}]}),/INVALID_INPUT/,'action URL is rejected at storage');
 const resultPath='/api/results/native/v1?artifactId='+artifactId+'&revision=1';
 const saved=await call(resultPath,owner);assert.equal(saved.status,200,JSON.stringify(saved.body));
 assert.equal(saved.body.data.artifactId,artifactId);assert.equal(saved.body.data.revision,1);assert.equal(saved.body.data.current,true);
 assert.equal(saved.body.data.source.inputMessageId,links[0].messageId);
 const second=JSON.parse(publish(1,randomUUID(),{...content,summary:'Synthetic revision two; still no travel recommendation.'}));
 assert.equal(second.revision,2);
 const currentPath='/api/results/native/v1?artifactId='+artifactId+'&revision=2';
 assert.equal((await call(currentPath,owner)).body.data.current,true);
 assert.equal((await call(resultPath,owner)).body.data.current,false,'older immutable revision cannot remain current');
 assert.throws(()=>e.sql(`update turn_private.result_revisions set content='{}'::jsonb where artifact_id='${artifactId}' and revision=1;`),/IMMUTABLE_RESULT_REVISION/);
 const serviceKey=identityLocalEnv()?.SERVICE_ROLE_KEY;assert.ok(serviceKey);
 const raceId=randomUUID();
 const raceParams=(key)=>({p_owner_id:e.users[0].id,p_artifact_id:raceId,p_expected_revision:0,p_idempotency_key:key,
   p_task_id:taskIds[0],p_goal_id:goalId,p_input_message_id:links[0].messageId,p_trip_id:null,p_trip_version:null,
   p_goal_version:2,p_memory_basis:[],p_content:content});
 const raceCall=async(key)=>{const response=await fetch(identityLocalEnv().API_URL+'/rest/v1/rpc/publish_comparison_result_v1',{
   method:'POST',headers:{apikey:serviceKey,Authorization:'Bearer '+serviceKey,'Content-Type':'application/json'},body:JSON.stringify(raceParams(key))});
   return response.status;};
 assert.deepEqual((await Promise.all([raceCall(randomUUID()),raceCall(randomUUID())])).sort(),[200,409],'concurrent distinct keys get one CAS winner');
 assert.equal(e.sql(`select count(*) from turn_private.result_revisions where artifact_id='${raceId}';`),'1');
 assert.equal((await call(resultPath,other)).body.data.kind,'empty','other owner cannot read the result');
 assert.equal((await call('/api/results/native/v1?artifactId='+artifactId+'&revision=3',owner)).body.data.kind,'empty');
 const revised=make('amendment',{text:'Change synthetic planning basis',goalId,expectedGoalVersion:2,parentMessageId:links[1].messageId,turnId:null});
 assert.equal((await call(base+'/conversation',owner,'POST',revised)).status,201);
 const stale=await call(currentPath,owner);assert.equal(stale.body.data.current,false,'goal CAS makes prior basis stale');
 assert.equal(stale.body.data.historicalReadable,true,'authorized history remains readable');
 assert.equal(e.sql(`select count(*) from turn_private.result_events where artifact_id='${artifactId}' and event_type='ready';`),'1','result and ready outbox were committed together');
 assert.equal((await call('/api/results/native/v1?artifactId=bad',owner)).status,400);
 const currentLink=make('follow_up',{text:'Attach task under current scope',goalId,expectedGoalVersion:3,parentMessageId:revised.messageId,taskId:taskIds[0],turnId:null});
 assert.equal((await call(base+'/conversation',owner,'POST',currentLink)).status,201);
 const memoryId=randomUUID(),memoryConsent=randomUUID(),memoryReceipt=randomUUID();
 e.sql(`begin;set constraints all deferred;
   insert into public.memory_consents(id,owner_id,status) values('${memoryConsent}','${e.users[0].id}','granted');
   insert into public.memory_profiles(id,owner_id,source_receipt_id,consent_id,state,constraint_kind,summary)
     values('${memoryId}','${e.users[0].id}','${memoryReceipt}','${memoryConsent}','explicit','preference','Synthetic pace');
   insert into public.memory_receipts(id,owner_id,memory_id,event_state,source_kind)
     values('${memoryReceipt}','${e.users[0].id}','${memoryId}','explicit','system');commit;`);
 const dependentId=randomUUID(),dependentKey=randomUUID(),tripId=randomUUID();
 e.sql(`insert into public.trips(id,owner_id,title) values('${tripId}','${e.users[0].id}','Synthetic trip');`);
 const dependentPath='/api/results/native/v1?artifactId='+dependentId+'&revision=1';
 const dependentContent=JSON.stringify(content).replaceAll("'","''");
 const basis=JSON.stringify([{id:memoryId,revision:1}]).replaceAll("'","''");
 const dependentPublish=e.sql(`set request.jwt.claim.role='service_role';select public.publish_comparison_result_v1('${e.users[0].id}','${dependentId}',0,'${dependentKey}',
   '${taskIds[0]}','${goalId}','${currentLink.messageId}','${tripId}',0,3,'${basis}'::jsonb,'${dependentContent}'::jsonb);`);
 assert.equal(JSON.parse(dependentPublish).revision,1);
 assert.equal((await call(dependentPath,owner)).body.data.current,true);
 const tripOnlyId=randomUUID(),tripOnlyPath='/api/results/native/v1?artifactId='+tripOnlyId+'&revision=1';
 assert.equal(JSON.parse(e.sql(`set request.jwt.claim.role='service_role';select public.publish_comparison_result_v1('${e.users[0].id}','${tripOnlyId}',0,'${randomUUID()}',
   '${taskIds[0]}','${goalId}','${currentLink.messageId}','${tripId}',0,3,'[]'::jsonb,'${dependentContent}'::jsonb);`)).revision,1);
 assert.equal((await call(tripOnlyPath,owner)).body.data.current,true);
 e.sql(`update public.memory_profiles set summary='Changed synthetic pace' where id='${memoryId}';`);
 assert.equal((await call(dependentPath,owner)).body.data.current,false,'memory revision invalidates currentness');
 assert.equal((await call(dependentPath,owner)).body.data.historicalReadable,true);
 assert.equal((await call(tripOnlyPath,owner)).body.data.current,true,'unrelated memory correction leaves independent result current');
 e.sql(`update public.trips set head_version=1 where id='${tripId}';`);
 assert.equal((await call(tripOnlyPath,owner)).body.data.current,false,'new Trip base invalidates relevant result');
 e.sql(`update public.memory_profiles set state='deleted',summary=null where id='${memoryId}';`);
 assert.equal((await call(dependentPath,owner)).body.data.kind,'unavailable','deleted memory cannot be recovered from result content');
 e.sql(`delete from public.trips where id='${tripId}';`);
 assert.equal(e.sql(`select count(*) from turn_private.result_artifacts where id='${dependentId}';`),'0','Trip deletion cascades result and index');
 assert.equal(e.sql(`select count(*) from turn_private.result_artifacts where id='${tripOnlyId}';`),'0');
 const withdraw=()=>JSON.parse(e.sql(`set request.jwt.claim.role='service_role';select public.withdraw_result_artifact_v1('${e.users[0].id}','${artifactId}',2);`));
 assert.equal(withdraw().reused,false);
 assert.equal(withdraw().reused,true,'withdrawal replay has one durable event');
 assert.equal((await call(resultPath,owner)).body.data.kind,'unavailable','withdrawn content is hidden');
 assert.equal(e.sql(`select count(*) from turn_private.result_events where artifact_id='${artifactId}' and event_type='withdrawn';`),'1');
 const otherGoalId=randomUUID(),otherStart=make('goal_start',{text:'A separate goal',goalId:otherGoalId,turnId:null});
 assert.equal((await call(base+'/conversation',owner,'POST',otherStart)).status,201);
 assert.equal((await call(base+'/conversation',owner,'POST',make('follow_up',{text:'Do not reassign the first task',goalId:otherGoalId,expectedGoalVersion:1,parentMessageId:otherStart.messageId,taskId:taskIds[0],turnId:null}))).status,409);
 await login(e.users[0]);assert.equal((await call(base+'/conversation',owner)).status,401,'replaced session cannot read');
 assert.equal((await call(resultPath,owner)).status,401,'replaced session cannot read result');
 const replacement=await login(e.users[0]);
 assert.equal((await call(base+'/conversation',replacement)).body.messages.length,9,'new session reads durable conversation');
 assert.equal((await call(base+'/consent',replacement,'DELETE',{policyId:policy.id})).status,200);
 assert.equal((await call(base+'/conversation',replacement)).status,403,'withdrawal hides transcript');
 assert.equal((await call(resultPath,replacement)).body.data.kind,'unavailable','withdrawal hides result content');
 assert.equal((await call(base+'/conversation',replacement,'POST',make('independent_question'))).status,403,'withdrawal denies new work');
});
