import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createNativeTextEnvironment} from './native-text-environment.mjs';
import {waitUntil} from '../identity/database-barrier.mjs';
import {createServerClient} from '@supabase/ssr';
import {identityLocalEnv} from '../identity/local-supabase.mjs';

test('grounded native HTTP preserves scope, consent, current-input egress and revalidated durable results',{skip:process.env.VP_NATIVE_GROUNDED_INTEGRATION!=='true',timeout:180000},async t=>{
 const e=await createNativeTextEnvironment({grounded:true});t.after(()=>e.cleanup());
 const call=async(path,token,method='GET',body)=>{
  const r=await fetch(e.api+path,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});
  return {status:r.status,body:await r.json()};
 };
 const login=async user=>{const attemptId=randomUUID();const r=await call('/api/auth/native/v2/credentials',null,'POST',{email:user.email,password:user.password,attemptId});assert.equal(r.status,200);assert.equal((await call('/api/auth/native/v2/login',r.body.accessToken,'POST',{attemptId})).status,200);return r.body.accessToken;};
 const token=await login(e.users[0]),other=await login(e.users[1]),base='/api/chat/native/v4';
 const local=identityLocalEnv();
 const browserLogin=async user=>{
  const jar=new Map();
  const client=createServerClient(local.API_URL,local.PUBLISHABLE_KEY||local.ANON_KEY,{cookies:{getAll:()=>[...jar].map(([name,value])=>({name,value})),setAll:values=>values.forEach(({name,value})=>jar.set(name,value))}});
  assert.equal((await client.auth.signInWithPassword({email:user.email,password:user.password})).error,null);
  return {client,cookie:()=>[...jar].map(([name,value])=>name+'='+value).join('; ')};
 };
 const browser=await browserLogin(e.users[0]),foreignBrowser=await browserLogin(e.users[1]);
 const web=async(cookie=browser.cookie(),suffix='',headers={})=>{const r=await fetch(e.api+'/api/chat/grounded'+suffix,{headers:{...(cookie?{cookie}:{}),...headers}});return {status:r.status,body:await r.json()};};
 assert.equal((await web('')).status,401);
 assert.equal((await web()).status,503,'read cannot accept consent');
 assert.equal((await web(browser.cookie(),'?policyId='+e.groundedPolicyId)).status,400);
 assert.equal((await web(browser.cookie(),'',{Authorization:'Bearer '+token})).status,400);
 assert.equal((await web(browser.cookie(),'',{Origin:'https://foreign.example'})).status,400);
 assert.equal((await call(base+'/policy')).status,401);
 const policy=await call(base+'/policy',token);assert.equal(policy.status,200);assert.equal(policy.body.version,4);assert.equal(policy.body.policy.id,e.groundedPolicyId);
 const input={threadId:randomUUID(),turnId:randomUUID(),idempotencyKey:randomUUID(),policyId:e.groundedPolicyId,locale:'en',city:'shanghai',text:'Synthetic adult passport boarding document question',serviceTask:{id:randomUUID(),scopeVersion:1,relationship:'new_goal',parentTurnId:null}};
 const submit=body=>call(base+'/turns',token,'POST',body);
 assert.equal((await submit(input)).status,403);
 assert.equal((await call(base+'/consent',token,'POST',{policyId:e.groundedPolicyId,noticeHash:e.taskNoticeHash})).status,403);
 assert.equal((await call(base+'/consent',token,'POST',{policyId:e.groundedPolicyId,noticeHash:e.groundedNoticeHash})).status,200);
 assert.equal((await submit({...input,city:'paris'})).status,400);
 assert.equal((await submit({...input,facts:[]})).status,400);
 assert.deepEqual((await Promise.all([submit(input),submit(input)])).map(r=>r.status).sort(),[200,201]);
 const eventsURL=id=>e.api+base+'/turns/'+id+'/events';
 const events=async(id,cursor=0,bearer=token,headers={})=>fetch(eventsURL(id),{headers:{Authorization:'Bearer '+bearer,'Last-Event-ID':String(cursor),...headers}});
 const decode=text=>text.trim().split('\n\n').filter(Boolean).map(block=>({name:/^event: (.+)$/m.exec(block)?.[1],id:/^id: (.+)$/m.exec(block)?.[1],data:JSON.parse(/^data: (.+)$/m.exec(block)[1])}));
 const read=async()=>{const r=await call(base+'/turns',token);assert.equal(r.status,200);assert.equal(r.body.version,4);assert.equal(r.body.kind,'grounded_history');return r.body.turns;};
 const waitTurn=async(id,outcome)=>{await waitUntil(async()=> (await read()).some(x=>x.turnId===id&&x.outcome===outcome),30000,'grounded durable completion');return (await read()).find(x=>x.turnId===id);};
 const final=await waitTurn(input.turnId,'answered');
 const completed=await events(input.turnId);assert.equal(completed.status,200);assert.match(completed.headers.get('content-type'),/text\/event-stream/);
 const completedFrames=decode(await completed.text()),terminal=completedFrames.find(f=>f.data.type==='terminal');
 assert.equal(terminal.data.turn.turnId,input.turnId);assert.equal(terminal.data.turn.serviceTaskId,input.serviceTask.id);assert.equal(terminal.data.turn.result.knowledge.statements.length,2);
 const resumed=decode(await (await events(input.turnId,terminal.id)).text());assert.equal(resumed.length,1);assert.equal(resumed[0].name,'projection');assert.equal(resumed[0].id,undefined);
 assert.equal((await events(input.turnId,Number(terminal.id)+1)).status,400);
 assert.equal((await events(input.turnId,'01')).status,400);
 assert.equal((await events(input.turnId,0,token,{cookie:'invalid=1'})).status,400);
 assert.equal((await events(input.turnId,0,token,{origin:e.api})).status,400);
 assert.equal((await events(input.turnId,0,other)).status,403);
 const browserRead=await web();assert.equal(browserRead.status,200);assert.equal(browserRead.body.data.ownerId,e.users[0].id);
 const saved=browserRead.body.data.turns.find(turn=>turn.id===input.turnId);
 assert.equal(saved.taskId,input.serviceTask.id);assert.equal(saved.facts.length,2);assert.equal(saved.city,'shanghai');
 assert.ok(browserRead.body.data.lifetimeMs>0&&browserRead.body.data.lifetimeMs<=30000);
 assert.ok(!JSON.stringify(browserRead.body).includes('_basis'));
 assert.equal((await web(foreignBrowser.cookie())).status,503,'other owner has no accepted consent');
 assert.equal((await call(base+'/consent',other,'POST',{policyId:e.groundedPolicyId,noticeHash:e.groundedNoticeHash})).status,200);
 const foreignRead=await web(foreignBrowser.cookie());assert.equal(foreignRead.status,200);assert.deepEqual(foreignRead.body.data.turns,[],'accepted foreign owner cannot see original owner');
 assert.equal(final.output,'reviewed-answer-v1');assert.equal(final.result.city,'shanghai');assert.equal(final.result.knowledge.statements.length,2);
 assert.equal(e.counts.http,1);assert.equal(e.requests[0].messages.length,2);assert.equal(e.requests[0].messages[1].content,input.text);
 assert.ok(!JSON.stringify(e.requests).includes('PRIVATE SOURCE NEVER SENT'));assert.ok(!JSON.stringify(e.requests).includes('Synthetic reviewed'));
 assert.equal(e.sql(`select status||':'||actual_micros from public.model_budget_attempts where task_id='${input.serviceTask.id}';`),'settled:1');
 assert.equal((await submit(input)).status,200);assert.equal((await submit({...input,city:'beijing'})).status,409);
 assert.equal((await call(base+'/turns',other)).body.turns.length,0);
 const compound={...input,threadId:randomUUID(),turnId:randomUUID(),idempotencyKey:randomUUID(),text:'Synthetic passport question extra-needs',serviceTask:{...input.serviceTask,id:randomUUID()}};
 assert.equal((await submit(compound)).status,201);assert.equal((await waitTurn(compound.turnId,'partial')).result.requestScope,'additional_needs');
 const vague={...compound,threadId:randomUUID(),turnId:randomUUID(),idempotencyKey:randomUUID(),text:'Synthetic kind=clarification',serviceTask:{...compound.serviceTask,id:randomUUID()}};
 assert.equal((await submit(vague)).status,201);await waitTurn(vague.turnId,'clarification');
 const next={...vague,turnId:randomUUID(),idempotencyKey:randomUUID(),text:'Synthetic restated adult passport question',serviceTask:{...vague.serviceTask,relationship:'clarification',parentTurnId:vague.turnId}};
 assert.equal((await submit(next)).status,201);await waitTurn(next.turnId,'answered');
 const dispatched=e.requests.find(r=>r.messages.at(-1).content===next.text);assert.equal(dispatched.messages.length,2,'prior turns and evidence never enter classifier');
 // A held synthetic model creates an actual in-flight HTTP stream. Interrupt
 // after its first frame, reconnect with that cursor, then release completion.
 const held={...input,threadId:randomUUID(),turnId:randomUUID(),idempotencyKey:randomUUID(),text:'Synthetic HOLD adult passport question',serviceTask:{...input.serviceTask,id:randomUUID()}};
 assert.equal((await submit(held)).status,201);
 await waitUntil(async()=>e.requests.some(r=>r.messages.at(-1).content===held.text),10000,'held provider request');
 const firstStream=await events(held.turnId),reader=firstStream.body.getReader();
 const chunk=await reader.read();assert.equal(chunk.done,false);const firstFrames=decode(new TextDecoder().decode(chunk.value));
 const acknowledged=firstFrames.filter(f=>f.id).at(-1);assert.ok(acknowledged);assert.equal(acknowledged.data.type,'accepted');
 await reader.cancel();
 const reconnect=await events(held.turnId,acknowledged.id);
 e.releaseModels();
 const recovered=decode(await reconnect.text()),end=recovered.find(f=>f.data.type==='terminal');
 assert.ok(end,'terminal arrives on the same open connection');assert.equal(end.data.turn.serviceTaskId,held.serviceTask.id);
 assert.ok(recovered.filter(f=>f.id).every(f=>Number(f.id)>Number(acknowledged.id)));
 assert.equal(e.requests.filter(r=>r.messages.at(-1).content===held.text).length,1);
 assert.equal(e.sql(`select count(*) from public.model_budget_attempts where task_id='${held.serviceTask.id}';`),'1');
 const cancelled={...input,threadId:randomUUID(),turnId:randomUUID(),idempotencyKey:randomUUID(),text:'Synthetic HOLD cancellation after worker dispatch',serviceTask:{...input.serviceTask,id:randomUUID()}};
 assert.equal((await submit(cancelled)).status,201);
 await waitUntil(async()=>e.requests.some(r=>r.messages.at(-1).content===cancelled.text),10000,'cancellation provider boundary');
 const cancelPath='/api/chat/native/v1/turns/'+cancelled.turnId+'/cancel';
 assert.equal((await call(cancelPath,null,'POST',{})).status,401,'cancellation does not require legacy generation mode');
 assert.equal((await call(cancelPath,other,'POST',{})).status,403,'foreign owner cannot cancel');
 assert.equal((await call(cancelPath,token,'POST',{policyId:e.groundedPolicyId})).status,400);
 assert.equal((await call(cancelPath+'?policyId='+e.groundedPolicyId,token,'POST',{})).status,400);
 for(const headers of [{cookie:'invalid=1'},{origin:e.api}])assert.equal((await fetch(e.api+cancelPath,{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...headers},body:'{}'})).status,400);
 e.sql('update knowledge_review_private.publication_settings set enabled=false;');
 assert.equal((await call(cancelPath,token,'POST',{})).status,200,'owner can cancel while source reading is disabled');
 assert.equal((await call(cancelPath,token,'POST',{})).status,200,'exact cancel repeat remains idempotent');
 e.releaseModels();
 await waitUntil(()=>e.sql(`select status from public.turns where id='${cancelled.turnId}';`)==='cancelled',5000,'cancelled original Turn');
 assert.equal(e.sql(`select count(*) from public.chat_turn_events where turn_id='${cancelled.turnId}' and event_type='terminal';`),'1');
 assert.equal(e.sql(`select count(*) from public.model_budget_attempts where task_id='${cancelled.serviceTask.id}';`),'1');
 assert.equal((await call('/api/chat/native/v1/turns/'+input.turnId+'/cancel',token,'POST',{})).status,503,'completed answer is never converted into cancellation');

 const hidden=(await read()).find(x=>x.turnId===input.turnId);assert.equal(hidden.result.projection,'unavailable');assert.equal(hidden.result.knowledge,null);assert.equal(hidden.outcome,'answered');
 const webHidden=(await web()).body.data.turns.find(turn=>turn.id===input.turnId);assert.deepEqual(webHidden.facts,[]);assert.equal(webHidden.projection,'unavailable');
 const hiddenReplay=decode(await (await events(input.turnId,terminal.id)).text());assert.equal(hiddenReplay[0].data.turn.result.knowledge,null);
 assert.equal((await call(base+'/consent',token,'DELETE',{policyId:e.groundedPolicyId})).status,200);assert.deepEqual(await read(),[]);
 assert.equal((await events(input.turnId,terminal.id)).status,403);
 assert.equal((await web()).status,503,'withdrawn consent hides browser read');
 assert.equal((await call('/api/auth/native/v2/logout',token,'POST',{})).status,200);
 assert.equal((await call(cancelPath,token,'POST',{})).status,401,'logged-out native session cannot replay cancellation');
 const oldCookie=browser.cookie();await browser.client.auth.signOut();assert.equal((await web(oldCookie)).status,401,'deleted session cannot reuse its cookie');
 assert.equal(e.counts.http,6,'replay and history do not dispatch or charge');
});
