// Real ordinary Auth -> HTTP -> current migrated disposable SQL. No provider execution.
import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID as uuid} from 'node:crypto';
import {NextRequest} from 'next/server.js';
import {nativePlanningIntakeHTTP} from '../../../lib/server/turn/native-planning-intake-http.ts';
import {createNativeTextEnvironment} from './native-text-environment.mjs';
import {identityLocalEnv} from '../identity/local-supabase.mjs';
const intake={schemaVersion:'stay-area-intake/1',city:'shanghai',comparisonTarget:'area_transport',durationDays:10,partySize:2,interests:['food','photography'],pace:'relaxed',lodgingBudget:null,dates:null,mobilityConstraints:null};
test('v2 local transport preserves atomic admission, current receipt and revoked boundaries',{skip:process.env.VP_PLANNING_INTAKE_HTTP!=='true',timeout:240000},async t=>{
 const local=identityLocalEnv(),project=process.env.VP_NATIVE_INTAKE_PLANNING_HTTP_PROJECT;
 assert.match(project,/^vp-native-ask-[a-f0-9]{8}$/);assert.equal(local.DB_CONTAINER,'supabase_db_'+project);assert.equal(local.API_URL,process.env.VP_IDENTITY_SUPABASE_API_URL);
 const e=await createNativeTextEnvironment();t.after(()=>e.cleanup());assert.equal(e.api,process.env.VP_NATIVE_INTAKE_PLANNING_HTTP_API);
 const base='/api/chat/native/v5',endpoint=base+'/planning/intake-tasks';
 const call=async(path,token,method='GET',body)=>{const r=await fetch(e.api+path,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});assert.match(r.headers.get('content-type')??'',/application\/json/);return {status:r.status,body:await r.json()};};
 const login=async user=>{const attemptId=uuid(),r=await call('/api/auth/native/v2/credentials',null,'POST',{email:user.email,password:user.password,attemptId});assert.equal(r.status,200);assert.equal((await call('/api/auth/native/v2/login',r.body.accessToken,'POST',{attemptId})).status,200);return r.body.accessToken;};
 let owner=await login(e.users[0]);const other=await login(e.users[1]),planningPolicyId=uuid(),noticeHash='a'.repeat(64);
 const textConsent=()=>call(base+'/consent',owner,'POST',{policyId:e.policyId,noticeHash:e.noticeHash});assert.equal((await textConsent()).status,200);
 e.sql(`insert into turn_private.planning_policies(id,text_policy_id,environment,notice_version,notice_hash,notice_zh,notice_en,effective_at,expires_at) values('${planningPolicyId}','${e.policyId}','local_synthetic','test','${noticeHash}','合成','Synthetic',now()-interval '1 minute',now()+interval '1 day');`);
 const planningConsent=()=>call(base+'/planning/policy',owner,'POST',{policyId:planningPolicyId,noticeHash});assert.equal((await planningConsent()).status,201);
 const write=body=>call(endpoint,owner,'POST',body);
 const seed=async()=>{const conversationId=uuid(),goalId=uuid(),messageId=uuid();const r=await call(base+'/travel-intake',owner,'POST',{conversationId,goalId,messageId,idempotencyKey:uuid(),policyId:e.policyId,locale:'en',text:'Explicit Shanghai stay-area comparison',relationship:'goal_start',parentMessageId:null,expectedGoalVersion:null,expectedIntakeRevision:0,intake,memoryBasis:[]});assert.equal(r.status,201,JSON.stringify(r));
  return {conversationId,goalId,expectedGoalVersion:1,parentMessageId:messageId,messageId:uuid(),messageKey:uuid(),threadId:uuid(),turnId:uuid(),taskId:uuid(),taskKey:uuid(),planningPolicyId,locale:'en',text:'Compare explicit Shanghai stay areas',memoryBasis:[],expectedIntakeMessageId:messageId,expectedSourceSequence:r.body.messageSequence,expectedIntakeRevision:1,expectedIntakeDigest:r.body.contextDigest,intake};};
 const state=()=>e.sql(`select jsonb_build_array((select count(*) from turn_private.service_tasks where owner_id='${e.users[0].id}'),(select count(*) from turn_private.assistant_messages where owner_id='${e.users[0].id}'),(select count(*) from turn_private.assistant_travel_intakes where owner_id='${e.users[0].id}'));`);
 const b=await seed();const before=state();
 for(const patch of [{expectedIntakeDigest:'d'.repeat(64)},{expectedSourceSequence:b.expectedSourceSequence+1},{expectedIntakeRevision:2},{expectedGoalVersion:2},{intake:{...intake,pace:'fast'}},{memoryBasis:[{id:uuid(),revision:1}]}]){const r=await write({...b,...patch});assert.equal(r.status,409,JSON.stringify(r));assert.equal(state(),before,'failed transport admission rolls back all writes');}
 assert.equal((await call(endpoint,other,'POST',b)).status,403);assert.equal((await call(endpoint,null,'POST',b)).status,401);assert.equal((await write({...b,ownerId:uuid()})).status,400);
 const accepted=await write(b);assert.equal(accepted.status,201,JSON.stringify(accepted));assert.equal(accepted.body.current,true);assert.equal(accepted.body.executionAvailable,false);assert.equal(accepted.body.readyForProvider,false);assert.notEqual(accepted.body.intakeContextDigest,b.expectedIntakeDigest);assert.notEqual(accepted.body.planningContextDigest,accepted.body.intakeContextDigest);
 const after=state(),reused=await write(b);assert.equal(reused.status,200);assert.equal(reused.body.reused,true);assert.equal(reused.body.artifactId,accepted.body.artifactId);assert.equal(state(),after);
 assert.equal((await write({...b,text:'Changed immutable text'})).status,409);assert.equal((await write({...b,taskId:uuid(),taskKey:uuid()})).status,409,'new Task cannot borrow original Turn/message scope');assert.equal(state(),after);
 assert.equal(e.sql(`select execution_mode from turn_private.work where turn_id='${b.turnId}';`),'planning_intake_comparison_v2');
 const amend=async body=>{const source=(await call(base+'/travel-intake?conversationId='+body.conversationId+'&goalId='+body.goalId,owner)).body;const r=await call(base+'/travel-intake',owner,'POST',{conversationId:body.conversationId,goalId:body.goalId,messageId:uuid(),idempotencyKey:uuid(),policyId:e.policyId,locale:'en',text:'Explicit later correction',relationship:'amendment',parentMessageId:source.messageId,expectedGoalVersion:source.goalVersion,expectedIntakeRevision:source.intakeRevision,intake:{...intake,pace:'balanced'},memoryBasis:[]});assert.equal(r.status,201,JSON.stringify(r));};
 await amend(b);const historical=await write(b);assert.equal(historical.status,200);assert.equal(historical.body.current,false);assert.equal(historical.body.artifactId,accepted.body.artifactId);for(const k of ['intakeContextDigest','planningContextDigest','contextDigest','intake','memoryBasis'])assert.equal(Object.hasOwn(historical.body,k),false);
 // Actual first admission response is held while ordinary HTTP correction/withdrawal completes.
 const patch={NEXT_PUBLIC_SUPABASE_URL:local.API_URL,NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:local.PUBLISHABLE_KEY||local.ANON_KEY,VISEPANDA_NATIVE_LOCAL_TEXT:'true',VISEPANDA_NATIVE_LOCAL_TEXT_POLICY:e.policyId,VISEPANDA_NATIVE_LOCAL_ASSISTANT_CONVERSATION:'true'};
 const prior=new Map(Object.keys(patch).map(k=>[k,process.env[k]]));Object.assign(process.env,patch);t.after(()=>{for(const[k,v]of prior)v===undefined?delete process.env[k]:process.env[k]=v;});
 const boundary=async(body,change)=>{let admissions=0;const original=globalThis.fetch,mock=t.mock.method(globalThis,'fetch',async(input,init)=>{const r=new Request(input,init),response=await original(input,init);if(new URL(r.url).pathname.endsWith('/submit_planning_comparison_v2')){admissions++;await change();}return response;});
  try{const r=await nativePlanningIntakeHTTP(new NextRequest(e.api+endpoint,{method:'POST',headers:{Authorization:'Bearer '+owner,'Content-Type':'application/json'},body:JSON.stringify(body)}));assert.equal(admissions,1);return {status:r.status,body:await r.json()};}finally{mock.mock.restore();}};
 const changed=await seed(),changedResult=await boundary(changed,()=>amend(changed));assert.equal(changedResult.status,201);assert.equal(changedResult.body.current,false);assert.equal(Object.hasOwn(changedResult.body,'intakeContextDigest'),false);assert.equal(Object.hasOwn(changedResult.body,'planningContextDigest'),false);
 const replaced=await seed(),oldOwner=owner;owner=await login(e.users[0]);assert.equal((await call(endpoint,oldOwner,'POST',replaced)).status,401);
 const revoked=await seed(),revokedResult=await boundary(revoked,async()=>assert.equal((await call(base+'/planning/policy',owner,'DELETE',{policyId:planningPolicyId})).status,200));assert.equal(revokedResult.status,403);assert.deepEqual(revokedResult.body,{error:{code:'DATA_POLICY_BLOCKED'}});assert.equal((await planningConsent()).status,403,'ordinary withdrawal is terminal for this policy');assert.equal((await write(revoked)).status,403);
 // Independent ordinary actor keeps terminal withdrawn consent intact.
 owner=other;assert.equal((await textConsent()).status,200);assert.equal((await planningConsent()).status,201);
 const textRevoked=await seed(),textResult=await boundary(textRevoked,async()=>assert.equal((await call(base+'/consent',owner,'DELETE',{policyId:e.policyId})).status,200));assert.equal(textResult.status,403);assert.equal((await write(textRevoked)).status,403);
 assert.equal(e.counts.http,0,'no synthetic or external provider execution');assert.equal(e.sql(`select count(*) from public.model_budget_attempts where task_id in(select id from turn_private.service_tasks where owner_id='${e.users[0].id}');`),'0');assert.equal(e.sql(`select count(*) from public.trips where owner_id='${e.users[0].id}';`),'0');
 t.diagnostic('PLANNING_INTAKE_AUTH_HTTP_SQL_PASS: current migrations, one RPC admission, false execution flags, zero provider/cost/Trip writes');
});
