import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID as uuid} from 'node:crypto';import {createClient} from '@supabase/supabase-js';
import {createNativeTextEnvironment} from './native-text-environment.mjs';import {identityLocalEnv} from '../identity/local-supabase.mjs';
test('actual native Auth → v6 ordinary message/reference → first-party context persists and rejects actor/CAS/late scope',{skip:process.env.VP_SELECTED_SOURCE_HTTP!=='true',timeout:180000},async t=>{
 const e=await createNativeTextEnvironment();t.after(()=>e.cleanup());const call=async(path,token,method='GET',body)=>{const r=await fetch(e.api+path,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});assert.match(r.headers.get('content-type')??'',/application\/json/);return {status:r.status,body:await r.json()};};
 const login=async u=>{const attemptId=uuid(),r=await call('/api/auth/native/v2/credentials',null,'POST',{email:u.email,password:u.password,attemptId});assert.equal(r.status,200);assert.equal((await call('/api/auth/native/v2/login',r.body.accessToken,'POST',{attemptId})).status,200);return r.body.accessToken;};
 const owner=await login(e.users[0]),other=await login(e.users[1]),v5='/api/chat/native/v5',v6='/api/chat/native/v6';for(const token of [owner,other])assert.equal((await call(v5+'/consent',token,'POST',{policyId:e.policyId,noticeHash:e.noticeHash})).status,200);
 const state=identityLocalEnv(),client=createClient(state.API_URL,state.PUBLISHABLE_KEY||state.ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:'Bearer '+owner}}});const trip=uuid();assert.ifError((await client.from('trips').insert({id:trip,owner_id:e.users[0].id,title:'上海之旅'})).error);
 const root={schemaVersion:'assistant-message-sources/2',conversationId:uuid(),messageId:uuid(),idempotencyKey:uuid(),policyId:e.policyId,locale:'en',text:'A continuing goal without fixed dates',relationship:'goal_start',goalId:uuid(),expectedGoalVersion:null,taskId:null,parentMessageId:null,turnId:null,selectedSources:{artifact:null,trip:null,evidence:[]}};
 let r=await call(v6+'/conversation',owner,'POST',root);assert.equal(r.status,201,JSON.stringify(r));assert.equal(Object.keys(r.body).length,11);assert.equal(r.body.readyForProvider,false);assert.equal((await call(v6+'/conversation',owner,'POST',root)).status,200);
 const follow={...root,messageId:uuid(),idempotencyKey:uuid(),relationship:'follow_up',expectedGoalVersion:1,parentMessageId:root.messageId,text:'Continue with this owned Trip reference',selectedSources:{artifact:null,trip:{tripId:trip,headVersion:0},evidence:[]}};r=await call(v6+'/conversation',owner,'POST',follow);assert.equal(r.status,201,JSON.stringify(r));
 const contextBody={conversationId:root.conversationId,goalId:root.goalId,messageId:follow.messageId,expectedGoalVersion:1,memoryIds:[]};r=await call(v6+'/context',owner,'POST',contextBody);assert.equal(r.status,200,JSON.stringify(r));assert.equal(r.body.schemaVersion,'assistant-goal-context/2');assert.equal(r.body.readyForProvider,false);assert.ok(r.body.context.sourceRefs.some(x=>x.id==='trip:'+trip));assert.equal(r.body.context.sourceRefs.some(x=>x.id.startsWith('goal:')),true);
 assert.equal((await call(v6+'/context',other,'POST',contextBody)).status,403);assert.equal((await call(v6+'/conversation',owner,'POST',{...follow,selectedSources:{artifact:null,trip:null,evidence:[]}})).status,409);
 const amend={...follow,messageId:uuid(),idempotencyKey:uuid(),relationship:'amendment',parentMessageId:follow.messageId,text:'Change explicit goal',selectedSources:{artifact:null,trip:null,evidence:[]}};r=await call(v6+'/conversation',owner,'POST',amend);assert.equal(r.status,201);assert.equal(r.body.scopeVersion,2);assert.equal((await call(v6+'/context',owner,'POST',contextBody)).status,409);
 const plain=await call(v5+'/conversation?conversationId='+root.conversationId,owner);assert.equal(plain.status,200);assert.ok(plain.body.messages.some(x=>x.messageId===amend.messageId));
 assert.equal(e.sql(`select count(*) from turn_private.service_tasks where owner_id='${e.users[0].id}';`),'0');assert.equal(e.sql(`select count(*) from turn_private.work where owner_id='${e.users[0].id}';`),'0');assert.equal(e.counts.http,0,'ordinary goal/follow/amend does not dispatch a provider');
 await login(e.users[0]);assert.equal((await call(v6+'/context',owner,'POST',{...contextBody,messageId:amend.messageId,expectedGoalVersion:2})).status,401);
 t.diagnostic('SELECTED_SOURCE_AUTH_HTTP_SQL_PASS: current migrated DB, no Task/new fee/provider/TripPatch; first-party source refs only');
});
