// Explicit network-none preparation only; all dependencies from this current checkout.
import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID as uuid} from 'node:crypto';
import {readFileSync,readdirSync} from 'node:fs';
import {command,sql} from '../cost/fixtures/postgres-rpc.mjs';
const enabled=process.env.VP_TURN_DB_TEST==='1',container='vpj78-selected-src-'+uuid().slice(0,8);
const mine='20261003090000_vpj78_selected_message_sources.sql';
let created=false;
const db=async q=>{const r=await sql(container,q);assert.equal(r.code,0,r.stderr);return r.stdout.trim();};
const lit=v=>v===null?'null':typeof v==='number'||typeof v==='boolean'?String(v):"'"+(typeof v==='object'?JSON.stringify(v):String(v)).replaceAll("'","''")+"'";
const query=(a,name,p)=>`begin;set role authenticated;set request.jwt.claim.role='authenticated';set request.jwt.claim.sub='${a.owner}';set request.jwt.claims='${JSON.stringify({session_id:a.session})}';select public.${name}(`+Object.entries(p).map(([k,v])=>k+'=>'+lit(v)).join(',')+');commit;';
const call=async(a,name,p)=>{const r=await sql(container,query(a,name,p));assert.equal(r.code,0,r.stderr);return JSON.parse(r.stdout.trim());};
const projection={schemaVersion:'stay-area-intake/1',city:'shanghai',comparisonTarget:'area_transport',durationDays:10,partySize:2,interests:['food','photography'],pace:'relaxed',lodgingBudget:null,dates:null,mobilityConstraints:[]};
const notice='a'.repeat(64);
async function owner(environment='local_synthetic',locale='en',goalText='First China visit, ten days with partner, food and photography, relaxed pace.'){
 const a={owner:uuid(),session:uuid(),policy:uuid(),planningPolicy:uuid(),conversation:uuid(),goal:uuid(),source:uuid()};
 await db(`insert into auth.users(id) values('${a.owner}');insert into identity_private.mobile_accounts(owner_id) values('${a.owner}');insert into auth.sessions(id,user_id) values('${a.session}','${a.owner}');
 insert into turn_private.text_policies(id,provider,recipient,endpoint,source_region,processing_region,storage_region,terms_version,notice_version,notice_hash,notice_zh,notice_en,retention,effective_at,expires_at,terms_recheck_at)
 values('${a.policy}','qwen','synthetic only','https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions','fixture','fixture','fixture','test','test','${notice}','合成','Synthetic','retain_after_hide_v1',now()-interval '1 hour',now()+interval '1 day',now()+interval '1 day');
 insert into turn_private.planning_policies(id,text_policy_id,environment,notice_version,notice_hash,notice_zh,notice_en,effective_at,expires_at)
 values('${a.planningPolicy}','${a.policy}','${environment}','test','${notice}','合成','Synthetic',now()-interval '1 hour',now()+interval '1 day');`);
 await call(a,'accept_text_policy',{p_policy_id:a.policy,p_notice_hash:notice});await call(a,'accept_planning_policy_v1',{p_policy_id:a.planningPolicy,p_notice_hash:notice});
 a.input={p_conversation_id:a.conversation,p_goal_id:a.goal,p_message_id:a.source,p_parent_message_id:null,p_expected_goal_version:null,p_expected_intake_revision:0,p_idempotency_key:uuid(),p_policy_id:a.policy,p_locale:locale,p_text:goalText,p_relationship:'goal_start',p_intake:projection,p_memory_basis:[]};
 a.receipt=await call(a,'submit_assistant_travel_intake_v1',a.input);return a;
}
const planning=a=>({p_conversation_id:a.conversation,p_goal_id:a.goal,p_expected_goal_version:1,p_parent_message_id:a.source,p_message_id:uuid(),p_message_key:uuid(),p_thread_id:uuid(),p_turn_id:uuid(),p_task_id:uuid(),p_task_key:uuid(),p_text_policy_id:a.policy,p_planning_policy_id:a.planningPolicy,p_locale:a.input.p_locale,p_text:'Compare Shanghai areas',p_memory_basis:[]});
const correction=a=>({...a.input,p_message_id:uuid(),p_parent_message_id:a.source,p_expected_goal_version:1,p_expected_intake_revision:1,p_idempotency_key:uuid(),p_text:'Explicit full correction to balanced pace',p_relationship:'amendment',p_intake:{...projection,pace:'balanced'}});
const state=a=>db(`select jsonb_build_object('goalVersion',g.scope_version,'text',g.current_text,'sequence',c.next_sequence,'messages',(select count(*) from turn_private.assistant_messages where goal_id=g.id),'intakes',(select count(*) from turn_private.assistant_travel_intakes where goal_id=g.id),'tasks',(select count(*) from turn_private.service_tasks where owner_id=g.owner_id),'work',(select count(*) from turn_private.work where owner_id=g.owner_id),'planning',(select count(*) from turn_private.planning_comparisons where owner_id=g.owner_id),'capacity',(select count(*) from turn_private.service_task_capacity where owner_id=g.owner_id),'attempts',(select count(*) from public.model_budget_attempts b join public.model_budget_scopes s on s.id=b.scope_id where s.owner_id=g.owner_id)) from turn_private.assistant_goals g join turn_private.assistant_conversations c on c.id=g.conversation_id where g.id='${a.goal}';`);
before(async()=>{
 if(!enabled)return;
 const r=await command('docker',['run','--pull=never','--rm','-d','--network','none','--name',container,'--user','postgres','--entrypoint','/bin/sh','public.ecr.aws/supabase/postgres:17.6.1.159','-c','umask 077;mkdir /tmp/vpj59-socket;initdb -D /tmp/vpj59-db -A trust --no-locale -E UTF8 >/tmp/init.log 2>&1 && exec postgres -D /tmp/vpj59-db -c listen_addresses= -c unix_socket_directories=/tmp/vpj59-socket -c unix_socket_permissions=0700']);assert.equal(r.code,0,r.stderr);created=true;
 for(let n=0;n<100;n++){if((await command('docker',['exec',container,'pg_isready','-h','/tmp/vpj59-socket','-U','postgres'])).code===0)break;await new Promise(r=>setTimeout(r,100));}
 await db(readFileSync('tests/integration/turn/fixtures/durable-work-schema.sql','utf8'));await db("create function auth.role() returns text language sql as $$select nullif(current_setting('request.jwt.claim.role',true),'')$$;create schema extensions;create extension pgcrypto with schema extensions;");
 for(const f of readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')&&f!==mine).sort())await db('begin;'+readFileSync('supabase/migrations/'+f,'utf8')+'commit;');
 const migration=readFileSync('supabase/migrations/'+mine,'utf8');await db('begin;'+migration+'rollback;');assert.equal(await db("select to_regclass('turn_private.assistant_message_source_receipts') is null;"),'t');await db('begin;'+migration+'commit;');
});
after(async()=>{if(created)assert.equal((await command('docker',['rm','-f',container])).code,0);});
const run=(name,fn)=>test(name,{skip:!enabled,timeout:120000},fn);
const v2=a=>({...planning(a),p_expected_intake_message_id:a.source,p_expected_source_sequence:1,p_expected_intake_revision:1,p_expected_intake_digest:a.receipt.contextDigest,p_intake:projection});
const bound=async(a,r,lease=null)=>JSON.parse(await db(`select turn_private.read_planning_qualified_intake_v1('${a.owner}','${r.turnId}',${lit(lease)});`));

const empty={artifact:null,trip:null,evidence:[]};
const message=a=>({p_conversation_id:a.conversation,p_message_id:uuid(),p_idempotency_key:uuid(),p_policy_id:a.policy,p_locale:'en',p_text:'Ordinary follow up, not another paid task',p_relationship:'follow_up',p_goal_id:a.goal,p_expected_goal_version:1,p_task_id:null,p_parent_message_id:a.source,p_turn_id:null,p_selected_sources:empty});
const context=(a,m,version=1)=>call(a,'read_assistant_message_sources_v2',{p_policy_id:a.policy,p_conversation_id:a.conversation,p_message_id:m.p_message_id,p_goal_id:a.goal,p_expected_goal_version:version});
run('ordinary v2 message captures empty/Trip refs atomically, same key replay and no new task',async t=>{
 const a=await owner(),m=message(a),before=JSON.parse(await state(a));let r=await call(a,'submit_assistant_message_sources_v2',m);assert.equal(r.kind,'accepted');assert.equal(r.reused,false);assert.equal(r.readyForProvider,false);assert.equal((await call(a,'submit_assistant_message_sources_v2',m)).reused,true);assert.equal(JSON.parse(await state(a)).tasks,before.tasks);
 const trip=uuid();await db(`insert into public.trips(id,owner_id,title) values('${trip}','${a.owner}','上海之旅');`);
 const withTrip={...message(a),p_parent_message_id:m.p_message_id,p_selected_sources:{...empty,trip:{tripId:trip,headVersion:0}}};r=await call(a,'submit_assistant_message_sources_v2',withTrip);assert.equal(r.selectedSources.trip.tripId,trip);const read=await context(a,withTrip);assert.equal(read.trip.title,'上海之旅');assert.equal(read.recipient,'first_party');assert.equal(read.readyForProvider,false);
 const fail=await sql(container,query(a,'submit_assistant_message_sources_v2',{...withTrip,p_selected_sources:empty}));assert.notEqual(fail.code,0);assert.match(fail.stderr,/IDEMPOTENCY_KEY_REUSE/);
 const b=await owner(),bad={...message(a),p_selected_sources:{...empty,trip:{tripId:uuid(),headVersion:0}}},snapshot=await state(a);const rejected=await sql(container,query(a,'submit_assistant_message_sources_v2',bad));assert.notEqual(rejected.code,0);assert.equal(await state(a),snapshot);
 await db(`update public.trips set head_version=1 where id='${trip}';`);const stale=await sql(container,query(a,'read_assistant_message_sources_v2',{p_policy_id:a.policy,p_conversation_id:a.conversation,p_message_id:withTrip.p_message_id,p_goal_id:a.goal,p_expected_goal_version:1}));assert.notEqual(stale.code,0);assert.match(stale.stderr,/SERVICE_TASK_CONFLICT/);t.diagnostic(JSON.stringify({network:'none',container,scope:'ordinary message/source refs',newPaidTasks:0}));
});
async function artifactFixture(a,memoryBasis=[]){const p=planning(a),r=await call(a,'submit_planning_comparison_v1',p),id=uuid();await db(`update public.turns set status='completed' where id='${r.turnId}';update turn_private.text_content set output_kind='answered',output_text='Synthetic fixture only' where turn_id='${r.turnId}';`);
 const content={schemaVersion:'comparison/1',title:'Synthetic selected result',summary:'Earlier comparison, not hotel inventory',options:[{id:'jingan',title:'Jingan',tradeoff:'Synthetic rail access'},{id:'peoples_square',title:'Square',tradeoff:'Synthetic rail access'}],actions:[]};
 const publish={p_owner_id:a.owner,p_artifact_id:id,p_expected_revision:0,p_idempotency_key:uuid(),p_task_id:r.taskId,p_goal_id:a.goal,p_input_message_id:p.p_message_id,p_trip_id:null,p_trip_version:null,p_goal_version:1,p_memory_basis:memoryBasis,p_content:content};const out=await db("set role service_role;set request.jwt.claim.role='service_role';select public.publish_comparison_result_v1("+Object.entries(publish).map(([k,v])=>k+'=>'+lit(v)).join(',')+');');assert.equal(JSON.parse(out).kind,'published');return {id,p,r,publish};}
run('selected artifact exact revision/current actor captured and own amendment is explicit previous reference',async()=>{
 const a=await owner(),artifact=await artifactFixture(a),m={...message(a),p_parent_message_id:artifact.p.p_message_id,p_selected_sources:{...empty,artifact:{artifactId:artifact.id,revision:1}}};const before=JSON.parse(await state(a));const r=await call(a,'submit_assistant_message_sources_v2',m);assert.equal(r.selectedSources.artifact.artifactId,artifact.id);const read=await context(a,m);assert.equal(read.artifact.current,true);assert.equal(read.tasks.length,1);assert.equal(JSON.parse(await state(a)).tasks,before.tasks);
 const amend={...message(a),p_parent_message_id:m.p_message_id,p_relationship:'amendment',p_selected_sources:m.p_selected_sources};const accepted=await call(a,'submit_assistant_message_sources_v2',amend);assert.equal(accepted.scopeVersion,2);assert.equal(accepted.selectedSources.artifact.purpose,'previous_result_reference');const previous=await context(a,amend,2);assert.equal(previous.artifact.current,false);assert.equal(previous.artifact.historicalReadable,true);assert.equal(previous.capturedSources.artifact.originGoalVersion,1);assert.equal((await call(a,'submit_assistant_message_sources_v2',amend)).reused,true);
 const foreign=await owner();const invalid={...message(foreign),p_selected_sources:m.p_selected_sources},snapshot=await state(foreign);const rejected=await sql(container,query(foreign,'submit_assistant_message_sources_v2',invalid));assert.notEqual(rejected.code,0);assert.match(rejected.stderr,/DATA_POLICY_BLOCKED/);assert.equal(await state(foreign),snapshot);
});
run('two source-bound goal amendments have one CAS winner; stale/extra refs roll back and export has exact owner',async()=>{
 const a=await owner(),messages=['one','two'].map(text=>({...message(a),p_relationship:'amendment',p_text:text})),r=await Promise.all(messages.map(m=>sql(container,query(a,'submit_assistant_message_sources_v2',m))));assert.deepEqual(r.map(x=>x.code===0).sort(),[false,true]);assert.match(r.find(x=>x.code!==0).stderr,/SERVICE_TASK_CONFLICT/);
 const bad={...message(a),p_expected_goal_version:2,p_parent_message_id:messages[r[0].code===0?0:1].p_message_id,p_selected_sources:{...empty,extra:true}},before=await state(a);assert.notEqual((await sql(container,query(a,'submit_assistant_message_sources_v2',bad))).code,0);assert.equal(await state(a),before);
 const exported=JSON.parse(await db(`set role service_role;set request.jwt.claim.role='service_role';select public.assistant_message_source_export_owner_v2('${a.owner}',null,1);`));assert.equal(exported.items.length,1);assert.equal(exported.sectionComplete,true);assert.equal((await sql(container,query(a,'assistant_message_source_export_owner_v2',{p_owner:a.owner,p_limit:1}))).code!==0,true);
 for(const role of ['anon','authenticated','service_role'])assert.equal(await db(`select has_table_privilege('${role}','turn_private.assistant_message_source_receipts','SELECT,INSERT,UPDATE,DELETE');`),'f');
});
run('qualified published evidence records exact scope/version and revocation blocks context without exposing private source',async()=>{
 const a=await owner(),b=await owner(),cid=uuid();await db(`update knowledge_review_private.settings set enabled=true;update knowledge_review_private.publication_settings set enabled=true;insert into knowledge_review_private.members(actor_id,active) values('${a.owner}',true),('${b.owner}',true);`);
 const statement={schemaVersion:'knowledge-statement/1',assertion:{subjectId:'synthetic-payment',predicate:'accepts_method',objectId:'synthetic-cash',conditions:['synthetic-condition'],exclusions:['no-real-acceptance']},scope:{cities:['shanghai'],scene:'payment',audience:'international_independent_traveler'},expressions:{zh:{text:'合成支付说明。',conditions:['仅限合成测试。'],exclusions:['不表示真实支付受理。']},en:{text:'Synthetic payment note.',conditions:['Only synthetic.'],exclusions:['No real acceptance.']}},sources:[{sourceKey:'selected-'+cid,revisionLabel:'one',publisher:'Synthetic author',uri:'urn:vpj15:synthetic:selected:'+cid,locator:'test',snippet:'PRIVATE SOURCE DO NOT RETURN',usageDeclaration:'Owned synthetic test'}]};
 await call(a,'ops_review_workspace',{p_input:{action:'submit_statement',operationId:uuid(),candidateId:cid,title:'Synthetic scoped evidence',statement}});await call(b,'ops_review_workspace',{p_input:{action:'review',operationId:uuid(),candidateId:cid,expectedVersion:1,decision:'reviewed',note:'Synthetic independent review'}});await call(b,'ops_review_workspace',{p_input:{action:'publish_statement',operationId:uuid(),candidateId:cid,expectedVersion:2,expiresAt:new Date(Date.now()+3600000).toISOString(),useBasis:'original_factual_summary',useNote:'Synthetic first party'}});
 const domain=await call(a,'knowledge_read_v1',{p_input:{city:'shanghai',scene:'payment',locale:'en'}}),e=domain.statements.find(x=>x.assertion.objectId==='synthetic-cash');assert.ok(e);const ref={factId:e.factId,assertionId:e.assertionId,assertionRevision:e.assertionRevision,city:'shanghai',scene:'payment'},m={...message(a),p_selected_sources:{...empty,evidence:[ref]}};
 const accepted=await call(a,'submit_assistant_message_sources_v2',m);assert.equal(accepted.selectedSources.evidence[0].recipient,'first_party');const read=await context(a,m);assert.equal(read.evidence[0].text,'Synthetic payment note.');assert.equal(JSON.stringify(read).includes('PRIVATE SOURCE DO NOT RETURN'),false);
 await call(b,'ops_review_workspace',{p_input:{action:'revoke_statement',operationId:uuid(),candidateId:cid,expectedPublicationVersion:1,note:'Synthetic withdrawal'}});
 const stale=await sql(container,query(a,'read_assistant_message_sources_v2',{p_policy_id:a.policy,p_conversation_id:a.conversation,p_message_id:m.p_message_id,p_goal_id:a.goal,p_expected_goal_version:1}));assert.notEqual(stale.code,0);assert.match(stale.stderr,/SERVICE_TASK_CONFLICT/);
});
run('new result revision is not latest fallback; source receipt is immutable and conversation deletion cascades',async()=>{
 const a=await owner(),art=await artifactFixture(a),m={...message(a),p_parent_message_id:art.p.p_message_id,p_selected_sources:{...empty,artifact:{artifactId:art.id,revision:1}}};await call(a,'submit_assistant_message_sources_v2',m);assert.equal((await context(a,m)).artifact.revision,1);
 const revised={...art.publish,p_expected_revision:1,p_idempotency_key:uuid(),p_content:{...art.publish.p_content,summary:'New synthetic revision'}};const r=await db("set role service_role;set request.jwt.claim.role='service_role';select public.publish_comparison_result_v1("+Object.entries(revised).map(([k,v])=>k+'=>'+lit(v)).join(',')+');');assert.equal(JSON.parse(r).revision,2);
 const stale=await sql(container,query(a,'read_assistant_message_sources_v2',{p_policy_id:a.policy,p_conversation_id:a.conversation,p_message_id:m.p_message_id,p_goal_id:a.goal,p_expected_goal_version:1}));assert.notEqual(stale.code,0);assert.match(stale.stderr,/SERVICE_TASK_CONFLICT/);
 const immutable=await sql(container,`update turn_private.assistant_message_source_receipts set captured_sources='{}' where message_id='${m.p_message_id}';`);assert.notEqual(immutable.code,0);assert.match(immutable.stderr,/IMMUTABLE_SOURCE_RECEIPT/);
 await db(`delete from turn_private.assistant_conversations where id='${a.conversation}' and owner_id='${a.owner}';`);assert.equal(await db(`select count(*) from turn_private.assistant_message_source_receipts where message_id='${m.p_message_id}';`),'0');
});

run('previous-result purpose cannot resurrect a changed Memory dependency or withdrawn artifact',async()=>{
 const a=await owner(),memory=uuid();const rows=async(name,p)=>{const r=await sql(container,query(a,name,p).replace('select public.',"select jsonb_agg(to_jsonb(m)) from public.").replace(');commit;',') m;commit;'));assert.equal(r.code,0,r.stderr);return JSON.parse(r.stdout.trim());};const consent=(await rows('create_memory_retrieval_consent',{}))[0].consent_id;await rows('create_explicit_memory_profile_v2',{p_memory_id:memory,p_receipt_id:uuid(),p_consent_id:consent,p_constraint_kind:'preference',p_summary:'Synthetic prior preference'});
 const art=await artifactFixture(a,[{id:memory,revision:1}]),m={...message(a),p_parent_message_id:art.p.p_message_id,p_relationship:'amendment',p_selected_sources:{...empty,artifact:{artifactId:art.id,revision:1}}};await call(a,'submit_assistant_message_sources_v2',m);assert.equal((await context(a,m,2)).artifact.current,false);
 await rows('transition_memory_profile',{p_memory_id:memory,p_next_state:'paused'});const blocked=await sql(container,query(a,'read_assistant_message_sources_v2',{p_policy_id:a.policy,p_conversation_id:a.conversation,p_message_id:m.p_message_id,p_goal_id:a.goal,p_expected_goal_version:2}));assert.notEqual(blocked.code,0);assert.match(blocked.stderr,/DATA_POLICY_BLOCKED|SERVICE_TASK_CONFLICT/);
 const b=await owner(),other=await artifactFixture(b),msg={...message(b),p_parent_message_id:other.p.p_message_id,p_selected_sources:{...empty,artifact:{artifactId:other.id,revision:1}}};await call(b,'submit_assistant_message_sources_v2',msg);await db(`set role service_role;set request.jwt.claim.role='service_role';select public.withdraw_result_artifact_v1('${b.owner}','${other.id}',1);`);assert.notEqual((await sql(container,query(b,'read_assistant_message_sources_v2',{p_policy_id:b.policy,p_conversation_id:b.conversation,p_message_id:msg.p_message_id,p_goal_id:b.goal,p_expected_goal_version:1}))).code,0);
});
