// One actual fixed-SQL support read through HTTP. Admin synthetic SQL and signed
// local fixture credentials are not real target Auth/permission activation.
import test from 'node:test';import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';import {readFileSync,readdirSync} from 'node:fs';
import {NextRequest} from 'next/server.js';
import {command,sql} from '../cost/fixtures/postgres-rpc.mjs';
import {nativeFixture,subject,sessionId} from '../../contract/identity/native-fixture.ts';
import {nativeTripSupportHTTP} from '../../../lib/server/trip/support/native-http.ts';
const enabled=process.env.VP_TURN_DB_TEST==='1',migration='20261003200000_vpj65_trip_item_support.sql';
const lit=v=>v===null?'null':typeof v==='number'||typeof v==='boolean'?String(v):"'"+(typeof v==='object'?JSON.stringify(v):String(v)).replaceAll("'","''")+"'";
test('fixed SQL current support12 fields survive real HTTP decoding; withdrawn values stay null and Ops IDs excluded',{skip:!enabled,timeout:120000},async t=>{
 const container='vp-native-support-read-'+randomUUID().slice(0,8);let created=false;
 const db=async q=>{const r=await sql(container,q);assert.equal(r.code,0,r.stderr);return r.stdout.trim();};
 try{
  const r=await command('docker',['run','--pull=never','--rm','-d','--network','none','--name',container,'--user','postgres','--entrypoint','/bin/sh','public.ecr.aws/supabase/postgres:17.6.1.159','-c','umask 077;mkdir /tmp/vpj59-socket;initdb -D /tmp/vpj59-db -A trust --no-locale -E UTF8 >/tmp/init.log 2>&1 && exec postgres -D /tmp/vpj59-db -c listen_addresses= -c unix_socket_directories=/tmp/vpj59-socket -c unix_socket_permissions=0700']);assert.equal(r.code,0,r.stderr);created=true;
  for(let n=0;n<100;n++){if((await command('docker',['exec',container,'pg_isready','-h','/tmp/vpj59-socket','-U','postgres'])).code===0)break;await new Promise(r=>setTimeout(r,100));}
  await db(readFileSync('tests/integration/turn/fixtures/durable-work-schema.sql','utf8'));await db("create function auth.role()returns text language sql as $$select nullif(current_setting('request.jwt.claim.role',true),'')$$;create schema extensions;create extension pgcrypto with schema extensions;");
  if(process.env.VP_SUPPORT_READ_SQL_SOURCE)throw Error('Historical SQL source overrides forbidden; use current checkout.');
  const source=readFileSync('supabase/migrations/'+migration,'utf8');
  for(const name of [...new Set([...readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')),migration])].sort())await db('begin;'+(name===migration?source:readFileSync('supabase/migrations/'+name,'utf8'))+'commit;');
  const actors=Array.from({length:3},()=>({id:randomUUID(),session:randomUUID()}));const [author,reviewer,mapper]=actors,owner={id:subject,session:sessionId};actors.push(owner);
  for(const a of actors)await db(`insert into auth.users(id)values('${a.id}');insert into auth.sessions(id,user_id)values('${a.session}','${a.id}');insert into identity_private.mobile_accounts(owner_id)values('${a.id}');insert into knowledge_review_private.members(actor_id,active)values('${a.id}',true);`);
  await db('update knowledge_review_private.settings set enabled=true;update knowledge_review_private.publication_settings set enabled=true;');
  const actor=a=>`set request.jwt.claim.role='authenticated';set request.jwt.claim.sub='${a.id}';set request.jwt.claims='${JSON.stringify({session_id:a.session})}';`;
  const rpc=async(a,name,p)=>JSON.parse(await db(actor(a)+(name==='create_trip_proposal_patch'?'select coalesce(jsonb_agg(to_jsonb(r)),\'[]\')from public.':'select public.')+name+'('+Object.entries(p).map(([k,v])=>k+'=>'+lit(v)).join(',')+(name==='create_trip_proposal_patch'?')r;':');')));
  const candidate=randomUUID(),statement={schemaVersion:'knowledge-statement/2',assertion:{subjectId:'test_gallery',predicate:'opens_during',objectId:'opening_hours',conditions:[],exclusions:[]},scope:{cities:['shanghai'],scene:'attraction',audience:'international_independent_traveler'},place:{names:{en:'Test Gallery',zh:'测试展馆'}},value:{startsAt:'2026-10-03T01:00:00Z',endsAt:'2026-10-03T08:00:00Z',timeZone:'Asia/Shanghai'},expressions:{en:{text:'Synthetic window',conditions:[],exclusions:[]},zh:{text:'合成时窗',conditions:[],exclusions:[]}},sources:[{sourceKey:'support-'+randomUUID(),revisionLabel:'one',publisher:'Fixture',uri:'urn:vpj15:synthetic:support',locator:'Fixture only',snippet:'NO REAL SOURCE',usageDeclaration:'private synthetic fixture'}]};
  await rpc(author,'ops_review_workspace',{p_input:{action:'submit_statement',operationId:randomUUID(),candidateId:candidate,title:'Synthetic',statement}});
  await rpc(reviewer,'ops_review_workspace',{p_input:{action:'review',operationId:randomUUID(),candidateId:candidate,expectedVersion:1,decision:'reviewed',note:'Independent'}});
  await rpc(reviewer,'ops_review_workspace',{p_input:{action:'publish_statement',operationId:randomUUID(),candidateId:candidate,expectedVersion:2,useBasis:'original_factual_summary',useNote:'synthetic',expiresAt:new Date(Date.now()+86400000).toISOString()}});
  const st=JSON.parse(await db(`select jsonb_build_object('id',statement_id,'revision',revision,'hash',trip_support_private.hash(payload))from knowledge_review_private.statements where candidate_id='${candidate}';`)),poi=randomUUID(),trip=randomUUID(),ref=randomUUID();
  await db(`insert into public.canonical_pois(id,primary_name_zh,primary_name_en)values('${poi}','测试展馆','Test Gallery');insert into public.trips(id,owner_id,title)values('${trip}','${owner.id}','Synthetic owned Trip');insert into public.trip_place_references(id,trip_id,owner_id,reference_kind,canonical_poi_id)values('${ref}','${trip}','${owner.id}','canonical','${poi}');`);
  const refs=JSON.parse(await db(`select jsonb_agg(jsonb_build_object('sourceRevisionId',r.id,'revisionLabel',r.revision_label,'snippetHash',r.snippet_hash,'submittedBy',r.submitted_by)order by r.id)from knowledge_review_private.statement_sources ss join knowledge_review_private.source_revisions r on r.id=ss.source_revision_id where ss.candidate_id='${candidate}';`)),digest=await db(`select trip_support_private.hash(${lit(refs)}::jsonb);`);
  const mapping=await rpc(mapper,'submit_trip_support_entity_mapping_v1',{p_input:{operationId:randomUUID(),canonicalPoiId:poi,statementId:st.id,expectedClaimRevision:st.revision,expectedPayloadHash:st.hash,expectedSourceDigest:digest,basisMetadata:{city:'shanghai',scene:'attraction',locale:'en',sourceRefs:refs}}});
  const approved=await rpc(reviewer,'review_trip_support_entity_mapping_v1',{p_mapping:mapping.mappingId,p_expected_version:mapping.version,p_expected_digest:mapping.digest,p_decision:'approve'});
  const proposed=await rpc(owner,'create_trip_proposal_patch',{p_trip_id:trip,p_patch:{expectedVersion:0,operations:[{kind:'upsert_day',dayId:'Day_A',date:'2026-10-03',timeZone:'Asia/Shanghai'},{kind:'upsert_item',itemId:'Item_A',dayId:'Day_A',title:'My explicit activity',startsAt:'2026-10-03T02:00:00Z',endsAt:'2026-10-03T03:00:00Z'}]}}),proposal=proposed[0].proposal_id;
  const p=JSON.parse(await db(actor(owner)+`select to_jsonb(r)from public.read_trip_proposal_v2('${proposal}')r;`)),itemDigest=await db(`select trip_support_private.hash(trip_support_private.item(public.apply_trip_content_patch(public.trip_content_snapshot('${trip}','Synthetic owned Trip'),${lit(p.proposal.patch)}::jsonb),'Day_A','Item_A'));`);
  const prepared=await rpc(owner,'prepare_trip_item_support_v1',{p_input:{operationId:randomUUID(),tripId:trip,placeReferenceId:ref,dayId:'Day_A',itemId:'Item_A',proposalId:proposal,expectedProposalRevision:1,expectedBaseVersion:0,expectedProposalDigest:p.digest,expectedItemDigest:itemDigest,mappingId:approved.mappingId,expectedMappingVersion:approved.version,expectedMappingDigest:approved.digest,city:'shanghai',scene:'attraction',locale:'en',scope:'opening_window_reference',expectedClaimRevision:st.revision,expectedPayloadHash:st.hash,expectedSourceDigest:digest}});
  assert.equal(prepared.kind,'prepared');await rpc(owner,'confirm_and_apply_supported_trip_proposal_v1',{p_proposal_id:proposal,p_idempotency_key:randomUUID(),p_digest:p.digest,p_support_selection:[{receiptId:prepared.receiptId,version:prepared.version,sourceDigest:prepared.sourceDigest}]});
  const database='https://dzqdzetcctkhbrhlxxgn.supabase.co',host='vp-v4-supportjoint-jtcao515s-projects.vercel.app',auth=await nativeFixture(t,database),env={VERCEL_ENV:'preview',VERCEL_URL:host,VISEPANDA_NATIVE_STAGING:'true',VISEPANDA_TRIP_PROTOCOL_V2:'true',NEXT_PUBLIC_SUPABASE_URL:database,NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:auth.config.publishableKey};
  const old=Object.fromEntries(Object.keys(env).map(k=>[k,process.env[k]]));t.after(()=>{for(const[k,v]of Object.entries(old))v===undefined?delete process.env[k]:process.env[k]=v;});Object.assign(process.env,env);
  const prior=globalThis.fetch;t.mock.method(globalThis,'fetch',async(input,init)=>{const r=new Request(input,init),path=new URL(r.url).pathname;if(path.endsWith('/native_session_v2'))return Response.json({subject,sessionId,mobileEpoch:1});if(path.endsWith('/read_trip_item_support_v1'))return Response.json(await rpc(owner,'read_trip_item_support_v1',await r.json()));return prior(input,init);});
  const request=()=>new NextRequest(`https://${host}/api/trips/native/v2/${trip}/support?expectedTripVersion=1&dayId=Day_A&itemId=Item_A`,{headers:{authorization:'Bearer '+auth.token}});
  const current=await nativeTripSupportHTTP(request(),'read',trip);assert.equal(current.status,200);const entry=(await current.json()).entries[0];assert.equal(Object.keys(entry).length,12);assert.equal(entry.placeReferenceId,ref);assert.equal(entry.sourceRefs.length,1);assert.equal(Object.hasOwn(entry.sourceRefs[0],'submittedBy'),false);assert.ok(entry.claim);
  await rpc(author,'ops_source_revision_withdraw_v1',{p_input:{operationId:randomUUID(),sourceRevisionId:refs[0].sourceRevisionId,reason:'synthetic source withdrawal'}});
  const revoked=await nativeTripSupportHTTP(request(),'read',trip);assert.equal(revoked.status,200);assert.equal((await revoked.json()).entries[0].claim,null);
  const denied=await sql(container,'set role authenticated;'+actor(owner)+`select public.read_trip_item_support_v1('${trip}',1,'Day_A','Item_A');`);assert.notEqual(denied.code,0);assert.match(denied.stderr,/permission denied for function/);
 }finally{if(created)assert.equal((await command('docker',['rm','-f',container])).code,0);}
});
