// Administrator-only Unix-socket fixture, ordinary JWT claims simulated; no API grants/signed permits.
import test,{before,after} from 'node:test';import assert from 'node:assert/strict';
import {randomUUID as uuid,createHash} from 'node:crypto';import {readFileSync,readdirSync} from 'node:fs';
import {command,sql} from '../cost/fixtures/postgres-rpc.mjs';
const enabled=process.env.VP_TURN_DB_TEST==='1',container='vpj25-offline-'+uuid().slice(0,8);let created=false;
const db=async q=>{const r=await sql(container,q);assert.equal(r.code,0,r.stderr);return r.stdout.trim();};
const lit=v=>v===null?'null':typeof v==='number'||typeof v==='boolean'?String(v):"'"+(typeof v==='object'?JSON.stringify(v):String(v)).replaceAll("'","''")+"'";
const actor=a=>`set request.jwt.claim.role='authenticated';set request.jwt.claim.sub='${a.owner}';set request.jwt.claims='${JSON.stringify({role:'authenticated',is_anonymous:false,session_id:a.session})}';`;
const invoke=(a,name,p)=>actor(a)+'select to_jsonb(public.'+name+'('+Object.entries(p).map(([k,v])=>k+'=>'+lit(v)).join(',')+'));';
const call=async(a,name,p)=>JSON.parse(await db(invoke(a,name,p)));
const deny=async(a,name,p,error)=>{const r=await sql(container,invoke(a,name,p));assert.notEqual(r.code,0);assert.match(r.stderr,new RegExp(error));};
async function owner(){const a={owner:uuid(),session:uuid(),trip:uuid(),epoch:1};await db(`insert into auth.users(id) values('${a.owner}');insert into auth.sessions(id,user_id) values('${a.session}','${a.owner}');insert into identity_private.mobile_accounts(owner_id,epoch,session_id) values('${a.owner}',1,'${a.session}');insert into identity_private.mobile_attempts(owner_id,attempt_id,session_id,epoch) values('${a.owner}','${uuid()}','${a.session}',1);${actor(a)}insert into public.trips(id,owner_id,title) values('${a.trip}','${a.owner}','Existing Trip title is not offline authored');`);return a;}
const submit=(a,date='2026-10-12',title='My explicitly submitted new day')=>({p_trip_id:a.trip,p_operation_id:uuid(),p_expected_head_version:0,p_date:date,p_title:title,p_save_offline:true});
async function confirm(a,id){const intent=await call(a,'read_trip_proposal_v2',{p_proposal_id:id});return call(a,'confirm_and_apply_trip_proposal',{p_proposal_id:id,p_idempotency_key:uuid(),p_digest:intent.digest});}
const read=(a,head)=>call(a,'read_offline_trip_text_provenance_v1',{p_trip_id:a.trip,p_expected_head_version:head,p_expected_epoch:a.epoch});
async function ordinary(a,head,operations){const r=await call(a,'create_trip_proposal_patch',{p_trip_id:a.trip,p_patch:{expectedVersion:head,operations}});await confirm(a,r.proposal_id);return r;}
const canonical=v=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v!==null&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
const sha=v=>createHash('sha256').update(v).digest('hex');
before(async()=>{if(!enabled)return;const r=await command('docker',['run','--pull=never','--rm','-d','--network','none','--name',container,'--user','postgres','--entrypoint','/bin/sh','public.ecr.aws/supabase/postgres:17.6.1.159','-c','umask 077;mkdir /tmp/vpj59-socket;initdb -D /tmp/vpj59-db -A trust --no-locale -E UTF8 >/tmp/init.log 2>&1 && exec postgres -D /tmp/vpj59-db -c listen_addresses= -c unix_socket_directories=/tmp/vpj59-socket -c unix_socket_permissions=0700']);assert.equal(r.code,0,r.stderr);created=true;for(let n=0;n<100;n++){if((await command('docker',['exec',container,'pg_isready','-h','/tmp/vpj59-socket','-U','postgres'])).code===0)break;await new Promise(r=>setTimeout(r,100));}
 await db(readFileSync('tests/integration/turn/fixtures/durable-work-schema.sql','utf8'));await db("create function auth.role() returns text language sql as $$select nullif(current_setting('request.jwt.claim.role',true),'')$$;create schema extensions;create extension pgcrypto with schema extensions;");for(const f of readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')).sort())await db('begin;'+readFileSync('supabase/migrations/'+f,'utf8')+'commit;');});
after(async()=>{if(created)assert.equal((await command('docker',['rm','-f',container])).code,0);});
const run=(name,fn)=>test(name,{skip:!enabled,timeout:120000},fn);
run('controlled command is candidate only, confirm binds exact fields; same operation retries do not mint rights',async()=>{
 const a=await owner(),p=submit(a),r=await call(a,'submit_offline_trip_text_proposal_v1',p);assert.equal(r.kind,'offline_text_proposal/1');assert.equal(r.provenanceState,'candidate');assert.equal(r.dayId,'ofd_'+p.p_operation_id.replaceAll('-',''));assert.equal((await call(a,'submit_offline_trip_text_proposal_v1',p)).reused,true);
 assert.equal((await read(a,1)).kind,'unavailable');await deny(a,'submit_offline_trip_text_proposal_v1',{...p,p_title:'Other input'},'IDEMPOTENCY_KEY_REUSE');
 assert.equal((await confirm(a,r.proposalId)).outcome,'applied');const out=await read(a,1);assert.equal(out.kind,'offline_text_provenance/1');assert.equal(out.sourceSemantics,'controlled_user_text_submission');assert.deepEqual(out.coverage,{kind:'full',excludedDays:0,excludedItems:0});assert.equal(out.fields.length,2);assert.equal(out.qualifiedPayload.days[0].items[0].title,p.p_title);assert.equal(out.qualifiedPayloadDigest,sha(canonical(out.qualifiedPayload)));
 assert.equal(await db(`select count(*) from offline_private.text_version_bindings_v1 where trip_id='${a.trip}';`),'2');assert.equal((await call(a,'submit_offline_trip_text_proposal_v1',p)).reused,true);
});
run('existing ordinary content remains online, partial qualified subset and canonical bytes preserve opaque IDs',async()=>{
 const a=await owner();await ordinary(a,0,[{kind:'upsert_day',dayId:'DAY_Upper-1',date:'2026-10-10'},{kind:'upsert_item',dayId:'DAY_Upper-1',itemId:'ITEM_Mixed-1',title:'Unknown existing origin'}]);assert.equal((await read(a,1)).kind,'unavailable');
 const p={...submit(a,'2026-10-11','我的行程 😀 "quoted"\nline'),p_expected_head_version:1};const r=await call(a,'submit_offline_trip_text_proposal_v1',p);await confirm(a,r.proposalId);let out=await read(a,2);assert.deepEqual(out.coverage,{kind:'partial',excludedDays:1,excludedItems:1});assert.equal(out.qualifiedPayload.days.length,1);assert.equal(out.qualifiedPayloadDigest,sha(canonical(out.qualifiedPayload)));
 await ordinary(a,2,[{kind:'upsert_item',dayId:r.dayId,itemId:'UNKNOWN_Mixed-2',title:'Unknown inserted title'}]);out=await read(a,3);assert.deepEqual(out.coverage,{kind:'partial',excludedDays:1,excludedItems:2});assert.equal(out.qualifiedPayload.days[0].items.length,1);
 const sample={days:[{id:'DAY_Upper-1',date:'2026-10-10',items:[{id:'ITEM_Mixed-1',title:'Unicode 😀 "literal"'}]}]};assert.equal(await db(`select offline_private.canonical_v1(${lit(sample)}::jsonb);`),canonical(sample));
 for(const [field,day,item,value] of [['days.date','DAY_Upper-1',null,'2026-10-10'],['days.items.title','DAY_Upper-1','ITEM_Mixed-1','非ASCII 😀 \"quote\"\nline']])assert.equal(await db(`select offline_private.field_digest_v1(${[field,day,item,value].map(lit).join(',')});`),sha(canonical([field,day,item,value])));
 for(const field of out.fields){const day=out.qualifiedPayload.days.find(d=>d.id===field.dayId);const value=field.field==='days.date'?day.date:day.items.find(i=>i.id===field.itemId).title;assert.equal(field.valueDigest,sha(canonical([field.field,field.dayId,field.itemId,value])));}
 const online=JSON.parse(await db(`select content from public.trip_version_snapshots where trip_id='${a.trip}' and version=3;`));assert.equal(online.days.length,2);
});
run('same-date/new command cannot overwrite, old revision/rejection/expiry/rollback cannot acquire provenance',async()=>{
 const a=await owner(),p=submit(a),r=await call(a,'submit_offline_trip_text_proposal_v1',p);const revised=await call(a,'revise_trip_proposal_patch',{p_proposal_id:r.proposalId,p_patch:{expectedVersion:0,operations:[{kind:'upsert_day',dayId:r.dayId,date:p.p_date},{kind:'upsert_item',dayId:r.dayId,itemId:r.itemId,title:'Ordinary revision has no new source'}]}});await confirm(a,revised.proposal_id);assert.equal((await read(a,1)).kind,'unavailable');
 await deny(a,'submit_offline_trip_text_proposal_v1',{...submit(a),p_expected_head_version:1},'OFFLINE_DATE_EXISTS');
 const second=await call(a,'submit_offline_trip_text_proposal_v1',{...submit(a,'2026-10-13'),p_expected_head_version:1});await confirm(a,second.proposalId);assert.equal((await read(a,2)).kind,'offline_text_provenance/1');
 const rollback=await call(a,'create_trip_rollback_proposal',{p_trip_id:a.trip,p_target_version:1});await confirm(a,rollback.proposal_id);assert.equal((await read(a,3)).kind,'unavailable');
 const rejected=await call(a,'submit_offline_trip_text_proposal_v1',{...submit(a,'2026-10-15'),p_expected_head_version:3});await call(a,'reject_trip_proposal_v2',{p_proposal_id:rejected.proposalId});assert.equal((await confirm(a,rejected.proposalId)).outcome,'proposal_not_confirmable');
 const expired=await call(a,'submit_offline_trip_text_proposal_v1',{...submit(a,'2026-10-16'),p_expected_head_version:3});await db(`update public.trip_proposals set expires_at=now()-interval '1 second' where id='${expired.proposalId}';`);assert.equal((await confirm(a,expired.proposalId)).outcome,'proposal_expired');assert.equal((await read(a,3)).kind,'unavailable');
});
run('revoke, epoch replacement, archive/deletion, foreign actor and closed ACL all fail read without grants',async()=>{
 const a=await owner(),p=submit(a),r=await call(a,'submit_offline_trip_text_proposal_v1',p);await confirm(a,r.proposalId);const b=await owner();await deny(b,'read_offline_trip_text_provenance_v1',{p_trip_id:a.trip,p_expected_head_version:1,p_expected_epoch:1},'FORBIDDEN');
 const rev={p_trip_id:a.trip,p_expected_epoch:1,p_operation_id:uuid()};assert.equal((await call(a,'revoke_offline_trip_text_provenance_v1',rev)).generation,2);assert.equal((await call(a,'revoke_offline_trip_text_provenance_v1',rev)).reused,true);assert.equal((await read(a,1)).kind,'unavailable');
 const next=await call(a,'submit_offline_trip_text_proposal_v1',{...submit(a,'2026-10-14'),p_expected_head_version:1});await confirm(a,next.proposalId);assert.equal((await read(a,2)).kind,'offline_text_provenance/1');
 await db(`update identity_private.mobile_accounts set epoch=2 where owner_id='${a.owner}';`);a.epoch=2;assert.equal((await read(a,2)).kind,'unavailable');
 assert.equal(await db("select has_function_privilege('authenticated','public.submit_offline_trip_text_proposal_v1(uuid,uuid,integer,text,text,boolean)','EXECUTE') or has_function_privilege('service_role','public.read_offline_trip_text_provenance_v1(uuid,integer,bigint)','EXECUTE');"),'f');
 assert.equal(await db("select has_table_privilege('authenticated','offline_private.text_sources_v1','SELECT');"),'f');
});

run('archive and queued/completed Trip deletion close reads and cascade source metadata through old lifecycle',async()=>{
 for(const mode of ['archive','delete']){const a=await owner(),r=await call(a,'submit_offline_trip_text_proposal_v1',submit(a));await confirm(a,r.proposalId);
 if(mode==='archive'){await call(a,'archive_trip_v1',{p_trip_id:a.trip,p_expected_version:1,p_idempotency_key:uuid(),p_confirmed:true});assert.equal((await read(a,1)).kind,'unavailable');}
 else {const request=uuid();assert.equal((await call(a,'request_trip_deletion_v1',{p_request_id:request,p_trip_id:a.trip,p_expected_version:1,p_confirmed:true})).state,'queued');assert.equal((await read(a,1)).kind,'unavailable');const done=JSON.parse(await db(`set request.jwt.claim.role='service_role';set request.jwt.claims='{"role":"service_role"}';select public.execute_trip_deletion_v1('${request}');`));assert.equal(done.state,'completed');assert.equal(await db(`select count(*) from offline_private.text_sources_v1 where trip_id='${a.trip}';`),'0');assert.equal(await db(`select count(*) from offline_private.text_commands_v1 where trip_id='${a.trip}';`),'0');}
 }
});
run('late source binding fault rolls back original confirmation; no snapshot/event/head/receipt partial write',async()=>{
 const a=await owner(),r=await call(a,'submit_offline_trip_text_proposal_v1',submit(a));const snapshot=()=>db(`select jsonb_build_object('head',(select head_version from public.trips where id='${a.trip}'),'snapshots',(select count(*) from public.trip_version_snapshots where trip_id='${a.trip}'),'events',(select count(*) from public.trip_events where trip_id='${a.trip}'),'bindings',(select count(*) from offline_private.text_version_bindings_v1 where trip_id='${a.trip}'),'proposal',(select status from public.trip_proposals where id='${r.proposalId}'));`);const before=await snapshot();
 await db(`create function offline_private.fixture_bind_fault() returns trigger language plpgsql as $$begin if new.trip_id='${a.trip}' then raise exception 'FIXTURE_SOURCE_BIND_FAILURE';end if;return new;end $$;create trigger fixture_bind_fault before insert on offline_private.text_version_bindings_v1 for each row execute function offline_private.fixture_bind_fault();`);
 const intent=await call(a,'read_trip_proposal_v2',{p_proposal_id:r.proposalId});await deny(a,'confirm_and_apply_trip_proposal',{p_proposal_id:r.proposalId,p_idempotency_key:uuid(),p_digest:intent.digest},'FIXTURE_SOURCE_BIND_FAILURE');assert.equal(await snapshot(),before);
 await db('drop trigger fixture_bind_fault on offline_private.text_version_bindings_v1;drop function offline_private.fixture_bind_fault();');await confirm(a,r.proposalId);assert.equal((await read(a,1)).kind,'offline_text_provenance/1');
});
