// Actual network-none PostgreSQL and ops/source relations; administrator claim
// fixture is not deployed signed-ops, scheduler, supplier or fee evidence.
import test,{before,after} from 'node:test';import assert from 'node:assert/strict';
import {randomUUID as uuid} from 'node:crypto';import {readFileSync,readdirSync} from 'node:fs';
import {handleSourceImpactConsumeOnce} from '../../../lib/server/knowledge/report/consume-once.ts';
import {command,sql} from '../cost/fixtures/postgres-rpc.mjs';
const enabled=process.env.VP_TURN_DB_TEST==='1',container='vpj65-support-'+uuid().slice(0,8);let created=false;
const db=async q=>{const r=await sql(container,q);assert.equal(r.code,0,r.stderr);return r.stdout.trim();};
const lit=v=>v===null?'null':typeof v==='number'||typeof v==='boolean'?String(v):"'"+(typeof v==='object'?JSON.stringify(v):String(v)).replaceAll("'","''")+"'";
const rpc=async(actor,name,p)=>JSON.parse(await db(`begin;set request.jwt.claim.role='authenticated';set request.jwt.claim.sub='${actor.id}';set request.jwt.claims='${JSON.stringify({session_id:actor.session})}';${name==='create_trip_proposal_patch'?"select coalesce(jsonb_agg(to_jsonb(r)),'[]') from public.":'select public.'}${name}(`+Object.entries(p).map(([k,v])=>k+'=>'+lit(v)).join(',')+(name==='create_trip_proposal_patch'?') r;commit;':');commit;')));
before(async()=>{
 if(!enabled)return;const r=await command('docker',['run','--pull=never','--rm','-d','--network','none','--name',container,'--user','postgres','--entrypoint','/bin/sh','public.ecr.aws/supabase/postgres:17.6.1.159','-c','umask 077;mkdir /tmp/vpj59-socket;initdb -D /tmp/vpj59-db -A trust --no-locale -E UTF8 >/tmp/init.log 2>&1 && exec postgres -D /tmp/vpj59-db -c listen_addresses= -c unix_socket_directories=/tmp/vpj59-socket -c unix_socket_permissions=0700']);assert.equal(r.code,0,r.stderr);created=true;
 for(let n=0;n<100;n++){if((await command('docker',['exec',container,'pg_isready','-h','/tmp/vpj59-socket','-U','postgres'])).code===0)break;await new Promise(r=>setTimeout(r,100));}
 await db(readFileSync('tests/integration/turn/fixtures/durable-work-schema.sql','utf8'));await db("create function auth.role() returns text language sql as $$select nullif(current_setting('request.jwt.claim.role',true),'')$$;create schema extensions;create extension pgcrypto with schema extensions;");
 for(const f of readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')).sort())await db('begin;'+readFileSync('supabase/migrations/'+f,'utf8')+'commit;');
});
after(async()=>{if(created)assert.equal((await command('docker',['rm','-f',container])).code,0);});
const run=(name,fn)=>test(name,{skip:!enabled,timeout:120000},fn);
run('full200 migration compiles and all new support APIs remain default revoked with no direct ordinary Trip mutation',async()=>{
 assert.equal(await db("select has_function_privilege('authenticated','public.confirm_and_apply_supported_trip_proposal_v1(uuid,text,text,jsonb)','EXECUTE') or has_function_privilege('service_role','public.prepare_trip_item_support_v1(jsonb)','EXECUTE');"),'f');
 assert.equal(await db("select count(*) from trip_support_private.item_supports;"),'0');
});
run('actual typed window NULL/missing/bad calendar cannot become matched; replacement window re-evaluates current item',async()=>{
 const item={day:{id:'Day_A',date:'2026-10-03',timeZone:'Asia/Shanghai'},item:{id:'Item_A',startsAt:'2026-10-03T02:00:00Z',endsAt:'2026-10-03T03:00:00Z'}},base={claimType:'time_window',value:{startsAt:'2026-10-03T01:00:00Z',endsAt:'2026-10-03T04:00:00Z',timeZone:'Asia/Shanghai'}};
 for(const value of [{},{startsAt:null,endsAt:null,timeZone:'Asia/Shanghai'},{...base.value,endsAt:null},{...base.value,startsAt:'2026-02-30T00:00:00Z'},{...base.value,timeZone:null}]){
  assert.equal(await db(`select trip_support_private.valid_typed_value('time_window',${lit(value)}::jsonb);`),'f');assert.equal(await db(`select trip_support_private.applicability(${lit(item)}::jsonb,'opening_window_reference',${lit({...base,value})}::jsonb);`),'unverified');
 }
 assert.equal(await db(`select trip_support_private.applicability(${lit(item)}::jsonb,'opening_window_reference',${lit(base)}::jsonb);`),'matched');
 assert.equal(await db(`select trip_support_private.applicability(${lit(item)}::jsonb,'opening_window_reference',${lit({...base,value:{...base.value,startsAt:'2026-10-03T04:00:00Z',endsAt:'2026-10-03T06:00:00Z'}})}::jsonb);`),'unverified');
});
async function fixture(){
 const actors=Array.from({length:4},()=>({id:uuid(),session:uuid()})),[author,reviewer,mapper,owner]=actors;
 for(const a of actors)await db(`insert into auth.users(id) values('${a.id}');insert into auth.sessions(id,user_id) values('${a.session}','${a.id}');insert into identity_private.mobile_accounts(owner_id) values('${a.id}');insert into knowledge_review_private.members(actor_id,active) values('${a.id}',true);`);
 await db('update knowledge_review_private.settings set enabled=true;update knowledge_review_private.publication_settings set enabled=true;');
 const rpc=async(a,name,p)=>JSON.parse(await db(`begin;set request.jwt.claim.role='authenticated';set request.jwt.claim.sub='${a.id}';set request.jwt.claims='${JSON.stringify({session_id:a.session})}';${name==='create_trip_proposal_patch'?"select coalesce(jsonb_agg(to_jsonb(r)),'[]') from public.":'select public.'}${name}(`+Object.entries(p).map(([k,v])=>k+'=>'+lit(v)).join(',')+(name==='create_trip_proposal_patch'?') r;commit;':');commit;')));
 const candidate=uuid(),statement={schemaVersion:'knowledge-statement/2',assertion:{subjectId:'test_gallery',predicate:'opens_during',objectId:'opening_hours',conditions:[],exclusions:[]},scope:{cities:['shanghai'],scene:'attraction',audience:'international_independent_traveler'},place:{names:{en:'Test Gallery',zh:'测试展馆'}},value:{startsAt:'2026-10-03T01:00:00Z',endsAt:'2026-10-03T08:00:00Z',timeZone:'Asia/Shanghai'},expressions:{en:{text:'Synthetic opening window',conditions:[],exclusions:[]},zh:{text:'合成开放时窗',conditions:[],exclusions:[]}},sources:[{sourceKey:'support-'+uuid(),revisionLabel:'one',publisher:'Fixture source',uri:'urn:vpj15:synthetic:support',locator:'Fixture only',snippet:'NO REAL SUPPLIER',usageDeclaration:'private synthetic fixture'}]};
 await rpc(author,'ops_review_workspace',{p_input:{action:'submit_statement',operationId:uuid(),candidateId:candidate,title:'Synthetic typed source',statement}});
 await rpc(reviewer,'ops_review_workspace',{p_input:{action:'review',operationId:uuid(),candidateId:candidate,expectedVersion:1,decision:'reviewed',note:'Independent fixture review'}});
 await rpc(reviewer,'ops_review_workspace',{p_input:{action:'publish_statement',operationId:uuid(),candidateId:candidate,expectedVersion:2,useBasis:'original_factual_summary',useNote:'synthetic only no deployment',expiresAt:new Date(Date.now()+86400000).toISOString()}});
 const st=JSON.parse(await db(`select jsonb_build_object('id',statement_id,'revision',revision,'hash',trip_support_private.hash(payload)) from knowledge_review_private.statements where candidate_id='${candidate}';`)),poi=uuid(),trip=uuid(),placeRef=uuid();
 await db(`insert into public.canonical_pois(id,primary_name_zh,primary_name_en) values('${poi}','测试展馆','Test Gallery');insert into public.trips(id,owner_id,title,head_version) values('${trip}','${owner.id}','User intent not globally verified',0);insert into public.trip_place_references(id,trip_id,owner_id,reference_kind,canonical_poi_id) values('${placeRef}','${trip}','${owner.id}','canonical','${poi}');`);
 const basis=await rpc(owner,'knowledge_read_v1',{p_input:{city:'shanghai',scene:'attraction',locale:'en'}});assert.equal(basis.status,'available');
 const sourceRefs=JSON.parse(await db(`select jsonb_agg(jsonb_build_object('sourceRevisionId',r.id,'revisionLabel',r.revision_label,'snippetHash',r.snippet_hash,'submittedBy',r.submitted_by) order by r.id) from knowledge_review_private.statement_sources ss join knowledge_review_private.source_revisions r on r.id=ss.source_revision_id where ss.candidate_id='${candidate}';`)),digest=await db(`select trip_support_private.hash(${lit(sourceRefs)}::jsonb);`);
 const mapping=await rpc(mapper,'submit_trip_support_entity_mapping_v1',{p_input:{operationId:uuid(),canonicalPoiId:poi,statementId:st.id,expectedClaimRevision:st.revision,expectedPayloadHash:st.hash,expectedSourceDigest:digest,basisMetadata:{city:'shanghai',scene:'attraction',locale:'en',sourceRefs}}});assert.equal(mapping.kind,'mapping_candidate',JSON.stringify(mapping));
 const mapped=await rpc(reviewer,'review_trip_support_entity_mapping_v1',{p_mapping:mapping.mappingId,p_expected_version:mapping.version,p_expected_digest:mapping.digest,p_decision:'approve'});assert.equal(mapped.kind,'mapping_reviewed');
 const proposed=await rpc(owner,'create_trip_proposal_patch',{p_trip_id:trip,p_patch:{expectedVersion:0,operations:[{kind:'upsert_day',dayId:'Day_A',date:'2026-10-03',timeZone:'Asia/Shanghai'},{kind:'upsert_item',itemId:'Item_A',dayId:'Day_A',title:'User selected gallery',startsAt:'2026-10-03T02:00:00Z',endsAt:'2026-10-03T03:00:00Z'}]}});
 const proposalId=Array.isArray(proposed)?proposed[0].proposal_id:proposed.proposal_id;
 const read=JSON.parse(await db(`set request.jwt.claim.sub='${owner.id}';select to_jsonb(r) from public.read_trip_proposal_v2('${proposalId}') r;`)),itemHash=await db(`select trip_support_private.hash(trip_support_private.item(public.apply_trip_content_patch(public.trip_content_snapshot('${trip}','User intent not globally verified'),${lit(read.proposal.patch)}::jsonb),'Day_A','Item_A'));`);
 const prepared=await rpc(owner,'prepare_trip_item_support_v1',{p_input:{operationId:uuid(),tripId:trip,placeReferenceId:placeRef,dayId:'Day_A',itemId:'Item_A',proposalId,expectedProposalRevision:read.proposal.revision,expectedBaseVersion:0,expectedProposalDigest:read.digest,expectedItemDigest:itemHash,mappingId:mapped.mappingId,expectedMappingVersion:mapped.version,expectedMappingDigest:mapped.digest,city:'shanghai',scene:'attraction',locale:'en',scope:'opening_window_reference',expectedClaimRevision:st.revision,expectedPayloadHash:st.hash,expectedSourceDigest:digest}});assert.equal(prepared.kind,'prepared',JSON.stringify(prepared));
 return {rpc,owner,reviewer,author,mapper,trip,proposalId,read,prepared,sourceRefs,poi,placeRef,candidate,statement};
}
run('actual reviewed source and entity mapping -> selected receipt -> original confirmation and support, replay selection cannot change',async()=>{
 const f=await fixture(),key='support-'+uuid(),selection=[{receiptId:f.prepared.receiptId,version:f.prepared.version,sourceDigest:f.prepared.sourceDigest}],p={p_proposal_id:f.proposalId,p_idempotency_key:key,p_digest:f.read.digest,p_support_selection:selection};
 const confirmed=await f.rpc(f.owner,'confirm_and_apply_supported_trip_proposal_v1',p);assert.equal(confirmed.kind,'confirmed',JSON.stringify(confirmed));assert.equal(confirmed.outcome,'applied');assert.equal(confirmed.supports.length,1);
 const recovered=await f.rpc(f.owner,'read_supported_trip_confirmation_receipt_v1',{p_idempotency_key:key,p_proposal_id:f.proposalId,p_proposal_digest:f.read.digest,p_support_selection:selection});assert.equal(recovered.historicalOnly,true);assert.deepEqual(recovered.receipt,confirmed);
 assert.deepEqual(await f.rpc(f.owner,'confirm_and_apply_supported_trip_proposal_v1',p),confirmed);assert.equal((await f.rpc(f.owner,'confirm_and_apply_supported_trip_proposal_v1',{...p,p_support_selection:[{...selection[0],sourceDigest:'f'.repeat(64)}]})).kind,'conflict');
 const current=await f.rpc(f.owner,'read_trip_item_support_v1',{p_trip:f.trip,p_expected_trip_version:1,p_day:'Day_A',p_item:'Item_A'});assert.equal(current.entries[0].status,'reference_current');assert.equal(current.entries[0].applicability,'matched');
 await f.rpc(f.author,'ops_source_revision_withdraw_v1',{p_input:{operationId:uuid(),sourceRevisionId:f.sourceRefs[0].sourceRevisionId,reason:'Fixture rights withdrawal'}});
 const stale=await f.rpc(f.owner,'read_trip_item_support_v1',{p_trip:f.trip,p_expected_trip_version:1,p_day:'Day_A',p_item:'Item_A'});assert.equal(stale.entries[0].status,'recheck_required');assert.equal(stale.entries[0].claim,null);assert.equal(await db(`select head_version from public.trips where id='${f.trip}';`),'1');
});
run('actual renewal with reviewed noncovering window loses matched and old/renewed private rows follow deletion ordering',async()=>{
 const f=await fixture(),confirm=await f.rpc(f.owner,'confirm_and_apply_supported_trip_proposal_v1',{p_proposal_id:f.proposalId,p_idempotency_key:'renew-'+uuid(),p_digest:f.read.digest,p_support_selection:[{receiptId:f.prepared.receiptId,version:f.prepared.version,sourceDigest:f.prepared.sourceDigest}]});assert.equal(confirm.kind,'confirmed');
 const candidate=uuid(),changed=structuredClone(f.statement);changed.sources[0].sourceKey='replacement-'+uuid();changed.value={startsAt:'2026-10-03T05:00:00Z',endsAt:'2026-10-03T08:00:00Z',timeZone:'Asia/Shanghai'};
 await f.rpc(f.author,'ops_review_workspace',{p_input:{action:'submit_statement',operationId:uuid(),candidateId:candidate,title:'Reviewed later noncovering hours',statement:changed}});await f.rpc(f.reviewer,'ops_review_workspace',{p_input:{action:'review',operationId:uuid(),candidateId:candidate,expectedVersion:1,decision:'reviewed',note:'Independent fixture'}});await f.rpc(f.reviewer,'ops_review_workspace',{p_input:{action:'publish_statement',operationId:uuid(),candidateId:candidate,expectedVersion:2,expiresAt:new Date(Date.now()+86400000).toISOString(),useBasis:'original_factual_summary',useNote:'synthetic only'}});
 const st=JSON.parse(await db(`select jsonb_build_object('id',statement_id,'revision',revision,'hash',trip_support_private.hash(payload)) from knowledge_review_private.statements where candidate_id='${candidate}';`)),refs=JSON.parse(await db(`select jsonb_agg(jsonb_build_object('sourceRevisionId',r.id,'revisionLabel',r.revision_label,'snippetHash',r.snippet_hash,'submittedBy',r.submitted_by) order by r.id) from knowledge_review_private.statement_sources ss join knowledge_review_private.source_revisions r on r.id=ss.source_revision_id where ss.candidate_id='${candidate}';`)),digest=await db(`select trip_support_private.hash(${lit(refs)}::jsonb);`);
 const mapping=await f.rpc(f.mapper,'submit_trip_support_entity_mapping_v1',{p_input:{operationId:uuid(),canonicalPoiId:f.poi,statementId:st.id,expectedClaimRevision:st.revision,expectedPayloadHash:st.hash,expectedSourceDigest:digest,basisMetadata:{city:'shanghai',scene:'attraction',locale:'en',sourceRefs:refs}}});assert.equal(mapping.kind,'mapping_candidate');const reviewed=await f.rpc(f.reviewer,'review_trip_support_entity_mapping_v1',{p_mapping:mapping.mappingId,p_expected_version:mapping.version,p_expected_digest:mapping.digest,p_decision:'approve'});
 const renewed=await f.rpc(f.owner,'renew_trip_item_support_v1',{p_input:{operationId:uuid(),supportId:confirm.supports[0].supportId,expectedVersion:1,tripVersion:1,dayId:'Day_A',itemId:'Item_A',mappingId:reviewed.mappingId,expectedMappingVersion:reviewed.version,expectedMappingDigest:reviewed.digest,expectedClaimRevision:st.revision,expectedPayloadHash:st.hash,expectedSourceDigest:digest}});assert.equal(renewed.kind,'renewed',JSON.stringify(renewed));
 const now=await f.rpc(f.owner,'read_trip_item_support_v1',{p_trip:f.trip,p_expected_trip_version:1,p_day:'Day_A',p_item:'Item_A'});assert.equal(now.entries[0].applicability,'unverified');assert.equal(now.entries[0].claim.value.startsAt,changed.value.startsAt);assert.equal(await db(`select count(*) from trip_support_private.preparations where trip_id='${f.trip}';`),'2');assert.equal(await db("select count(*) from information_schema.columns where table_schema='trip_support_private' and column_name='typed_claim';"),'0');
 await db(`begin;delete from public.trip_events where trip_id='${f.trip}';delete from public.trip_idempotency where proposal_id='${f.proposalId}';delete from public.trip_audit_events where trip_id='${f.trip}';delete from public.trip_proposals where trip_id='${f.trip}';delete from public.trip_version_snapshots where trip_id='${f.trip}';delete from public.trips where id='${f.trip}';commit;`);
 assert.equal(await db(`select count(*) from trip_support_private.preparations where trip_id='${f.trip}';`),'0');assert.equal(await db(`select count(*) from trip_support_private.item_supports where trip_id='${f.trip}';`),'0');assert.equal(await db(`select count(*) from trip_support_private.confirmation_receipts where trip_id='${f.trip}';`),'0');
});
run('source loss between selection and confirmation preserves Trip but emits minimal marker; owner deletion removes support inventory',async()=>{
 const f=await fixture();await f.rpc(f.author,'ops_source_revision_withdraw_v1',{p_input:{operationId:uuid(),sourceRevisionId:f.sourceRefs[0].sourceRevisionId,reason:'Fixture withdrawal before confirm'}});
 const r=await f.rpc(f.owner,'confirm_and_apply_supported_trip_proposal_v1',{p_proposal_id:f.proposalId,p_idempotency_key:'withdraw-'+uuid(),p_digest:f.read.digest,p_support_selection:[{receiptId:f.prepared.receiptId,version:f.prepared.version,sourceDigest:f.prepared.sourceDigest}]});assert.equal(r.outcome,'applied');assert.equal(r.supports[0].status,'recheck_required');
 const read=await f.rpc(f.owner,'read_trip_item_support_v1',{p_trip:f.trip,p_expected_trip_version:1,p_day:'Day_A',p_item:'Item_A'});assert.equal(read.entries[0].claim,null);assert.equal(await db(`select title from public.trip_items where trip_id='${f.trip}' and item_id='Item_A';`),'User selected gallery');
 const before=await f.rpc(f.owner,'trip_item_support_owner_metadata_v1',{p_trip:f.trip,p_after:null,p_limit:50});assert.equal(before.kind,'metadata');assert.ok(!JSON.stringify(before).includes('Synthetic opening window'));assert.ok(!JSON.stringify(before).includes('NO REAL SUPPLIER'));
 await db(`delete from auth.users where id='${f.owner.id}';`);
 for(const table of ['preparations','item_supports','confirmation_receipts'])assert.equal(await db(`select count(*) from trip_support_private.${table} where owner_id='${f.owner.id}';`),'0');
});
run('actual one reviewed source set delivers two supports with lost ACK and immutable provenance; renewed receipt makes old set stale',async()=>{
 const f=await fixture(),selection=[{receiptId:f.prepared.receiptId,version:f.prepared.version,sourceDigest:f.prepared.sourceDigest}];
 const first=await f.rpc(f.owner,'confirm_and_apply_supported_trip_proposal_v1',{p_proposal_id:f.proposalId,p_idempotency_key:'bridge-a-'+uuid(),p_digest:f.read.digest,p_support_selection:selection});assert.equal(first.kind,'confirmed');
 const secondProposal=await f.rpc(f.owner,'create_trip_proposal_patch',{p_trip_id:f.trip,p_patch:{expectedVersion:1,operations:[{kind:'upsert_item',itemId:'Item_B',dayId:'Day_A',title:'Second explicit user selection',startsAt:'2026-10-03T04:00:00Z',endsAt:'2026-10-03T05:00:00Z'}]}}),pid=secondProposal[0].proposal_id;
 const ctx=await f.rpc(f.owner,'read_trip_item_support_context_v1',{p_trip:f.trip,p_expected_trip_version:1,p_proposal:pid,p_expected_proposal_revision:secondProposal[0].revision,p_day:'Day_A',p_item:'Item_B'});assert.equal(ctx.kind,'support_context');assert.equal(ctx.canonicalPlaceReferences[0].referenceId,f.placeRef);
 const candidates=await f.rpc(f.owner,'read_trip_item_support_candidates_v1',{p_trip:f.trip,p_expected_trip_version:1,p_place_reference:f.placeRef,p_city:'shanghai',p_scene:'attraction',p_locale:'en',p_cursor:null,p_limit:50}),m=candidates.entries[0];assert.ok(m);assert.ok(!JSON.stringify(candidates).includes('basisMetadata'));
 const prep=await f.rpc(f.owner,'prepare_trip_item_support_v1',{p_input:{operationId:uuid(),tripId:f.trip,placeReferenceId:f.placeRef,dayId:'Day_A',itemId:'Item_B',proposalId:pid,expectedProposalRevision:ctx.proposalRevision,expectedBaseVersion:1,expectedProposalDigest:ctx.proposalDigest,expectedItemDigest:ctx.itemDigest,mappingId:m.mappingId,expectedMappingVersion:m.mappingVersion,expectedMappingDigest:m.mappingDigest,city:'shanghai',scene:'attraction',locale:'en',scope:m.scope,expectedClaimRevision:m.claimRevision,expectedPayloadHash:m.payloadHash,expectedSourceDigest:m.sourceDigest}});assert.equal(prep.kind,'prepared');
 const second=await f.rpc(f.owner,'confirm_and_apply_supported_trip_proposal_v1',{p_proposal_id:pid,p_idempotency_key:'bridge-b-'+uuid(),p_digest:ctx.proposalDigest,p_support_selection:[{receiptId:prep.receiptId,version:prep.version,sourceDigest:prep.sourceDigest}]});assert.equal(second.kind,'confirmed');
 await f.rpc(f.author,'ops_source_revision_withdraw_v1',{p_input:{operationId:uuid(),sourceRevisionId:f.sourceRefs[0].sourceRevisionId,reason:'Real fixture source action'}});
 const source=JSON.parse(await db(`select jsonb_build_object('label',revision_label,'hash',snippet_hash,'at',withdrawn_at) from knowledge_review_private.source_revisions where id='${f.sourceRefs[0].sourceRevisionId}';`));
 const captured=await f.rpc(f.mapper,'capture_source_impact_v1',{p_operation:uuid(),p_source:f.sourceRefs[0].sourceRevisionId,p_expected_label:source.label,p_expected_hash:source.hash,p_expected_withdrawn_at:source.at,p_kind:'withdrawn',p_replacement:null,p_limit:100});assert.equal(captured.kind,'captured');assert.equal(captured.complete,true);
 const reviewed=await f.rpc(f.reviewer,'review_source_impact_v1',{p_set:captured.setId,p_expected_version:captured.version,p_expected_digest:captured.digest,p_decision:'approve'});assert.equal(reviewed.kind,'reviewed');
 const composed=await handleSourceImpactConsumeOnce(new Request('http://127.0.0.1/api/ops/source-impact/consume-once',{method:'POST',headers:{'content-type':'application/json','x-ops-expected-actor':f.mapper.id},body:JSON.stringify({consumer:'trip_item_support'})}),{enabled:true,sameOrigin:true,createRpc:()=>({authenticate:async()=>f.mapper.id,call:async(name,p)=>({data:await f.rpc(f.mapper,name,p),error:null})})});assert.equal(composed.status,200);assert.equal(composed.body.data.outcome,'acked');
 const leased=JSON.parse(await db(`select knowledge_review_private.impact_delivery_wire(id) from knowledge_review_private.source_impact_outbox where set_id='${captured.setId}' and consumer='trip_item_support' and state='acked';`));assert.equal(leased.setId,captured.setId);const p={p_delivery:leased.deliveryId,p_lease:leased.leaseToken,p_expected_attempt:leased.attempt,p_expected_digest:leased.sourceDigest};
 const applied=await f.rpc(f.mapper,'apply_reviewed_trip_support_delivery_v1',p);assert.equal(applied.kind,'applied',JSON.stringify(applied));assert.deepEqual(await f.rpc(f.mapper,'apply_reviewed_trip_support_delivery_v1',p),applied);
 const recovered=await f.rpc(f.mapper,'read_reviewed_trip_support_delivery_v1',{p_delivery:leased.deliveryId});assert.equal(recovered.state,'acked');assert.equal(recovered.receiptId,applied.receiptId);
 const lease2=await f.rpc(f.mapper,'claim_trip_support_impact_delivery_v1',{p_limit:1,p_lease_ms:15000});assert.equal(lease2.setId,captured.setId);assert.notEqual(lease2.deliveryId,leased.deliveryId);assert.equal((await f.rpc(f.mapper,'apply_reviewed_trip_support_delivery_v1',{p_delivery:lease2.deliveryId,p_lease:lease2.leaseToken,p_expected_attempt:lease2.attempt,p_expected_digest:lease2.sourceDigest})).kind,'applied');
 assert.equal(await db(`select count(*) from trip_support_private.item_supports where trip_id='${f.trip}' and status='recheck_required' and version=2 and provenance_version=1;`),'2');assert.equal(await db(`select head_version from public.trips where id='${f.trip}';`),'2');
 // Renew through actual existing publication/mapping/owner APIs, not a fake state write.
 const c=uuid(),replacement=structuredClone(f.statement);replacement.sources[0].sourceKey='bridge-renew-'+uuid();replacement.value={startsAt:'2026-10-03T01:00:00Z',endsAt:'2026-10-03T09:00:00Z',timeZone:'Asia/Shanghai'};
 await f.rpc(f.author,'ops_review_workspace',{p_input:{action:'submit_statement',operationId:uuid(),candidateId:c,title:'Reviewed replacement',statement:replacement}});await f.rpc(f.reviewer,'ops_review_workspace',{p_input:{action:'review',operationId:uuid(),candidateId:c,expectedVersion:1,decision:'reviewed',note:'Independent renewal fixture'}});await f.rpc(f.reviewer,'ops_review_workspace',{p_input:{action:'publish_statement',operationId:uuid(),candidateId:c,expectedVersion:2,useBasis:'original_factual_summary',useNote:'synthetic only',expiresAt:new Date(Date.now()+86400000).toISOString()}});
 const st=JSON.parse(await db(`select jsonb_build_object('id',statement_id,'revision',revision,'hash',trip_support_private.hash(payload)) from knowledge_review_private.statements where candidate_id='${c}';`)),refs=JSON.parse(await db(`select jsonb_agg(jsonb_build_object('sourceRevisionId',r.id,'revisionLabel',r.revision_label,'snippetHash',r.snippet_hash,'submittedBy',r.submitted_by) order by r.id) from knowledge_review_private.statement_sources ss join knowledge_review_private.source_revisions r on r.id=ss.source_revision_id where ss.candidate_id='${c}';`)),digest=await db(`select trip_support_private.hash(${lit(refs)}::jsonb);`);
 const map=await f.rpc(f.mapper,'submit_trip_support_entity_mapping_v1',{p_input:{operationId:uuid(),canonicalPoiId:f.poi,statementId:st.id,expectedClaimRevision:st.revision,expectedPayloadHash:st.hash,expectedSourceDigest:digest,basisMetadata:{city:'shanghai',scene:'attraction',locale:'en',sourceRefs:refs}}}),review=await f.rpc(f.reviewer,'review_trip_support_entity_mapping_v1',{p_mapping:map.mappingId,p_expected_version:map.version,p_expected_digest:map.digest,p_decision:'approve'});
 assert.equal(review.kind,'mapping_reviewed');
 const identities=JSON.parse(await db(`set request.jwt.claim.role='authenticated';set request.jwt.claim.sub='${f.owner.id}';set request.jwt.claims='${JSON.stringify({session_id:f.owner.session})}';select jsonb_build_object('stored',s.item_digest,'current',trip_support_private.hash(trip_support_private.item(v.content,s.day_id,s.item_id)),'storedItem',(select trip_support_private.item(original.content,s.day_id,s.item_id) from public.trip_version_snapshots original where original.trip_id=s.trip_id and original.version=1),'currentItem',trip_support_private.item(v.content,s.day_id,s.item_id),'stateVersion',s.version,'mappingValid',trip_support_private.mapping_basis('${review.mappingId}') is not null) from trip_support_private.item_supports s join public.trip_version_snapshots v on v.trip_id=s.trip_id and v.version=2 where s.id='${first.supports[0].supportId}';`));
 assert.equal(identities.mappingValid,true,JSON.stringify(identities));assert.equal(identities.stateVersion,2,JSON.stringify(identities));assert.equal(identities.stored,identities.current,JSON.stringify(identities));
 assert.equal((await f.rpc(f.owner,'renew_trip_item_support_v1',{p_input:{operationId:uuid(),supportId:first.supports[0].supportId,expectedVersion:2,tripVersion:2,dayId:'Day_A',itemId:'Item_A',mappingId:review.mappingId,expectedMappingVersion:review.version,expectedMappingDigest:review.digest,expectedClaimRevision:st.revision,expectedPayloadHash:st.hash,expectedSourceDigest:digest}})).kind,'renewed');assert.equal((await f.rpc(f.mapper,'read_reviewed_trip_support_delivery_v1',{p_delivery:leased.deliveryId})).kind,'stale');
 await db(`begin;delete from public.trip_events where trip_id='${f.trip}';delete from public.trip_idempotency where proposal_id in(select id from public.trip_proposals where trip_id='${f.trip}');delete from public.trip_audit_events where trip_id='${f.trip}';delete from public.trip_proposals where trip_id='${f.trip}';delete from public.trip_version_snapshots where trip_id='${f.trip}';delete from public.trips where id='${f.trip}';commit;`);
 const sanitized=JSON.parse(await db(`select jsonb_build_object('status',status,'graph',graph_snapshot,'cursor',next_cursor,'complete',complete) from knowledge_review_private.source_impact_sets where id='${captured.setId}';`));assert.equal(sanitized.status,'invalidated');assert.equal(sanitized.complete,false);assert.equal(sanitized.cursor,null);assert.ok(!JSON.stringify(sanitized).includes(first.supports[0].supportId));assert.ok(!JSON.stringify(sanitized).includes(second.supports[0].supportId));assert.ok(sanitized.graph.some(x=>x.target.kind==='statement'));assert.equal(await db(`select count(*) from knowledge_review_private.source_impact_pages where set_id='${captured.setId}';`),'0');
});
