export type JourneyLocale = "en" | "zh";
export const EARLY_ACCESS_URL = "https://form.jotform.com/cjttttt/visepanda-early-access";
export const earlyAccessCopy = {
 en: { nav: "Early Access", plan: "Try planning a trip", workspace: "Open Chat + Canvas preview", title: ["Be part of", "the next chapter."], body: "Help shape a more thoughtful way to travel China.", cardTitle: "Your next journey starts here.", cardBody: "Tell us about the trip you have in mind and apply to try VisePanda early.", note: "Opens our application form on JotForm in a new tab." },
 zh: { nav: "申请 Early Access", plan: "试试行程规划", workspace: "打开 Chat + Canvas 预览", title: ["下一段旅程，", "邀你一起出发。"], body: "一起打磨更从容、更懂你的中国旅行体验。", cardTitle: "来聊聊你的下一程。", cardBody: "告诉我们你正在计划的中国旅行，申请抢先体验 VisePanda。", note: "将在新标签页打开 JotForm 申请表。" },
} as const;
export const journeyCopy = {
  en: {
    nav: ["About", "Ask", "Explore", "Profile"], home: "VisePanda home", skip: "Skip to content", menu: "Menu", close: "Close menu",
    title: ["A little wonder.", "A lot of China."], intro: "For the places you came for. And the moments you didn’t see coming.", cta: "Find your China", scroll: "A little further", location: "Guilin, China", caption: "A slower kind of beautiful.", imageNote: "AI-generated destination inspiration",
    idea: "THE IDEA", aboutTitle: ["Less searching.", "More being there."], aboutLead: "China is a thousand little worlds. Find the one that feels like you.", aboutBody: "A quiet teahouse. A street you hadn’t planned to turn down. We’re creating a more thoughtful way to explore China, with room for your own kind of journey.", aboutRows: ["Follow your curiosity", "Make room for the unexpected", "Travel at your own pace"], aboutFoot: "A moment in the tea hills · Hangzhou", stamp: "SLOW DOWN",
    askLabel: "ASK VISEPANDA", askTitle: ["Every good trip", "starts with", "a question."], askBody: "A big idea, a small curiosity, or no plan at all. Start somewhere. We’ll show you what the conversation could look like.", prompts: ["A slower side of China", "My first trip to China", "A city full of stories"], companion: "Your travel companion", preview: "Interactive preview", welcome: "Where does your curiosity take you?", welcomeBody: "Choose an idea below, or tell us what you’re dreaming of.", placeholder: "Tell us what you’re dreaming of…", send: "Send message", reset: "Start again", chatNote: "Demo responses · No AI connected · Nothing is saved after reload", responseLabel: "A LITTLE INSPIRATION", exploreAction: "Explore this feeling", customReply: "Thanks for sharing your idea. This preview can’t create a personalized answer yet. Try one of the three sample conversations, or explore the places below.", replies: [
      { title: "A little room to wander.", body: "Imagine a gentler journey: misty hills, a pot of tea, and an afternoon with no particular agenda.", steps: ["Guilin · Let the landscape set the pace", "Hangzhou · Leave time for tea", "Your journey · Keep an afternoon open"], category: "slow" },
      { title: "Your first chapter in China.", body: "Start with what moves you. This sample pairs a city story with a quieter landscape; the real itinerary would be yours to shape.", steps: ["Shanghai · Find your city rhythm", "Hangzhou · A change of scenery", "Your journey · Make space between stops"], category: "all" },
      { title: "Take the long way around.", body: "Picture a city discovered on foot: leafy streets, small corners, and a coffee that becomes an afternoon.", steps: ["Shanghai · Follow a leafy street", "Pause · Find a corner to watch the world", "Your journey · Follow your curiosity"], category: "city" },
    ],
    exploreLabel: "FOLLOW YOUR CURIOSITY", exploreTitle: ["Somewhere that", "stays with you."], filters: ["All places", "Slow living", "City stories"], placeNote: "An inspiration collection, not a live destination guide.", places: [
      { name: "Guilin", category: "LANDSCAPES / SLOW LIVING", line: "Where the world exhales.", body: "A little mist. A river with nowhere to rush. A landscape that asks you to stay a while.", alt: "Generated landscape of misty karst mountains and a bamboo raft on a quiet river" },
      { name: "Shanghai", category: "CITY STORIES", line: "A thousand stories. Your own rhythm.", body: "Past the skyline, there are leafy streets, neighborhood corners, and small discoveries waiting for you.", alt: "Generated Shanghai-inspired leafy street with a bicycle and warm historic buildings" },
      { name: "Hangzhou", category: "TEA & TRANQUILITY / SLOW LIVING", line: "Leave a little time for tea.", body: "Green hills, winding paths, and the simple pleasure of an unhurried afternoon.", alt: "Generated Hangzhou-inspired green tea terraces with a traditional pavilion" },
    ], save: "Save", unsave: "Remove", view: "Discover", detailNote: "Concept story · AI-generated image · No live availability or booking", dismiss: "Close story", askPlace: "Try a related conversation",
    profileLabel: "YOUR CORNER", profileTitle: ["A journey,", "your way."], profileBody: "Keep a little collection of the places that move you. Let your curiosity do the curating.", traveler: "The curious traveler", guest: "Guest preview · this session only", pace: "Your pace", paces: ["Unhurried", "A little of everything", "Always exploring"], saved: "Your little collection", empty: "Your next favorite place is out there. Save a place from Explore to begin.", more: "Explore more places", session: "Preferences and saved places reset when you reload. No account is connected.", footer: "Good journeys begin with curiosity.", back: "Back to the beginning", legal: "VisePanda · An independent spirit", footerNote: "Product concept · Generated imagery · Local preview",
  },
  zh: {
    nav: ["关于", "问问 VP", "探索", "我的"], home: "VisePanda 首页", skip: "跳至正文", menu: "菜单", close: "关闭菜单",
    title: ["带一点好奇，", "遇见万千中国。"], intro: "为向往的风景而来，也为计划之外的片刻停留。", cta: "发现你的中国", scroll: "再往前一点", location: "中国 · 桂林", caption: "慢一点，美好自会发生。", imageNote: "AI 生成的目的地意境图",
    idea: "关于我们", aboutTitle: ["少一点搜索，", "多一点身临其境。"], aboutLead: "中国有万千种模样，总有一种，与你相契。", aboutBody: "一间安静的茶馆，一条偶然走进的小巷。我们想让中国旅行多一份从容，也为你自己的故事，留一点空白。", aboutRows: ["跟着好奇心出发", "给不期而遇留点空间", "按自己的节奏旅行"], aboutFoot: "茶山里的片刻 · 杭州", stamp: "慢下来",
    askLabel: "问问 VISEPANDA", askTitle: ["好的旅行，", "从一个", "问题开始。"], askBody: "一个大大的想法，一点小小的好奇，或是还没想好。从这里开始，看看未来的旅行对话可以是什么样。", prompts: ["想看看慢一点的中国", "第一次来中国旅行", "想逛一座有故事的城"], companion: "你的旅行伙伴", preview: "交互演示", welcome: "你的好奇心，想去哪里？", welcomeBody: "选一个灵感，或聊聊你心里的旅行。", placeholder: "聊聊你向往的旅行……", send: "发送消息", reset: "重新开始", chatNote: "预设回复 · 未接入 AI · 刷新后不保留输入", responseLabel: "给你一点灵感", exploreAction: "顺着灵感去探索", customReply: "收到你的旅行想法了。这个预览暂时不能生成个性化回答。你可以试试三个示例话题，或看看下方的目的地灵感。", replies: [
      { title: "给漫游，留一点空白。", body: "想象一段慢下来的旅行：朦胧的山、一壶茶，和一个不必赶路的下午。", steps: ["桂林 · 让山水决定步调", "杭州 · 给一杯茶留点时间", "你的旅程 · 空出一个下午"], category: "slow" },
      { title: "你与中国的第一章。", body: "先从最打动你的事物开始。这个示例把城市故事与宁静山水放在一起，真正的行程，留给你来决定。", steps: ["上海 · 寻找城市的节奏", "杭州 · 换一种风景", "你的旅程 · 在站与站之间留白"], category: "all" },
      { title: "不妨，绕一点远路。", body: "想象一座用脚步认识的城市：树荫、小巷，还有一杯不知不觉喝了整个下午的咖啡。", steps: ["上海 · 沿一条绿荫街道走走", "停一停 · 在街角看看来往的人", "你的旅程 · 跟着好奇心继续"], category: "city" },
    ],
    exploreLabel: "跟着好奇心出发", exploreTitle: ["总有一个地方，", "让你念念不忘。"], filters: ["全部灵感", "慢生活", "城市故事"], placeNote: "这里是旅行灵感合集，并非实时目的地指南。", places: [
      { name: "桂林", category: "山水之间 / 慢生活", line: "世界在这里，轻轻呼吸。", body: "一点雾，一条不必匆忙的河。一片让人想多待一会儿的山水。", alt: "AI 生成的桂林意境图：薄雾里的喀斯特山峰、静水和竹筏" },
      { name: "上海", category: "城市故事", line: "万千故事，自有你的节奏。", body: "天际线之外，还有绿荫街道、邻里转角，和等待你发现的小小日常。", alt: "AI 生成的上海街巷意境图：绿荫、自行车和温暖的老建筑" },
      { name: "杭州", category: "茶与宁静 / 慢生活", line: "给一杯茶，留一点时间。", body: "青绿的山，蜿蜒的路，还有一个不紧不慢的下午。", alt: "AI 生成的杭州茶山意境图：层叠茶园与远处的传统亭子" },
    ], save: "收藏", unsave: "取消收藏", view: "发现", detailNote: "概念故事 · AI 生成图片 · 无实时库存或预订服务", dismiss: "关闭故事", askPlace: "体验相关示例对话",
    profileLabel: "属于你的一角", profileTitle: ["你的旅行，", "自有模样。"], profileBody: "把打动你的地方，收进自己的小小合集。让好奇心，替你挑选下一程。", traveler: "心怀好奇的旅行者", guest: "访客演示 · 仅本次页面会话", pace: "你的旅行节奏", paces: ["慢慢来", "什么都想试一点", "一直在探索"], saved: "你的灵感小集", empty: "下一个心动的地方，正在等你。从「探索」收藏一处风景，就从这里开始。", more: "发现更多地方", session: "刷新页面后偏好与收藏会重置，尚未连接真实账号。", footer: "好的旅行，从好奇开始。", back: "回到故事开头", legal: "VisePanda · 自由探索的心", footerNote: "产品概念 · 生成图片 · 本地预览",
  },
} as const;
