// Actual original Ops candidate/source/review/publication routines in a network-none synthetic stack.
import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import {randomUUID as uuid} from 'node:crypto';import {readFileSync,readdirSync} from 'node:fs';import {command,sql} from '../cost/fixtures/postgres-rpc.mjs';
const enabled=process.env.VP_TURN_DB_TEST==='1',container='vpj23-hotel-'+uuid().slice(0,8);let created=false;
const db=async q=>{const r=await sql(container,q);assert.equal(r.code,0,r.stderr);return r.stdout.trim();};
const lit=v=>"'"+JSON.stringify(v).replaceAll("'","''")+"'::jsonb";
const claims=a=>`set request.jwt.claim.role='authenticated';set request.jwt.claim.sub='${a.owner}';set request.jwt.claims='${JSON.stringify({role:'authenticated',is_anonymous:false,session_id:a.session})}';`;
const ops=(a,input)=>db(claims(a)+`select public.ops_lodging_classification_v1(${lit(input)});`).then(JSON.parse);
async function actor(member=false){const a={owner:uuid(),session:uuid()};await db(`insert into auth.users(id) values('${a.owner}');insert into auth.sessions(id,user_id) values('${a.session}','${a.owner}');insert into identity_private.mobile_accounts(owner_id,epoch,session_id) values('${a.owner}',1,'${a.session}');insert into identity_private.mobile_attempts values('${a.owner}','${uuid()}','${a.session}',1);`);if(member)await db(`insert into knowledge_review_private.members(actor_id,active) values('${a.owner}',true);`);return a;}
function statement(){return {schemaVersion:'knowledge-lodging-classification/1',assertion:{subjectId:'synthetic_hotel',predicate:'classified_as',objectId:'hotel',conditions:[],exclusions:['classification_only','no_price_or_inventory_claim','no_guest_eligibility_claim']},scope:{cities:['shanghai'],scene:'lodging_classification',audience:'international_independent_traveler'},expressions:{en:{text:'Synthetic classification only.',conditions:[],exclusions:['Classification only.','No price or inventory.','No guest eligibility.']},zh:{text:'合成酒店分类。',conditions:[],exclusions:['仅分类','不含价格库存','不含入住资格']}},sources:[{sourceKey:'hotel_'+uuid(),revisionLabel:'one',publisher:'Synthetic publisher',uri:'urn:vpj15:synthetic:hotel',locator:'Synthetic only',snippet:'Synthetic classification evidence, no real content.',usageDeclaration:'Synthetic first-party test metadata only.'}]};}
const readSQL=f=>claims(f.owner)+`select public.read_reviewed_lodging_classifications_v1('${f.trip}',0,'shanghai','en',array['${f.poi}']::uuid[]);`;
const read=f=>db(readSQL(f)).then(JSON.parse);
async function fixture(){const f={author:await actor(true),reviewer:await actor(true),owner:await actor(),trip:uuid(),poi:uuid(),candidate:uuid(),statement:statement()};await db(`${claims(f.owner)}insert into public.trips(id,owner_id,title) values('${f.trip}','${f.owner.owner}','Synthetic owned Trip');insert into public.canonical_pois(id,primary_name_zh,primary_name_en,category) values('${f.poi}','合成住宿身份','Synthetic identity','other');`);return f;}
async function publish(f){f.submit={action:'submit',operationId:uuid(),candidateId:f.candidate,title:'Synthetic classification',statement:f.statement};f.c=await ops(f.author,f.submit);assert.equal(f.c.kind,'lodging_classification_candidate');assert.equal(f.c.status,'pending');
 f.review={action:'review',operationId:uuid(),candidateId:f.candidate,expectedVersion:1,decision:'reviewed',note:'Independent synthetic review'};const reviewed=await ops(f.reviewer,f.review);assert.equal(reviewed.status,'reviewed');
 f.pub=await ops(f.reviewer,{action:'publish',operationId:uuid(),candidateId:f.candidate,expectedVersion:2,expiresAt:new Date(Date.now()+600000).toISOString(),useBasis:'original_factual_summary',useNote:'Synthetic controlled facts only; not real licence evidence.'});assert.equal(f.pub.state,'published');return f;}
async function map(f){f.m=await ops(f.author,{action:'submit_mapping',operationId:uuid(),canonicalPoiId:f.poi,statementId:f.c.statementId,expectedStatementRevision:1,expectedPayloadHash:f.c.payloadHash,expectedSourceDigest:f.c.sourceDigest,expectedPublicationVersion:1,expectedRightsDigest:f.pub.rightsDigest,city:'shanghai'});assert.equal(f.m.status,'pending');f.mappingReview={action:'review_mapping',operationId:uuid(),mappingId:f.m.mappingId,expectedVersion:1,expectedDigest:f.m.digest,decision:'approved',note:'Explicit independent canonical identity binding'};f.approved=await ops(f.reviewer,f.mappingReview);assert.equal(f.approved.status,'approved');return f;}
before(async()=>{if(!enabled)return;const r=await command('docker',['run','--pull=never','--rm','-d','--network','none','--name',container,'--user','postgres','--entrypoint','/bin/sh','public.ecr.aws/supabase/postgres:17.6.1.159','-c','umask 077;mkdir /tmp/vpj59-socket;initdb -D /tmp/vpj59-db -A trust --no-locale -E UTF8 >/tmp/init.log 2>&1 && exec postgres -D /tmp/vpj59-db -c listen_addresses= -c unix_socket_directories=/tmp/vpj59-socket -c unix_socket_permissions=0700']);assert.equal(r.code,0,r.stderr);created=true;for(let i=0;i<100;i++){if((await command('docker',['exec',container,'pg_isready','-h','/tmp/vpj59-socket','-U','postgres'])).code===0)break;await new Promise(r=>setTimeout(r,100));}
 await db(readFileSync('tests/integration/turn/fixtures/durable-work-schema.sql','utf8'));await db("create function auth.role() returns text language sql as $$select nullif(current_setting('request.jwt.claim.role',true),'')$$;create schema extensions;create extension pgcrypto with schema extensions;");for(const f of readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')).sort())await db('begin;'+readFileSync('supabase/migrations/'+f,'utf8')+'commit;');await db('update knowledge_review_private.settings set enabled=true;update knowledge_review_private.publication_settings set enabled=true;');});
after(async()=>{if(created)assert.equal((await command('docker',['rm','-f',container])).code,0);});const run=(name,fn)=>test(name,{skip:!enabled,timeout:120000},fn);
run('strict new validator and true Ops review/publication/mapping yield hotel only; other/name/pending never qualify',async()=>{
 const f=await fixture();assert.equal((await read(f)).items.length,0);assert.equal(await db(`select knowledge_review_private.statement_valid_v1(${lit(f.statement)}) or knowledge_review_private.statement_valid(${lit(f.statement)});`),'f');assert.equal(await db(`select lodging_classification_private.statement_valid_v1(${lit(f.statement)});`),'t');
 for(const bad of [{...f.statement,price:10},{...f.statement,assertion:{...f.statement.assertion,objectId:'five_star_hotel'}},{...f.statement,assertion:{...f.statement.assertion,predicate:'offers_procedure'}}])assert.equal(await db(`select lodging_classification_private.statement_valid_v1(${lit(bad)});`),'f');
 f.submit={action:'submit',operationId:uuid(),candidateId:f.candidate,title:'Synthetic classification',statement:f.statement};f.c=await ops(f.author,f.submit);assert.equal(f.c.kind,'lodging_classification_candidate');assert.deepEqual(await ops(f.author,f.submit),f.c);assert.deepEqual(await ops(f.author,{action:'review',operationId:uuid(),candidateId:f.candidate,expectedVersion:1,decision:'reviewed',note:'Cannot self review'}),{kind:'blocked'});
 const review=await ops(f.reviewer,{action:'review',operationId:uuid(),candidateId:f.candidate,expectedVersion:1,decision:'reviewed',note:'Independent reviewer'});assert.equal(review.status,'reviewed');f.pub=await ops(f.reviewer,{action:'publish',operationId:uuid(),candidateId:f.candidate,expectedVersion:2,expiresAt:new Date(Date.now()+600000).toISOString(),useBasis:'original_factual_summary',useNote:'Synthetic controlled factual classification.'});assert.equal(f.pub.state,'published');assert.equal((await read(f)).items.length,0);
 await map(f);const result=await read(f);assert.equal(result.items.length,1);assert.equal(result.items[0].classification,'hotel');assert.equal(result.items[0].canonicalPoiId,f.poi);assert.equal(Object.keys(result.items[0]).length,15);assert.equal(Object.keys(result.items[0].sourceRefs[0]).length,6);assert.ok(Date.parse(result.items[0].expiresAt)-Date.parse(result.evaluatedAt)<=30000);
 for(const word of ['snippet"','submittedBy','price','inventory','guestEligibility'])assert.equal(JSON.stringify(result).includes(word),false);
 const old=JSON.parse(await db(claims(f.owner)+`select public.knowledge_read_v1('{"city":"shanghai","scene":"accommodation","locale":"en"}');`));assert.equal(old.statements.length,0);assert.equal(await db(`select category from public.canonical_pois where id='${f.poi}';`),'other');
});
run('current membership, source withdrawal, publication TTL/rights/revoke and canonical/provider/mapping drift fail closed',async()=>{
 for(const change of ['member','source','ttl','rights','canonical','provider','mapping']){const f=await map(await publish(await fixture()));assert.equal((await read(f)).items.length,1);let mutation;
 if(change==='member')mutation=`update knowledge_review_private.members set revision=revision+1 where actor_id='${f.reviewer.owner}';`;
 if(change==='source')mutation=`update knowledge_review_private.source_revisions set withdrawn_at=clock_timestamp(),withdrawn_by='${f.reviewer.owner}',withdrawal_reason='Synthetic withdrawal' where id=(select source_revision_id from knowledge_review_private.statement_sources where candidate_id='${f.candidate}');`;
 if(change==='ttl')mutation=`update knowledge_review_private.publications set expires_at=published_at+interval '1 millisecond' where candidate_id='${f.candidate}';`;
 if(change==='rights')mutation=`update knowledge_review_private.publications set use_note='Changed reviewed usage basis' where candidate_id='${f.candidate}';`;
 if(change==='canonical')mutation=`update public.canonical_pois set primary_name_en='Changed identity' where id='${f.poi}';`;
 if(change==='provider')mutation=`insert into public.provider_poi_mappings(canonical_poi_id,provider,provider_poi_id,raw_name) values('${f.poi}','amap','synthetic-provider-id','Changed provider identity');`;
 if(change==='mapping')mutation=claims(f.reviewer)+`select public.ops_lodging_classification_v1(${lit({action:'revoke_mapping',operationId:uuid(),mappingId:f.m.mappingId,expectedVersion:2,note:'Synthetic mapping revoke'})});`;
 await db(mutation);assert.equal((await read(f)).items.length,0,change);
 }
 const f=await map(await publish(await fixture()));await ops(f.reviewer,{action:'revoke',operationId:uuid(),candidateId:f.candidate,expectedPublicationVersion:1,note:'Synthetic publication revoke'});assert.equal((await read(f)).items.length,0);
});
run('owner/Trip/selector bounds and duplicate qualified identity refuse; new role ACL closed',async()=>{
 const f=await map(await publish(await fixture())),other=await actor();assert.deepEqual(JSON.parse(await db(claims(other)+`select public.read_reviewed_lodging_classifications_v1('${f.trip}',0,'shanghai','en',array['${f.poi}']::uuid[]);`)),{kind:'unavailable'});
 assert.deepEqual(JSON.parse(await db(claims(f.owner)+`select public.read_reviewed_lodging_classifications_v1('${f.trip}',1,'shanghai','en',array['${f.poi}']::uuid[]);`)),{kind:'conflict'});
 const duplicate=await sql(container,claims(f.owner)+`select public.read_reviewed_lodging_classifications_v1('${f.trip}',0,'shanghai','en',array['${f.poi}','${f.poi}']::uuid[]);`);assert.notEqual(duplicate.code,0);assert.match(duplicate.stderr,/INVALID_INPUT/);
 await map(f);assert.equal((await read(f)).items.length,0,'two qualified identity bindings are ambiguous');
 for(const role of ['anon','authenticated','service_role'])assert.equal(await db(`select has_function_privilege('${role}','public.ops_lodging_classification_v1(jsonb)','EXECUTE') or has_function_privilege('${role}','public.read_reviewed_lodging_classifications_v1(uuid,integer,text,text,uuid[])','EXECUTE');`),'f');
});
run('two sessions canonical root serializes provider and approval-set phantom; no partial identity mutation',async()=>{
 const f=await map(await publish(await fixture()));const holder=sql(container,`set application_name='hotel_identity_reader';begin;${readSQL(f)}select pg_sleep(2);commit;`);
 for(let i=0;i<100;i++){if(await db("select exists(select 1 from pg_stat_activity where application_name='hotel_identity_reader' and wait_event_type='Timeout');")==='t')break;if(i===99)assert.fail('reader holder absent');await new Promise(r=>setTimeout(r,10));}
 const write=await sql(container,`insert into public.provider_poi_mappings(canonical_poi_id,provider,provider_poi_id,raw_name) values('${f.poi}','amap','synthetic-provider','Synthetic identity');`);assert.notEqual(write.code,0);assert.match(write.stderr,/could not obtain lock on row in relation "canonical_pois"/);assert.equal((await holder).code,0);assert.equal(await db(`select count(*) from public.provider_poi_mappings where canonical_poi_id='${f.poi}';`),'0');assert.equal((await read(f)).items.length,1);
});
