import assert from "node:assert/strict";
import {schemaInventorySQL} from './schema-inventory.mjs';
import {execFileSync,spawnSync} from 'node:child_process';
import {readFileSync,writeFileSync} from 'node:fs';
import {createDecipheriv,createHash,randomUUID} from 'node:crypto';
import {tableSnapshotSQL,validateSnapshot} from './table-snapshot.mjs';
const dockerContext='desktop-linux';
if(process.env.DOCKER_HOST||process.env.DOCKER_CONTEXT)throw Error('Docker overrides refused');
const endpoint=execFileSync('docker',['context','inspect',dockerContext,'--format','{{.Endpoints.docker.Host}}'],{encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
if(endpoint!=='unix:///Users/jtcao/.docker/run/docker.sock')throw Error('Unexpected Docker endpoint');
const root='/Users/jtcao/Library/Caches/visepanda/place-grounding-staging-20260914',dir=readFileSync(root+'/current-backup-path','utf8');
const image='public.ecr.aws/supabase/postgres:17.6.1.159',container='vpj02-restore-'+randomUUID().slice(0,8);let created=false,stage='manifest';
const run=(args,input)=>spawnSync('docker',['--context',dockerContext,...args],{input,encoding:'utf8',maxBuffer:8*1024*1024,timeout:120000});
const sql=(input)=>run(['exec','-i',container,'psql','-h','/tmp/vpj02-socket','-U','postgres','-X','-q','-At','-v','ON_ERROR_STOP=1'],input);
try{
const meta=JSON.parse(readFileSync(dir+'/manifest.json','utf8')),blob=readFileSync(meta.file);if(createHash('sha256').update(blob).digest('hex')!==meta.ciphertextSha256||blob.subarray(0,4).toString()!=='VPB1')throw Error();
const key=Buffer.from(execFileSync('/usr/bin/security',['find-generic-password','-a','VP-V4','-s',meta.keychainService,'-w'],{encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim(),'base64'),dec=createDecipheriv('aes-256-gcm',key,blob.subarray(4,16));dec.setAuthTag(blob.subarray(-16));const dump=Buffer.concat([dec.update(blob.subarray(16,-16)),dec.final()]);key.fill(0);
stage='isolated-init';const started=run(['run','--label','vpj02.owner=place-grounding-staging-20260914','--pull=never','--rm','-d','--network','none','--name',container,'--user','postgres','--entrypoint','/bin/sh',image,'-c','umask 077; mkdir /tmp/vpj02-socket; initdb -D /tmp/vpj02-pg -A trust --no-locale -E UTF8 >/tmp/init.log 2>&1 && exec postgres -D /tmp/vpj02-pg -c listen_addresses= -c unix_socket_directories=/tmp/vpj02-socket -c unix_socket_permissions=0700']);if(started.status!==0)throw Error();created=true;
const iso=JSON.parse(execFileSync('docker',['--context',dockerContext,'inspect',container],{encoding:'utf8'}))[0];if(iso.HostConfig.NetworkMode!=='none'||Object.keys(iso.HostConfig.PortBindings??{}).length)throw Error();let ready=false;for(let i=0;i<30;i++){if(run(['exec',container,'pg_isready','-h','/tmp/vpj02-socket','-U','postgres']).status===0){ready=true;break;}await new Promise(r=>setTimeout(r,1000));}if(!ready)throw Error();
stage='roles-extensions';const existing=sql('select rolname from pg_roles;');if(existing.status!==0)throw Error();const names=meta.restoreRoleNames.filter(n=>!new Set(existing.stdout.trim().split('\n')).has(n));if(names.some(n=>!/^[a-z_][a-z0-9_]{0,62}$/.test(n)))throw Error();if(sql(names.map(n=>`create role "${n}" nologin;`).join('\n')+'\ncreate schema extensions; create extension pgcrypto with schema extensions; create extension "uuid-ossp" with schema extensions;').status!==0)throw Error();
stage='public-bootstrap';const bootstrap=sql("select jsonb_build_object('owner',pg_get_userbyid(nspowner),'acl',(select jsonb_agg(x::text order by x::text collate \"C\") from unnest(nspacl) x)) from pg_namespace where nspname='public';");if(bootstrap.status!==0)throw Error();const publicBootstrap=JSON.parse(bootstrap.stdout.trim());if(publicBootstrap.owner!=='pg_database_owner'||JSON.stringify(publicBootstrap.acl)!==JSON.stringify(['=U/pg_database_owner','pg_database_owner=UC/pg_database_owner']))throw Error('Unexpected initial public schema');
stage='restore-toc';const toc=run(['run','--rm','--network','none','--pull=never','-i','--entrypoint','pg_restore',image,'--list'],dump);if(toc.status!==0)throw Error();let publicEntries=0;const filtered=toc.stdout.split('\n').map(line=>{if(/^\d+; \d+ \d+ SCHEMA - public pg_database_owner$/.test(line)){publicEntries++;return '; preserve verified initdb public schema: '+line;}return line;}).join('\n');if(publicEntries!==1)throw Error('Unexpected public schema archive entry');if(run(['exec','-i',container,'/bin/sh','-c','umask 077; cat > /tmp/vpj02-restore-toc'],filtered).status!==0)throw Error();
stage='restore';const restored=run(['exec','-i',container,'pg_restore','-h','/tmp/vpj02-socket','-U','postgres','-d','postgres','--clean','--if-exists','--use-list','/tmp/vpj02-restore-toc','--exit-on-error'],dump);dump.fill(0);if(restored.status!==0)throw Error();
stage='data-match';const checked=sql(`set time zone 'UTC'; select json_build_object('authCount',(select count(*) from auth.users),'tripCount',(select count(*) from public.trips),'migrationCount',(select count(*) from supabase_migrations.schema_migrations),'authDigest',(select encode(sha256(convert_to(coalesce(jsonb_agg(to_jsonb(u) order by id),'[]')::text,'UTF8')),'hex') from auth.users u),'tripDigest',(select encode(sha256(convert_to(coalesce(jsonb_agg(to_jsonb(t) order by id),'[]')::text,'UTF8')),'hex') from public.trips t));`);if(checked.status!==0)throw Error();const data=JSON.parse(checked.stdout.trim());if(JSON.stringify(data)!==JSON.stringify(meta.sourceBefore))throw Error();
const tablesResult=sql(tableSnapshotSQL(meta.tablesBefore));if(tablesResult.status!==0)throw Error('Table restore query failed');const restoredTables=validateSnapshot(JSON.parse(tablesResult.stdout.trim()));if(JSON.stringify(restoredTables)!==JSON.stringify(meta.tablesBefore))throw Error('Table restore mismatch');
stage='schema-grants-match';const schemaResult=sql(schemaInventorySQL);if(schemaResult.status!==0)throw Error('Inventory query failed');const restoredSchema=JSON.parse(schemaResult.stdout.trim());if(JSON.stringify(restoredSchema)!==JSON.stringify(meta.schemaBefore)){const expectedMap=new Map(meta.schemaBefore.map(r=>[r.kind+':'+r.identity,r.digest]));const actualMap=new Map(restoredSchema.map(r=>[r.kind+':'+r.identity,r.digest]));const different=[...new Set([...expectedMap.keys(),...actualMap.keys()])].filter(k=>expectedMap.get(k)!==actualMap.get(k));writeFileSync(dir+'/restore-schema-differences.json',JSON.stringify(different)+'\n',{mode:0o600});console.log(JSON.stringify({differentSchemaIdentities:different}));const diag=sql(readFileSync(root+'/acl-diagnostic.sql','utf8'));if(diag.status===0)writeFileSync(root+'/acl-restored.json',diag.stdout.trim()+'\n',{mode:0o600});throw Error('Function or grant restore mismatch');}meta.restoreSchemaInventoryMatched=meta.schemaBefore.length;meta.restorePublicBootstrap={owner:publicBootstrap.owner,acl:publicBootstrap.acl,omittedTocEntries:1,omittedType:'SCHEMA - public',allOtherEntriesRetained:true};
stage='candidate-rollback';
const manifest=JSON.parse(readFileSync(root+'/migrations.json','utf8'));
assert.equal(manifest.head,'e19bd584ba86604047c9216e50c5329e8881dcf8');
assert.equal(manifest.migrations.length,48);
const pending=manifest.migrations.slice(46);
assert.deepEqual(pending.map(x=>x.file),['20260914040000_vpj_16_place_statements.sql','20260914041000_vpj_16_place_questions.sql']);
const candidate=pending.map(m=>{const bytes=readFileSync(root+'/frozen/supabase/migrations/'+m.file);assert.equal(createHash('sha256').update(bytes).digest('hex'),m.sha256);return bytes.toString();}).join('\n');
const inner=s=>s.replace(/begin(?: isolation level repeatable read)? read only;/g,'').replace(/rollback;/g,'');
const columnsSql=`select jsonb_build_object('columns',(select jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notNull',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid)) order by a.attnum) from pg_attribute a left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where a.attrelid='turn_private.grounded_turns'::regclass and a.attnum>0 and not a.attisdropped),'constraints',(select jsonb_agg(jsonb_build_object('name',conname,'definition',pg_get_constraintdef(oid)) order by conname) from pg_constraint where conrelid='turn_private.grounded_turns'::regclass));`;
const snapshot=inner(schemaInventorySQL)+columnsSql+inner(tableSnapshotSQL(meta.tablesBefore));
const original=sql(snapshot);assert.equal(original.status,0);
const projected=sql('begin;'+candidate+snapshot+'rollback;');assert.equal(projected.status,0,'Candidate rollback failed');
const rows=projected.stdout.trim().split('\n').map(x=>JSON.parse(x));assert.equal(rows.length,3);
const old=original.stdout.trim().split('\n').map(x=>JSON.parse(x));assert.equal(old.length,3);
assert.deepEqual(rows[2],old[2]);
assert.deepEqual(rows[1].columns.slice(0,-3),old[1].columns);
assert.deepEqual(rows[1].columns.slice(-3).map(c=>[c.name,c.type,c.notNull,c.default]),['place_subject_id','place_name','place_resolution'].map(n=>[n,'text',false,null]));
const originalSchemaMap=new Map(old[0].map(x=>[x.kind+':'+x.identity,x.digest]));
const current=new Map(rows[0].map(x=>[x.kind+':'+x.identity,x.digest]));
const changed=[...originalSchemaMap.keys()].filter(k=>originalSchemaMap.get(k)!==current.get(k));
const expectedChanged=['knowledge_review_private.statement_valid','knowledge_review_private.question_definition','knowledge_review_private.resolve_question','public.complete_grounded_work','public.read_grounded_turn','public.ops_review_workspace'];
assert.deepEqual(changed.map(k=>k.slice(9).split('(')[0]).sort(),expectedChanged.sort());
const extra=rows[0].filter(x=>!originalSchemaMap.has(x.kind+':'+x.identity));
assert.deepEqual(extra.map(x=>x.kind+':'+x.identity.split('(')[0]).sort(),['knowledge_review_private.statement_valid_v1','knowledge_review_private.place_text','knowledge_review_private.place_name','knowledge_review_private.place_subject','knowledge_review_private.question_definition_general_v1','knowledge_review_private.selected_question_input','knowledge_review_private.ops_review_workspace_publication_v1','turn_private.complete_selected_grounded_work','public.complete_grounded_place_work'].map(x=>'function:'+x).sort());
assert.deepEqual(rows[1].constraints.filter(c=>!['grounded_turns_intent_check','grounded_place_selection_shape'].includes(c.name)),old[1].constraints.filter(c=>c.name!=='grounded_turns_intent_check'));
assert.equal(rows[1].constraints.length,old[1].constraints.length+1);
const rollback=sql(snapshot);assert.equal(rollback.status,0);assert.equal(rollback.stdout,original.stdout,'Rollback exact full snapshot mismatch');
writeFileSync(root+'/candidate-schema.json',JSON.stringify({head:manifest.head,migrations:pending,schema:rows[0],groundedShape:rows[1],changed,added:extra.map(x=>x.kind+':'+x.identity),retainedTables:rows[2].length,rollbackExact:true},null,2)+'\n',{mode:0o600});
meta.candidateRollbackExact=true;
meta.restoreTableDigestsMatched=restoredTables.length;meta.restoreRehearsal='PASS';meta.restoreVerifiedAt=new Date().toISOString();meta.restoreImage=image;meta.restoreNetwork='none';meta.restorePublishedPorts=0;writeFileSync(dir+'/manifest.json',JSON.stringify(meta,null,2)+'\n',{mode:0o600});console.log(JSON.stringify({restore:'PASS',authCount:data.authCount,tripCount:data.tripCount,migrationCount:data.migrationCount,recordDigestsMatch:true,network:'none',publishedPorts:0}));
}catch{console.error(JSON.stringify({restore:'FAIL',stage}));process.exitCode=1; }finally{if(created){
 let cleaned=false;
 try{
  const own=run(['inspect','--format','{{index .Config.Labels "vpj02.owner"}}',container]);
  if(own.status!==0||own.stdout.trim()!=='place-grounding-staging-20260914')throw Error('Ownership unverified');
  const removed=run(['rm','-f',container]);if(removed.status!==0)throw Error('Removal unverified');
  const listed=run(['ps','-aq','--no-trunc','--filter','name=^/'+container+'$']);
  if(listed.status!==0||listed.stdout.trim()!=='')throw Error('Absence unverified');
  cleaned=true;
 }catch{process.exitCode=1;}
 console.log(JSON.stringify({temporaryContainerCleaned:cleaned}));
 const finalMeta=JSON.parse(readFileSync(dir+'/manifest.json','utf8'));finalMeta.restoreContainerCleaned=cleaned;writeFileSync(dir+'/manifest.json',JSON.stringify(finalMeta,null,2)+'\n',{mode:0o600});
 if(!cleaned)process.exitCode=1;
}}
