// Network-none disposable PostgreSQL, actual source functions, synthetic admin claims only.
import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import {randomUUID as uuid} from 'node:crypto';import {readFileSync,readdirSync} from 'node:fs';import {command,sql} from '../cost/fixtures/postgres-rpc.mjs';
const enabled=process.env.VP_TURN_DB_TEST==='1',container='vpj21-declarations-'+uuid().slice(0,8);let created=false;
const db=async q=>{const r=await sql(container,q);assert.equal(r.code,0,r.stderr);return r.stdout.trim();};
const lit=v=>"'"+JSON.stringify(v).replaceAll("'","''")+"'::jsonb";
const claims=a=>`set request.jwt.claim.role='authenticated';set request.jwt.claim.sub='${a.owner}';set request.jwt.claims='${JSON.stringify({role:'authenticated',is_anonymous:false,session_id:a.session})}';`;
const read=a=>db(claims(a)+`select public.read_readiness_declarations_v1('${a.trip}','${a.task}');`).then(JSON.parse);
const decl=(scenario='connectivity')=>({scenario,city:'shanghai',locale:'en',subjectId:null,applies:'yes',resourcesReady:'yes',conditionsChecked:'yes',checkAt:'now'});
const saveSQL=(a,basis,revision,op,v)=>claims(a)+`select public.save_readiness_declaration_v1('${a.trip}','${a.task}',${lit(basis)},${revision},'${op}',${lit(v)});`;
const save=(a,r,op=uuid(),v=decl())=>db(saveSQL(a,r.basis,r.revision,op,v)).then(JSON.parse);
async function fixture(){const a=Object.fromEntries(['owner','session','trip','task','thread','turn','policy','conversation','goal','message','followup'].map(k=>[k,uuid()]));
 await db(`insert into auth.users(id) values('${a.owner}');insert into auth.sessions(id,user_id) values('${a.session}','${a.owner}');insert into identity_private.mobile_accounts(owner_id,epoch,session_id) values('${a.owner}',1,'${a.session}');insert into identity_private.mobile_attempts values('${a.owner}','${uuid()}','${a.session}',1);${claims(a)}insert into public.trips(id,owner_id,title) values('${a.trip}','${a.owner}','Synthetic Trip');insert into turn_private.text_policies(id,provider,recipient,endpoint,source_region,processing_region,storage_region,terms_version,notice_version,notice_hash,notice_zh,notice_en,retention,effective_at,expires_at,terms_recheck_at) values('${a.policy}','qwen','synthetic','https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions','local','local','local','test','test','${'a'.repeat(64)}','合成','Synthetic','retain_after_hide_v1',now()-interval '1 hour',now()+interval '1 day',now()+interval '1 day');insert into turn_private.text_consents(owner_id,policy_id) values('${a.owner}','${a.policy}');
 select public.submit_assistant_message_v1('${a.conversation}','${a.message}','${uuid()}','${a.policy}','en','Existing goal','goal_start','${a.goal}',null,null,null,null);
 select public.set_assistant_goal_trip_link_v1('${uuid()}','${a.conversation}','${a.goal}','${a.message}',1,0,'link','${a.trip}',0,true);
 select public.submit_service_task_turn('${a.thread}','${a.turn}','${uuid()}','${a.policy}','en','Existing Task','${a.task}',1,'new_goal',null);
 select public.submit_assistant_message_v1('${a.conversation}','${a.followup}','${uuid()}','${a.policy}','en','Explicit follow up','follow_up','${a.goal}',2,'${a.task}','${a.message}',null);
 update public.turns set status='completed' where id='${a.turn}';update turn_private.work set state='completed',lease_token=null,expires_at=null where turn_id='${a.turn}';update turn_private.text_content set output_kind='answered',output_text='Synthetic completed answer' where turn_id='${a.turn}';`);return a;
}
async function patch(a,date,zone){const version=Number(await db(`select head_version from public.trips where id='${a.trip}';`)),value={expectedVersion:version,operations:[{kind:'upsert_day',dayId:'day',date,timeZone:zone}]};
 const proposal=JSON.parse(await db(claims(a)+`select row_to_json(p) from public.create_trip_proposal_patch('${a.trip}',${lit(value)}) p;`));const digest=await db(claims(a)+`select digest from public.read_trip_proposal_v2('${proposal.proposal_id}');`);const result=await db(claims(a)+`select outcome from public.confirm_and_apply_trip_proposal('${proposal.proposal_id}','${uuid()}','${digest}');`);assert.equal(result,'applied');}
before(async()=>{if(!enabled)return;const r=await command('docker',['run','--pull=never','--rm','-d','--network','none','--name',container,'--user','postgres','--entrypoint','/bin/sh','public.ecr.aws/supabase/postgres:17.6.1.159','-c','umask 077;mkdir /tmp/vpj59-socket;initdb -D /tmp/vpj59-db -A trust --no-locale -E UTF8 >/tmp/init.log 2>&1 && exec postgres -D /tmp/vpj59-db -c listen_addresses= -c unix_socket_directories=/tmp/vpj59-socket -c unix_socket_permissions=0700']);assert.equal(r.code,0,r.stderr);created=true;for(let i=0;i<100;i++){if((await command('docker',['exec',container,'pg_isready','-h','/tmp/vpj59-socket','-U','postgres'])).code===0)break;await new Promise(r=>setTimeout(r,100));}
 await db(readFileSync('tests/integration/turn/fixtures/durable-work-schema.sql','utf8'));await db("create function auth.role() returns text language sql as $$select nullif(current_setting('request.jwt.claim.role',true),'')$$;create schema extensions;create extension pgcrypto with schema extensions;");for(const f of readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')).sort())await db('begin;'+readFileSync('supabase/migrations/'+f,'utf8')+'commit;');});
after(async()=>{if(created)assert.equal((await command('docker',['rm','-f',container])).code,0);});const run=(name,fn)=>test(name,{skip:!enabled,timeout:120000},fn);
run('true Task/confirmed link owner declarations persist across Native/Web; exact operation replay and CAS create no Task',async()=>{
 const a=await fixture(),empty=await read(a);assert.equal(empty.kind,'readiness_declarations');assert.equal(empty.state,'empty');assert.equal(empty.revision,0);assert.equal(empty.basis.taskTurnId,a.turn);
 const op=uuid(),first=await save(a,empty,op);assert.equal(first.revision,1);assert.deepEqual(await save(a,empty,op),first);assert.equal(first.declarationBasis,'explicit_user_report');assert.deepEqual(await read(a),first);
 assert.deepEqual(await save(a,empty),{kind:'conflict'});assert.deepEqual(await save(a,empty,op,{...decl(),applies:'no'}),{kind:'conflict'});
 const web={...a,session:uuid()};await db(`insert into auth.sessions(id,user_id) values('${web.session}','${a.owner}');`);assert.deepEqual(await read(web),first);const next=await save(web,first,uuid(),decl('payment'));assert.equal(next.revision,2);assert.equal(next.declarations.length,2);assert.deepEqual(await read(a),next);assert.deepEqual(await save(a,empty,op),{kind:'conflict'});
 assert.equal(await db(`select count(*) from turn_private.service_tasks where owner_id='${a.owner}';`),'1');const bad=await sql(container,saveSQL(a,next.basis,next.revision,uuid(),{...decl(),passportNumber:'forbidden'}));assert.notEqual(bad.code,0);assert.match(bad.stderr,/INVALID_INPUT/);
});
run('real confirmed date/zone patch makes old reports stale; rebase clears every prior yes and old ACK',async()=>{
 const a=await fixture(),r=await read(a),op=uuid();await save(a,r,op);const two=await save(a,await read(a),uuid(),decl('payment'));await patch(a,'2026-10-09','Asia/Shanghai');
 const stale=await read(a);assert.equal(stale.state,'stale');assert.equal(stale.revision,2);assert.deepEqual(stale.declarations,[]);assert.notEqual(stale.basis.dateBasis,r.basis.dateBasis);assert.deepEqual(await save(a,r,op),{kind:'conflict'});
 const rebased=await save(a,stale,uuid(),{...decl('admission'),resourcesReady:'unknown',conditionsChecked:'unknown'});assert.equal(rebased.revision,3);assert.deepEqual(rebased.declarations.map(d=>d.scenario),['admission']);await patch(a,'2026-10-09','Asia/Tokyo');assert.equal((await read(a)).state,'stale');assert.notEqual((await read(a)).basis.dateBasis,stale.basis.dateBasis);assert.equal(two.declarations.length,2);
});
run('foreign/unlinked Task and hidden/revoked/terminal lifecycle clear reports while retaining original Task',async()=>{
 const a=await fixture(),b=await fixture();await save(b,await read(b));assert.deepEqual(await read({...b,trip:a.trip,task:a.task}),{kind:'unavailable'});assert.deepEqual(await read({...a,task:b.task}),{kind:'unavailable'});await save(a,await read(a));
 await db(`update turn_private.text_content set hidden_at=clock_timestamp() where turn_id='${a.turn}';`);assert.deepEqual(await read(a),{kind:'unavailable'});assert.equal(await db(`select count(*) from readiness_private.scopes_v1 where owner_id='${a.owner}';`),'0');assert.equal(await db(`select count(*) from turn_private.service_tasks where id='${a.task}';`),'1');assert.equal(await db(`select count(*) from readiness_private.operations_v1 where owner_id='${a.owner}';`),'0');
 for(const lifecycle of ['consent','unlink','delete','terminal','text-delete']){const f=await fixture();await save(f,await read(f));let statement;
 if(lifecycle==='consent')statement=`update turn_private.text_consents set revoked_at=clock_timestamp() where owner_id='${f.owner}';`;
 if(lifecycle==='unlink')statement=claims(f)+`select public.set_assistant_goal_trip_link_v1('${uuid()}','${f.conversation}','${f.goal}',null,2,1,'unlink',null,null,true);`;
 if(lifecycle==='delete')statement=`delete from public.chat_threads where id='${f.thread}';`;
 if(lifecycle==='text-delete')statement=`begin;create temporary table retained_source as select * from turn_private.text_content where turn_id='${f.turn}';delete from turn_private.text_content where turn_id='${f.turn}';do $$begin if exists(select 1 from readiness_private.scopes_v1 where task_id='${f.task}') or exists(select 1 from readiness_private.operations_v1 where task_id='${f.task}') then raise exception 'READINESS_DELETE_NOT_SCRUBBED';end if;end $$;insert into turn_private.text_content(turn_id,owner_id,thread_id,policy_id,consent_id,locale,input_text,output_kind,output_text,hidden_at,created_at) select turn_id,owner_id,thread_id,policy_id,consent_id,locale,'[synthetic retained text tombstone]',null,null,clock_timestamp(),created_at from retained_source;commit;`;
 if(lifecycle==='terminal')statement=`update public.turns set status='cancelled' where id='${f.turn}';`;
 await db(statement);if(lifecycle==='text-delete'){assert.equal(await db(`select count(*) from public.turns where id='${f.turn}';`),'1');assert.equal(await db(`select count(*) from turn_private.service_tasks where id='${f.task}';`),'1');}
 assert.equal(await db(`select count(*) from readiness_private.scopes_v1 where owner_id='${f.owner}';`),'0');assert.equal(await db(`select count(*) from readiness_private.operations_v1 where owner_id='${f.owner}';`),'0');assert.deepEqual(await read(f),{kind:'unavailable'});}
 assert.equal((await read(b)).revision,1);assert.equal((await read(b)).declarations[0].resourcesReady,'yes');
});
run('two real transactions serialize scoped CAS; private export is exact job/lease-only and old granted output unchanged',async()=>{
 const gated=await fixture(),basis=await read(gated);const holder=sql(container,`set application_name='readiness_policy_holder';begin;select id from turn_private.text_policies where id='${gated.policy}' for update;select pg_sleep(2);commit;`);
 for(let i=0;i<100;i++){if(await db("select exists(select 1 from pg_stat_activity where application_name='readiness_policy_holder' and wait_event_type='Timeout');")==='t')break;if(i===99)assert.fail('policy holder not observed');await new Promise(r=>setTimeout(r,10));}
 assert.deepEqual(await save(gated,basis),{kind:'unavailable'});assert.equal(await db(`select count(*) from readiness_private.scopes_v1 where task_id='${gated.task}';`),'0');assert.equal((await holder).code,0);
 const a=await fixture(),r=await read(a);const attempts=await Promise.all([db(saveSQL(a,r.basis,0,uuid(),decl())).then(JSON.parse),db(saveSQL(a,r.basis,0,uuid(),{...decl(),applies:'no'})).then(JSON.parse)]);assert.equal(attempts.filter(x=>x.kind==='readiness_declarations').length,1);assert.equal(attempts.filter(x=>x.kind==='conflict').length,1);assert.equal((await read(a)).revision,1);
 const old=JSON.parse(await db(`set request.jwt.claim.role='service_role';select public.assistant_conversation_export_owner_v1('${a.owner}','messages',null,100);`));assert.equal(JSON.stringify(old).includes('readinessDeclaration'),false);assert.equal(JSON.stringify(old).includes('resourcesReady'),false);
 for(const role of ['anon','authenticated','service_role']){assert.equal(await db(`select has_function_privilege('${role}','public.read_readiness_declarations_v1(uuid,uuid)','EXECUTE') or has_function_privilege('${role}','public.save_readiness_declaration_v1(uuid,uuid,jsonb,bigint,uuid,jsonb)','EXECUTE') or has_function_privilege('${role}','readiness_private.export_metadata_v1(uuid,uuid,integer,uuid,integer)','EXECUTE');`),'f');}
 const request=uuid(),policy=uuid();await db(`insert into export_private.core_policies_v1(id,revision,enabled,environment,key_id,max_run_ms,artifact_ttl_ms,ticket_ttl_ms,max_pages,page_size,max_bytes,valid_until) values('${policy}',1,true,'local','synthetic',90000,600000,300000,100,100,8388608,clock_timestamp()+interval '1 day');`);
 await db(claims(a)+`select public.privacy_core_export_v1('request',${lit({requestId:request,confirmed:true})});`);const lease=JSON.parse(await db(`set request.jwt.claim.role='service_role';select public.privacy_core_export_v1('claim',${lit({requestId:request,operationId:uuid(),maxRunMs:30000,expectedEnvironment:'local',expectedKeyId:'synthetic'})});`));
 const page=JSON.parse(await db(`set request.jwt.claim.role='service_role';select readiness_private.export_metadata_v1('${request}','${lease.leaseId}',${lease.generation},null,1);`));assert.equal(page.enrolled,false);assert.equal(page.items.length,1);assert.equal(page.items[0].historical,true);assert.equal(page.items[0].basis.taskId,a.task);assert.equal(JSON.stringify(page).includes('input_digest'),false);
 assert.deepEqual(JSON.parse(await db(`set request.jwt.claim.role='service_role';select readiness_private.export_metadata_v1('${request}','${uuid()}',${lease.generation},null,1);`)),{kind:'unavailable'});
 await db(`delete from auth.users where id='${a.owner}';`);assert.equal(await db(`select count(*) from readiness_private.scopes_v1 where owner_id='${a.owner}';`),'0');assert.equal(await db(`select count(*) from readiness_private.operations_v1 where owner_id='${a.owner}';`),'0');
});
