import Foundation

enum NativeTurnDataCopy {
    static func scope(_ sensitive: Bool, chinese: Bool) -> String {
        sensitive ? (chinese ? "本人所选已完成轮次的敏感资料" : "My selected completed Turn sensitive data")
            : (chinese ? "本清理出口的临时预览进度" : "This cleanup exit transient preview progress")
    }
    static func label(_ code: String, chinese: Bool) -> String {
        let labels: [String: (String, String)] = [
            "turnIds": ("所选轮次身份", "Selected Turn identities"),
            "messageIds": ("相关消息身份", "Related message identities"),
            "artifactIds": ("独占成果及其全部版本", "Exclusive results and all their revisions"),
            "taskIds": ("原任务", "Original tasks"),
            "threadIds": ("原线程", "Original threads"),
            "conversationIds": ("原会话", "Original conversations"),
            "goalIds": ("原目标", "Original goals"),
            "tripIds": ("原行程", "Original Trips"),
            "memoryIds": ("原显式记忆", "Original explicit Memory"),
            "events": ("轮次事件", "Turn events"),
            "idempotency": ("轮次请求记录", "Turn request records"),
            "feedback": ("轮次反馈", "Turn feedback"),
            "artifacts": ("所选成果敏感内容", "Selected result's sensitive content"),
            "revisions": ("全部成果版本", "All result revisions"),
            "resultEvents": ("成果事件敏感内容", "Sensitive result event content"),
            "sourceReceipts": ("选中消息的来源回执", "Selected message source receipts"),
            "intakes": ("选中消息的旅行需求副本", "Selected message travel requirement copies"),
            "intakeBindings": ("所选轮次的需求绑定", "Selected Turn intake bindings"),
            "planning": ("独占规划副本", "Exclusive planning copies"),
            "actionReceipts": ("所选轮次的工具回执", "Selected Turn tool receipts"),
            "observations": ("所选轮次的观察记录", "Selected Turn observations"),
            "modelDispatches": ("所选轮次的模型调用副本", "Selected Turn model dispatch copies"),
            "checkpoints": ("所选轮次的执行断点", "Selected Turn execution checkpoints"),
            "attemptBindings": ("所选轮次的调用绑定", "Selected Turn attempt bindings"),
            "localJournals": ("独占本地执行日志副本", "Exclusive local execution journal copies"),
            "executionRuns": ("独占执行记录", "Exclusive execution records"),
            "callWindows": ("独占调用记录", "Exclusive call records"),
            "collectorOrigins": ("独占采集来源副本", "Exclusive collector source copies"),
            "collectorOutputs": ("独占采集输出副本", "Exclusive collector output copies"),
            "resultClaims": ("独占成果声明副本", "Exclusive result claim copies"),
            "completionProofs": ("独占完成证明副本", "Exclusive completion proof copies"),
            "completedReceipts": ("独占完成回执副本", "Exclusive completion receipt copies"),
            "grounded": ("所选轮次的有据回答副本", "Selected Turn grounded answer copies"),
            "assistJobs": ("所选轮次的补充工作副本", "Selected Turn assist copies"),
            "work": ("所选轮次的工作副本", "Selected Turn work copies"),
            "memoryConsumers": ("轮次对记忆的使用引用", "Turn Memory use references"),
            "turns": ("保留原轮次", "Preserved original turns"),
            "messages": ("保留原消息", "Preserved original messages"),
            "tasks": ("保留原任务", "Preserved original tasks"),
            "taskTurns": ("保留任务与轮次关系", "Retained Task and Turn relations"),
            "capacity": ("保留任务容量记录", "Retained Task capacity records"),
            "budgetAttempts": ("保留预算与尝试记录", "Preserved budget and attempt records"),
            "textDispatches": ("保留原文字调用元数据", "Retained original text dispatch metadata"),
            "threads": ("保留原线程", "Preserved original threads"),
            "conversations": ("保留原会话", "Preserved original conversations"),
            "goals": ("保留原目标", "Preserved original goals"),
            "SCOPE_TOO_LARGE": ("关系或副本范围超出安全清理上限", "The graph or copies exceed the safe cleanup bound"),
            "ACTIVE_WORK": ("仍有活动工作，当前无法安全清理", "Active work prevents safe cleanup"),
            "SHARED_OR_FOREIGN_SCOPE": ("涉及共享或其他用户对象，不能清理", "Shared or other-user objects prevent cleanup"),
            "CROSS_TURN_REFERENCE": ("其他轮次或混合成果依赖此来源，须先处理原引用", "Other Turns or mixed results depend on this source; resolve their original references first"),
            "PROPOSAL_REFERENCE": ("已应用或未应用提案仍有依赖，须通过原提案流程处理", "An applied or unapplied proposal remains dependent; use its original flow"),
            "READINESS_REFERENCE": ("准备事项仍有引用，须通过原流程处理", "Readiness references require their original flow"),
            "GUIDE_REFERENCE": ("旅途指南仍有引用，须通过原流程处理", "Guide references require their original flow"),
            "SCOPED_EDIT_REFERENCE": ("局部修改仍有引用，须通过原流程处理", "Scoped edits require their original flow"),
            "NOTIFICATION_REFERENCE": ("通知仍有引用，须通过原通知流程处理", "Notification references require their original flow"),
            "BRIEF_REFERENCE": ("旅行简报仍有引用，须通过原流程处理", "Brief references require their original flow"),
            "CORE_EXPORT_COPY": ("已有导出副本，须通过原导出清理流程处理", "Existing export copies require their original cleanup flow"),
            "OTHER_DELETE_PENDING": ("存在其他未决清理，须先核验原操作", "Another cleanup is pending; verify its original operation first"),
            "SOURCE_UNSUPPORTED": ("来源资格或独占关系尚不能核验，不能清理", "Source authority or exclusivity cannot be verified; cleanup is blocked"),
            "textBodies": ("轮次输入与输出正文", "Turn input and output bodies"),
            "messageBodies": ("相关消息正文", "Related message bodies"),
            "taskDigests": ("原任务中所选输入的摘要副本", "Selected input digest copies in original Tasks"),
            "selected_turn_events_feedback_idempotency": ("仅清理所选轮次的事件、反馈和请求记录", "Clear only the selected Turn events, feedback and request records"),
            "exclusive_result_revisions_events": ("清理独占成果的全部版本与事件", "Clear all revisions and events of exclusive results"),
            "selected_intakes_source_receipts": ("清理选中消息的需求与来源回执副本", "Clear selected message intake and source receipt copies"),
            "selected_grounded_planning_worker_sensitive_copies": ("清理所选轮次的回答、规划与执行敏感副本", "Clear selected Turn answer, planning and execution sensitive copies"),
            "selected_memory_consumer_references": ("清理所选轮次的记忆使用引用，原显式记忆保留", "Clear selected Turn Memory use references; original explicit Memory remains"),
            "selected_text_input_output_permanently_hidden": ("永久清理所选轮次的输入输出正文，轮次身份保留", "Permanently clear selected Turn input and output bodies; Turn identity remains"),
            "selected_message_input_fixed_deleted_marker": ("相关消息正文改为固定删除标记，消息身份保留", "Replace related message bodies with a fixed deletion marker; message identity remains"),
            "selected_root_task_digest_fixed_deleted_marker": ("仅核验为所选原始输入副本的任务摘要改为删除标记；数量单独列明", "Only Task digests qualified as copies of selected root input receive a deletion marker; counts are shown separately"),
            "turn_message_task_thread_conversation_goal_identity": ("保留原轮次、消息、任务、线程、会话与目标身份", "Original Turn, message, Task, thread, conversation and goal identities remain"),
            "other_turns_and_parent_contents_except_selected_root_task_digest": ("保留其他轮次及原父对象内容；上列任务摘要副本例外会单独核验", "Other Turns and parent contents remain; the Task digest copy exception above is reviewed separately"),
            "confirmed_trip_content_history_proposals": ("保留原行程内容、历史与提案", "Original Trip content, history and proposals remain"),
            "explicit_memory_profiles_receipts_consents": ("保留原显式记忆、偏好、回执与同意", "Original explicit Memory, profiles, receipts and consent remain"),
            "capacity_budget_dispatch_financial_metadata": ("保留容量、预算、调用和财务元数据", "Capacity, budget, dispatch and financial metadata remain"),
            "permanent_identity_operation_fences": ("保留永久身份与操作隔离记录", "Permanent identity and operation isolation records remain"),
            "active_shared_cross_turn_and_mixed_result_references_blocked": ("活动、共享、跨轮次与混合成果引用会阻挡清理", "Active, shared, cross Turn and mixed result references block cleanup"),
            "guide_brief_proposal_knowledge_source_references_require_original_flow": ("指南、简报、提案与知识来源引用须通过原流程处理", "Guide, brief, proposal and knowledge source references require their original flow"),
            "mixed_core_export_copies_require_original_cleanup": ("混合核心导出副本须通过原流程处理", "Mixed core export copies require their original cleanup flow"),
            "provider_external_copies_not_erased": ("供应商与外部副本不在本次清理范围", "Provider and external copies are outside this cleanup scope"),
            "backup_restore_old_device_acceptance_unverified": ("备份恢复与旧设备清理尚未验收", "Backup restore and old device cleanup remain unverified"),
            "selected_transient_preview_graph_counts_references_conflicts": ("仅清理所选操作的临时预览关系、数量、引用与阻挡明细", "Only selected operations' transient preview graphs, counts, references and conflicts are cleared"),
            "original_selection_actor_epoch_hash_time_operation_fences": ("保留原选择、本人会话资格、摘要、时间与操作隔离记录", "Original selection, actor/session authority, digests, times and operation isolation records remain"),
            "immutable_minimal_decisions": ("保留不可变的最小决策回执", "Immutable minimal decision receipts remain"),
            "source_turn_data_not_erased": ("清理临时进度不会清理原轮次资料", "Clearing transient progress does not clear original Turn data"),
            "unselected_operations": ("未选操作保留", "Unselected operations remain"),
            "external_copies": ("外部副本保留", "External copies remain"),
        ]
        guard let value = labels[code] else { return chinese ? "此字段尚无法核验" : "This field cannot yet be verified" }
        return chinese ? value.0 : value.1
    }
}
