import test from 'node:test';
import assert from 'node:assert/strict';
import { createHostedScopedEditWorker, parseScopedHostedProfile } from '../../../lib/server/turn/scoped-edit/hosted-job.ts';
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const profile={schemaVersion:'vpj10-hosted-scoped-edit/1',loop:{schemaVersion:'vpj07-hosted-text-worker/1',pollIntervalMs:1000,maxLifetimeMs:60000,drainMs:0,concurrency:1,groupLimit:1,modes:['current_input_v1'],qwen:{priceVersion:'reviewed',pricing:{mode:'flat',inputMicrosPerMillion:1,outputMicrosPerMillion:2,cachedInputMicrosPerMillion:null},reservedMicros:1000,maxOutputTokens:1024,timeoutMs:1000,configurationId:id(3),configurationVersion:1}},target:{ownerId:id(1),policyId:id(2),scopeId:id(4)}};
const endpoint='https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions';
function deps(signal:AbortController, enabled=false){const paths:string[]=[];let providerKeys=0;return {paths,get providerKeys(){return providerKeys;},dependencies:{scopedEditEnabled:true,workerId:id(5),build:'local-closed-test',startedAt:'2026-10-05T04:00:00.000Z',qwenEndpoint:endpoint,workerCredential:()=> 'synthetic-service-key',providerCredential:()=>{providerKeys++;return 'synthetic-provider-key';},journal:{job:async()=>{},usage:async()=>{},knowledge:async()=>{},destination:async()=>{},planningUsage:async()=>{},event:async()=>{}},fetch:async(input:RequestInfo|URL)=>{const path=String(input).split('/').at(-1)!;paths.push(path);if(path==='hosted_worker_heartbeat'){signal.abort();return Response.json({kind:'ok',enabled});}throw Error('unexpected dispatch');}}};}
test('closed profile requires explicit new schema and target; original profile stays separate',()=>{assert.ok(parseScopedHostedProfile(profile));assert.throws(()=>parseScopedHostedProfile({...profile,target:{...profile.target,ready:true}}));assert.throws(()=>parseScopedHostedProfile({...profile,enabled:true}));});
test('mode remains default off and construction reads no credentials',()=>{const c=new AbortController(),f=deps(c),p=parseScopedHostedProfile(profile);assert.throws(()=>createHostedScopedEditWorker(p,{...f.dependencies,scopedEditEnabled:undefined}));assert.equal(f.paths.length,0);assert.equal(f.providerKeys,0);});
test('original stop/heartbeat loop stops before discovery or claim; provider secret remains unread',async()=>{const c=new AbortController(),f=deps(c);const run=createHostedScopedEditWorker(parseScopedHostedProfile(profile),f.dependencies);const result=await run(c.signal);assert.equal(result.reason,'stopped');assert.ok(f.paths.length>0);assert.ok(f.paths.every(p=>p==='hosted_worker_heartbeat'));assert.equal(f.providerKeys,0);});
test('first SQL heartbeat enabled cannot arm file-secret startup',async()=>{const c=new AbortController(),f=deps(c,true);const run=createHostedScopedEditWorker(parseScopedHostedProfile(profile),{...f.dependencies,requireInitialDisabled:true});const result=await run(c.signal);assert.equal(result.polls,0);assert.equal(f.providerKeys,0);});
