import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID as uuid} from 'node:crypto';
import {isHotelClassificationStatement,isClassificationOperation,decodeClassificationReply,CLASSIFICATION_EXCLUSIONS} from '../../../lib/server/knowledge/classification/contract.ts';
import {isKnowledgeStatement} from '../../../lib/server/knowledge/publication/statement.ts';
import {handleClassificationOps} from '../../../lib/server/knowledge/classification/http-ops.ts';
const statement={schemaVersion:'knowledge-lodging-classification/1',assertion:{subjectId:'fixture_hotel',predicate:'classified_as',objectId:'hotel',conditions:[],exclusions:[...CLASSIFICATION_EXCLUSIONS]},scope:{cities:['shanghai'],scene:'lodging_classification',audience:'international_independent_traveler'},expressions:{en:{text:'Synthetic classification only',conditions:[],exclusions:['Classification only','No price or inventory claim','No guest eligibility claim']},zh:{text:'仅合成酒店分类',conditions:[],exclusions:['仅分类','不涉及价格库存','不涉及入住资格']}},sources:[{sourceKey:'fixture_hotel',revisionLabel:'one',publisher:'Fixture operator',uri:'urn:vpj15:synthetic:classification',locator:'Fixture only',snippet:'Synthetic not live hotel evidence',usageDeclaration:'Synthetic offline test'}]};
const candidateId=uuid(),mappingId=uuid(),canonicalPoiId=uuid(),statementId=uuid(),h='a'.repeat(64);
const actions=[{action:'submit',operationId:uuid(),candidateId,title:'Classification',statement},{action:'review',operationId:uuid(),candidateId,expectedVersion:1,decision:'reviewed',note:'Independent review'},{action:'publish',operationId:uuid(),candidateId,expectedVersion:2,expiresAt:'2026-10-05T00:00:00.000Z',useBasis:'original_factual_summary',useNote:'Synthetic allowed test'},{action:'revoke',operationId:uuid(),candidateId,expectedPublicationVersion:1,note:'Withdrawal'},{action:'submit_mapping',operationId:uuid(),canonicalPoiId,statementId,expectedStatementRevision:1,expectedPayloadHash:h,expectedSourceDigest:h,expectedPublicationVersion:1,expectedRightsDigest:h,city:'shanghai'},{action:'review_mapping',operationId:uuid(),mappingId,expectedVersion:1,expectedDigest:h,decision:'approved',note:'Independent mapping'},{action:'revoke_mapping',operationId:uuid(),mappingId,expectedVersion:2,note:'Mapping withdrawal'}];
test('classification is separate, closed and cannot add price/stock/guest eligibility or broaden old validator',()=>{
 assert.equal(isHotelClassificationStatement(statement),true);assert.equal(isKnowledgeStatement(statement),false);
 for(const bad of [{...statement,price:1},{...statement,scope:{...statement.scope,scene:'accommodation'}},{...statement,assertion:{...statement.assertion,predicate:'located_at'}},{...statement,assertion:{...statement.assertion,objectId:'hostel'}},{...statement,assertion:{...statement.assertion,conditions:['allows_foreign_guests']}},{...statement,sources:[statement.sources[0],statement.sources[0]]}])assert.equal(isHotelClassificationStatement(bad),false);
});
test('all seven exact operations reject extra fields, arrays/coercion, stale CAS and malformed dates',()=>{
 for(const a of actions){assert.equal(isClassificationOperation(a),true,a.action);assert.equal(isClassificationOperation({...a,classificationApproved:true}),false,a.action);}
 for(const a of [{...actions[1],decision:['reviewed']},{...actions[2],expiresAt:'2026-02-30T00:00:00Z'},{...actions[4],expectedStatementRevision:2},{...actions[5],expectedDigest:null},{...actions[6],expectedVersion:1},{...actions[0],operationId:uuid().toUpperCase()}])assert.equal(isClassificationOperation(a),false);
});
test('default-off zero credential/RPC and malformed operations do not dispatch; actual HTTP seam only calls dedicated RPC',async()=>{
 let credentials=0,calls=0;const make=(operation:unknown)=>new Request('http://127.0.0.1/api/ops/lodging-classification',{method:'POST',headers:{'content-type':'application/json','x-ops-expected-actor':candidateId},body:JSON.stringify(operation)});
 const createRpc=()=>{credentials++;return {authenticate:async()=>uuid(),call:async(name:string,p:Record<string,unknown>)=>{calls++;assert.equal(name,'ops_lodging_classification_v1');assert.equal(p.p_input,actions[0]);return {data:null,error:null};}};};
 assert.equal((await handleClassificationOps(make(actions[0]),{enabled:false,sameOrigin:true,createRpc})).status,503);assert.equal(credentials,0);assert.equal(calls,0);
 assert.equal((await handleClassificationOps(make({...actions[0],price:100}),{enabled:true,sameOrigin:true,createRpc})).status,400);assert.equal(credentials,0);
 const input=actions[0];assert.ok(isClassificationOperation(input));const reply={kind:'lodging_classification_candidate',operationId:input.operationId,candidateId,statementId,statementRevision:1,payloadHash:h,sourceDigest:h,status:'pending',version:1,reviewerMemberRevision:null};
 const result=await handleClassificationOps(make(input),{enabled:true,sameOrigin:true,createRpc:()=>({authenticate:async()=>candidateId,call:async(name,p)=>{assert.equal(name,'ops_lodging_classification_v1');assert.deepEqual(p.p_input,input);return {data:reply,error:null};}})});assert.equal(result.status,200);assert.deepEqual(result.body,{data:reply});
 for(const bad of [{...reply,extra:true},{...reply,operationId:uuid()},{...reply,status:'reviewed'},{...reply,reviewerMemberRevision:1}])assert.equal(decodeClassificationReply(bad,input),null);
});


test('lost ACK preserves original body/op across recovery; actor changes prevent dispatch and hide receipts',async()=>{
 const {decodePendingClassification,dispatchClassificationPending}=await import('../../../lib/server/knowledge/classification/pending.ts');
 const input=actions[0];assert.ok(isClassificationOperation(input));const saved={actorId:candidateId,input,createdAt:Date.now()};const recovered=decodePendingClassification(JSON.parse(JSON.stringify(saved)));assert.ok(recovered);assert.deepEqual(recovered.input,input);
 const sent:unknown[]=[];const io={isCurrent:()=>true,currentActor:async()=>candidateId,send:async(body:unknown)=>{sent.push(body);throw new Error('Lost ACK');}};
 assert.deepEqual(await dispatchClassificationPending(recovered,io),{kind:'unknown'});assert.deepEqual(await dispatchClassificationPending(recovered,io),{kind:'unknown'});assert.deepEqual(sent,[input,input]);
 assert.deepEqual(await dispatchClassificationPending(recovered,{...io,currentActor:async()=>mappingId}),{kind:'identity_changed'});assert.equal(sent.length,2);
 let reads=0;assert.deepEqual(await dispatchClassificationPending(recovered,{...io,currentActor:async()=>++reads===1?candidateId:mappingId,send:async()=>({ok:true,status:200,data:{privateReceipt:true}})}),{kind:'identity_changed'});
 let current=true;assert.deepEqual(await dispatchClassificationPending(recovered,{...io,isCurrent:()=>current,send:async()=>{current=false;return {ok:true,status:200,data:{privateReceipt:true}};}}),{kind:'identity_changed'});
 let authReads=0;const result=await handleClassificationOps(new Request('http://localhost/api/ops/lodging-classification',{method:'POST',headers:{'content-type':'application/json','x-ops-expected-actor':candidateId},body:JSON.stringify(input)}),{enabled:true,sameOrigin:true,createRpc:()=>({authenticate:async()=>++authReads===1?candidateId:mappingId,call:async()=>({data:{privateReceipt:true},error:null})})});assert.equal(result.status,503);assert.deepEqual(result.body,{error:'OPS_ACK_UNKNOWN'});
});
